### ISSUE TITLE
io.fits fails / has unexpected behavior when writing single float objects

### ISSUE THREAD

**Issue by eigenbrot** [astropy/astropy#10022]
When writing an HDU initialized with a single float `fits` will happily write the file, but the result is corrupted and cannot be read:

```python
>>> ph = fits.PrimaryHDU(6.28)
>>> ph.writeto('tmp.fits')
>>> hdl = fits.open('tmp.fits')
>>> hdl
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/astropy/io/fits/hdu/base.py", line 406, in _readfrom_internal
    header_str, header = _BasicHeader.fromfile(data)
  File "/usr/lib/python3.8/site-packages/astropy/io/fits/header.py", line 2077, in fromfile
    header_str, cards = parse_header(fileobj)
  File "astropy/io/fits/_utils.pyx", line 38, in astropy.io.fits._utils.parse_header
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb8 in position 3: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 242, in __repr__
>>> hdl[0].header
SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                  -64 / array data type                                
NAXIS   =                    0 / number of array dimensions                     
EXTEND  =                    T            
>>> hdl[0].data is None
True
```
I would have expected the `writeto` to either complain and error out or wrap the single number in a format that resulted in a readable file.

This error happens with either `PrimaryHDU` or `ImageHDU` objects.

**Comment by saimn** [comment]
I agree some validation was missing here, see  #10041 for a fix. Thanks for reporting.
