### ISSUE TITLE
Abort error when convolving an empty array

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#10048]
**Actual behavior**

```python
In [12]: from astropy.convolution import convolve                               

In [13]: import numpy as np                                                     

In [14]: x = np.array([])                                                       

In [15]: y = np.array([1.])                                                     

In [16]: convolve(x, y)                                                         
python3.7: astropy/convolution/src/convolve.c:217: convolve1d: Assertion `_nx > 2*_wkx' failed.
Aborted (core dumped)
```

**Expected behavior**

For empty arrays, the output should be an empty array with the same dimensions.

**Comment by pllim** [comment]
Just for completeness, here is the `gdb` trace that I got:
```
#0  0x00007ffff7827377 in raise () from /lib64/libc.so.6
#1  0x00007ffff7828a68 in abort () from /lib64/libc.so.6
#2  0x00007ffff7820196 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffff7820242 in __assert_fail () from /lib64/libc.so.6
#4  0x00007fffc83265df in convolve1d (n_threads=<optimized out>, 
    _embed_result_within_padded_region=<optimized out>, _nan_interpolate=<optimized out>, 
    _nkx=<optimized out>, g=<optimized out>, _nx=<optimized out>, f=<optimized out>, 
    result=<optimized out>) at astropy/convolution/src/convolve.c:217
#5  convolve1d_c (result=0x555555e9a2a0, f=<optimized out>, nx=<optimized out>, g=<optimized out>, 
    nkx=1, nan_interpolate=<optimized out>, embed_result_within_padded_region=false, n_threads=1)
    at astropy/convolution/src/convolve.c:125
#6  0x00007ffff7e81630 in ffi_call_unix64 ()
   from .../lib/python3.7/lib-dynload/../../libffi.so.6
#7  0x00007ffff7e80fed in ffi_call ()
   from .../lib/python3.7/lib-dynload/../../libffi.so.6
#8  0x00007fffc8d67fce in _call_function_pointer (argcount=9, resmem=0x7fffffffcb80, 
    restype=<optimized out>, atypes=0x7fffffffcac0, avalues=0x7fffffffcb20, 
    pProc=0x7fffc8327d90 <convolveNd_c>, flags=4353)
    at .../conda/python-3.7.3/Modules/_ctypes/callproc.c:827
#9  _ctypes_callproc () at .../conda/python-3.7.3/Modules/_ctypes/callproc.c:1184
#10 0x00007fffc8d68a04 in PyCFuncPtr_call ()
    at .../conda/python-3.7.3/Modules/_ctypes/_ctypes.c:3969
#11 0x00005555556c516b in _PyObject_FastCallKeywords ()
    at .../work/Objects/call.c:199
#12 0x0000555555729bb6 in call_function (kwnames=0x0, oparg=<optimized out>, 
    pp_stack=<synthetic pointer>)
    at .../work/Python/ceval.c:4619
#13 _PyEval_EvalFrameDefault ()
    at .../work/Python/ceval.c:3124
#14 0x000055555566a929 in _PyEval_EvalCodeWithName ()
    at .../work/Python/ceval.c:3930
#15 0x000055555566b9f5 in _PyFunction_FastCallDict ()
    at .../work/Objects/call.c:376
#16 0x000055555567d584 in PyObject_Call ()
    at .../work/Objects/call.c:226
#17 0x000055555572703c in do_call_core (kwdict=0x7ffff7f0bf78, callargs=0x7ffff0906388, 
    func=0x7fff979d8488)
    at .../work/Python/ceval.c:4645
#18 _PyEval_EvalFrameDefault ()
    at .../work/Python/ceval.c:3191
#19 0x000055555566b1d9 in _PyEval_EvalCodeWithName ()
    at .../work/Python/ceval.c:3930
#20 0x00005555556bbf87 in _PyFunction_FastCallKeywords ()
    at .../work/Objects/call.c:433
#21 0x0000555555725506 in call_function (kwnames=0x0, oparg=<optimized out>, 
    pp_stack=<synthetic pointer>)
    at .../work/Python/ceval.c:4616
#22 _PyEval_EvalFrameDefault ()
    at .../work/Python/ceval.c:3124
#23 0x00005555556bbcfb in function_code_fastcall (globals=<optimized out>, nargs=0, 
    args=<optimized out>, co=<optimized out>)
    at .../work/Objects/call.c:283
#24 _PyFunction_FastCallKeywords ()
    at .../work/Objects/call.c:408
#25 0x0000555555725506 in call_function (kwnames=0x0, oparg=<optimized out>, 
    pp_stack=<synthetic pointer>)
    at .../work/Python/ceval.c:4616
#26 _PyEval_EvalFrameDefault ()
    at .../work/Python/ceval.c:3124
#27 0x000055555566a929 in _PyEval_EvalCodeWithName ()
    at .../work/Python/ceval.c:3930
#28 0x000055555566b7e4 in PyEval_EvalCodeEx ()
    at .../work/Python/ceval.c:3959
#29 0x000055555566b80c in PyEval_EvalCode (co=co@entry=0x7ffff7e9bb70, 
    globals=globals@entry=0x7ffff7ed71b0, locals=locals@entry=0x7ffff7ed71b0)
    at .../work/Python/ceval.c:524
#30 0x0000555555783ac4 in run_mod ()
    at .../work/Python/pythonrun.c:1035
#31 0x000055555578ddb1 in PyRun_FileExFlags ()
    at .../work/Python/pythonrun.c:988
#32 0x000055555578dfa3 in PyRun_SimpleFileExFlags ()
    at .../work/Python/pythonrun.c:429
#33 0x000055555578e06d in PyRun_AnyFileExFlags ()
    at .../work/Python/pythonrun.c:84
#34 0x000055555578f0bf in pymain_run_file (p_cf=0x7fffffffd880, filename=0x5555558c6470 L"lol.py", 
    fp=0x555555942e00)
    at .../work/Modules/main.c:427
#35 pymain_run_filename (cf=0x7fffffffd880, pymain=0x7fffffffd990)
    at .../work/Modules/main.c:1627
#36 pymain_run_python (pymain=0x7fffffffd990)
    at .../work/Modules/main.c:2877
#37 pymain_main ()
    at .../work/Modules/main.c:3038
#38 0x000055555578f1dc in _Py_UnixMain ()
    at .../work/Modules/main.c:3073
#39 0x00007ffff7813545 in __libc_start_main () from /lib64/libc.so.6
#40 0x0000555555734d3d in _start () at ../sysdeps/x86_64/elf/start.S:103
```

https://github.com/astropy/astropy/blob/24dc50ac020b25ac395ee74679a90dabc3acb1f0/astropy/convolution/src/convolve.c#L125

https://github.com/astropy/astropy/blob/24dc50ac020b25ac395ee74679a90dabc3acb1f0/astropy/convolution/src/convolve.c#L217

**Comment by keflavich** [comment]
Seems like an easy fix: just check that the kernel & array are non-empty before convolving.  Is that a good enough solution?
