### ISSUE TITLE
Fits bzero and bscale arguments cause a crash when writing fits file to disk.

### ISSUE THREAD

**Issue by samaloney** [astropy/astropy#10168]
### Description

Setting the bzero and bscale argument in a fits Column results in errors when writing the resulting fits HDUL to a file.

### Expected behavior

The bzero and bscale are applied and the HUDL is written to disk

### Actual behavior

Crash as show below, it seem that when the bscale and bzero are being applied the input value has already been typecast to the specified format but this need to be done after application of bscale and bzero. So at this point
https://github.com/astropy/astropy/blob/d91f4441ee45f406efa3a470fa092392b806190d/astropy/io/fits/fitsrec.py#L1134-L1137
point dummy is already type case the fits paper suggests they should be floating point number.

### Steps to Reproduce

1. Tried values I was using.
2. Tried the default values as indicated in the fits paper `TSCALEn=1.0`, `TZEROn=0.0`

```python
c = [fits.Column(name='t', format='I', bzero=2.0**15, bscale=0.1, unit='s', 
        array=np.array(2.0**np.arange(1, 17)-1))]
bt = fits.BinTableHDU.from_columns(c)
hdul = fits.HDUList([fits.PrimaryHDU(), bt])
hdul.writeto('test.fits', overwrite=True)
---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
<ipython-input-304-da4d78d26915> in <module>
      2 bt = fits.BinTableHDU.from_columns(c)
      3 hdul = fits.HDUList([fits.PrimaryHDU(), bt])
----> 4 hdul.writeto('test.fits', overwrite=True)

~/.virtualenvs/stix/lib/python3.7/site-packages/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    533                     warnings.warn(message, warning_type, stacklevel=2)
    534
--> 535             return function(*args, **kwargs)
    536
    537         return wrapper

~/.virtualenvs/stix/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py in writeto(self, fileobj, output_verify, overwrite, checksum)
    941         with _free_space_check(self, dirname=dirname):
    942             for hdu in self:
--> 943                 hdu._prewriteto(checksum=checksum)
    944                 hdu._writeto(hdulist._file)
    945                 hdu._postwriteto()

~/.virtualenvs/stix/lib/python3.7/site-packages/astropy/io/fits/hdu/table.py in _prewriteto(self, checksum, inplace)
    500         if self._has_data:
    501             self.data._scale_back(
--> 502                 update_heap_pointers=not self._manages_own_heap)
    503             # check TFIELDS and NAXIS2
    504             self._header['TFIELDS'] = len(self.data._coldefs)

~/.virtualenvs/stix/lib/python3.7/site-packages/astropy/io/fits/fitsrec.py in _scale_back(self, update_heap_pointers)
   1133                     dummy = field.copy()
   1134                     if _zero:
-> 1135                         dummy -= bzero
   1136                     if _scale:
   1137                         dummy /= bscale

UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('float64') to dtype('int16') with casting rule 'same_kind'
```

With default values from fits paper.

```python
c = [fits.Column(name='t', format='I', bzero=1.0, bscale=1.0, unit='s', array=np.array(2.0**np.arange(1, 17)-1))]
bt = fits.BinTableHDU.from_columns(c)
hdul = fits.HDUList([fits.PrimaryHDU(), bt])
hdul.writeto('test.fits', overwrite=True)
---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
<ipython-input-305-3f0391ec4df8> in <module>
      2 bt = fits.BinTableHDU.from_columns(c)
      3 hdul = fits.HDUList([fits.PrimaryHDU(), bt])
----> 4 hdul.writeto('test.fits', overwrite=True)

~/.virtualenvs/stix/lib/python3.7/site-packages/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    533                     warnings.warn(message, warning_type, stacklevel=2)
    534
--> 535             return function(*args, **kwargs)
    536
    537         return wrapper

~/.virtualenvs/stix/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py in writeto(self, fileobj, output_verify, overwrite, checksum)
    941         with _free_space_check(self, dirname=dirname):
    942             for hdu in self:
--> 943                 hdu._prewriteto(checksum=checksum)
    944                 hdu._writeto(hdulist._file)
    945                 hdu._postwriteto()

~/.virtualenvs/stix/lib/python3.7/site-packages/astropy/io/fits/hdu/table.py in _prewriteto(self, checksum, inplace)
    500         if self._has_data:
    501             self.data._scale_back(
--> 502                 update_heap_pointers=not self._manages_own_heap)
    503             # check TFIELDS and NAXIS2
    504             self._header['TFIELDS'] = len(self.data._coldefs)

~/.virtualenvs/stix/lib/python3.7/site-packages/astropy/io/fits/fitsrec.py in _scale_back(self, update_heap_pointers)
   1133                     dummy = field.copy()
   1134                     if _zero:
-> 1135                         dummy -= bzero
   1136                     if _scale:
   1137                         dummy /= bscale

UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('float64') to dtype('int16') with casting rule 'same_kind'
```

### System Details

Darwin-19.3.0-x86_64-i386-64bit
Python 3.7.0 (default, Nov  7 2018, 00:55:12)
[Clang 10.0.0 (clang-1000.11.45.5)]
Numpy 1.17.2
astropy 4.0.1.post1
Scipy 1.3.1

**Comment by samaloney** [comment]
I have been looking into this a bit myself an the input array is actually typecast early when the column is created the input array is type cast here https://github.com/astropy/astropy/blob/d91f4441ee45f406efa3a470fa092392b806190d/astropy/io/fits/column.py#L659
and the original type and associate information is lost.

**Comment by dhomeier** [comment]
No, afaics the data are still preserved, as `_convert_to_valid_data_type` explicitly handles the cases of pseudo-unsigned int with the appropriate offsets.
Essentially a fix like I suggested on Slack should work; perhaps replacing the in-place operations only if really needed in `fitsrec.py`:
```
                    if _zero:
                        try:
                            dummy -= bzero
                        except UFuncTypeError:
                            dummy = dummy - bzero
                    if _scale:
                        try:
                            dummy /= bscale
                        # Strangely, 'subtract' raises UFuncTypeError, 'true_divide' a TypeError
                        except (TypeError, UFuncTypeError):
                            dummy = dummy / bscale
```
That seems to resolve the basic conversion error, at least the table is written with the expected numbers, when checking with `fv`. Validating with `io.fits` is not directly possible since reading with non-integer `BZERO`/`BSCALE` fails similarly in [_convert_other](https://github.com/astropy/astropy/blob/d91f4441ee45f406efa3a470fa092392b806190d/astropy/io/fits/fitsrec.py#L970-L971).
```
  File "/sw/lib/python3.8/site-packages/astropy/io/fits/fitsrec.py", line 726, in field
    converted = self._convert_other(column, field, recformat)
  File "/sw/lib/python3.8/site-packages/astropy/io/fits/fitsrec.py", line 971, in _convert_other
    np.multiply(field, bscale, field)
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('uint16') with casting rule 'same_kind'
```
Just catching the exceptions there as well does not get one much further, since the rescaled data seem completely botched.

Also your original test case has its problems, as the `bscale=0.1` means that the written table column `dummy/bscale` would still exceed `uint16` range. But even for numbers within the range it's not clear of the simple fix sketched above does write correct values, if the data array is cast to the FITS format too early before the `bzero` and `bscale` adjustments are made. Although I am starting to doubt if `fv` handles that case correctly either...

**Comment by saimn** [comment]
I guess we need something similar to what was done for ImageHDU (when Numpy's casting rules changed a few years ago): 
https://github.com/astropy/astropy/blob/d91f4441ee45f406efa3a470fa092392b806190d/astropy/io/fits/hdu/image.py#L528
And the same when reading such a file, thanks @dhomeier for pointing that.

**Comment by samaloney** [comment]
I actually don't it is possible to use the unsigned int bzero trick and a bscale other than 1.0 by definition. From the paper
`physical_value = TZEROn + TSCALn * field_value` 
so if `TSCALn` is anything but one I don't think it will behave as expected.

Also from the [paper](https://fits.gsfc.nasa.gov/standard40/fits_standard40aa-le.pdf) p16, Section  5.2.5. Unsigned integers
> Instead, the appropriate offset must be applied to the unsigned integer to shift the value into the range of the corresponding signed integer, which is then stored in the FITS file. The BSCALE keyword shall have the **default value of 1.0** in this case, and the
appropriate BZERO value, as a function of BITPIX, is specified
in Table 11.

A case of RTFM from my side 🤦probably should raise an error if a user tries this? 

I think it should work for normal signed ints but doesn't
```python
c = [fits.Column(name='t', format='I', bzero=0.0, bscale=10.0,
        array=np.array([-2**15, 0, 2**15-1])*10)]
bt = fits.BinTableHDU.from_columns(c, uint=True)
hdul = fits.HDUList([fits.PrimaryHDU(), bt])
hdul.writeto('test.fits', overwrite=True)
...
#same errors as before
```
Tired the fixes as suggested by @dhomeier  and @saimn which do resolve the errors but the values are not what I would expect. An may related the the conversion:
> No, afaics the data are still preserved, as _convert_to_valid_data_type explicitly handles the cases of pseudo-unsigned int with the appropriate offsets.
But the input array has to be in physical_units with bzero and bscale applied so will have to be some kind of float which looks to be irreversibly cast in `_convert_to_valid_data_type`. Imagine the physical value is 10.5 for I,J,K this will be cast to a int here and then we apply a bscale of 5.25 and the result is recast to an int (10/5.25=1.9->1) which is not correct, I think it should bebe (10.5/5.25=2.0 -> 2)?

**Comment by dhomeier** [comment]
> But the input array has to be in physical_units with bzero and bscale applied so will have to be some kind of float which looks to be irreversibly cast in `_convert_to_valid_data_type`. Imagine the physical value is 10.5 for I,J,K this will be cast to a int here and then we apply a bscale of 5.25 and the result is recast to an int (10/5.25=1.9->1) which is not correct, I think it should bebe (10.5/5.25=2.0 -> 2)?

Yes, ideally I think it should be checked if any of `array`, `bzero` or `bscale` (or rather `1 / bscale`) are non-integer-valued, and in that case all conversions be made on float that would only be converted to the `format`-type in the last step.

And in principle it seems legitimate, having e.g. input data in the range 0-6400 that are only needed at 0.1 precision, to store them as unsigned `I` with `BSCALE = 0.1`, but I agree with your reading of the standard that this shall not be accepted. At the very least checking for the correct ranges and types would become quite complicated in such a case. But indeed then a verification error should be raised.

**Comment by samaloney** [comment]
> At the very least checking for the correct ranges and types would become quite complicated in such a case. But indeed then a verification error should be raised.

Yea I suppose what I really meant was that for uints with bzero and bscale=1.0 the mapping from physicals to field values is 1-to-1 but with other values it's non-trivial going from physical to field values as you noted. I think an option would be to allow the field value to be directly set through the use of a keyword etc I think this could be achieved using the `_physical_values` attribute?

**Comment by dhomeier** [comment]
> I think an option would be to allow the field value to be directly set through the use of a keyword etc I think this could be achieved using the `_physical_values` attribute?

You mean adding an option to the writer that leaves `column._physical_values` at `True` and signal through that, that the original values of `array` shall be written to the hdu unmodified? That would leave the transformation in the responsibility of the user, but I don't think this is a good solution.

1. _If_ there is consensus that `bscale != 1.0` values for `uint` data violate the standard, I don't think think support for writing such files will be accepted. Although I don't see any general restrictions on using arbitrary combinations of `BZERO` and `BSCALE`, and the particular convention on interpreting an `I`with the specific `2**15` offset as `uint16` is maybe really more a reading issue...

2. While the combined processing of scale and zero offset may be not trivial, it is certainly possible to implement in a verifiable manner. My concern was rather that it would become complicated for the user to keep track of the supported data range in their data and the FITS data object. But leaving the entire transformation up to them would not make this easier.

3. I one really wants to write data directly to FITS bypassing all the conversions, I think the low-level access routines would still permit this.

**Comment by matteobachetti** [comment]
Hi, I'm having an issue with this, when adding columns to an existing FITS file (from NICER) and then trying to write the modified file to disk. The problem arises in _existing_ columns, not the ones I add, and the only workaround seems removing these columns before applying my modifications. 
It seems that there are various cases where even official mission files have BZERO/BSCALE set to floating values and the actual columns having integer values, so it would be really good if Astropy allowed to handle these cases, maybe with a warning.

**Comment by samaloney** [comment]
Just an update the default values from the fits paper now work but the original values I was using still cause a crash but it seem to be a different error now?

```
c = [fits.Column(name='t', format='I', bzero=2.0**15, bscale=0.1, unit='s',
    ...:         array=np.array(2.0**np.arange(1, 17)-1))]
    ...: bt = fits.BinTableHDU.from_columns(c)
    ...: hdul = fits.HDUList([fits.PrimaryHDU(), bt])
    ...: hdul.writeto('test.fits', overwrite=True)
---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
Cell In[11], line 5
      3 bt = fits.BinTableHDU.from_columns(c)
      4 hdul = fits.HDUList([fits.PrimaryHDU(), bt])
----> 5 hdul.writeto('test.fits', overwrite=True)

File ~/.virtualenvs/radiospectra/lib/python3.12/site-packages/astropy/io/fits/hdu/hdulist.py:1059, in HDUList.writeto(self, fileobj, output_verify, overwrite, checksum)
   1057 for hdu in self:
   1058     hdu._output_checksum = checksum
-> 1059     hdu._prewriteto()
   1060     hdu._writeto(hdulist._file)
   1061     hdu._postwriteto()

File ~/.virtualenvs/radiospectra/lib/python3.12/site-packages/astropy/io/fits/hdu/table.py:482, in _TableBaseHDU._prewriteto(self, inplace)
    480 def _prewriteto(self, inplace=False):
    481     if self._has_data:
--> 482         self.data._scale_back(update_heap_pointers=not self._manages_own_heap)
    483         # check TFIELDS and NAXIS2
    484         self._header["TFIELDS"] = len(self.data._coldefs)

File ~/.virtualenvs/radiospectra/lib/python3.12/site-packages/astropy/io/fits/fitsrec.py:1193, in FITS_rec._scale_back(self, update_heap_pointers)
   1191     dummy -= np.array(bzero).astype(dummy.dtype, casting="unsafe")
   1192 if _scale:
-> 1193     dummy /= bscale
   1194 # This will set the raw values in the recarray back to
   1195 # their non-physical storage values, so the column should
   1196 # be mark is not scaled
   1197 column._physical_values = False

UFuncTypeError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int16') with casting rule 'same_kind'
```
