### ISSUE TITLE
TST: pyinstaller cron job broken

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10368]
### Description

Example log:  https://travis-ci.org/github/astropy/astropy/jobs/688437965 

```
[9319] /home/travis/build/astropy/astropy/.pyinstaller$ /home/travis/build/astropy/astropy/.pyinstaller/run_astropy_tests
Traceback (most recent call last):
  File "run_astropy_tests.py", line 5, in <module>
    import astropy  # noqa
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/travis/build/astropy/astropy/.tox/pyinstaller/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "astropy/__init__.py", line 333, in <module>
  File "astropy/__init__.py", line 326, in _get_bibtex
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEII9WN88/astropy/CITATION'
[9320] Failed to execute script run_astropy_tests
ERROR: InvocationError for command /home/travis/build/astropy/astropy/.pyinstaller/run_astropy_tests (exited with code 255) (exited with code 255)
```

### Expected behavior

The job passes.

**Comment by pllim** [comment]
Well, symlink was removed and this file is in manifest. Not sure what is going on.

https://github.com/astropy/astropy/blob/b8e827810207a0ac5e12be67c94c9c2990e4967b/MANIFEST.in#L7

**Comment by astrofrog** [comment]
I wonder if somehow the astropy hook is not collecting that file on this line:

https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-astropy.py#L16

**Comment by pllim** [comment]
We also defined it as package data:

https://github.com/astropy/astropy/blob/b8e827810207a0ac5e12be67c94c9c2990e4967b/setup.cfg#L83

Glancing at https://github.com/pyinstaller/pyinstaller/blob/f11fb8b87f8797b7e086a09f13be94003554b777/PyInstaller/utils/hooks/__init__.py#L666 , can't tell if it is something we overlooked or a bug of `pyinstaller`.

**Comment by astrofrog** [comment]
It might be a recent bug in pyinstaller as I think I got the job working a couple weeks ago. Will need to investigate!

**Comment by pllim** [comment]
I think the failure went away.
