### ISSUE TITLE
TST: html-docs job failing on CircleCI

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10473]
Not sure when it started but now I see something like this on `master` and also in my PR(s). RTD can build fine though but its log also shows similar warning.

```
Warning, treated as error:
 
autodoc: failed to import method '__call__' from module 'keyword'; the following exception was raised:
 
Traceback (most recent call last):
 
  File "/home/circleci/project/.tox/build_docs/lib/python3.7/site-packages/sphinx/util/inspect.py", line 323, in safe_getattr
 
    return getattr(obj, name, *defargs)
 
AttributeError: module 'keyword' has no attribute '__call__'
 

 
During handling of the above exception, another exception occurred:
 

 
Traceback (most recent call last):
 
  File "/home/circleci/project/.tox/build_docs/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 71, in import_object
 
    obj = attrgetter(obj, attrname)
 
  File "/home/circleci/project/.tox/build_docs/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 246, in get_attr
 
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
 
  File "/home/circleci/project/.tox/build_docs/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 2059, in autodoc_attrgetter
 
    return safe_getattr(obj, name, *defargs)
 
  File "/home/circleci/project/.tox/build_docs/lib/python3.7/site-packages/sphinx/util/inspect.py", line 339, in safe_getattr
 
    raise AttributeError(name)
 
AttributeError: __call__
```

Maybe some clue from RTD log:
```
/home/docs/checkouts/readthedocs.org/user_builds/astropy/checkouts/latest/docs/api/astropy.tests.runner.keyword.rst:14:<autosummary>:1: WARNING: py:obj reference target not found: astropy.tests.runner.keyword.__call__
```

**Comment by pllim** [comment]
Maybe this is because Sphinx version is different. Last successful log used Sphinx 3.0.4 and the failed log used Sphinx 3.1.0.
