### ISSUE TITLE
IndexError when accessing EarthLocation.info

### ISSUE THREAD

**Issue by astromancer** [astropy/astropy#10591]
### Description

EarthLocation info display is broken on current master

### Expected behavior

display the site info

### Steps to Reproduce

```python
from astropy.coordinates import EarthLocation

keck = EarthLocation.of_site('Keck Observatory')
keck.info
```
Produces the following exception
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hannes/work/repos/astropy/astropy/utils/data_info.py", line 488, in __repr__
    self.__call__(out=out)
  File "/home/hannes/work/repos/astropy/astropy/utils/data_info.py", line 472, in __call__
    info['length'] = len(dat)
  File "/home/hannes/work/repos/astropy/astropy/coordinates/earth.py", line 799, in __len__
    raise IndexError('0-d EarthLocation arrays cannot be indexed')
IndexError: 0-d EarthLocation arrays cannot be indexed
```

### System Details

```
>>> import platform; print(platform.platform())
Linux-4.15.0-111-generic-x86_64-with-Ubuntu-18.04-bionic
>>> import sys; print("Python", sys.version)
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.20.0.dev0+2ccfd79
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.2.dev434+gd1e34fb0c
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.5.1
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.2.1.post2723+g89fa0e43b
```

**Comment by pllim** [comment]
cc @eteq and @adrn
