### ISSUE TITLE
Installing astropy from pypi fails with ModuleNotFoundError: No module named 'extension_helpers'

### ISSUE THREAD

**Issue by mfeldt** [astropy/astropy#11057]
### Description
A test build on travis failed due to astropy not installing properly. Log is 

```
Searching for astropy

Reading https://pypi.org/simple/astropy/

Downloading https://files.pythonhosted.org/packages/76/cc/1679628361120106d28438ca8f178e615c3e380e9d089dac363aa61bb1ae/astropy-4.2rc1.tar.gz#sha256=ebb4e2fd3dcdfd6b4fbf7f500242431f81ff0ada38a2ca59a3c07a2146e610af

Best match: astropy 4.2rc1

Processing astropy-4.2rc1.tar.gz

Writing /tmp/easy_install-81mebc2u/astropy-4.2rc1/setup.cfg

Running astropy-4.2rc1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-81mebc2u/astropy-4.2rc1/egg-dist-tmp-ctathtm1

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules

    yield saved

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context

    yield

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup

    _execfile(setup_script, ns)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile

    exec(code, globals, locals)

  File "/tmp/easy_install-81mebc2u/astropy-4.2rc1/setup.py", line 67, in <module>

ModuleNotFoundError: No module named 'extension_helpers'

During handling of the above exception, another exception occurred:

```

### Expected behavior

I expected astropy to instll properly

### Actual behavior
fatal exception

### System Details

See output on https://travis-ci.org/github/mfeldt/AOSAT/builds/744421972

**Comment by Cadair** [comment]
You need to replace the `python setup.py install` command with `pip install .` installing astropy directly through `setup.py` is no longer supported.

**Comment by mfeldt** [comment]
How would I teach travis to do so?

**Comment by Cadair** [comment]
Change this line: https://github.com/mfeldt/AOSAT/blob/master/.travis.yml#L3 to `pip install .`

**Comment by mfeldt** [comment]
perfect, will try that! thx!
