### ISSUE TITLE
astropy on big sur

### ISSUE THREAD

**Issue by thewoz** [astropy/astropy#11095]
Hi,

I have install pynton 3.9 with brew
an I have numpy 1.19.4

when I try to install on Big Sur astropy I got:
```
ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/57/ffw3x1tj6tx38bnhbbzhyysm0000gn/T/tmpl5ki95vg
       cwd: /private/var/folders/57/ffw3x1tj6tx38bnhbbzhyysm0000gn/T/pip-install-4vm5hbmx/astropy
  Complete output (37 lines):
  init_dgelsd failed init
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/57/ffw3x1tj6tx38bnhbbzhyysm0000gn/T/pip-build-env-ofjq56ls/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/private/var/folders/57/ffw3x1tj6tx38bnhbbzhyysm0000gn/T/pip-build-env-ofjq56ls/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/57/ffw3x1tj6tx38bnhbbzhyysm0000gn/T/pip-build-env-ofjq56ls/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 70, in <module>
      ext_modules=get_extensions())
    File "/private/var/folders/57/ffw3x1tj6tx38bnhbbzhyysm0000gn/T/pip-build-env-ofjq56ls/overlay/lib/python3.9/site-packages/extension_helpers/_setup_helpers.py", line 48, in get_extensions
      for setuppkg in iter_setup_packages(srcdir, packages):
    File "/private/var/folders/57/ffw3x1tj6tx38bnhbbzhyysm0000gn/T/pip-build-env-ofjq56ls/overlay/lib/python3.9/site-packages/extension_helpers/_setup_helpers.py", line 109, in iter_setup_packages
      module = import_file(setup_package,
    File "/private/var/folders/57/ffw3x1tj6tx38bnhbbzhyysm0000gn/T/pip-build-env-ofjq56ls/overlay/lib/python3.9/site-packages/extension_helpers/_utils.py", line 194, in import_file
      mod = loader.load_module()
    File "<frozen importlib._bootstrap_external>", line 469, in _check_name_wrapper
    File "<frozen importlib._bootstrap_external>", line 969, in load_module
    File "<frozen importlib._bootstrap_external>", line 794, in load_module
    File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
    File "<frozen importlib._bootstrap>", line 711, in _load
    File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 790, in exec_module
    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    File "./astropy/wcs/setup_package.py", line 14, in <module>
      import numpy
    File "/private/var/folders/57/ffw3x1tj6tx38bnhbbzhyysm0000gn/T/pip-build-env-ofjq56ls/overlay/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
      raise RuntimeError(msg)
  RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
  RankWarning: Polyfit may be poorly conditioned
  
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/57/ffw3x1tj6tx38bnhbbzhyysm0000gn/T/tmpl5ki95vg Check the logs for full command output.
```

**Comment by saimn** [comment]
As the error says, this is an issue with you Numpy installation:
> Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.

When compiling Numpy you must choose another blas library.

**Comment by thewoz** [comment]
Thank.
Do you know how to do that?
I have install openblas via home-brew

**Comment by saimn** [comment]
I guess https://numpy.org/doc/stable/user/building.html?highlight=installation#accelerated-blas-lapack-libraries could help (I don't know much more for MacOS, sorry)

**Comment by saimn** [comment]
Or https://github.com/numpy/numpy/issues/15947

**Comment by thewoz** [comment]
Thank you!
