### ISSUE TITLE
Error in ASCII encoder when writing to fits (v3.2.3)

### ISSUE THREAD

**Issue by Alex-Broughton** [astropy/astropy#11163]
With Astropy-3.2.3, I get this error in the ascii encoder, which seems like it cold be a version issue.
```
2020-12-11 16:50:10 INFO    GTAnalysis.write_fits(): Writing /data/users/abrought/ML_Project/Galactic_Center_Machine_Learning/Gamma_Ray_Sims/Process_GALPROP_Output/after_setup.fits...
WARNING: Format %s cannot be mapped to the accepted TDISPn keyword values.  Format will not be moved into TDISPn keyword. [astropy.io.fits.column]
WARNING: Format %f cannot be mapped to the accepted TDISPn keyword values.  Format will not be moved into TDISPn keyword. [astropy.io.fits.column]
Traceback (most recent call last):
  File "run_fermipy.py", line 15, in <module>
    gta.write_roi('after_setup')
  File "/data/users/abrought/miniconda/envs/myenv/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 3723, in write_roi
    self.write_fits(fitsfile)
  File "/data/users/abrought/miniconda/envs/myenv/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 3794, in write_fits
    fits_utils.write_hdus(hdus, fitsfile)
  File "/data/users/abrought/miniconda/envs/myenv/lib/python3.7/site-packages/fermipy/fits_utils.py", line 112, in write_hdus
    hdulist.writeto(outfile, overwrite=True)
  File "/data/users/abrought/miniconda/envs/myenv/lib/python3.7/site-packages/astropy/utils/decorators.py", line 521, in wrapper
    return function(*args, **kwargs)
  File "/data/users/abrought/miniconda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 928, in writeto
    hdu._prewriteto(checksum=checksum)
  File "/data/users/abrought/miniconda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/table.py", line 502, in _prewriteto
    update_heap_pointers=not self._manages_own_heap)
  File "/data/users/abrought/miniconda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/fitsrec.py", line 1136, in _scale_back
    self._scale_back_strings(indx, dummy, raw_field)
  File "/data/users/abrought/miniconda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/fitsrec.py", line 1183, in _scale_back_strings
    _ascii_encode(input_field, out=output_field)
  File "/data/users/abrought/miniconda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/fitsrec.py", line 1321, in _ascii_encode
    op_flags=op_flags, flags=['zerosize_ok'])
ValueError: operands could not be broadcast together with shapes (0,) (0,10) 
```

**Comment by saimn** [comment]
@Alex-Broughton - Could you provide an example to reproduce this issue, if this is still an issue for you ?

**Comment by Alex-Broughton** [comment]
The issue is already fixed.

Alex

**Comment by saimn** [comment]
Ok, closing then.

**Comment by ldivenere** [comment]
> The issue is already fixed. Alex

@Alex-Broughton I'm running in the same issue. How was it solved for you?
