### ISSUE TITLE
Error installing older version of astropy

### ISSUE THREAD

**Issue by Alex-Broughton** [astropy/astropy#11160]
Installing astropy==2.0.4 with pip and cython==0.29.21 in a Python3 environment. Are these compatilble?

```
    building 'astropy.table._np_utils' extension
    creating build/temp.linux-x86_64-3.7/astropy/table
    /data/users/abrought/miniconda/envs/env/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data/users/abrought/miniconda/envs/env/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /data/users/abrought/miniconda/envs/env/include -fPIC -I/data/users/abrought/miniconda/envs/env/lib/python3.7/site-packages/numpy/core/include -I/data/users/abrought/miniconda/envs/env/include/python3.7m -c astropy/table/_np_utils.c -o build/temp.linux-x86_64-3.7/astropy/table/_np_utils.o -Wp,-w -Wno-unused-function
    astropy/table/_np_utils.c: In function '__Pyx__ExceptionSave':
    astropy/table/_np_utils.c:7287:21: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_type'; did you mean 'curexc_type'?
         *type = tstate->exc_type;
                         ^~~~~~~~
                         curexc_type
    astropy/table/_np_utils.c:7288:22: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_value'; did you mean 'curexc_value'?
         *value = tstate->exc_value;
                          ^~~~~~~~~
                          curexc_value
    astropy/table/_np_utils.c:7289:19: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
         *tb = tstate->exc_traceback;
                       ^~~~~~~~~~~~~
                       curexc_traceback
    astropy/table/_np_utils.c: In function '__Pyx__ExceptionReset':
    astropy/table/_np_utils.c:7296:24: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_type'; did you mean 'curexc_type'?
         tmp_type = tstate->exc_type;
                            ^~~~~~~~
                            curexc_type
    astropy/table/_np_utils.c:7297:25: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_value'; did you mean 'curexc_value'?
         tmp_value = tstate->exc_value;
                             ^~~~~~~~~
                             curexc_value
    astropy/table/_np_utils.c:7298:22: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
         tmp_tb = tstate->exc_traceback;
                          ^~~~~~~~~~~~~
                          curexc_traceback
    astropy/table/_np_utils.c:7299:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_type'; did you mean 'curexc_type'?
         tstate->exc_type = type;
                 ^~~~~~~~
                 curexc_type
    astropy/table/_np_utils.c:7300:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_value'; did you mean 'curexc_value'?
         tstate->exc_value = value;
                 ^~~~~~~~~
                 curexc_value
    astropy/table/_np_utils.c:7301:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
         tstate->exc_traceback = tb;
                 ^~~~~~~~~~~~~
                 curexc_traceback
    astropy/table/_np_utils.c: In function '__Pyx__GetException':
    astropy/table/_np_utils.c:7371:24: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_type'; did you mean 'curexc_type'?
         tmp_type = tstate->exc_type;
                            ^~~~~~~~
                            curexc_type
    astropy/table/_np_utils.c:7372:25: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_value'; did you mean 'curexc_value'?
         tmp_value = tstate->exc_value;
                             ^~~~~~~~~
                             curexc_value
    astropy/table/_np_utils.c:7373:22: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
         tmp_tb = tstate->exc_traceback;
                          ^~~~~~~~~~~~~
                          curexc_traceback
    astropy/table/_np_utils.c:7374:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_type'; did you mean 'curexc_type'?
         tstate->exc_type = local_type;
                 ^~~~~~~~
                 curexc_type
    astropy/table/_np_utils.c:7375:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_value'; did you mean 'curexc_value'?
         tstate->exc_value = local_value;
                 ^~~~~~~~~
                 curexc_value
    astropy/table/_np_utils.c:7376:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
         tstate->exc_traceback = local_tb;
                 ^~~~~~~~~~~~~
                 curexc_traceback
    error: command '/data/users/abrought/miniconda/envs/env/bin/x86_64-conda-linux-gnu-cc' failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of astropy
  Moving to /data/users/abrought/miniconda/envs/env/bin/fits2bitmap
   from /tmp/pip-uninstall-68pjcb65/fits2bitmap
  Moving to /data/users/abrought/miniconda/envs/env/bin/fitscheck
   from /tmp/pip-uninstall-68pjcb65/fitscheck
  Moving to /data/users/abrought/miniconda/envs/env/bin/fitsdiff
   from /tmp/pip-uninstall-68pjcb65/fitsdiff
  Moving to /data/users/abrought/miniconda/envs/env/bin/fitsheader
   from /tmp/pip-uninstall-68pjcb65/fitsheader
  Moving to /data/users/abrought/miniconda/envs/env/bin/fitsinfo
   from /tmp/pip-uninstall-68pjcb65/fitsinfo
  Moving to /data/users/abrought/miniconda/envs/env/bin/samp_hub
   from /tmp/pip-uninstall-68pjcb65/samp_hub
  Moving to /data/users/abrought/miniconda/envs/env/bin/volint
   from /tmp/pip-uninstall-68pjcb65/volint
  Moving to /data/users/abrought/miniconda/envs/env/bin/wcslint
   from /tmp/pip-uninstall-68pjcb65/wcslint
  Moving to /data/users/abrought/miniconda/envs/env/lib/python3.7/site-packages/astropy-2.0.9.dist-info/
   from /data/users/abrought/miniconda/envs/env/lib/python3.7/site-packages/~stropy-2.0.9.dist-info
  Moving to /data/users/abrought/miniconda/envs/env/lib/python3.7/site-packages/astropy/
   from /data/users/abrought/miniconda/envs/env/lib/python3.7/site-packages/~stropy
ERROR: Command errored out with exit status 1: /data/users/abrought/miniconda/envs/env/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z3k3d51y/astropy_3e57fa01abfa4fdfa1c1d68c422022a4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z3k3d51y/astropy_3e57fa01abfa4fdfa1c1d68c422022a4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-k3_s5bfk/install-record.txt --single-version-externally-managed --compile --install-headers /data/users/abrought/miniconda/envs/env/include/python3.7m/astropy Check the logs for full command output.

```

**Comment by pllim** [comment]
Version 2 is no longer supported. Currently long-term support (LTS) is version 4. Is there a reason why you must use version 2?

You might want to try older versions of everything else to make it work if you must, but there is no plan to make it compatible with newer upstream releases. We apologize for any inconvenience caused.

**Comment by saimn** [comment]
FWIW, installing astropy 2.0.16 on Python 3.7 works for me.

**Comment by pllim** [comment]
Hard to say what is wrong... I see a conda path, so who knows what kind of C compiler or numpy version is in that env.

**Comment by Alex-Broughton** [comment]
I have numpy version 1.19.4 in my conda environment.

The reason I wanted to install an older version of astropy is because running with Astropy 4.x.x, I get this error: 
```
2020-12-10 11:44:59 INFO    GTAnalysis.write_fits(): Writing /data/users/abrought/ML_Project/Galactic_Center_Machine_Learning/Gamma_Ray_Sims/Process_GALPROP_Output/after_setup.fits...
WARNING: Format %s cannot be mapped to the accepted TDISPn keyword values.  Format will not be moved into TDISPn keyword. [astropy.io.fits.column]
WARNING: Format %s cannot be mapped to the accepted TDISPn keyword values.  Format will not be moved into TDISPn keyword. [astropy.io.fits.column]
WARNING: Format %f cannot be mapped to the accepted TDISPn keyword values.  Format will not be moved into TDISPn keyword. [astropy.io.fits.column]
Traceback (most recent call last):
  File "/data/users/abrought/miniconda/envs/env/lib/python3.7/site-packages/astropy/table/table.py", line 2766, in insert_row
    newcol = col.insert(index, val, axis=0)
  File "/data/users/abrought/miniconda/envs/env/lib/python3.7/site-packages/astropy/table/column.py", line 1065, in insert
    self_for_insert = _expand_string_array_for_values(self, values)
  File "/data/users/abrought/miniconda/envs/env/lib/python3.7/site-packages/astropy/table/column.py", line 147, in _expand_string_array_for_values
    values_str_len = np.char.str_len(values).max()
  File "<__array_function__ internals>", line 6, in str_len
  File "/data/users/abrought/miniconda/envs/env/lib/python3.7/site-packages/numpy/core/defchararray.py", line 283, in str_len
    return _vec_string(a, int_, '__len__')
TypeError: string operation on non-string array

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_fermipy.py", line 15, in <module>
    gta.write_roi('after_setup')
  File "/data/users/abrought/miniconda/envs/env/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 3723, in write_roi
    self.write_fits(fitsfile)
  File "/data/users/abrought/miniconda/envs/env/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 3768, in write_fits
    tab = self.roi.create_source_table()
  File "/data/users/abrought/miniconda/envs/env/lib/python3.7/site-packages/fermipy/roi_model.py", line 2171, in create_source_table
    tab.add_row([row_dict[k] for k in tab.columns])
  File "/data/users/abrought/miniconda/envs/env/lib/python3.7/site-packages/astropy/table/table.py", line 2658, in add_row
    self.insert_row(len(self), vals, mask)
  File "/data/users/abrought/miniconda/envs/env/lib/python3.7/site-packages/astropy/table/table.py", line 2790, in insert_row
    .format(name, err))
ValueError: Unable to insert row because of exception in column 'spectrum_file':
string operation on non-string array
```

**Comment by pllim** [comment]
Might be a compatibility problem in `fermipy`. Have you ask its devs?

**Comment by Alex-Broughton** [comment]
I think you're right, I'll raise an issue over there. Since 2.x.x is unsupported, I will mark this as resolved.

**Comment by embray** [comment]
Agreed this was not an astropy issue.
