### ISSUE TITLE
Astropy 2.0.16 not working after clean install

### ISSUE THREAD

**Issue by dankocevski** [astropy/astropy#11223]
Any idea why the following isn't working?

```
conda create --name py2.7.15 python=2.7.15
conda activate py2.7.15
conda install astropy

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15

  added / updated specs:
    - astropy


The following NEW packages will be INSTALLED:

  astropy            pkgs/main/linux-64::astropy-2.0.16-py27h7b6447c_0
  atomicwrites       pkgs/main/noarch::atomicwrites-1.4.0-py_0
  attrs              pkgs/main/noarch::attrs-20.3.0-pyhd3eb1b0_0
  blas               pkgs/main/linux-64::blas-1.0-mkl
  funcsigs           pkgs/main/linux-64::funcsigs-1.0.2-py27_0
  intel-openmp       pkgs/main/linux-64::intel-openmp-2020.2-254
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-7.3.0-hdf63c60_0
  mkl                pkgs/main/linux-64::mkl-2020.2-256
  mkl-service        pkgs/main/linux-64::mkl-service-2.3.0-py27he904b0f_0
  mkl_fft            pkgs/main/linux-64::mkl_fft-1.0.15-py27ha843d7b_0
  mkl_random         pkgs/main/linux-64::mkl_random-1.1.0-py27hd6b4f25_0
  more-itertools     pkgs/main/linux-64::more-itertools-5.0.0-py27_0
  numpy              pkgs/main/linux-64::numpy-1.16.6-py27hbc911f0_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.16.6-py27hde5b4d6_0
  pluggy             pkgs/main/linux-64::pluggy-0.6.0-py27_0
  py                 pkgs/main/noarch::py-1.10.0-pyhd3eb1b0_0
  pytest             pkgs/main/linux-64::pytest-3.6.4-py27_0
  six                pkgs/main/noarch::six-1.15.0-py_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
 
conda list
> astropy                   2.0.16           py27h7b6447c_0  

(py2.7.15)$ python
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 19:04:19) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from astropy import coordinates as coord
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python2.7/site-packages/astropy/coordinates/__init__.py", line 12, in <module>
    from .angles import *
  File "/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python2.7/site-packages/astropy/coordinates/angles.py", line 17, in <module>
    from . import angle_utilities as util
  File "/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python2.7/site-packages/astropy/coordinates/angle_utilities.py", line 26, in <module>
    from .. import units as u
  File "/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python2.7/site-packages/astropy/units/__init__.py", line 16, in <module>
    from .decorators import *
  File "/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python2.7/site-packages/astropy/units/decorators.py", line 11, in <module>
    from .physical import _unit_physical_mapping
  File "/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python2.7/site-packages/astropy/units/physical.py", line 17, in <module>
    from . import astrophys
  File "/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python2.7/site-packages/astropy/units/astrophys.py", line 46, in <module>
    def_unit(['lyr', 'lightyear'], (_si.c * si.yr).to(si.m),
  File "/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python2.7/site-packages/astropy/constants/constant.py", line 45, in wrapper
    self.unit.to(inst.unit)
  File "/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python2.7/site-packages/astropy/units/quantity.py", line 895, in unit
    return self._unit
  File "/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python2.7/site-packages/astropy/utils/decorators.py", line 770, in __get__
    val = self.fget(obj)
  File "/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python2.7/site-packages/astropy/constants/constant.py", line 169, in _unit
    return Unit(self._unit_string)
  File "/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python2.7/site-packages/astropy/units/core.py", line 1820, in __call__
    raise ValueError(msg)
ValueError: 'm / (s)' did not parse as unit: 'module' object has no attribute '_tabversion'
```

The contents of my sys.path are as follows:

```
>>> import sys
>>> sys.path
['', '/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python27.zip', '/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python2.7', '/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python2.7/plat-linux2', '/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python2.7/lib-tk', '/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python2.7/lib-old', '/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python2.7/lib-dynload', '/nfs/slac/g/ki/ki08/kocevski/bin/miniconda2/envs/py2.7.15/lib/python2.7/site-packages'
```
I'm using this install/enviroment to support a legacy data analysis pipeline that is written in python2, so upgrading to python3 isn't really an option unfortunately. Any suggestions on how to resolve this problem would be appreciated.

**Comment by pllim** [comment]
Works for me. I think something is not right with your PYTHONPATH somehow or your installation isn't as clean as you thought. Did you overwrite conda's default path management? What version of conda? I would recommend you comment out any custom PYTHONPATH setup in your shell scripts and use the latest conda version, then let conda do its thing.

```
(py2.7.15) $ python
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 19:04:19) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from astropy import coordinates as coord
>>> 
```

```
(py2.7.15) $ conda --version
conda 4.9.2
```

**Comment by pllim** [comment]
I removed a couple of outdated channels from my `~/.condarc`, leaving `defaults` followed by `conda-forge`. Still works for me.

```
(py2.7.15) $ python
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 19:04:19) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import astropy
>>> astropy.__version__
u'2.0.16'
>>> from astropy import coordinates as coord
>>> 
```

```
(py2.7.15) $ conda list
# packages in environment at .../miniconda/envs/py2.7.15:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
astropy                   2.0.16           py27h7b6447c_0  
atomicwrites              1.4.0                      py_0  
attrs                     20.3.0             pyhd3eb1b0_0  
blas                      1.0                         mkl  
ca-certificates           2020.12.8            h06a4308_0  
certifi                   2020.6.20          pyhd3eb1b0_3  
funcsigs                  1.0.2                    py27_0  
intel-openmp              2020.2                      254  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
mkl                       2020.2                      256  
mkl-service               2.3.0            py27he904b0f_0  
mkl_fft                   1.0.15           py27ha843d7b_0  
mkl_random                1.1.0            py27hd6b4f25_0  
more-itertools            5.0.0                    py27_0  
ncurses                   6.2                  he6710b0_1  
numpy                     1.16.6           py27hbc911f0_0  
numpy-base                1.16.6           py27hde5b4d6_0  
openssl                   1.1.1i               h27cfd23_0  
pip                       19.3.1                   py27_0  
pluggy                    0.6.0                    py27_0  
py                        1.10.0             pyhd3eb1b0_0  
pytest                    3.6.4                    py27_0  
python                    2.7.15               h9bab390_6  
readline                  7.0                  h7b6447c_5  
setuptools                44.0.0                   py27_0  
six                       1.15.0                     py_0  
sqlite                    3.33.0               h62c20be_0  
tk                        8.6.10               hbc83047_0  
wheel                     0.36.2             pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
```

**Comment by pllim** [comment]
Just to ensure there is no namespace confusion, start your Python session from inside an empty directory and try again.

**Comment by pllim** [comment]
I am tentatively adding a "Close?" label because we have dropped support for Python 2 a long time ago and I don't find any problem with the legacy conda install. If you plan to use this pipeline for the long term, perhaps might want to consider porting the relevant parts to Python 3, or consider alternatives. Good luck!

**Comment by dankocevski** [comment]
Thanks for the help.  I tried my best to ensure that outside builds were not being called referenced in my PYTHONPATH and still encountered the error. 

What did work was installing astropy 2.0.15 via pip, which uninstalled the conda installed 2.0.16 version and built a new copy of the library.  I'm guessing the problem was that conda was finding a cached version of 2.0.16 which somehow didn't build or download properly.

Thanks again!

**Comment by taldcroft** [comment]
Looks like this was resolved so closing.

**Comment by pllim** [comment]
@dankocevski , glad you found a solution!
