### ISSUE TITLE
astropy cannot import modules

### ISSUE THREAD

**Issue by sam687** [astropy/astropy#11289]
While running a python script I got this error. It was okay with previous versions of python and astropy. Now I have Python3.8 and astropy 4.0. Is there any solution? 

```
Traceback (most recent call last):
  File "ic348_var_sed.py", line 3, in <module>
    from sedfitter import fit
  File "/home/samrat/anaconda3/lib/python3.8/site-packages/sedfitter/__init__.py", line 5, in <module>
    from .plot import *
  File "/home/samrat/anaconda3/lib/python3.8/site-packages/sedfitter/plot.py", line 31, in <module>
    from .sed import SED
  File "/home/samrat/anaconda3/lib/python3.8/site-packages/sedfitter/sed/__init__.py", line 4, in <module>
    from .cube import *
  File "/home/samrat/anaconda3/lib/python3.8/site-packages/sedfitter/sed/cube.py", line 6, in <module>
    from astropy.extern import six
**ImportError: cannot import name 'six' from 'astropy.extern' (/home/samrat/anaconda3/lib/python3.8/site-packages/astropy/extern/__init__.py)**
```

**Comment by saimn** [comment]
It seems sedfitter has been updated to avoid importing six from astropy: https://github.com/astrofrog/sedfitter/pull/67
But I'm not sure if this has been released. Maybe try their development version ?
Closing since this is not an Astropy issue.
