### ISSUE TITLE
UTC->UT1 conversion fails for zero-length Time object

### ISSUE THREAD

**Issue by lpsinger** [astropy/astropy#11454]
### Description
Converting a zero-length Time object from UTC to UT1 fails because the IERS `_interpolate` method does not handle the corner case of an empty array.

Example code:

```python
from astropy.time import Time
from astropy import units as u
import numpy as np

time = Time.now() + np.arange(24) * u.hour

indices = np.asarray([0, 1, 2], dtype=np.intp)
print(time[indices].ut1) # This is fine

empty_indices = np.asarray([], dtype=np.intp)
print(time[empty_indices].ut1)  # KABOOM
```

### Expected behavior

Should print:

```
[datetime.datetime(2021, 3, 31, 18, 17, 6, 727233)
 datetime.datetime(2021, 3, 31, 19, 17, 6, 727213)
 datetime.datetime(2021, 3, 31, 20, 17, 6, 727193)]
[]
```

### Actual behavior

Actually prints:

```
[datetime.datetime(2021, 3, 31, 18, 17, 6, 727233)
 datetime.datetime(2021, 3, 31, 19, 17, 6, 727213)
 datetime.datetime(2021, 3, 31, 20, 17, 6, 727193)]
Traceback (most recent call last):
  File "./test.py", line 32, in <module>
    print(time[empty_indices].ut1)  # KABOOM
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/time/core.py", line 1327, in __getattr__
    tm._set_scale(attr)
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/time/core.py", line 576, in _set_scale
    args.append(get_dt(jd1, jd2))
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/time/core.py", line 1944, in _get_delta_ut1_utc
    delta = iers_table.ut1_utc(jd1, jd2)
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/utils/iers/iers.py", line 276, in ut1_utc
    return self._interpolate(jd1, jd2, ['UT1_UTC'],
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/utils/iers/iers.py", line 360, in _interpolate
    self._refresh_table_as_needed(mjd)
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/utils/iers/iers.py", line 719, in _refresh_table_as_needed
    max_input_mjd = np.max(mjd)
  File "<__array_function__ internals>", line 5, in amax
  File "/private/tmp/env/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2733, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/private/tmp/env/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

### Steps to Reproduce

(See sample code above)

### System Details

```pycon
>>> import platform; print(platform.platform())
macOS-10.15.7-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.8.8 (default, Mar 18 2021, 06:01:57) 
[Clang 11.0.3 (clang-1103.0.32.62)]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.20.2
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.1.dev3458+g7811614f8
>>> import scipy; print("Scipy", scipy.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'matplotlib'
```

**Comment by pllim** [comment]
I am curious how you managed to install `astropy 4.1.dev3458+g7811614f8`. It should be `4.3.devXXXXXX` by now.

**Comment by mhvk** [comment]
Thanks for reporting, including where the problem lies. That should not be too hard a fix - and probably one we'll need to extend to getting the polar motion information...

**Comment by lpsinger** [comment]
> I am curious how you managed to install `astropy 4.1.dev3458+g7811614f8`. It should be `4.3.devXXXXXX` by now.

Looks like I hadn't run `git fetch upstream --tags` in a while.

**Comment by bhavyakh** [comment]
Is there anyone working on this issue. I would like to work on it.

**Comment by lpsinger** [comment]
Go for it, @bhavyakh!
