### ISSUE TITLE
Issue with our isort config

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#11496]
It seems isort no more likes `length_sort_stdlib = true`:

```
❯ isort docs/conf.py 
Traceback (most recent call last):
  File "/home/simon/.pyenv/versions/3.9.1/bin/isort", line 8, in <module>
    sys.exit(main())
  File "/home/simon/.pyenv/versions/3.9.1/lib/python3.9/site-packages/isort/main.py", line 1065, in main
    config = Config(**config_dict)
  File "/home/simon/.pyenv/versions/3.9.1/lib/python3.9/site-packages/isort/settings.py", line 480, in __init__
    raise UnsupportedSettings(unsupported_config_errors)
isort.exceptions.UnsupportedSettings: isort was provided settings that it doesn't support:

	- length_sort_stdlib = true  (source: '/home/simon/dev/astropy/setup.cfg')

For a complete and up-to-date listing of supported settings see: https://pycqa.github.io/isort/docs/configuration/options/.

❯ isort --version   

                 _                 _
                (_) ___  ___  _ __| |_
                | |/ _/ / _ \/ '__  _/
                | |\__ \/\_\/| |  | |_
                |_|\___/\___/\_/   \_/

      isort your imports, so you don't have to.

                    VERSION 5.8.0
```

**Comment by pllim** [comment]
That sounds familiar but I don't remember from where. I just vaguely remember that @Cadair knows how to fix it.

**Comment by saimn** [comment]
Can I just remove it ? (alphabetical sort FTW :))

**Comment by pllim** [comment]
Sort by length sounds crazy to me. I do alphabetical too. #yolo ❓
