### ISSUE TITLE
`realize_frame(representation)` fails if `representation` is a view

### ISSUE THREAD

**Issue by lpsinger** [astropy/astropy#11572]
### Description
The `realize_frame` method fails if the data passed to it is a view (e.g., resulting from Numpy broadcasting).

The sample code below is a minor variation on #11571, revealing another corner case of frame and representation handling.

### Expected behavior
```
fov.shape=(4,)
center.shape=(360, 181)
frame.shape=(360, 181, 90)
new_shape=(360, 181, 90, 4)
with copy, result.shape=(360, 181, 90, 4)
without copy, result.shape=(360, 181, 90, 4)
```

### Actual behavior
```
fov.shape=(4,)
center.shape=(360, 181)
frame.shape=(360, 181, 90)
new_shape=(360, 181, 90, 4)
with copy, result.shape=(360, 181, 90, 4)
Traceback (most recent call last):
  File "./test.py", line 35, in <module>
    result = frame_bcast.realize_frame(fov_bcast)  # KABOOM
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/coordinates/baseframe.py", line 988, in realize_frame
    return self._replicate(data, **kwargs)
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/coordinates/baseframe.py", line 908, in _replicate
    return self.__class__(data, copy=False, **kwargs)
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/coordinates/builtin_frames/skyoffset.py", line 164, in __init__
    self._set_skyoffset_data_lon_wrap_angle(self.data)
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/coordinates/builtin_frames/skyoffset.py", line 169, in _set_skyoffset_data_lon_wrap_angle
    data.lon.wrap_angle = 180. * u.deg
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/coordinates/angles.py", line 682, in wrap_angle
    self._wrap_internal()
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/coordinates/angles.py", line 673, in _wrap_internal
    self -= (wraps * a360) << self.unit
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/coordinates/angles.py", line 691, in __array_ufunc__
    results = super().__array_ufunc__(*args, **kwargs)
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/units/quantity.py", line 486, in __array_ufunc__
    result = super().__array_ufunc__(function, method, *arrays, **kwargs)
ValueError: output array is read-only
```

### Steps to Reproduce
```python
#!/usr/bin/env python
from astropy.coordinates import SkyCoord, UnitSphericalRepresentation
from astropy import units as u
import numpy as np

# Square field of view of telescope
fov_width = 50 * u.deg
fov_lon = np.asarray([0.5, 0.5, -0.5, -0.5]) * fov_width
fov_lat = np.asarray([0.5, -0.5, -0.5, 0.5]) * fov_width
fov = UnitSphericalRepresentation(fov_lon, fov_lat)
print(f'{fov.shape=}')

# RA, Dec, and roll grid
ra = np.arange(0, 360) * u.deg
dec = np.arange(-90, 91) * u.deg
roll = np.arange(90) * u.deg

# Telescope boresight grid
center = SkyCoord(ra[:, np.newaxis], dec[np.newaxis, :])
print(f'{center.shape=}')

# Frame grid with boresights and roll angles
frame = center[..., np.newaxis].skyoffset_frame(roll)
print(f'{frame.shape=}')

# Expected output shape
new_shape = np.broadcast_shapes(frame[..., np.newaxis].shape, fov.shape)
frame_bcast = np.broadcast_to(frame[..., np.newaxis], new_shape, subok=True)
fov_bcast = np.broadcast_to(fov, new_shape, subok=True)
print(f'{new_shape=}')

result = frame_bcast.realize_frame(fov_bcast.copy())
print(f'with copy, {result.shape=}')

result = frame_bcast.realize_frame(fov_bcast)  # KABOOM
print(f'without copy, {result.shape=}')
```

### System Details
```pycon
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.20.2
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.3.dev1015+g620a5a654
>>> import scipy; print("Scipy", scipy.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'matplotlib'
```

**Comment by mhvk** [comment]
Just thinking first why this goes wrong:
- The immediate problem is that a broadcast array is made read-only (by numpy), combined with the fact that longitude in the sky offset frame has a different wrap angle than RA - hence, the copy does work. In principle, this is correct: the broadcasting means the same memory element might start to refer to multiple roll angles, which is asking for problems!
- A larger problems is that the broadcasting is not done automatically: I would have liked `frame.realize_frame(fov)` to just work! Which is of course your #11571.

To me, the lack of automatic broadcasting is the larger problem!

p.s. I'll change the title to refer to broadcasting rather than a view.
