### ISSUE TITLE
`np.arange` does not work with unitful quantities

### ISSUE THREAD

**Issue by lpsinger** [astropy/astropy#11582]
### Description
The `np.arange` function does not work with unitful quantities. This forces you to convert to a value, and then add the units afterward.

### Expected behavior
```pycon
>>> from astropy import units as u
>>> import numpy as np
>>> np.arange(0, 10, 1) * u.min
<Quantity [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.] min>
>>> np.arange(0 * u.min, 10 * u.min, 1 * u.min)
<Quantity [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.] min>
```

### Actual behavior
```pycon
>>> from astropy import units as u
>>> import numpy as np
>>> np.arange(0, 10, 1) * u.min
<Quantity [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.] min>
>>> np.arange(0 * u.min, 10 * u.min, 1 * u.min)
Traceback (most recent call last):
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/units/quantity.py", line 747, in to_value
    scale = self.unit._to(unit)
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/units/core.py", line 956, in _to
    raise UnitConversionError(
astropy.units.core.UnitConversionError: 'Unit("min")' is not a scaled version of 'Unit(dimensionless)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/units/quantity.py", line 1090, in __float__
    return float(self.to_value(dimensionless_unscaled))
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/units/quantity.py", line 750, in to_value
    value = self._to_value(unit, equivalencies)
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/units/quantity.py", line 669, in _to_value
    return self.unit.to(unit, self.view(np.ndarray),
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/units/core.py", line 993, in to
    return self._get_converter(Unit(other),
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/units/core.py", line 924, in _get_converter
    raise exc
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/units/core.py", line 909, in _get_converter
    return self._apply_equivalencies(
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/units/core.py", line 885, in _apply_equivalencies
    raise UnitConversionError(
astropy.units.core.UnitConversionError: 'min' (time) and '' (dimensionless) are not convertible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/env/lib/python3.8/site-packages/astropy/units/quantity.py", line 1092, in __float__
    raise TypeError('only dimensionless scalar quantities can be '
TypeError: only dimensionless scalar quantities can be converted to Python scalars
```

### Steps to Reproduce
See Python samples above.

### System Details
```pycon
>>> import platform; print(platform.platform())
macOS-10.15.7-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.8.9 (default, Apr  3 2021, 06:24:49) 
[Clang 11.0.3 (clang-1103.0.32.62)]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.20.2
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.3.dev1021+gebb743ea0.d20210415
>>> import scipy; print("Scipy", scipy.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'matplotlib'
```

**Comment by pllim** [comment]
I think this is a known issue covered under https://docs.astropy.org/en/latest/known_issues.html#numpy-array-creation-functions-cannot-be-used-to-initialize-quantity ? Maybe @mhvk can confirm.

**Comment by lpsinger** [comment]
Is there already an issue to capture that? If not I can add a link to this one in the docs.

**Comment by pllim** [comment]
@mhvk , since support for this probably need changes within Numpy, should we close this as "won't fix"?

**Comment by mhvk** [comment]
Indeed, except that I think at some point we should add support for the `like` argument which at least in principle allows some form of control. But that can be tracked in #10575. So, let's close this one. Thanks again for the fix to the docs, @lpsinger!

**Comment by mhvk** [comment]
@dstansby - numpy did more or less what is needed - within astropy, we need to add support for `np.arange` with a `like` argument (since the arguments to `np.arange` cannot be arrays, they cannot be overridden themselves via `__array_function__` - this is unlikely to change).

I have not gotten around to it mostly because it doesn't seem super useful - `linspace` really is the right routine to use with floats and/or quantities, and calling something like `np.arange(10*u.m, 20*u.m, 1*u.cm, like=u.Quantity)` just seems quite unhandy and undiscoverable.

**Comment by dstansby** [comment]
I'd find it super useful! Often I want to generate an array with regular spacing without knowing how big it would be beforehand. If there are technical barriers to doing it in numpy, how would you feel about a thin wrapper in astropy so one could do e.g. `u.arange(1*u.m, 3*u.m, 0.1*u.m)`?

**Comment by mhvk** [comment]
Yes, a wrapper would be possible, and should be easy to implement; I don't think `np.arange` itself is going to change to no longer require `like=u.Quantity`.
