### ISSUE TITLE
TimeSeries.iloc failed when time comes from another TimeSeries

### ISSUE THREAD

**Issue by orionlee** [astropy/astropy#11704]
### Description

`TimeSeries.iloc[:]` failed with `TypeError: list indices must be integers or slices, not NoneType` when the `time` of the object comes from another TimeSeries object's `time`.

### Steps to Reproduce

```python
import numpy as np
from astropy.time import Time
from astropy.timeseries import TimeSeries

time=Time(np.arange(100000, 100003), format='jd')

ts = TimeSeries(time=time)
ts.iloc[:]   # worked

ts2 = TimeSeries(time=Time(time.value, format=time.format, scale=time.scale))
ts2.iloc[:]  # worked

ts3 = TimeSeries(time=ts.time.copy())
ts3.iloc[:]  # worked (but failed in earlier astropy v4.1 with the same error & stacktrace)

ts4 = TimeSeries(time=ts.time)
ts4.iloc[:]  # failed
```

the above codes produce the error
```python
Traceback (most recent call last):
  File "tmp/test_ts_iloc_issue11704.py"", line 20, in <module>
    ts4.iloc[:]  # failed
  File "c:\dev\astropy\astropy\table\index.py", line 940, in __getitem__
    index = self.indices[key]
  File "c:\dev\astropy\astropy\table\index.py", line 796, in __getitem__
    return super().__getitem__(item)
TypeError: list indices must be integers or slices, not NoneType
```

### System Details
```
Windows-10-10.0.19041-SP0
Python 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
Numpy 1.20.2
astropy 4.3.dev1386+ge1c5f637c
Scipy 1.6.3
Matplotlib 3.4.1
```

**Comment by orionlee** [comment]
Diagnosis: the issue seems to be due to missing `primary_key` when the time of a `TimeSeries` objects comes from another TimeSeries.
In the above code snippets,
- `ts.primary_key` is `('time',)`
- but `ts4.primary_key` is `None`

The `primary_key` is used when calling `iloc`:

https://github.com/astropy/astropy/blob/77607ae8846038f8244e244ac90e9b2976044e9d/astropy/table/index.py#L935-L940

**Comment by orionlee** [comment]
@astrofrog The problem persisted in the latest astropy v7.1.1 release and the current `main`. The sample codes above still fails, with essentially the same error / stacktrace.
