### ISSUE TITLE
FITS header verification change from astropy version 4.2 to 4.2.1 (FIXED: Use 4.2.2 or later when available)

### ISSUE THREAD

**Issue by cbethge** [astropy/astropy#11815]
### Description
I am using astropy.io.fits to work with fits files from GOES/SUVI. Those fits files have an issue with the CONTINUE convention, which is implemented incorrectly. Until astropy version 4.2, I was able to use the .tostring() method to convert the corrupt fits header to a string, fix it, and convert it back to a corrected fits header. Starting with astropy version 4.2.1, this is no longer possible: the .tostring() method now seems to do a fits header validity check and will not allow me to access the header. Setting verify to "ignore" does not help, but maybe I am using it wrong. 

Is this the desired behaviour? For me this means I am no longer able to fix the corrupt fits header. I believe that if it is known that a fits header is not compliant with the fits standard, there should at least be an option to ignore the validity check so it is still accessible and can be fixed. 

### Expected behavior
Behaviour with Astropy 4.2 in a one-liner on the command line (test files can be found [here](https://data.ngdc.noaa.gov/platforms/solar-space-observing-satellites/goes/goes16/l1b/suvi-l1b-fe171/2021/06/04/)):
```
python -c "import astropy; from astropy.io import fits; hdu = fits.open('OR_SUVI-L1b-Fe171_G16_s20193490001210_e20193490001220_c20193490001462.fits'); print('Astropy version:', astropy.__version__); hdu.verify('ignore'); hdu[0].header.tostring()"
Astropy version: 4.2
```

### Actual behavior
Behaviour with Astropy 4.2.1 in a one-liner on the command line:
```
python -c "import astropy; from astropy.io import fits; hdu = fits.open('OR_SUVI-L1b-Fe171_G16_s20193490001210_e20193490001220_c20193490001462.fits'); print('Astropy version:', astropy.__version__); hdu.verify('ignore'); hdu[0].header.tostring()"
Astropy version: 4.2.1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/chris/opt/anaconda3/envs/astropy_test/lib/python3.8/site-packages/astropy/io/fits/header.py", line 689, in tostring
    s = str(card)
  File "/Users/chris/opt/anaconda3/envs/astropy_test/lib/python3.8/site-packages/astropy/io/fits/card.py", line 206, in __str__
    return self.image
  File "/Users/chris/opt/anaconda3/envs/astropy_test/lib/python3.8/site-packages/astropy/io/fits/card.py", line 501, in image
    self.verify('fix+warn')
  File "/Users/chris/opt/anaconda3/envs/astropy_test/lib/python3.8/site-packages/astropy/io/fits/verify.py", line 73, in verify
    errs = self._verify(opt)
  File "/Users/chris/opt/anaconda3/envs/astropy_test/lib/python3.8/site-packages/astropy/io/fits/card.py", line 1100, in _verify
    keyword = self._split()[0]
  File "/Users/chris/opt/anaconda3/envs/astropy_test/lib/python3.8/site-packages/astropy/io/fits/card.py", line 815, in _split
    for card in self._itersubcards():
  File "/Users/chris/opt/anaconda3/envs/astropy_test/lib/python3.8/site-packages/astropy/io/fits/card.py", line 1174, in _itersubcards
    if not isinstance(card.value, str):
  File "/Users/chris/opt/anaconda3/envs/astropy_test/lib/python3.8/site-packages/astropy/io/fits/card.py", line 286, in value
    value = self._value = self._parse_value()
  File "/Users/chris/opt/anaconda3/envs/astropy_test/lib/python3.8/site-packages/astropy/io/fits/card.py", line 733, in _parse_value
    raise VerifyError("Unparsable card ({}), fix it first with "
astropy.io.fits.verify.VerifyError: Unparsable card (CONTINUE), fix it first with .verify('fix').
```

### Steps to Reproduce
See above.

### System Details

Darwin-20.5.0-x86_64-i386-64bit
Python 3.7.10 (default, Feb 26 2021, 10:16:00) 
[Clang 10.0.0 ]
Numpy 1.19.2
astropy 4.2 and astropy 4.2.1
Scipy 1.6.0
Matplotlib 3.3.4

**Comment by saimn** [comment]
I think this has been fixed by  #11487, in master currently. 
So it will be in 4.3 (to be released in a few weeks) and hopefully 4.2.2 as well (ping @eteq).

**Comment by cbethge** [comment]
Good to know, thanks!

**Comment by pllim** [comment]
I updated the title to reflect the answer and closing this. Hopefully 4.3 will happen soon.

**Comment by pllim** [comment]
"it was supposed to get fixed with astropy version 4.3. I just updated to 4.3 and this is still an issue."

**Comment by pllim** [comment]
Hrrmmm... @eteq , did #11487 ever get backported?

**Comment by pllim** [comment]
Hrrrmmmmm... I do see #11487 listed in https://github.com/astropy/astropy/blob/v4.3.x/CHANGES.rst under "4.3.0". @saimn , perhaps that PR did not fix everything?

**Comment by cbethge** [comment]
Thanks for re-opening it. Output on my machine with Astropy version 4.3:

```
/Users/chris/opt/anaconda3/envs/astropy_test/bin/python -c "import astropy; from astropy.io import fits; hdu = fits.open('OR_SUVI-L1b-Fe131_G16_s20211761003001_e20211761003011_c20211761003186.fits'); print('Astropy version:', astropy.__version__); hdu.verify('ignore'); hdu[0].header.tostring()"

Astropy version: 4.3.post1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/chris/opt/anaconda3/envs/astropy_test/lib/python3.8/site-packages/astropy/io/fits/header.py", line 690, in tostring
    s = str(card)
  File "/Users/chris/opt/anaconda3/envs/astropy_test/lib/python3.8/site-packages/astropy/io/fits/card.py", line 206, in __str__
    return self.image
  File "/Users/chris/opt/anaconda3/envs/astropy_test/lib/python3.8/site-packages/astropy/io/fits/card.py", line 500, in image
    self.verify('fix+warn')
  File "/Users/chris/opt/anaconda3/envs/astropy_test/lib/python3.8/site-packages/astropy/io/fits/verify.py", line 73, in verify
    errs = self._verify(opt)
  File "/Users/chris/opt/anaconda3/envs/astropy_test/lib/python3.8/site-packages/astropy/io/fits/card.py", line 1108, in _verify
    keyword = self._split()[0]
  File "/Users/chris/opt/anaconda3/envs/astropy_test/lib/python3.8/site-packages/astropy/io/fits/card.py", line 815, in _split
    for card in self._itersubcards():
  File "/Users/chris/opt/anaconda3/envs/astropy_test/lib/python3.8/site-packages/astropy/io/fits/card.py", line 1187, in _itersubcards
    if not isinstance(card.value, str):
  File "/Users/chris/opt/anaconda3/envs/astropy_test/lib/python3.8/site-packages/astropy/io/fits/card.py", line 286, in value
    value = self._value = self._parse_value()
  File "/Users/chris/opt/anaconda3/envs/astropy_test/lib/python3.8/site-packages/astropy/io/fits/card.py", line 732, in _parse_value
    raise VerifyError("Unparsable card ({}), fix it first with "
astropy.io.fits.verify.VerifyError: Unparsable card (CONTINUE), fix it first with .verify('fix').```

**Comment by saimn** [comment]
Actually the error has nothing to do with #11487, sorry I should have looked more in detail. The problem is that the file is not valid FITS, there should be two spaces between `CONTINUE` and the string:
```
ORIGIN  = 'DOC/NOAA/NESDIS> U.S. Department of Commerce, National Oceanic and &'
CONTINUE'Atmospheric Administration, National Environmental Satellite, Data,&'
CONTINUE' and Information Services'
```
And this is not something that can be fixed currently by `.verify('fix')`.

**Comment by pllim** [comment]
So, how do we solve this original problem? "Until astropy version 4.2, I was able to use the .tostring() method to convert the corrupt fits header to a string, fix it, and convert it back to a corrected fits header. Starting with astropy version 4.2.1, this is no longer possible..."

**Comment by cbethge** [comment]
Pinging this... I saw that astropy 5 was released, I am still having the same issue. Any chance of getting this fixed in one of the next astropy minor versions? Thanks!

**Comment by nabobalis** [comment]
Hi everyone!

What would be a good outcome for this issue?

Allowing a person to get a non-standard fits header through `.getheader()` and allowing that to be exported to a string via ` .tostring()` to be fixed later on?
Fixing the lack of spaces after `CONTINUE` in the fits header through verify?

**Comment by knservis** [comment]
A good outcome would be for the code to be doing what it was doing before, which seems consistent with the documentation: https://docs.astropy.org/en/stable/io/fits/usage/verification.html
That is, not to throw an exception on read as that is highly problematic.

**Comment by knservis** [comment]
@embray Is it possible that this commit broke the parsing of FITS headers: https://github.com/astropy/astropy/commit/c5400c7332da7025180164e44b42cd991c4bb038 

Which seems to have been done to solve this https://github.com/astropy/astropy/issues/5408

**Comment by saimn** [comment]
Looking a bit more into that, and trying to understand what v4.2 was doing: I don't think it was fixing the card. I think it was working because it wasn't parsing the card, but printing one of the CONTINUE card would have produced the same error.

> What would be a good outcome for this issue?
Allowing a person to get a non-standard fits header through .getheader() and allowing that to be exported to a string via  .tostring() to be fixed later on?
Fixing the lack of spaces after CONTINUE in the fits header through verify?

Yes `verify` can already fix various problems, and could probably fix this one if someone takes the time to implement the fix.
