### ISSUE TITLE
TST: importlib usage broke pyinstaller cron job

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#12155]
#11714 broken pyinstaller job. Any idea how to fix, @saimn or @mhvk  ?

Example log: https://github.com/astropy/astropy/runs/3551720784?check_suite_focus=true

```
pyinstaller run-test: commands[1] | ./run_astropy_tests
Traceback (most recent call last):
  File "astropy/utils/introspection.py", line 154, in minversion
  File "importlib/metadata.py", line 530, in version
  File "importlib/metadata.py", line 503, in distribution
  File "importlib/metadata.py", line 177, in from_name
importlib.metadata.PackageNotFoundError: numpy

...

  File ".../PyInstaller/loader/pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "astropy/utils/compat/numpycompat.py", line 13, in <module>
  File "astropy/utils/decorators.py", line 536, in wrapper
  File "astropy/utils/introspection.py", line 161, in minversion
KeyError: 'numpy'
```

**Comment by pllim** [comment]
Seems like assumption that it must exist in `dist_names` is incorrect for this build:

https://github.com/astropy/astropy/blob/9ebf553b9a9b45ff96f1c0d7777cb7a21259bbfb/astropy/utils/introspection.py#L153-L161

**Comment by mhvk** [comment]
Bizarre!!

**Comment by saimn** [comment]
I have no idea how pyinstaller works :hushed:

**Comment by pllim** [comment]
Me neither. I think @astrofrog set it up.

**Comment by mhvk** [comment]
I think the weird thing is that `metadata.version('numpy')` apparently failed in the first part of the `try/except` - how can numpy be available and not found!?

**Comment by astrofrog** [comment]
I've managed to get beyond the ``metadata.version`` error - but I'm now running into bizarre ``numpy.distutils`` errors, mainly related to convolution and the use of ctypes.

I do think we should re-work the convolution extension to not use ctypes to load the extension but just use the regular C extension approach used by other modules, for consistency...
