### ISSUE TITLE
AttributeError: module 'typing_extensions' has no attribute 'OrderedDictTypedDict'

### ISSUE THREAD

**Issue by redeaglekr** [astropy/astropy#12551]
Hi, 
I was using astropy wcs while working with my images. I have been using this code for more than one month and this is the first time I am getting this error. I uninstalled astropy and then re installed v5.0. but the error doesn't go away.

```python
from astropy.wcs import WCS
w = WCS(hdu[1].header)
```

the error is :

```
Traceback (most recent call last):
  File "/home/XXXXXXs/.local/lib/python3.8/site-packages/astropy/units/_typing.py", line 9, in <module>
    from typing import Annotated
ImportError: cannot import name 'Annotated' from 'typing' (/usr/lib/python3.8/typing.py)
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/XXXXXXX/photometry/XXXXX/photometryopener.py", line 3, in <module>
    from astropy.wcs import WCS
  File "/home/XXXXXX/.local/lib/python3.8/site-packages/astropy/wcs/__init__.py", line 26, in <module>
    from .wcs import *
  File "/home/XXXXXX/.local/lib/python3.8/site-packages/astropy/wcs/wcs.py", line 50, in <module>
    from astropy import units as u
  File "/home/XXXXXX/.local/lib/python3.8/site-packages/astropy/units/__init__.py", line 40, in <module>
    from .decorators import *
  File "/home/XXXXXX/.local/lib/python3.8/site-packages/astropy/units/decorators.py", line 13, in <module>
    from . import _typing as T
  File "/home/XXXXXX/.local/lib/python3.8/site-packages/astropy/units/_typing.py", line 18, in <module>
    from typing_extensions import *  # override typing
AttributeError: module 'typing_extensions' has no attribute 'OrderedDictTypedDict'
```

**Comment by pllim** [comment]
@nstarman added that typing module in #10662 , so hopefully he can advise.

Might also be helpful if you let us know what is this WCS by printing out `w`.

**Comment by redeaglekr** [comment]
Hi,

I tried to print "w", but nothing is printed out.

**Comment by pllim** [comment]
Ah, right, because the error happened in the WCS call. My bad. Please do this:

```python
print(hdu[1].header)
```

**Comment by redeaglekr** [comment]
Hi,

No change!!!

Traceback (most recent call last):
  File "/home/XXXXXX/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 1157, in _try_while_unread_hdus
    return func(*args, **kwargs)
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/XXXXXXX/.local/lib/python3.8/site-packages/astropy/units/_typing.py", line 9, in <module>
    from typing import Annotated
ImportError: cannot import name 'Annotated' from 'typing' (/usr/lib/python3.8/typing.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/XXXXXXX/photometry/XXXXXX/photometryopener.py", line 61, in <module>
    fc(dirname1)
  File "/home/XXXXXXX/photometry/XXXXXX/photometryopener.py", line 19, in fc
    ecflux = hdu[2].data["flux"]
  File "/home/XXXXXX/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 322, in __getitem__
    return self._try_while_unread_hdus(super().__getitem__,
  File "/home/XXXXXXX/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 1159, in _try_while_unread_hdus
    if self._read_next_hdu():
  File "/home/XXXXXXX/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 1200, in _read_next_hdu
    hdu = _BaseHDU.readfrom(fileobj, **kwargs)
  File "/home/XXXXXX/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/base.py", line 332, in readfrom
    hdu = cls._readfrom_internal(fileobj, checksum=checksum,
  File "/home/XXXXXXX/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/base.py", line 475, in _readfrom_internal
    hdu = cls(data=DELAYED, header=header, **new_kwargs)
  File "/home/XXXXXXXX/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/compressed.py", line 618, in __init__
    super().__init__(data=data, header=header)
  File "/home/XXXXXXX/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/table.py", line 855, in __init__
    from astropy.table import Table
  File "/home/XXXXXX/.local/lib/python3.8/site-packages/astropy/table/__init__.py", line 4, in <module>
    from .column import Column, MaskedColumn, StringTruncateWarning, ColumnInfo
  File "/home/XXXXXXX/.local/lib/python3.8/site-packages/astropy/table/column.py", line 12, in <module>
    from astropy.units import Unit, Quantity
  File "/home/XXXXXX/.local/lib/python3.8/site-packages/astropy/units/__init__.py", line 40, in <module>
    from .decorators import *
  File "/home/XXXXXX/.local/lib/python3.8/site-packages/astropy/units/decorators.py", line 13, in <module>
    from . import _typing as T
  File "/home/XXXXXX/.local/lib/python3.8/site-packages/astropy/units/_typing.py", line 18, in <module>
    from typing_extensions import *  # override typing
AttributeError: module 'typing_extensions' has no attribute 'OrderedDictTypedDict'
>>>

**Comment by saimn** [comment]
It seems there is an issue with your [typing_extensions](https://pypi.org/project/typing-extensions/) installation. Which version do you have ? You could try to uninstall and reinstall it.

**Comment by redeaglekr** [comment]
Solved! Thanks.

**Comment by lpsinger** [comment]
This was closed, but I think that the bug remains: there needs to be a minimum version set for `typing_extensions`.
