### ISSUE TITLE
Bug in parsing wcslib errors in WCS.fix()

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#12737]
I have a fits file with a non-standard CTYPE1 value (`RA--TAN `). Creating a WCS from it issues the `FITSFixedWarning`, but then also a traceback as it in fact doesn't fix the CTYPE but rather raises an `InconsistentAxisTypesError` that I think hasn't been parsed properly in https://github.com/astropy/astropy/blob/main/astropy/wcs/wcs.py#L702-L710. I think it should have been left as an error rather than a warning for a fix (or a fix should have been done for CTYPE1, though I understand why an automated fix for it is not happening).

Full header and traceback:

```
In [1]: from astropy.io import fits

In [2]: from astropy.wcs import WCS

In [3]: header = fits.open('IRAC.1.EXTPRF.5X.fits')[0].header

In [4]: header
Out[4]: 
SIMPLE  =                    T / Created with PDL (http://pdl.perl.org)         
BITPIX  =                  -32 / Bits per pixel- floating point                 
NAXIS   =                    2 / STANDARD FITS FORMAT                           
NAXIS1  =                 1281 / Axis Lenght                                    
NAXIS2  =                 1281 / Axis Lenght                                    
BUNIT   = 'MJy/sr  '           / Units of image data                            
CRVAL1  =                    0 / [deg] RA at CRPIX1,CRPIX2                      
CRVAL2  =                    0 / [deg] DEC at CRPIX1,CRPIX2                     
CRPIX1  =                  641 / Reference pixel along axis 1                   
CRPIX2  =                  641 / Reference pixel along axis 2                   
TELESCOP= 'Spitzer '           / SPITZER Space Telescope                        
INSTRUME= 'IRAC    '           / SPITZER Space Telescope instrument ID          
CHNLNUM =                    1 / 1 digit instrument channel number              
RADESYS = 'ICRS    '           / International Celestial Reference System       
EQUINOX =                 2000 / Equinox for ICRS celestial coord. system       
CTYPE1  = 'RA--TAN '           / RA projection type                             
CTYPE2  = 'DEC--TAN'           / DEC projection type                            
CDELT1  =          -6.7963E-05 / [deg/pix] Scale for axis 1                     
CDELT2  =            6.796E-05 / [deg/pix] Scale for axis 2                     
CROTA2  =                    0 / [deg] Orientation of axis 2 (W of N, +=CW)     
COMMENT Spitzer/IRAC High Dynamic Range PRF                                     
COMMENT PRF image calibrated as an actual image of Vega                         
COMMENT M. Marengo - mmarengo@cfa.harvard.edu - Jun/2007                        

In [5]: WCS(header)
WARNING: FITSFixedWarning: 'celfix' made the change 'Unmatched celestial axes'. [astropy.wcs.wcs]
---------------------------------------------------------------------------
InconsistentAxisTypesError                Traceback (most recent call last)
<ipython-input-5-f2267b5702f8> in <module>
----> 1 WCS(header)

~/.pyenv/versions/3.9.1/lib/python3.9/site-packages/astropy/wcs/wcs.py in __init__(self, header, fobj, key, minerr, relax, naxis, keysel, colsel, fix, translate_units, _do_set)
    529 
    530         if _do_set:
--> 531             self.wcs.set()
    532 
    533         for fd in close_fds:

InconsistentAxisTypesError: ERROR 4 in wcs_types() at line 3062 of file cextern/wcslib/C/wcs.c:
Unmatched celestial axes.
```

**Comment by Vital-Fernandez** [comment]
Hello @bsipocz. I wonder if you found a solution for this issue. I have the MUSE header as:

> XTENSION= 'IMAGE   '           / IMAGE extension                                
> BITPIX  =                  -32 / Number of bits per data pixel                  
> NAXIS   =                    3 / Number of data axes                            
> NAXIS1  =                   74 /                                                
> NAXIS2  =                   74 /                                                
> NAXIS3  =                 4563 /                                                
> PCOUNT  =                    0 / No Group Parameters                            
> GCOUNT  =                    1 / One Data Group                                 
> AUTHOR  = 'Brian Cherinka & David Law <bcherinka@stsci.edu, dlaw@stsci.edu>' /  
> VERSIDL = 'x86_64 linux unix linux 7.1.1 Aug 21 2009 64 64 ' / Version of IDL   
> BSCALE  =              1.00000 / Intensity unit scaling                         
> BZERO   =              0.00000 / Intensity zeropoint                            
> BUNIT   = '1E-17 erg/s/cm^2/Angstrom/spaxel' / Specific intensity (per spaxel)  
> MASKNAME= 'MANGA_DRP3PIXMASK'  / Bits in sdssMaskbits.par used by mask extension
> TELESCOP= 'SDSS 2.5-M'         / Sloan Digital Sky Survey                       
> INSTRUME= 'MaNGA   '           / SDSS-IV MaNGA IFU                              
> SRVYMODE= 'MaNGA dither'       / Survey leading this observation and its mode   
> PLATETYP= 'APOGEE-2&MaNGA'     / Type of plate (e.g. MaNGA, APOGEE-2&MANGA)     
> OBJSYS  = 'ICRS    '           / The TCC objSys                                 
> EQUINOX =              2000.00 /                                                
> RADESYS = 'FK5     '           /                                                
> LAMPLIST= 'lamphgcdne.dat'     /                                                
> TPLDATA = 'BOSZ_3000-11000A.fits' /                                             
> NEXP    =                    9 / Total number of exposures                      
> EXPTIME =              8100.61 / Total exposure time (seconds)                  
> BLUESN2 =              20.9439 / Total SN2 in blue channel                      
> REDSN2  =              44.8315 / Total SN2 in red channel                       
> AIRMSMIN=              1.13152 / Minimum airmass                                
> AIRMSMED=              1.16129 / Median airmass                                 
> AIRMSMAX=              1.20905 / Maximum airmass                                
> SEEMIN  =              1.14656 / Best guider seeing                             
> SEEMED  =              1.52701 / Median guider seeing                           
> SEEMAX  =              2.16413 / Worst guider seeing                            
> TRANSMIN=             0.669740 / Worst guider transparency                      
> TRANSMED=             0.806429 / Median guider transparency                     
> TRANSMAX=             0.849714 / Best guider transparency                       
> MJDMIN  =                57274 / MJD of first exposure                          
> MJDMED  =                57277 / MJD of median exposure                         
> MJDMAX  =                57278 / MJD of last exposure                           
> DATE-OBS= '2015-09-12'         / Date of median exposure                        
> IFURA   =        263.755220000 / IFU R.A. (J2000 deg.)                          
> IFUDEC  =        57.0524330000 / IFU Dec. (J2000 deg.)                          
> OBJRA   =        263.755218506 / Object R.A. (J2000 deg.)                       
> OBJDEC  =        57.0524330139 / Object Dec. (J2000 deg.)                       
> CENRA   =        263.236420000 / Plate center R.A. (J2000 deg.)                 
> CENDEC  =        56.7846870000 / Plate center Dec. (J2000 deg.)                 
> CTYPE3  = 'WAVE-LOG'           /                                                
> CRPIX3  =                    1 / Starting pixel (1-indexed)                     
> CRVAL3  =        3621.59598486 / Central wavelength of first pixel              
> CD3_3   =       0.833903304339 / Initial dispersion per pixel                   
> CUNIT3  = 'Angstrom'           /                                                
> CRPIX1  =              38.0000 /Reference pixel (1-indexed)                     
> CRPIX2  =              38.0000 /Reference pixel (1-indexed)                     
> CRVAL1  =        263.755220000 /                                                
> CRVAL2  =        57.0524330000 /                                                
> CD1_1   =         -0.000138889 /                                                
> CD2_2   =          0.000138889 /                                                
> CTYPE1  = 'RA---TAN'           /                                                
> CTYPE2  = 'DEC--TAN'           /                                                
> CUNIT1  = 'deg     '           /                                                
> CUNIT2  = 'deg     '           /                                                
> HDUCLASS= 'SDSS    '           /SDSS format class                               
> HDUCLAS1= 'CUBE    '           /                                                
> HDUCLAS2= 'DATA    '           /                                                
> ERRDATA = 'IVAR    '           / Error extension name                           
> QUALDATA= 'MASK    '           / Mask extension name                            
> EXTNAME = 'FLUX    '           /                                                
> DATASUM = '2349999722'         / data unit checksum updated 2020-12-03T11:36:34 
> CHECKSUM= 'c0LFc0J9c0JCc0J9'   / HDU checksum updated 2020-12-03T11:36:34     

Once I create a WCS object I get:

```
wcs = WCS(hdr)
print(wcs)

Number of WCS axes: 3
CTYPE : 'RA---TAN'  'DEC--TAN'  'WAVE-LOG'  
CRVAL : 263.75522  57.052433  3.62159598486e-07  
CRPIX : 38.0  38.0  1.0  
CD1_1 CD1_2 CD1_3  : -0.000138889  0.0  0.0  
CD2_1 CD2_2 CD2_3  : 0.0  0.000138889  0.0  
CD3_1 CD3_2 CD3_3  : 0.0  0.0  8.33903304339e-11  
NAXIS : 74  74  4563
```

If I drop the spectral axis with ``wcs.dropaxis(2)``, it works as expected:

```
print(wcs.dropaxis(2))

Number of WCS axes: 2
CTYPE : 'RA---TAN'  'DEC--TAN'  
CRVAL : 263.75522  57.052433  
CRPIX : 38.0  38.0  
CD1_1 CD1_2  : -0.000138889  0.0  
CD2_1 CD2_2  : 0.0  0.000138889  
NAXIS : 74  74

```
I would like to drop the spatial axes to create multi-page .fits files from some spaxels. But once I try to drop any of the them (to export them into the new fits file header). I get your error:

```
print(wcs.dropaxis(0))

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-f72ce1cfa079>", line 1, in <module>
    wcs.dropaxis(1)
  File "C:\Users\Usuario\AppData\Roaming\Python\Python310\site-packages\astropy\wcs\wcs.py", line 3287, in dropaxis
    return self.sub([i + 1 for i in inds])
  File "C:\Users\Usuario\AppData\Roaming\Python\Python310\site-packages\astropy\wcs\wcs.py", line 680, in sub
    copy.wcs = copy.wcs.sub(axes)
astropy.wcs._wcs.InconsistentAxisTypesError: ERROR 4 in wcs_types() at line 3105 of file cextern\wcslib\C\wcs.c:
Unmatched celestial axes.
```

Would you suggest an alternative approach? (I am also concerned of the spectral (3) units conversion)

**Comment by bsipocz** [comment]
> Hello @bsipocz. I wonder if you found a solution for this issue

We ended up manually fixing `CTYPE1` before sending it to reproject. While the error messages are the same, I think that your problem of slicing your spectral data is quite different and would deserve a separate issue/discussion as this one is really about being consistent about warning and error handling in the code.
