### ISSUE TITLE
Weird error message if you give `sigma_clip` a quantity for `sigma`

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#12730]
In spectral-cube, I tried doing a sigma clip operation and got:

```python
~/repos/astropy/astropy/stats/sigma_clipping.py in sigma_clip(data, sigma, sigma_lower, sigma_upper, maxiters, cenfunc, stdfunc, axis, masked, return_bounds, copy, grow)
    833                         cenfunc=cenfunc, stdfunc=stdfunc, grow=grow)
    834 
--> 835     return sigclip(data, axis=axis, masked=masked,
    836                    return_bounds=return_bounds, copy=copy)
    837 

~/repos/astropy/astropy/stats/sigma_clipping.py in __call__(self, data, axis, masked, return_bounds, copy)
    627                 and self.stdfunc in ('std', 'mad_std')
    628                 and axis is not None and not self.grow):
--> 629             return self._sigmaclip_fast(data, axis=axis, masked=masked,
    630                                         return_bounds=return_bounds,
    631                                         copy=copy)

~/repos/astropy/astropy/stats/sigma_clipping.py in _sigmaclip_fast(self, data, axis, masked, return_bounds, copy)
    356             mask = np.broadcast_to(mask, data_reshaped.shape).copy()
    357 
--> 358         bound_lo, bound_hi = _sigma_clip_fast(
    359             data_reshaped, mask, self.cenfunc == 'median',
    360             self.stdfunc == 'mad_std',

~/repos/astropy/astropy/units/quantity.py in __array_ufunc__(self, function, method, *inputs, **kwargs)
    589         # consistent units between two inputs (e.g., in np.add) --
    590         # and the unit of the result (or tuple of units for nout > 1).
--> 591         converters, unit = converters_and_unit(function, method, *inputs)
    592 
    593         out = kwargs.get('out', None)

~/repos/astropy/astropy/units/quantity_helper/converters.py in converters_and_unit(function, method, *args)
    163     # input(s) to the unit required for the ufunc, as well as the unit the
    164     # result will have (a tuple of units if there are multiple outputs).
--> 165     ufunc_helper = UFUNC_HELPERS[function]
    166 
    167     if method == '__call__' or (method == 'outer' and function.nin == 2):

~/repos/astropy/astropy/units/quantity_helper/converters.py in __missing__(self, ufunc)
     90                         return self[ufunc]
     91 
---> 92         raise TypeError("unknown ufunc {}.  If you believe this ufunc "
     93                         "should be supported, please raise an issue on "
     94                         "https://github.com/astropy/astropy"

TypeError: unknown ufunc _sigma_clip_fast.  If you believe this ufunc should be supported, please raise an issue on https://github.com/astropy/astropy
```

A semi-MWE is:
```python
import numpy as np
from astropy.utils.data import download_file
from spectral_cube import SpectralCube
filename = download_file('ftp://ftp.cv.nrao.edu/NRAO-staff/rloomis/MAPS/HD_163296/images/CO/0.15arcsec/HD_163296_CO_220GHz.0.15arcsec.JvMcorr.image.pbcor.fits', cache=True)
cube = SpectralCube.read(filename, use_dask=True)
sigclip = cube.sigma_clip_spectrally(threshold=2*std, save_to_tmp_dir=True)
```

but I think the error message points pretty clearly to a cause.... that I don't understand.

Astropy version 5.1.dev424+ga1475dd9a

**Comment by pllim** [comment]
Are you able to provide a fully MWE that does not need `spectral_cube`?

**Comment by keflavich** [comment]
No, I don't understand the path well enough to produce that right now.

**Comment by keflavich** [comment]
OK I got it:
```python

In [21]: x = np.random.randn(100,20)*u.K

In [22]: sigma_clip(x, sigma=1*u.K, axis=0, masked=False, copy=True)
Traceback (most recent call last):
  File "<ipython-input-22-8597f64ea810>", line 1, in <module>
    sigma_clip(x, sigma=1*u.K, axis=0, masked=False, copy=True)
  File "/home/adam/repos/astropy/astropy/stats/sigma_clipping.py", line 835, in sigma_clip
    return sigclip(data, axis=axis, masked=masked,
  File "/home/adam/repos/astropy/astropy/stats/sigma_clipping.py", line 629, in __call__
    return self._sigmaclip_fast(data, axis=axis, masked=masked,
  File "/home/adam/repos/astropy/astropy/stats/sigma_clipping.py", line 358, in _sigmaclip_fast
    bound_lo, bound_hi = _sigma_clip_fast(
  File "/home/adam/repos/astropy/astropy/units/quantity.py", line 591, in __array_ufunc__
    converters, unit = converters_and_unit(function, method, *inputs)
  File "/home/adam/repos/astropy/astropy/units/quantity_helper/converters.py", line 165, in converters_and_unit
    ufunc_helper = UFUNC_HELPERS[function]
  File "/home/adam/repos/astropy/astropy/units/quantity_helper/converters.py", line 92, in __missing__
    raise TypeError("unknown ufunc {}.  If you believe this ufunc "
TypeError: unknown ufunc _sigma_clip_fast.  If you believe this ufunc should be supported, please raise an issue on https://github.com/astropy/astropy
```

**Comment by keflavich** [comment]
This is user error + misleading error message: `sigma` is supposed to be _number of sigma_, not a quantity.

**Comment by pllim** [comment]
I guess you can add checks here:

https://github.com/astropy/astropy/blob/b482b5d4600f9a310b3375ae76c3e268b4b9150d/astropy/stats/sigma_clipping.py#L226-L228

Though isn't the doc clear enough?

https://github.com/astropy/astropy/blob/b482b5d4600f9a310b3375ae76c3e268b4b9150d/astropy/stats/sigma_clipping.py#L129-L132

**Comment by keflavich** [comment]
The doc is clear, the lack of clarity came from `spectral-cube`, in which the parameter is called 'threshold'.  So that's an issue for somewhere else.

But, we probably should add a check in that first spot.  This is really low-priority, though.

**Comment by pllim** [comment]
> add a check

But then we also have to check for all the other parameters. Will that introduce performance issue? I need @larrybradley 's opinion.

**Comment by keflavich** [comment]
yeah, let's just close this.  I think the docs fix belongs in spectral-cube.  Hopefully the next person to encounter this error (i.e., me) will find this Issue by googling.

**Comment by dhomeier** [comment]
The docs as such are clear enough, but I think naming the parameter `sigma` was not an ideal choice.

**Comment by keflavich** [comment]
`nsigma` might've been better.

The `spectral-cube` version, using `threshold` as the keyword, is even less clear.  `nsigma_threshold` ?

**Comment by dhomeier** [comment]
Or `clip_sigma`?

**Comment by pllim** [comment]
Unless such mistake is very common, I'd like to avoid more deprecation...
