### ISSUE TITLE
Using `quantity_input` doesn't work with __future__ annotations

### ISSUE THREAD

**Issue by steven-murray** [astropy/astropy#12770]
### Description

Say I have a module:

```python
# module.py
from __future__ import annotations
import astropy.units as u

@u.quantity_input
def myfunc(x: u.Quantity['length']):
    return x

if __name__ == '__main__':
    myfunc(3 *u.m)
```

Running this gives 

```
Traceback (most recent call last):
  File "/home/steven/Documents/Projects/radio/EOR/tmp.py", line 10, in <module>
    myfunc(3 *u.m)
  File "/home/steven/miniconda3/envs/21cmSense/lib/python3.9/site-packages/astropy/units/decorators.py", line 257, in wrapper
    targets = _parse_annotation(targets)
  File "/home/steven/miniconda3/envs/21cmSense/lib/python3.9/site-packages/astropy/units/decorators.py", line 110, in _parse_annotation
    raise ValueError(f"invalid unit or physical type {target!r}.") from None
ValueError: invalid unit or physical type "u.Quantity['length']".

```
### Expected behavior

No error.

### Actual behavior

Error as above, but only if using the annotations from `__future__`. This seems to turn the type annotation into a string, which gets dealt with differently in the `_parse_annotation` function. 

### System Details
```
Linux-5.15.12-1-MANJARO-x86_64-with-glibc2.33
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]
Numpy 1.21.2
pyerfa 2.0.0
astropy 5.0
Scipy 1.7.3
Matplotlib 3.5.0
```

**Comment by Cadair** [comment]
This "future" feature is under a lot of debate in the core Python community, there are various PEPs and stuff talking about it. It also breaks libraries like pydantic.

I am not really willing to fix this until Python have decided on a path forward. :crossed_fingers: they choose the right one and do away with all this nonsense.

**Comment by pllim** [comment]
@Cadair , which is the right one? That they get rid of `__future__` altogether? 😸

**Comment by Cadair** [comment]
That `from __future__ import annotations` never becomes the default behaviour.

**Comment by neutrinoceros** [comment]
We also have started using `from __future__ import annotations` in `astropy` itself, so I guess this problem will come up sooner or later
```
 git grep "from __future__ import annotations" | wc
```

**Comment by nstarman** [comment]
@neutrinoceros, it's true but that was before it was deprecated. We need to start walking these back.

**Comment by nstarman** [comment]
@adrn unfortunately there's no way around this except to avoid `from __future__ import annotations`. Stringifying, as done by the `__future__` turned out to be a pretty terrible idea that ruins any run-time use of type hints, like ours. Thankfully it's deprecated, but while we wait for the PEP replacement to be rolled (idk about backport) it's necessary to manually stringify forward references if you want to mix them with run-time dependent type hints.

**Comment by neutrinoceros** [comment]
I missed the deprecation too, thank you for pointing this out !

**Comment by henryiii** [comment]
Stringifying doesn't not ruin runtime annotations, unless you don't handle it correctly, which is a border-line bug (PEP 484 requires that any type annotation can be replaced by it's string form, and that's not going away). Python provides tools to recover the non-stringified form. This doesn't _quite_ work everywhere (like if you define a type inside a closure[^1]), which is why PEP 649 exists. What doesn't work is putting invalid Python into type annotations, which happens if you use modern type hints but support older versions. But that's really, really useful unless you are using type annotations at runtime.

In other words, to play nicely, this should work, regardless of future imports or PEPs:

```python
# module.py
import astropy.units as u

@u.quantity_input
def myfunc(x: "u.Quantity['length']"):
    return x

if __name__ == '__main__':
    myfunc(3 *u.m)
```

[^1]: As far as I could tell, 99% of Pydantic usage is fine with the future import, and an extra .9% of the cases that weren't supported would have been fixed if they had not been dead set on pushing PEP 649, leaving only a very small (~2 issues) unsolvable with string annotations.

To properly handle them, there are tools in `typing` that can destringify most annotations for runtime use.
