### ISSUE TITLE
Migration to Astropy-asdf is incomplete ?

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#12929]
### Description

On the main branch, some modules other than `astropy.io.misc.asdf` raise a deprecation warning as a side effect when they are imported.

reproducer:
```
python -Werror -c "import astropy.nddata"
```

<details> <summary> Traceback </summary>

```python-traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/robcleme/dev/astropy/astropy/nddata/__init__.py", line 11, in <module>
    from .nddata import *
  File "/Users/robcleme/dev/astropy/astropy/nddata/nddata.py", line 13, in <module>
    from astropy.wcs.wcsapi import (BaseLowLevelWCS, BaseHighLevelWCS,
  File "/Users/robcleme/dev/astropy/astropy/wcs/__init__.py", line 26, in <module>
    from .wcs import *
  File "/Users/robcleme/dev/astropy/astropy/wcs/wcs.py", line 56, in <module>
    from .wcsapi.fitswcs import FITSWCSAPIMixin, SlicedFITSWCS
  File "/Users/robcleme/dev/astropy/astropy/wcs/wcsapi/fitswcs.py", line 11, in <module>
    from astropy.coordinates import SpectralCoord, Galactic, ICRS
  File "/Users/robcleme/dev/astropy/astropy/coordinates/__init__.py", line 16, in <module>
    from .builtin_frames import *
  File "/Users/robcleme/dev/astropy/astropy/coordinates/builtin_frames/__init__.py", line 29, in <module>
    from .fk5 import FK5
  File "/Users/robcleme/dev/astropy/astropy/coordinates/builtin_frames/fk5.py", line 11, in <module>
    from .utils import EQUINOX_J2000
  File "/Users/robcleme/dev/astropy/astropy/coordinates/builtin_frames/utils.py", line 16, in <module>
    from astropy.utils import iers
  File "/Users/robcleme/dev/astropy/astropy/utils/iers/__init__.py", line 2, in <module>
    from .iers import *
  File "/Users/robcleme/dev/astropy/astropy/utils/iers/iers.py", line 23, in <module>
    from astropy.table import QTable, MaskedColumn
  File "/Users/robcleme/dev/astropy/astropy/table/__init__.py", line 71, in <module>
    import astropy.io.misc.asdf.connect
  File "/Users/robcleme/dev/astropy/astropy/io/misc/asdf/__init__.py", line 5, in <module>
    warnings.warn(
astropy.utils.exceptions.AstropyDeprecationWarning: ASDF functionality for astropy is being moved out of the astropy package to the new asdf-astropy package. Please use this package instead. astropy.io.misc.asdf is deprecated since astropy 5.1 and will be removed in a future release.
```

</details>

The traceback leads to https://github.com/astropy/astropy/blob/40ba5e4c609d2760152898b8d92a146e3e38c744/astropy/table/__init__.py#L71

A quick grep shows that's the one and only (excluding tests) import statement left that pulls from `astropy.io.misc.asdf` into another astropy module.

**Comment by pllim** [comment]
Yes, I just noticed this myself. Perhaps @WilliamJamieson or @eslavich can open a quick follow-up PR to fix this in dev. Otherwise, I will have to revert #12903 . 

```
$ grep "astropy\.io\.misc" -r astropy/ | grep asdf
astropy/coordinates/tests/test_sky_coord.py:from astropy.io.misc.asdf.tags.helpers import skycoord_equal
astropy/table/tests/test_mixin.py:from astropy.io.misc.asdf.tags.helpers import skycoord_equal
astropy/table/tests/test_operations.py:from astropy.io.misc.asdf.tags.helpers import skycoord_equal
astropy/table/__init__.py:    import astropy.io.misc.asdf.connect
```

**Comment by pllim** [comment]
Update: Given #12930 , I will give it another day or two. If that PR gets too controversial, I will push for a hotfix PR that can get merged sooner, followed by another PR to wrap/clean up the hotfix. Thanks for your patience!

**Comment by pllim** [comment]
Should be fixed in dev now. If it still fails for you, make sure you are not caching. And if you are not caching, then please re-open the issue. 😬

**Comment by neutrinoceros** [comment]
Thank you ! I confirm that the issue is resolved.
