### ISSUE TITLE
Make u.Magnitude hashable

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#12979]
### Description

Currently, `u.Magnitude` is not hashable, different from `u.mag`:

```python
>>> import astropy.units as u
>>> mags = u.Magnitude([1., 2., 3.])
>>> mags
<Magnitude [1., 2., 3.] mag>
>>> mags.physical
<Quantity [0.39810717, 0.15848932, 0.06309573]>
>>> set(mags)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'Magnitude'
```
It would be useful to have magnitudes hashable, to allow them f.e. as a parameter of a function decorated with `@functools.cache`. 
The workaround of using `u.mag` here is ugly, since it lacks the `physical` property:

```Python
>>> import astropy.units as u
>>> mags = [1., 2., 3.]*u.mag
>>> mags
<Quantity [1., 2., 3.] mag>
>>> set(mags)
{<Quantity 1. mag>, <Quantity 2. mag>, <Quantity 3. mag>}
>>> mags.physical
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'RegularFunctionUnit' object has no attribute 'physical'
```

**Comment by nstarman** [comment]
I think this is NumPy's fault. I don't think ``Quantity`` is hashable, because ``ndarray`` is not... ?

**Comment by nstarman** [comment]
@mhvk, correct me if I'm wrong.

**Comment by olebole** [comment]
As in my example, a (non-array) Quantity is hashable. It works with `u.Quantity`, but not with `u.Magnitude`.
