### ISSUE TITLE
Coordinate Transformation produces ValueError: Column year failed to convert: invalid literal for int() with base 10: '<!'

### ISSUE THREAD

**Issue by c-type** [astropy/astropy#13007]
### Description
I get an error when performing a coordinate transformation from ITRS to GCRS.
I create an astropy coordinates object `ap_coord` referenced to the ITRS frame. I then use the `ap_coord.transform_to()` method to transform the coordinates into the GCRS reference frame. That step fails. Attached is a sample script that produces this error on my computer.

Any insights why this is happening?

### Expected behavior

The script should perform the transformation and print out the new coordinate object `ap_coord_new` referenced to the GCRS frame.

### Actual behavior

The transformation fails and I get a `ValueError: Column year failed to convert: invalid literal for int() with base 10: '<!'`. 
```
Traceback (most recent call last):
  File "/min_error_script.py", line 26, in <module>
    ap_coord_new = ap_coord.transform_to(
  File "/home/user/python3.8/site-packages/astropy/coordinates/baseframe.py", line 1205, in transform_to
    return trans(self, new_frame)
  File "/home/user/python3.8/site-packages/astropy/coordinates/transformations.py", line 1479, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "/home/user/python3.8/site-packages/astropy/coordinates/transformations.py", line 1012, in __call__
    reprwithoutdiff = supcall(from_diffless, toframe)
  File "/home/user/python3.8/site-packages/astropy/coordinates/builtin_frames/intermediate_rotation_transforms.py", line 213, in itrs_to_cirs
    pmat = cirs_to_itrs_mat(itrs_coo.obstime)
  File "/home/user/python3.8/site-packages/astropy/coordinates/builtin_frames/intermediate_rotation_transforms.py", line 52, in cirs_to_itrs_mat
    xp, yp = get_polar_motion(time)
  File "/home/user/python3.8/site-packages/astropy/coordinates/builtin_frames/utils.py", line 47, in get_polar_motion
    iers_table = iers.earth_orientation_table.get()
  File "/home/user/python3.8/site-packages/astropy/utils/state.py", line 40, in get
    return cls.validate(cls._value)
  File "/home/user/python3.8/site-packages/astropy/utils/iers/iers.py", line 862, in validate
    value = IERS_Auto.open()
  File "/home/user/python3.8/site-packages/astropy/utils/iers/iers.py", line 694, in open
    cls.iers_table = cls.read(file=filename)
  File "/home/user/python3.8/site-packages/astropy/utils/iers/iers.py", line 547, in read
    iers_a = super().read(file, format='cds', readme=readme)
  File "/home/user/python3.8/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
  File "/home/user/python3.8/site-packages/astropy/io/registry/core.py", line 199, in read
    data = reader(*args, **kwargs)
  File "/home/user/python3.8/site-packages/astropy/io/ascii/connect.py", line 18, in io_read
    return read(filename, **kwargs)
  File "/home/user/python3.8/site-packages/astropy/io/ascii/ui.py", line 376, in read
    dat = reader.read(table)
  File "/home/user/python3.8/site-packages/astropy/io/ascii/cds.py", line 343, in read
    return super().read(table)
  File "/home/user/python3.8/site-packages/astropy/io/ascii/core.py", line 1381, in read
    table = self.outputter(self.header.cols, self.meta)
  File "/home/user/python3.8/site-packages/astropy/io/ascii/core.py", line 1117, in __call__
    self._convert_vals(cols)
  File "/home/user/python3.8/site-packages/astropy/io/ascii/core.py", line 1060, in _convert_vals
    raise ValueError(f'Column {col.name} failed to convert: {last_err}')
ValueError: Column year failed to convert: invalid literal for int() with base 10: '<!'
```

### Steps to Reproduce

Here is a minimal code snippet that produces the error for me.

```python
import astropy
from astropy import coordinates
from astropy import time
from astropy import units as u
import numpy as np

print(astropy.__version__)

# Define an orbit state
pos = np.array([-27102584, -32299601, 73515])
vel = np.array([0, 0, 0])
epoch = time.Time(2460049.5, format='jd')

# build a ITRS coordinate object
ap_coord = coordinates.ITRS(
    pos[0] * u.m,
    pos[1] * u.m,
    pos[2] * u.m,
    vel[0] * u.m / u.s,
    vel[1] * u.m / u.s,
    vel[2] * u.m / u.s,
    obstime=epoch,
    representation_type='cartesian')

# Transform to GCRS coordinate system fails
ap_coord_new = ap_coord.transform_to(
    coordinates.GCRS(obstime=ap_coord.obstime))

print(ap_coord_new)
```

### System Details

Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Linux-5.13.0-35-generic-x86_64-with-glibc2.29
>>> import sys; print("Python", sys.version)
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.20.1
>>> import erfa; print("pyerfa", erfa.__version__)
pyerfa 2.0.0.1
>>> import astropy; print("astropy", astropy.__version__)
astropy 5.0.3
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.8.0
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)

**Comment by mexanick** [comment]
I don't think this is a problem on astropy side. IERS file server is down and the "table" astropy downloads from IERS file server looks like:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
	<head>
		<title>Sorry (BKG LPZ)</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<style type="text/css">
			body {
				background-color: #fff;
				color: #000;
				font-size: 0.9em;
				font-family: sans-serif,helvetica;
				margin: 0;
				padding: 0;
			}
			:link {
				color: #fff;
			}
			:visited {
				color: #fff;
			}
			a:hover {
				color: #000000;
			}
			h1 {
				text-align: center;
				margin: 0;
				padding: 0.6em 2em 0.4em;
				background-color: #0077b6;
				color: #fff;
				font-weight: bold;
				font-size: 1.75em;
				border-bottom: 2px solid #000;
			}
			h1 strong {
				font-weight: bold;
			}
			h2 {
				font-size: 1.1em;
				font-weight: bold;
			}
			.content {
				padding: 1em 5em;
			}
			.content-columns {
				/* Setting relative positioning allows for
				absolute positioning for sub-classes */
				position: relative;
				padding-top: 1em;
			}
			.content-column-left {
				/* Value for IE/Win; will be overwritten for other browsers */
				width: 47%;
				padding-right: 3%;
				float: left;
				padding-bottom: 2em;
			}
			.content-column-right {
				/* Values for IE/Win; will be overwritten for other browsers */
				width: 47%;
				padding-left: 3%;
				float: left;
				padding-bottom: 2em;
			}
			.content-columns>.content-column-left, .content-columns>.content-column-right {
				/* Non-IE/Win */
			}
			img {
				border: 2px solid #fff;
				padding: 2px;
				margin: 2px;
			}
			a:hover img {
				border: 2px solid #3399FF;
			}
		</style>
	</head>

	<body>
	<h1>Diese Seite ist zur Zeit nicht erreichbar.<br/><font size="-1">Bereitgestellt durch: <strong><br/><a href="http://www.bkg.bund.de/">Bundesamt fuer Kartographie und Geodaesie</a></font></strong></h1>
<p />
<hr />
        <h1>This site is currently unavailable.<br/><font size="-1">Provided by: <strong><br/><a href="http://www.bkg.bund.de/">Bundesamt fuer Kartographie und Geodaesie</a></font></strong></h1>
</body>
</html>
```

Perhaps a validation against such server-side issues plus a backup solution should be provided though

**Comment by mexanick** [comment]
Apparently the main URL download from CDDIS always fails (most probably due to SSL/TLS encryption) and the code falls back to URL mirror on IERS data server which is down at the moment.
A working mirror is a navy one:
https://maia.usno.navy.mil/ser7/finals2000A.all

related discussion with fix: https://github.com/astropy/astropy/pull/13004

A tested code snippet on how to download from CDDIS is:
```
Download single file via ftp-ssl

Place the code below into a file.

from ftplib import FTP_TLS
import sys

email = sys.argv[1]
directory = sys.argv[2]
filename = sys.argv[3]

ftps = FTP_TLS(host = 'gdc.cddis.eosdis.nasa.gov')
ftps.login(user='anonymous', passwd=email)
ftps.prot_p()
ftps.cwd(directory)
ftps.retrbinary("RETR " + filename, open(filename, 'wb').write)


Enter the following on the command line:

> python3 <source code file> <Your email address> <directory> <filename>
```
taken from CDDIS: https://cddis.nasa.gov/Data_and_Derived_Products/CDDIS_Archive_Access.html

**Comment by pllim** [comment]
We just updated the URL in dev last night. Can you please try the dev version of astropy? Thanks!

**Comment by mexanick** [comment]
with the navy mirror it works, thanks. I'm wondering if it is also possible to resolve the issue with the FTP download from CDDIS to add redundancy? Also, validation of downloaded resource would be useful, as currently a broken mirror download attempt still provides some content and the astropy code just crashes.

**Comment by pllim** [comment]
Definitely can be improved! Please discuss at #9227
