### ISSUE TITLE
VOUnit to issue VOWarning rather than generic UnitsWarning

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#13017]
`astropy.io.votable.exceptions.W50` is defined to be the warning for units that do not adhere to the VO standards: https://www.ivoa.net/documents/VOUnits

yet, astropy.units.format.vounit.VOUnit issues a generic `UnitsWarning` for the exact same reason.

This is somewhat unexpected in practice, and while in the example below we could ignore both, I don't think that's the right approach: 

https://github.com/astropy/astroquery/issues/2352

**Comment by pllim** [comment]
What would be a desired behavior here?

**Comment by bsipocz** [comment]
To use `astropy.io.votable.exceptions.W50` instead of `UnitsWarning` in e.g. astropy/units/format/vounit.py (and to double-check the rest of file for warnings and errors and use the existing VO specific ones if possible):

```
            if cls._custom_unit_regex.match(t.value):
                warnings.warn(
                    "Unit {!r} not supported by the VOUnit "
                    "standard. {}".format(
                        t.value, utils.did_you_mean_units(
                            t.value, cls._units, cls._deprecated_units,
                            cls._to_decomposed_alternative)),
                    core.UnitsWarning)
```

**Comment by pllim** [comment]
I am not sure if it will be a drop-in replacement in terms of the warning behavior. As you can see here:

https://github.com/astropy/astropy/blob/6c15aa65851dc31e8cac843bd16e83178c8b50bf/astropy/io/votable/exceptions.py#L1040-L1052

It is really customized towards displaying a particular XML format that goes beyond VO unit specification. If you pass it in as warning class, you will see some things that only makes sense if you also pass in things very specific to VO table parsing, like its configuration and position that the unit appears in the table. Is that what you really want?

```python
>>> import warnings
>>> from astropy.io.votable.exceptions import W50
>>> warnings.warn('foo', W50)
WARNING: W50: ?:?:?: W50: Invalid unit string 'foo' [warnings]
```

**Comment by bsipocz** [comment]
Then what about making this a new UnitsWarning, that is a subclass of W50? That would make the suppressing happy and can come with whatever custom text that makes sense for the units module.

**Comment by pllim** [comment]
Looking at the inheritance tree of these two warnings, `UnitsWarning` is higher up in the chain than `W50`. I am not sure if having yet another warning class is a good idea. Let's loop in the `units` maintainers (@nstarman , @mhvk , @adrn ) and see what they think.

`(Warning -> AstropyWarning -> VOWarning) + SyntaxWarning -> VOTableSpecWarning -> W50`

`Warning -> AstropyWarning -> UnitsWarning`

**Comment by nstarman** [comment]
I think both concerns — that incorrect VOUnits should warn with W50 and that we have a lot of warning classes — are reasonable. In this case ``units`` is working for compatibility with the VO standards, so my inclination would be to use the W50 warning.

Would it be possible to make ``W50`` itself a subclass of ``UnitsWarning`` and control the contents of the message depending on where the warning was raised? 
ie ``warnings.warn('foo', W50)`` should not show configuration and position information, which should be shown when parsing a table.

**Comment by bsipocz** [comment]
I don't see any issues with having multiple inheritances for W50, but @tomdonaldson needs to comment on that from the VO side.

**Comment by pllim** [comment]
I hope we are not over-engineering this...

> make `W50` itself a subclass of `UnitsWarning`

Theoretically possible but it is starting to hurt my head since it already mixing in two different classes to begin with.

> control the contents of the message depending on where the warning was raised?

I cannot think of a simple way to do this. I think at the very least you will have to rewrite its constructor to handle this logic that is currently defined up in `VOWarning`:

https://github.com/astropy/astropy/blob/6c15aa65851dc31e8cac843bd16e83178c8b50bf/astropy/io/votable/exceptions.py#L217

**Comment by eerovaher** [comment]
If we look at the code that parses the VOTable then we see that it should already properly replace any `UnitsWarning` instances with `W50`: https://github.com/astropy/astropy/blob/acdefa2cdde7b1dd5923e7acece15eca7812d127/astropy/io/votable/tree.py#L1390-L1404
The fact that we still get an `UnitsWarning` despite `parse_strict='silent'` means that there is a bug that would not be fixed by changing the warnings hierarchy, so that does not sound like a solution we should pursue. Indeed, the underlying bug can be easily confirmed if we try out different unit formats. With e.g. `format='cds'` everything works as expected:
```python
>>> from astropy import units as u
>>> u.Unit('e-/s', format='cds', parse_strict='raise')
...
ValueError: 'e-/s' did not parse as cds unit: Syntax error If this is meant to be a custom unit...
>>> u.Unit('e-/s', format='cds', parse_strict='warn')
WARNING: UnitsWarning: 'e-/s' did not parse as cds unit: Syntax error If this is meant to be a custom unit...
UnrecognizedUnit(e-/s)
>>> u.Unit('e-/s', format='cds', parse_strict='silent')
UnrecognizedUnit(e-/s)
```
But now with `format='vounit'`:
```python
>>> u.Unit('e-/s', format='vounit', parse_strict='raise')
WARNING: UnitsWarning: Unit 'e' not supported by the VOUnit standard.  [astropy.units.format.vounit]
...
ValueError: 'e-/s' did not parse as vounit unit: Invalid character at col 1 If this is meant to be a custom unit...
>>> u.Unit('e-/s', format='vounit', parse_strict='warn')
WARNING: UnitsWarning: Unit 'e' not supported by the VOUnit standard.  [astropy.units.format.vounit]
WARNING: UnitsWarning: 'e-/s' did not parse as vounit unit: Invalid character at col 1 If this is meant to be a custom unit...
UnrecognizedUnit(e-/s)
>>> u.Unit('e-/s', format='vounit', parse_strict='silent')
WARNING: UnitsWarning: Unit 'e' not supported by the VOUnit standard.  [astropy.units.format.vounit]
UnrecognizedUnit(e-/s)
```
We can see that using `format='vounit'` always results in an additional warning, which is the real bug that needs to be fixed.

**Comment by nstarman** [comment]
Thanks for the sleuthing @eerovaher!

**Comment by orionlee** [comment]
I accidentally came across a small test case that might narrow down the source of the warning.

The `UnitsWarning` was emitted **before** `parse_strict` argument was processed. See the following example when I supply an incorrect `parse_strict` value, the `UnitsWarning` is there.

```python
>>> from astropy import units as u
>>> u.Unit('e-/s', format='vounit', parse_strict='foobar')
WARNING: UnitsWarning: Unit 'e' not supported by the VOUnit standard.  [astropy.units.format.vounit]

Traceback (most recent call last):
  File "C:\dev\astropy\astropy\units\format\generic.py", line 612, in _do_parse
    return cls._parse_unit(s, detailed_exception=False)
  File "C:\dev\astropy\astropy\units\format\vounit.py", line 124, in _parse_unit
    raise ValueError()
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\dev\astropy\astropy\units\core.py", line 2019, in __call__
    return f.parse(s)
  File "C:\dev\astropy\astropy\units\format\vounit.py", line 94, in parse
    result = cls._do_parse(s, debug=debug)
  File "C:\dev\astropy\astropy\units\format\generic.py", line 615, in _do_parse
    return cls._parser.parse(s, lexer=cls._lexer, debug=debug)
  File "C:\dev\astropy\astropy\utils\parsing.py", line 115, in parse
    return self.parser.parse(*args, **kwargs)
  File "C:\dev\astropy\astropy\extern\ply\yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "C:\dev\astropy\astropy\extern\ply\yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "C:\dev\astropy\astropy\extern\ply\lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "C:\dev\astropy\astropy\units\format\generic.py", line 159, in t_error
    raise ValueError(
ValueError: Invalid character at col 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\dev\astropy\astropy\units\core.py", line 2045, in __call__
    raise ValueError("'parse_strict' must be 'warn', "
ValueError: 'parse_strict' must be 'warn', 'raise' or 'silent'
```

**Comment by pllim** [comment]
@orionlee 's clue is very valuable. I might have a fix and will submit a PR shortly. Just trying to see if there is a sane way to test it. Thanks!

**Comment by pllim** [comment]
I have proposed a fix at #13017 but it comes with some behavior change. I dunno if it is good or bad. Please have a look and discuss. Thanks!

**Comment by eerovaher** [comment]
Turns out the bug we uncovered here was reported already years ago: #6302

**Comment by JeremyMcCormick** [comment]
I see this is an old ticket at this point, but I ran into unexpected behavior today related to VOUnit definitions which seems to relate to this discussion.

If I define a `Unit` using a completely non-sensical string, astropy issues a warning rather than an exception when format is `vounit`:

```
In [17]: Unit("bad", format="vounit")
WARNING: UnitsWarning: Unit 'bad' not supported by the VOUnit standard. Did you mean Ba (deprecated), aD, ad or g.cm**-1.s**-2? [astropy.units.format.vounit]
Out[17]: Unit("bad")
```

This is not _at all_ the behavior I would expect. I want it to throw an exception here rather than proceed along with a completely non-sensical units definition. (Apologies if this is not exactly what this issue is about but it seemed related.)

The kind of fuzzy matching using regexp that seems to be in the code is overly clever. If it sees a unit that is not in the format specified, then it should always throw an error in my opinion, at least this is the behavior that I would expect. Suppressing legitimate exceptions that occur when you give the units parser a non-sensical string seems like a poor design decision, in my opinion.

**Comment by bsipocz** [comment]
Keep this open as while there is progress, I'm not yet sure the preferred W50 is raised, as I was running into issues reproducing the astroquery issue.

**Comment by bsipocz** [comment]
OK, I think this can indeed be closed now.
