### ISSUE TITLE
aggregate_downsample has unexpected behaviour for multidimensional variables

### ISSUE THREAD

**Issue by smangham** [astropy/astropy#13225]
Tested against the development version.

### Description

When using `aggregate_resample` to downsample a TimeSeries, it reduces any multidimensional columns to 1-d.

### Expected behavior
I expected `aggregate_resample` to downsample the time axis, but not any other axes of the data.

### Actual behavior

The `aggregate_resample` function also downsampled the column of multidimensional data on the _other_ axes, which in my case was frequency.

### Steps to Reproduce

1. Create a TimeSeries where one column is a multidimensional array.
2. Aggregate downsample that TimeSeries to reduce the time resolution.
3. The aggregate operation is applied across the whole multidimensional array, reducing it to 1-d.

```python
import numpy as np
from astropy import units as u
from astropy.timeseries import TimeSeries, aggregate_downsample

t = TimeSeries(time_start="2022-01-01", time_delta=u.s*1, n_samples=30)
t['data'] = np.ones([30, 3])
print(t)

d = aggregate_downsample(t, time_bin_size=3*u.s)
print(d)
```

I think that the default behaviour for `aggregate_downsample` should be to call `np.nanmean` with `axis=1`.

### System Details

Linux-5.13.0-40-generic-x86_64-with-glibc2.29
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]
Numpy 1.20.2
pyerfa 2.0.0.1
astropy 5.0.1
Scipy 1.6.3
Matplotlib 3.4.2

**Comment by neutrinoceros** [comment]
> I think that the default behaviour for aggregate_downsample should be to call np.nanmean with axis=1.

I just tried this with the following patch
```patch
diff --git a/astropy/timeseries/downsample.py b/astropy/timeseries/downsample.py
index 4b089f1f31..b5e8cbcf67 100644
--- a/astropy/timeseries/downsample.py
+++ b/astropy/timeseries/downsample.py
@@ -1,5 +1,6 @@
 # Licensed under a 3-clause BSD style license - see LICENSE.rst
 
+import functools
 import warnings
 
 import numpy as np
@@ -175,7 +176,7 @@ def aggregate_downsample(
     )
 
     if aggregate_func is None:
-        aggregate_func = np.nanmean
+        aggregate_func = functools.partial(np.nanmean, axis=1)
 
     # Start and end times of the binned timeseries
     bin_start = binned.time_bin_start
```

unfortunately it doesn't solve the issue but leads to an exception being raised
```python-traceback
Traceback (most recent call last):
  File "/Users/clm/dev/astropy-project/coordinated/astropy/bugs/13225/t.py", line 9, in <module>
    d = aggregate_downsample(t, time_bin_size=3*u.s)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/clm/dev/astropy-project/coordinated/astropy/astropy/timeseries/downsample.py", line 265, in aggregate_downsample
    data[unique_indices] = reduceat(values, groups, aggregate_func)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/clm/dev/astropy-project/coordinated/astropy/astropy/timeseries/downsample.py", line 34, in reduceat
    return np.array(result)
           ^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (10,) + inhomogeneous part.
```

This happens because bins are not necessarily equal in size. In this example, we get `indices = array([ 0,  4,  7, 10, 13, 16, 19, 22, 25, 28])`, so the first bin covers 4 samples while other bins only cover 3 each.
I honestly do not know wether that's a bug or not, or wether the default behaviour should be changed (at the moment it can't) but what's concerning is that, even though `aggregate_func` is exposed as a parameter, it doesn't seem currently possible to perform the desired operation on ND data points (for N>1).

**Comment by bhuvan-somisetty** [comment]
Still an issue on main / 8.0.1, and it's actually worse now than the original report. With the default aggregate_func it just crashes:

```python
import numpy as np
from astropy import units as u
from astropy.timeseries import TimeSeries, aggregate_downsample

ts = TimeSeries(time_start="2022-01-01", time_delta=1 * u.s, n_samples=30)
ts["flux"] = np.ones((30, 3))
out = aggregate_downsample(ts, time_bin_size=3 * u.s)
```

```
ValueError: operands could not be broadcast together with shapes (10,3) (10,)
```

Two things going on in downsample.py:

1. The output column is allocated as `shape=(n_bins,)`, so it drops any extra dimensions no matter what aggregate_func you pass.
2. `nanmean_reduceat` divides the reduced sum (shape (10,3)) by counts (shape (10,)), which is what actually throws above.

@neutrinoceros's axis=1 patch from 2024 only fixes #2 for equal size bins, that's why it still fails.

I'll raise a PR shortly for this that keeps trailing dimensions in the output shape and makes the count based averaging broadcast properly, with tests for a multi-dim Quantity column, plain ndarray, and masked column, both equal and unequal bin sizes.

Just want to confirm the expected behavior first: reduce along the time axis, leave other axes alone, matching what the original report suggested. Let me know if that's right.
