### ISSUE TITLE
FITSDiff raises TypeError  when comparing CFHT WIRCam guide images

### ISSUE THREAD

**Issue by SharonGoliath** [astropy/astropy#13474]
### Description

When comparing a compressed and uncompressed version of a CFHT WIRCam guide image file, get "TypeError: buffer is too small for requested array"

### Expected behavior

The expected behaviour would be something like the following output:
```
 fitsdiff: 4.3.1
 a: ./execution/1003191f.fits.gz
 b: ./execution/1003191f.fits.fz
 Keyword(s) not to be compared:
  *
 Keyword(s) whose comments are not to be compared:
  *
 Maximum number of different data values to be reported: 10
 Relative tolerance: 0.0, Absolute tolerance: 0.0

Files contain different numbers of HDUs:
 a: 1
 b: 2

Primary HDU:

   Headers contain differences:
     Headers have different number of cards:
      a: 322
      b: 6
```

### Actual behavior

The following exception is raised:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/astropy/io/fits/diff.py", line 316, in __init__
    super().__init__(a, b)
  File "/usr/local/lib/python3.9/site-packages/astropy/io/fits/diff.py", line 72, in __init__
    self._diff()
  File "/usr/local/lib/python3.9/site-packages/astropy/io/fits/diff.py", line 354, in _diff
    hdu_diff = HDUDiff.fromdiff(self, self.a[idx], self.b[idx])
  File "/usr/local/lib/python3.9/site-packages/astropy/io/fits/diff.py", line 107, in fromdiff
    return cls(a, b, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/astropy/io/fits/diff.py", line 534, in __init__
    super().__init__(a, b)
  File "/usr/local/lib/python3.9/site-packages/astropy/io/fits/diff.py", line 72, in __init__
    self._diff()
  File "/usr/local/lib/python3.9/site-packages/astropy/io/fits/diff.py", line 553, in _diff
    if self.a.data is None or self.b.data is None:
  File "/usr/local/lib/python3.9/site-packages/astropy/utils/decorators.py", line 767, in __get__
    val = self.fget(obj)
  File "/usr/local/lib/python3.9/site-packages/astropy/io/fits/hdu/table.py", line 402, in data
    data = self._get_tbdata()
  File "/usr/local/lib/python3.9/site-packages/astropy/io/fits/hdu/table.py", line 781, in _get_tbdata
    raw_data = self._get_raw_data(self._nrows, dtype, self._data_offset)
  File "/usr/local/lib/python3.9/site-packages/astropy/io/fits/hdu/base.py", line 529, in _get_raw_data
    return self._file.readarray(offset=offset, dtype=code, shape=shape)
  File "/usr/local/lib/python3.9/site-packages/astropy/io/fits/file.py", line 329, in readarray
    data = _array_from_file(self._file, dtype, count)
  File "/usr/local/lib/python3.9/site-packages/astropy/io/fits/util.py", line 587, in _array_from_file
    array = np.ndarray(buffer=s, dtype=dtype, shape=(count,))
TypeError: buffer is too small for requested array
```

### Steps to Reproduce

1. Retrieve a sample file: `wget https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/data/pub/CFHT/912666g.fits.gz -O 912666g.fits.gz`
2. Decompress: `gunzip -k 912666g.fits.gz`
3. Run the following:

```
from astropy.io import fits
x = fits.FITSDiff('./912666g.fits.gz', './912666g.fits')
```

### System Details

Original configuration:
```
Python 3.9.10 (main, Mar  8 2022, 01:25:30) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Linux-5.10.104-linuxkit-x86_64-with-glibc2.28
>>> import sys; print("Python", sys.version)
Python 3.9.10 (main, Mar  8 2022, 01:25:30) 
[GCC 8.3.0]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.22.3
>>> import erfa; print("pyerfa", erfa.__version__)
pyerfa 2.0.0.1
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.3.1
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.8.0
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.5.1
```

astropy development version configuration that fails with the same error:

```
>>> import platform; print(platform.platform())
Linux-5.10.104-linuxkit-x86_64-with-glibc2.31
>>> import sys; print("Python", sys.version)
Python 3.10.2 (main, Jan 29 2022, 02:55:36) [GCC 10.2.1 20210110]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.22.2
>>> import erfa; print("pyerfa", erfa.__version__)
pyerfa 2.0.0.1
>>> import astropy; print("astropy", astropy.__version__)
astropy 5.2.dev277+g3fc010a49
>>> import scipy; print("Scipy", scipy.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.5.2
```

**Comment by pllim** [comment]
@saimn , is this that lazy loading thingy again?

**Comment by saimn** [comment]
It seems the problem comes from the column format `TFORM1  = 'D16     '` which is not handled correctly by Astropy (it's missing the precision part):
```
In [1]: from astropy.io.fits.column import _parse_ascii_tformat

In [2]: _parse_ascii_tformat('D')
Out[2]: ('D', 25, 17)

In [3]: _parse_ascii_tformat('D16')
Out[3]: ('D', 25, 17)

In [4]: _parse_ascii_tformat('D16.7')
Out[4]: ('D', 16, 7)
```
