### ISSUE TITLE
TST: Transient PytestUnraisableExceptionWarning in cloud.rst

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#13907]
- [ ] Revert #13909

Occasionally, this will pop up but not always. Usually it is in this job (daily cron):

https://github.com/astropy/astropy/blob/e32652cf0e1d9dcfda9ec9ae1193e7ea3ee40788/.github/workflows/ci_cron_daily.yml#L45-L50

```
_____________________________ [doctest] cloud.rst ______________________________

cls = <class '_pytest.runner.CallInfo'>
func = <function call_runtest_hook.<locals>.<lambda> at 0x7f1c4972beb0>
when = 'call'
reraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)

    @classmethod
    def from_call(
        cls,
        func: "Callable[[], TResult]",
        when: "Literal['collect', 'setup', 'call', 'teardown']",
        reraise: Optional[
            Union[Type[BaseException], Tuple[Type[BaseException], ...]]
        ] = None,
    ) -> "CallInfo[TResult]":
        """Call func, wrapping the result in a CallInfo.
    
        :param func:
            The function to call. Called without arguments.
        :param when:
            The phase in which the function is called.
        :param reraise:
            Exception or exceptions that shall propagate if raised by the
            function, instead of being wrapped in the CallInfo.
        """
        excinfo = None
        start = timing.time()
        precise_start = timing.perf_counter()
        try:
>           result: Optional[TResult] = func()

/home/runner/work/astropy/astropy/.tox/py310-test-alldeps-predeps/lib/python3.10/site-packages/_pytest/runner.py:339: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>       lambda: ihook(item=item, **kwds), when=when, reraise=reraise
    )

/home/runner/work/astropy/astropy/.tox/py310-test-alldeps-predeps/lib/python3.10/site-packages/_pytest/runner.py:260: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_HookCaller 'pytest_runtest_call'>, args = ()
kwargs = {'item': <DoctestItem cloud.rst>}, argname = 'item'
firstresult = False

    def __call__(self, *args, **kwargs):
        if args:
            raise TypeError("hook calling supports only keyword arguments")
        assert not self.is_historic()
    
        # This is written to avoid expensive operations when not needed.
        if self.spec:
            for argname in self.spec.argnames:
                if argname not in kwargs:
                    notincall = tuple(set(self.spec.argnames) - kwargs.keys())
                    warnings.warn(
                        "Argument(s) {} which are declared in the hookspec "
                        "can not be found in this hook call".format(notincall),
                        stacklevel=2,
                    )
                    break
    
            firstresult = self.spec.opts.get("firstresult")
        else:
            firstresult = False
    
>       return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)

/home/runner/work/astropy/astropy/.tox/py310-test-alldeps-predeps/lib/python3.10/site-packages/pluggy/_hooks.py:265: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_pytest.config.PytestPluginManager object at 0x7f1c809db790>
hook_name = 'pytest_runtest_call'
methods = [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/home/runner/work/astropy/astropy/.tox/py310-te...rk/astropy/astropy/.tox/py310-test-alldeps-predeps/lib/python3.10/site-packages/_pytest/unraisableexception.py'>>, ...]
kwargs = {'item': <DoctestItem cloud.rst>}, firstresult = False

    def _hookexec(self, hook_name, methods, kwargs, firstresult):
        # called from all hookcaller instances.
        # enable_tracing will set its own wrapping function at self._inner_hookexec
>       return self._inner_hookexec(hook_name, methods, kwargs, firstresult)

/home/runner/work/astropy/astropy/.tox/py310-test-alldeps-predeps/lib/python3.10/site-packages/pluggy/_manager.py:80: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

hook_name = 'pytest_runtest_call'
hook_impls = [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/home/runner/work/astropy/astropy/.tox/py310-te...rk/astropy/astropy/.tox/py310-test-alldeps-predeps/lib/python3.10/site-packages/_pytest/unraisableexception.py'>>, ...]
caller_kwargs = {'item': <DoctestItem cloud.rst>}, firstresult = False

    def _multicall(hook_name, hook_impls, caller_kwargs, firstresult):
        """Execute a call into multiple python functions/methods and return the
        result(s).
    
        ``caller_kwargs`` comes from _HookCaller.__call__().
        """
        __tracebackhide__ = True
        results = []
        excinfo = None
        try:  # run impl and wrapper setup functions in a loop
            teardowns = []
            try:
                for hook_impl in reversed(hook_impls):
                    try:
                        args = [caller_kwargs[argname] for argname in hook_impl.argnames]
                    except KeyError:
                        for argname in hook_impl.argnames:
                            if argname not in caller_kwargs:
                                raise HookCallError(
                                    f"hook call must provide argument {argname!r}"
                                )
    
                    if hook_impl.hookwrapper:
                        try:
                            gen = hook_impl.function(*args)
                            next(gen)  # first yield
                            teardowns.append(gen)
                        except StopIteration:
                            _raise_wrapfail(gen, "did not yield")
                    else:
                        res = hook_impl.function(*args)
                        if res is not None:
                            results.append(res)
                            if firstresult:  # halt further impl calls
                                break
            except BaseException:
                excinfo = sys.exc_info()
        finally:
            if firstresult:  # first result hooks return a single value
                outcome = _Result(results[0] if results else None, excinfo)
            else:
                outcome = _Result(results, excinfo)
    
            # run all wrapper post-yield blocks
            for gen in reversed(teardowns):
                try:
>                   gen.send(outcome)

/home/runner/work/astropy/astropy/.tox/py310-test-alldeps-predeps/lib/python3.10/site-packages/pluggy/_callers.py:55: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @pytest.hookimpl(hookwrapper=True, tryfirst=True)
    def pytest_runtest_call() -> Generator[None, None, None]:
>       yield from unraisable_exception_runtest_hook()

/home/runner/work/astropy/astropy/.tox/py310-test-alldeps-predeps/lib/python3.10/site-packages/_pytest/unraisableexception.py:88: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def unraisable_exception_runtest_hook() -> Generator[None, None, None]:
        with catch_unraisable_exception() as cm:
            yield
            if cm.unraisable:
                if cm.unraisable.err_msg is not None:
                    err_msg = cm.unraisable.err_msg
                else:
                    err_msg = "Exception ignored in"
                msg = f"{err_msg}: {cm.unraisable.object!r}\n\n"
                msg += "".join(
                    traceback.format_exception(
                        cm.unraisable.exc_type,
                        cm.unraisable.exc_value,
                        cm.unraisable.exc_traceback,
                    )
                )
>               warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
E               pytest.PytestUnraisableExceptionWarning: Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x7f1c78a5c3a0>
E               
E               Traceback (most recent call last):
E                 File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/asyncio/sslproto.py", line 320, in __del__
E                   _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
E               ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7f1c2313a740>

/home/runner/work/astropy/astropy/.tox/py310-test-alldeps-predeps/lib/python3.10/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning
=========================== short test summary info ============================
FAILED ../../docs/io/fits/usage/cloud.rst::cloud.rst - pytest.PytestUnraisableExceptionWarning: Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x7f1c78a5c3a0>

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/asyncio/sslproto.py", line 320, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7f1c2313a740>
```

**Comment by barentsen** [comment]
Thanks for opening this issue @pllim!

The `ResourceWarning` encountered in the log is the result of a bug in the SSL protocol implementation in Python's built-in `asyncio` module ([cpython/cpython#90476](https://github.com/python/cpython/issues/90476)).  The SSL implementation was rewritten in February 2022 (i.e. Python 3.11), but all versions of Python<=3.10 continue to be affected.

Due to the asynchronous nature of asyncio, the issue is transient and can be observed in tests which do not directly appear to use asyncio.

I believe the best solution is to edit `setup.cfg` to ignore all warnings which match
`ignore:unclosed transport <asyncio.sslproto`.  I believe this is a safe thing to do because Astropy does not interact directly with asyncio's SSL implementation, and so it is hard to imagine a situation where this warning would indicate a genuine Astropy issue.

**Comment by barentsen** [comment]
@pllim I opened PR #13916 to propose the fix explained in my comment above (i.e., ignoring the warning via `setup.cfg`).  How do you feel about this?

**Comment by pllim** [comment]
Thanks for the clarifications! I think your solution is reasonable and I'll do a full review tomorrow.
