### ISSUE TITLE
Should calling `np.array_equal()` on `astropy.units.Quantity` instances with incompatible units return `False`?

### ISSUE THREAD

**Issue by byrdie** [astropy/astropy#14158]
### Description
Using `np.array_equal()` on `Quantity` instances with incompatible units raises a `UnitConversionError`.

### Expected behavior
I would've expected this function just to return `False` in this case. Do we think it's really necessary to halt if the units are incompatible?

### Actual behavior

An `astropy.core.UnitsConversionError` exception was raised.

### Steps to Reproduce

```python
>>> np.array_equal([1, 2, 3] * u.mm, [1, 2, 3] * u.s)

Traceback (most recent call last):
  File "C:\Users\royts\Kankelborg-Group\astropy\astropy\units\quantity.py", line 980, in to_value
    scale = self.unit._to(unit)
  File "C:\Users\royts\Kankelborg-Group\astropy\astropy\units\core.py", line 1129, in _to
    raise UnitConversionError(f"'{self!r}' is not a scaled version of '{other!r}'")
astropy.units.core.UnitConversionError: 'Unit("s")' is not a scaled version of 'Unit("mm")'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\royts\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-4e788b1e0c5a>", line 1, in <module>
    np.array_equal([1, 2, 3] * u.mm, [1, 2, 3] * u.s)
  File "<__array_function__ internals>", line 180, in array_equal
  File "C:\Users\royts\Kankelborg-Group\astropy\astropy\units\quantity.py", line 1844, in __array_function__
    args, kwargs, unit, out = function_helper(*args, **kwargs)
  File "C:\Users\royts\Kankelborg-Group\astropy\astropy\units\quantity_helper\function_helpers.py", line 566, in array_equal
    args, unit = _quantities2arrays(a1, a2)
  File "C:\Users\royts\Kankelborg-Group\astropy\astropy\units\quantity_helper\function_helpers.py", line 351, in _quantities2arrays
    arrays = tuple((q._to_own_unit(arg)) for arg in args)
  File "C:\Users\royts\Kankelborg-Group\astropy\astropy\units\quantity_helper\function_helpers.py", line 351, in <genexpr>
    arrays = tuple((q._to_own_unit(arg)) for arg in args)
  File "C:\Users\royts\Kankelborg-Group\astropy\astropy\units\quantity.py", line 1652, in _to_own_unit
    _value = value.to_value(unit)
  File "C:\Users\royts\Kankelborg-Group\astropy\astropy\units\quantity.py", line 983, in to_value
    value = self._to_value(unit, equivalencies)
  File "C:\Users\royts\Kankelborg-Group\astropy\astropy\units\quantity.py", line 889, in _to_value
    return self.unit.to(
  File "C:\Users\royts\Kankelborg-Group\astropy\astropy\units\core.py", line 1165, in to
    return self._get_converter(Unit(other), equivalencies)(value)
  File "C:\Users\royts\Kankelborg-Group\astropy\astropy\units\core.py", line 1094, in _get_converter
    raise exc
  File "C:\Users\royts\Kankelborg-Group\astropy\astropy\units\core.py", line 1077, in _get_converter
    return self._apply_equivalencies(
  File "C:\Users\royts\Kankelborg-Group\astropy\astropy\units\core.py", line 1054, in _apply_equivalencies
    raise UnitConversionError(f"{unit_str} and {other_str} are not convertible")
astropy.units.core.UnitConversionError: 's' (time) and 'mm' (length) are not convertible
```

### System Details

```
Windows-10-10.0.19045-SP0
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Numpy 1.23.5
pyerfa 2.0.0.1
astropy 5.3.dev89+g4989e530b
Scipy 1.9.1
Matplotlib 3.6.0
```

**Comment by mhvk** [comment]
Hmm, there certainly is precedent for `np.array_equal` to just return `False` for comparisons of strings and integers., and similarly something like `1*u.m == 1*u.s` returns `False`. So, yes, I guess. It would mean making it a `dispatched_function` and having a `try/except NotImplementedError` around `_quantities2arrays`. My tendency would be not to backport this, as it is a bit of an API change too.

**Comment by byrdie** [comment]
Ok, sounds good, I'll open a PR with your design. Do you think we should do the same with `numpy.array_equiv()`? There is the same behavior with that function as well.

**Comment by mhvk** [comment]
Yes, I agree `np.array_equiv` should behave similarly. Thanks for checking how the functions actually behave!

**Comment by byrdie** [comment]
No problem! Since I am developing a duck `Quantity` with my [named_arrays](https://github.com/Kankelborg-Group/named_arrays) package I get to explore every corner case in gory detail.

**Comment by mhvk** [comment]
Excellent! You'll almost certainly find other problems -- but it will be good for everyone!
