### ISSUE TITLE
The `range` argument to `numpy.histogram`-like functions does not accept instances of `astropy.units.Quantity`

### ISSUE THREAD

**Issue by byrdie** [astropy/astropy#14209]
### Description
When using `numpy.histogram()`, `numpy.histogram2d()`, etc. family of functions, with instances of `astropy.units.Quantity`, the `range` argument only accepts instances of `float`.

### Expected behavior
I would have expected that the `range` argument needs to be an instance of `astropy.units.Quantity` with compatible units.

### Actual behavior
An `astropy.units.core.UnitConversionError` is raised if `range` is an instance of `astropy.units.Quantity`.

### Steps to Reproduce

```python
>>> import numpy as np
>>> import astropy.units as u
>>> a = np.random.random(21) * u.m
>>> np.histogram(a, range=[.25, .75] * u.m)
Traceback (most recent call last):
  File "C:\Users\royts\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-4cd3ceb23e75>", line 1, in <module>
    np.histogram(a, range=[.2, .7] * u.m)
  File "<__array_function__ internals>", line 200, in histogram
  File "C:\Users\royts\Kankelborg-Group\astropy\astropy\units\quantity.py", line 1844, in __array_function__
    result = super().__array_function__(function, types, args, kwargs)
  File "C:\Users\royts\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\histograms.py", line 824, in histogram
    keep = (tmp_a >= first_edge)
  File "C:\Users\royts\Kankelborg-Group\astropy\astropy\units\quantity.py", line 699, in __array_ufunc__
    raise e
  File "C:\Users\royts\Kankelborg-Group\astropy\astropy\units\quantity.py", line 644, in __array_ufunc__
    converters, unit = converters_and_unit(function, method, *inputs)
  File "C:\Users\royts\Kankelborg-Group\astropy\astropy\units\quantity_helper\converters.py", line 200, in converters_and_unit
    raise UnitConversionError(
astropy.units.core.UnitConversionError: Can only apply 'less_equal' function to dimensionless quantities when other argument is not a quantity (unless the latter is all zero/infinity/nan).
```

### System Details

```
Windows-10-10.0.19045-SP0
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Numpy 1.24.0
pyerfa 2.0.0.1
astropy 5.3.dev128+ge512a6799
Scipy 1.9.1
Matplotlib 3.6.0
```

**Comment by mhvk** [comment]
Hmm, definitely an oversight; I do remember being quite fed up by the time I got to `histogram` as it had so many options... Anyway, I guess to fix this one needs to add treatment to https://github.com/astropy/astropy/blob/87963074a50b14626fbd825536f384a6e96835af/astropy/units/quantity_helper/function_helpers.py#L666-L687

Of course, also need to fix the other ones; maybe a small `_check_range` function would do the trick (in analogy with `_check_bins`).

**Comment by byrdie** [comment]
Ok, thanks for looking into this. I will open a PR shortly with my attempt
at a fix.
