### ISSUE TITLE
ValueError: 58762695:7: not well-formed (invalid token)

### ISSUE THREAD

**Issue by Venustiano** [astropy/astropy#14313]
Hello, 

I am trying to download  14.5M records 

```
from pyvo.dal import tap
import pandas as pd

ESO_TAP_CATS = "http://archive.eso.org/tap_cat"
tapcats = tap.TAPService(self.ESO_TAP_CATS)

query = 'SELECT TOP 14500000 DECJ2000, RAJ2000, Z_B, COLOUR_GAAP_u_g, MAG_GAAP_r FROM safcat.KiDS_DR4_1_ugriZYJHKs_cat_fits '

with tapcats.submit_job(query=query,maxrec=tapcats.hardlimit) as job:
      try:
                job.run()
                job.wait(timeout=3600)
                if job.phase == 'COMPLETED':
                    res = job.fetch_result()
                    res = pd.DataFrame(res)
                    print(res)
                    res.to_csv(filename, index=False, line_terminator='\r\n')
      finally:
            job.delete()
```

But I get the following error when I try to fetch the data

```
Downloading data from ESO_TAP_CAT         and saving into /home/svcg/Downloads/KiDS_14.5M.csv 
Job completed
Traceback (most recent call last):

  File "/home/svcg/dev/dd/data2dot/qtgui/qcatalogues.py", line 76, in qdownload_ESO_TAP_CAT
    res = job.fetch_result()
  File "/home/svcg/dev/dd/data2dot_env/lib/python3.8/site-packages/pyvo/dal/tap.py", line 841, in fetch_result
    return TAPResults(votableparse(response.raw.read), url=self.result_uri, session=self._session)
  File "/home/svcg/dev/dd/data2dot_env/lib/python3.8/site-packages/astropy/utils/decorators.py", line 535, in wrapper
    return function(*args, **kwargs)
  File "/home/svcg/dev/dd/data2dot_env/lib/python3.8/site-packages/astropy/io/votable/table.py", line 166, in parse
    return tree.VOTableFile(
  File "/home/svcg/dev/dd/data2dot_env/lib/python3.8/site-packages/astropy/io/votable/tree.py", line 3574, in parse
    tag_mapping.get(tag, self._add_unknown_tag)(
  File "/home/svcg/dev/dd/data2dot_env/lib/python3.8/site-packages/astropy/io/votable/tree.py", line 3485, in _add_resource
    resource.parse(self, iterator, config)
  File "/home/svcg/dev/dd/data2dot_env/lib/python3.8/site-packages/astropy/io/votable/tree.py", line 3286, in parse
    tag_mapping.get(tag, self._add_unknown_tag)(
  File "/home/svcg/dev/dd/data2dot_env/lib/python3.8/site-packages/astropy/io/votable/tree.py", line 3232, in _add_table
    table.parse(iterator, config)
  File "/home/svcg/dev/dd/data2dot_env/lib/python3.8/site-packages/astropy/io/votable/tree.py", line 2506, in parse
    self.array = self._parse_tabledata(
  File "/home/svcg/dev/dd/data2dot_env/lib/python3.8/site-packages/astropy/io/votable/tree.py", line 2584, in _parse_tabledata
    for start, tag, data, pos in iterator:
ValueError: 58762695:7: not well-formed (invalid token)
Aborted (core dumped)
```

Any suggestion to fix the problem?

Thanks

**Comment by pllim** [comment]
Hello. Is it possible to give us the offending file (with the just affected row(s)) and a minimally reproducible code that does not involve `pyvo` calls? We have very limited resources to maintain `io.votable` here so having that would speed up the process. Thanks!

**Comment by ManonMarchand** [comment]
Looks like there was no answer and we cannot reproduce the problem without @Venustiano 's file. Maybe this should be closed.

**Comment by bsipocz** [comment]
I don't think there is a file, the example in the OP works (after a very small modification). Well, that is said, it doesn't work in the sense that it produces the ValueError.
