### ISSUE TITLE
Astropy time scale value error

### ISSUE THREAD

**Issue by fredjane** [astropy/astropy#14683]
### Description

**I am trying to run a python code that has always worked up to today:**

#Import libraries

from astropy.wcs import WCS
from astropy.io import fits
from astropy.utils.data import get_pkg_data_filename

import numpy as np
import astropy.io.fits as pyfits
import astropy.wcs as wcs
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import matplotlib.cm as cm
import os

import matplotlib.colors as colors
import matplotlib.cbook as cbook

import matplotlib.patches as patch
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

import matplotlib

from astropy.coordinates import Angle
import astropy.units as u
from regions import PixCoord, EllipsePixelRegion

from matplotlib.patches import Rectangle

matplotlib.rc('xtick', labelsize=12) 
matplotlib.rc('ytick', labelsize=12)
#plt.rcParams["font.family"] = "sans serif"

import warnings
warnings.filterwarnings("ignore")

#Open and read moment maps

filename = get_pkg_data_filename('12-11_NH2CHO_mom0.fits')
filename1 = get_pkg_data_filename('12-11_NH2CHO_residuals_fit.fits')

levels = [1.34e-2, 3.57e-2, 5.8e-2, 8.02e-2, 0.10, 0.12, 0.15, 0.17, 0.19, 0.21, 0.24, 0.26, 0.28] #Contour levels for NH2CHO

hdu = fits.open(filename)[0]
wcs = WCS(hdu.header)
image_data = hdu.data

imObj = pyfits.open(filename)
Header = imObj[0].header

hdu1 = fits.open(filename1)[0]
wcs1 = WCS(hdu1.header)
image_data1 = hdu1.data

#WCSAxes can either plot one or two dimensional data; with higher dimensionality we have to select which dimensions to use for the x or x and y axes of the plot.
#Even though we are not plotting the all the dimensions, we have to specify which slices to select for the dimensions that are not shown.
plt.figure(figsize=(14,8))

ax = plt.subplot(projection=wcs, slices=('x', 'y', 0, 0))
ax.coords[2].set_ticklabel(exclude_overlapping=True)

ax1 = plt.subplot(projection=wcs, slices=('x', 'y', 0, 0))
ax1.coords[2].set_ticklabel(exclude_overlapping=True)

#In Numpy, the order of the axes is reversed so the first dimension in the FITS file appears last, the last dimension appears first and so on. Therefore the #index passed to imshow() should be the same as passed to slices but in reversed order.
img = ax.imshow(image_data[0, 0, :, :], cmap='afmhot')
img1 = ax1.imshow(image_data1[0, 0, :, :], cmap='veridis')

#Plot colorbar
cb = ax.colorbar(img, extend='both').set_label(label=r'$Integrated ~ intensity$ [$Jy/beam ~ km/s$]', size=14, labelpad=15)
cb1 = ax1.colorbar(img1, extend='both').set_label(label=r'$Integrated ~ intensity$ [$Jy/beam ~ km/s$]', size=14, labelpad=15)

#Plot contours on moment 0 map
CS = ax.contour(image_data[0, 0, :, :], levels=levels, cmap='winter')

#Plot centroids
ax.errorbar(634.862, 627.027, xerr=  0.024, yerr= 0.031, marker='+', color='white')
ax1.errorbar(634.862, 627.027, xerr=  0.024, yerr= 0.031, marker='+', color='white')

'''
#Plot restoring beam
bmaj = Header['BMAJ'] * 3600.
bmin = Header['BMIN'] * 3600.
bpa = Header['BPA']
reg = EllipsePixelRegion(PixCoord(612, 612), width=14.75*bmin, height=14.75*bmaj,
                         angle=Angle(-24.02, 'deg'))
patch = reg.plot(ax=ax, color='#89726F', fill=True)
'''
#Annotate the plotted molecular transition

ax.annotate(r'$NH_{2}CHO$ (12_{0,12}-11_{0,11})',
            xy=(1,1),
            color='white',
            fontsize=20)

ax1.annotate(r'$NH_{2}CHO$ (12_{0,12}-11_{0,11})',
            xy=(1,1),
            color='white',
            fontsize=20)

#Plot box where the gaussian fit has been performed
r = Rectangle((52.29363216, 31.22540764)*u.deg, 52.29330128*u.deg, 31.22569526*u.deg, edgecolor='#59C663', facecolor='none')
ax.add_patch(r)

#ax.legend(handles=legend_elements, loc= 'upper left')
ax.set_xlabel(r'$Right ~ Ascension ~ [ICRS]$',fontsize=14, labelpad=2)
ax.set_ylabel(r'$Declination ~ [ICRS]$',fontsize=14, labelpad=2)
#ax.set_xlim(610, 657)
#ax.set_ylim(610, 648)
#ax.set_title(r'NH$\bf{_{2}CHO}$ 12(0,12)-11(0,11) MOMENT 0 MAP', pad=20, fontweight="bold")

ax1.set_xlabel(r'$Right ~ Ascension ~ [ICRS]$',fontsize=14, labelpad=2)
ax1.set_ylabel(r'$Declination ~ [ICRS]$',fontsize=14, labelpad=2)
#ax1.set_xlim(610, 657)
#ax1.set_ylim(610, 648)
#ax1.set_title(r'NH$\bf{_{2}CHO}$ 12(0,12)-11(0,11) GAUSSIAN FIT RESIDUALS', pad=20, fontweight="bold")

#plt.savefig('60K_CH3OH_NH2CHO_final.png',dpi=500)
plt.show()
plt.close()
#plt.savefig('/scigarfs/opsw/work/jfredian/FAUST-IRAS4A/setup2/340K_CH3OH_CH3OCHO_final.png',dpi=100)

**But now when I try to run it with IDLE Python 3.9 this is the error that comes out:**

Traceback (most recent call last):
  File "/Users/jennyfrediani/Desktop/moment0_comp/mom_60K.py", line 63, in <module>
    ax = plt.subplot(projection=wcs, slices=('x', 'y', 0, 0))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/pyplot.py", line 1283, in subplot
    ax = fig.add_subplot(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/figure.py", line 772, in add_subplot
    ax = subplot_class_factory(projection_class)(self, *args, **pkw)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/matplotlib/axes/_subplots.py", line 34, in __init__
    self._axes_class.__init__(self, fig, [0, 0, 1, 1], **kwargs)
  File "/Users/jennyfrediani/Library/Python/3.9/lib/python/site-packages/astropy/visualization/wcsaxes/core.py", line 136, in __init__
    self.reset_wcs(
  File "/Users/jennyfrediani/Library/Python/3.9/lib/python/site-packages/astropy/visualization/wcsaxes/core.py", line 427, in reset_wcs
    transform, coord_meta = transform_coord_meta_from_wcs(
  File "/Users/jennyfrediani/Library/Python/3.9/lib/python/site-packages/astropy/visualization/wcsaxes/wcsapi.py", line 157, in transform_coord_meta_from_wcs
    transform = WCSPixel2WorldTransform(transform_wcs, invert_xy=invert_xy)
  File "/Users/jennyfrediani/Library/Python/3.9/lib/python/site-packages/astropy/visualization/wcsaxes/wcsapi.py", line 359, in __init__
    self.frame_out = wcsapi_to_celestial_frame(wcs)
  File "/Users/jennyfrediani/Library/Python/3.9/lib/python/site-packages/astropy/visualization/wcsaxes/wcsapi.py", line 276, in wcsapi_to_celestial_frame
    for cls, _, kwargs, *_ in wcs.world_axis_object_classes.values():
  File "/Users/jennyfrediani/Library/Python/3.9/lib/python/site-packages/astropy/wcs/wcsapi/wrappers/sliced_wcs.py", line 297, in world_axis_object_classes
    keys_keep = [item[0] for item in self.world_axis_object_components]
  File "/Users/jennyfrediani/Library/Python/3.9/lib/python/site-packages/astropy/wcs/wcsapi/wrappers/sliced_wcs.py", line 293, in world_axis_object_components
    return [self._wcs.world_axis_object_components[idx] for idx in self._world_keep]
  File "/Users/jennyfrediani/Library/Python/3.9/lib/python/site-packages/astropy/wcs/wcsapi/wrappers/sliced_wcs.py", line 293, in <listcomp>
    return [self._wcs.world_axis_object_components[idx] for idx in self._world_keep]
  File "/Users/jennyfrediani/Library/Python/3.9/lib/python/site-packages/astropy/wcs/wcsapi/fitswcs.py", line 358, in world_axis_object_components
    return self._get_components_and_classes()[0]
  File "/Users/jennyfrediani/Library/Python/3.9/lib/python/site-packages/astropy/wcs/wcsapi/fitswcs.py", line 452, in _get_components_and_classes
    obstime = Time(
  File "/Users/jennyfrediani/Library/Python/3.9/lib/python/site-packages/astropy/time/core.py", line 1853, in __init__
    self._init_from_vals(
  File "/Users/jennyfrediani/Library/Python/3.9/lib/python/site-packages/astropy/time/core.py", line 536, in _init_from_vals
    self._time = self._get_time_fmt(
  File "/Users/jennyfrediani/Library/Python/3.9/lib/python/site-packages/astropy/time/core.py", line 599, in _get_time_fmt
    return cls(val, val2, scale, precision, in_subfmt, out_subfmt)
  File "/Users/jennyfrediani/Library/Python/3.9/lib/python/site-packages/astropy/time/formats.py", line 153, in __init__
    self.set_jds(val1, val2)
  File "/Users/jennyfrediani/Library/Python/3.9/lib/python/site-packages/astropy/time/formats.py", line 565, in set_jds
    self._check_scale(self._scale)  # Validate scale.
  File "/Users/jennyfrediani/Library/Python/3.9/lib/python/site-packages/astropy/time/formats.py", line 373, in _check_scale
    raise ScaleValueError(
astropy.time.core.ScaleValueError: Scale value 'UTC' not in allowed values ('tai', 'tcb', 'tcg', 'tdb', 'tt', 'ut1', 'utc', 'local')

**Can anyone help me please, I have no idea how to solve this error.**

### Expected behavior

-

### How to Reproduce

-

### Versions

-

**Comment by fredjane** [comment]
I wanted to use the astropy.visualization.wcsaxes.add_beam() astropy function to add the restoring beam to my plot but there was apparently a problem with astropy not being able to get this package right, so I decided to update pip and then astropy to solve the problem but actually it didn't work. The other change I made in the past few days before the code started not working was to temporarily change the language of my computer, but of course, I think it doesn't have anything to do with this error.
Right now I have Pip 23.1, Python 3.9.7, Python 2.7.15 and Astropy 5.2.2 installed on my laptop.

**Comment by pllim** [comment]
Now I am confused, how can you possibly be running both Python 3.9.7 and Python 2.7.15 at the same time?

**Comment by fredjane** [comment]
I don't run them at the same time. I solved the problem by the way, I modified the column of the header of my fits file that was generating the problem. Thank you.

**Comment by pllim** [comment]
Ah, glad you solved it. Thanks for reporting back!
