### ISSUE TITLE
Column type incompatibility in vstack or similar functions should tell you the column name(s) which failed

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#14825]
### Description

This traceback:
```
  File "/data/dkist/prod/sync_asdfs.py", line 103, in <module>
    results = vstack([results, next_results], metadata_conflicts="silent")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stuart/Git/astropy/astropy/table/operations.py", line 682, in vstack
    out = _vstack(tables, join_type, col_name_map, metadata_conflicts)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stuart/Git/astropy/astropy/table/operations.py", line 1475, in _vstack
    col_cls = _get_out_class(cols)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/stuart/Git/astropy/astropy/table/operations.py", line 99, in _get_out_class
    raise ValueError(
ValueError: unmergeable object classes ['MaskedColumn', 'QueryResponseColumn']
```
doesn't tell me which column caused the error making it significantly harder to debug

### Expected behavior

Change the error message to something like `unmergeable object classes {} in column {}`.

**Comment by pllim** [comment]
Where does `QueryResponseColumn` even come from? Do you have code to reproduce?

**Comment by Cadair** [comment]
It's a sunpy custom column. When I have a moment i will write a MWE.

**Comment by neutrinoceros** [comment]
@Cadair any chance you could work out that example soon ?

**Comment by taldcroft** [comment]
This might already be fixed. ??
```
In [2]: t1 = Table([[1], ["a"]])

In [3]: t2 = Table([["a"], ["b"]])

In [4]: table.vstack([t1, t2])
---------------------------------------------------------------------------
MergeConflictError                        Traceback (most recent call last)
...
TableMergeError: The 'col0' columns have incompatible types: ['int64', 'str32']
```
