### ISSUE TITLE
Modelling error in sphinx parallel builds

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#14916]
### Description

As of astropy 5.3 I get the following error when building the `dkist` documentation with parallel jobs:
```
Process ForkProcess-19:               
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/stuart/Git/DKIST/dkist/.tox/build_docs/lib/python3.11/site-packages/sphinx/util/parallel.py", line 79, in _process
    logging.convert_serializable(collector.logs)
  File "/home/stuart/Git/DKIST/dkist/.tox/build_docs/lib/python3.11/site-packages/sphinx/util/logging.py", line 75, in convert_serializable
    r.msg = r.getMessage()
            ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
  File "/home/stuart/Git/DKIST/dkist/.tox/build_docs/lib/python3.11/site-packages/astropy/modeling/parameters.py", line 318, in __repr__
    args += f", value={self.value}"
                       ^^^^^^^^^^
  File "/home/stuart/Git/DKIST/dkist/.tox/build_docs/lib/python3.11/site-packages/astropy/modeling/parameters.py", line 360, in value
    if value.size == 1:
       ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'size'
```
It doesn't happen with 5.2 or when I disable parallel builds.

**Comment by astrofrog** [comment]
@Cadair - does this still happen?

**Comment by Cadair** [comment]
yes, this still happens with astropy 7.
