### ISSUE TITLE
ERROR: Failed building wheel for astropy when attempting to build from source

### ISSUE THREAD

**Issue by MatCat776** [astropy/astropy#15059]
### Answer

https://github.com/astropy/astropy/issues/15059#issuecomment-1633272304

### Description

I am trying to follow the instructions for "Building from Source" at this link:
https://docs.astropy.org/en/stable/install.html

### Expected behavior

I would expect astropy to install and be usable in the same way as if I installed using `pip3 install astropy`.  It is worth noting that `pip3 install astropy` works as expected. When I try to install per the astropy docs, I get a few pages of errors. The bits of the error message that seem most likely to be useful are copied below:
```

Building wheels for collected packages: astropy
  Building wheel for astropy (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp8o9qty2h
       cwd: /tmp/pip-req-build-diyrb7ti
  Complete output (1661 lines):

<cropped>


  astropy/wcs/src/wcslib_celprm_wrap.c: In function 'PyCelprm_deepcopy':
  astropy/wcs/src/wcslib_celprm_wrap.c:167:22: warning: initialization from incompatible pointer type [enabled by default]
       PyCelprm* copy = PyCelprm_new(&PyCelprmType, NULL, NULL);
                        ^
  astropy/wcs/src/wcslib_celprm_wrap.c: In function 'PyCelprm_set_ref':
  astropy/wcs/src/wcslib_celprm_wrap.c:327:5: warning: passing argument 1 of 'PyArray_DIMS' from incompatible pointer type [enabled by default]
       size = PyArray_SIZE(value_array);
       ^

<lots of other similar error messages edited out>

  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I./astropy/io/fits/_tiled_compression/src -I/usr/local/include/python3.9 -c ./astropy/io/fits/_tiled_compression/src/compression.c -o build/temp.linux-x86_64-cpython-39/./astropy/io/fits/_tiled_compression/src/compression.o
  ./astropy/io/fits/_tiled_compression/src/compression.c: In function 'compress_plio_1_c':
  ./astropy/io/fits/_tiled_compression/src/compression.c:117:3: error: 'for' loop initial declarations are only allowed in C99 mode
     for (int ii = 0; ii < tilesize; ii++)  {
     ^
  ./astropy/io/fits/_tiled_compression/src/compression.c:117:3: note: use option -std=c99 or -std=gnu99 to compile your code
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for astropy
Failed to build astropy
ERROR: Could not build wheels for astropy which use PEP 517 and cannot be installed directly
```

### How to Reproduce

I am running Centos7 with updated kernel Linux 5.18.7-1.el7.elrepo.x86_64 x86_64.

Relevant bits from my history:
```
sudo yum install python3-devel python3-numpy python3-setuptools python3-Cython python3-pytest-astropy
git clone https://github.com/astropy/astropy.git
cd astropy/
python3 -m pip install .
```

I get the same result if I replace the last line above with
`pip3 install .`

### Versions
```
>>> import astropy; print("astropy", astropy.__version__)
/generator/tmp/astropy/astropy/version.py:12: UserWarning: could not determine astropy package version; this indicates a broken installation
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/generator/tmp/astropy/astropy/__init__.py", line 176, in <module>
    _initialize_astropy()
  File "/generator/tmp/astropy/astropy/__init__.py", line 150, in _initialize_astropy
    raise ImportError(
ImportError: You appear to be trying to import astropy from within a source checkout or from an editable installation without building the extension modules first. Either run:

  pip install -e .

or

  python setup.py build_ext --inplace

to make sure the extension modules are built
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.25.0
>>> import erfa; print("pyerfa", erfa.__version__)
pyerfa 2.0.0.3
>>> import scipy; print("Scipy", scipy.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.7.1
```

**Comment by pllim** [comment]
Those instructions might be outdated. There is a note under https://docs.astropy.org/en/latest/install.html#prerequisites-for-linux. @astrofrog , I think you last updated them as part of #9726 ?

**Comment by MatCat776** [comment]
Is there a set of instructions that work to install on centos? Can anyone reproduce my error message so I know if the problem is in my environment or if the problem is more general?

**Comment by saimn** [comment]
This code should be compiled with `-std=c99` (or more recent), but with CentOS 7 you probably get a quite old version of GCC (4.8.5 it seems), which uses c89 by default:
```
gcc releases from 3.0 to 4.9.4 default to -std=gnu89 or -std=gnu90.
gcc releases from 5.5 to 10.4 default to -std=gnu11 (they skipped -std=gnu99, though you can still specify it).
gcc releases 11.3 and 12.2 default to std=gnu17.
```
(from https://stackoverflow.com/a/14737642/4728722).

For `astropy.wcs` we already enforce c99 so we could do the same for `io.fits._tiled_compression`. But it's also easy to fix the issue locally (`CFLAGS='-std=c99' pip install .` should work), so I'm not sure if we need to bother with GCC releases from ~10 years ago.

**Comment by MatCat776** [comment]
Your suggestion of `CFLAGS='-std=c99' pip install . `seems to fix the problem. I would suggest adding it to the instructions https://docs.astropy.org/en/stable/install.html.

**Comment by pllim** [comment]
@MatCat776 , are you interested to open a PR to add this to the doc to get credited for it? There is no need for change log, so the PR should be a simple one that only touches one file. Thanks for checking!😸
