### ISSUE TITLE
New FITS compression code breaks loading Pan-STARRS images 

### ISSUE THREAD

**Issue by karpov-sv** [astropy/astropy#15236]
### Description

The code for reading compressed FITS files in 5.3 is crashing on loading the images from Pan-STARRS. It was working nicely in 5.2.

The problem manifests like that:
```
$ python -c 'from astropy.io import fits; fits.getdata("http://ps1images.stsci.edu/rings.v3.skycell/1004/016/rings.v3.skycell.1004.016.stk.g.unconv.fits")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/ltzfs/ASTRO101/anaconda3/envs/astro101/lib/python3.11/site-packages/astropy/io/fits/convenience.py", line 232, in getdata
    data = hdu.data
           ^^^^^^^^
  File "/ltzfs/ASTRO101/anaconda3/envs/astro101/lib/python3.11/site-packages/astropy/utils/decorators.py", line 837, in __get__
    val = self.fget(obj)
          ^^^^^^^^^^^^^^
  File "/ltzfs/ASTRO101/anaconda3/envs/astro101/lib/python3.11/site-packages/astropy/io/fits/hdu/compressed.py", line 1558, in data
    data = self.section[...]
           ~~~~~~~~~~~~^^^^^
  File "/ltzfs/ASTRO101/anaconda3/envs/astro101/lib/python3.11/site-packages/astropy/io/fits/hdu/compressed.py", line 2189, in __getitem__
    data = decompress_hdu_section(self.hdu, first_tile_index, last_tile_index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ltzfs/ASTRO101/anaconda3/envs/astro101/lib/python3.11/site-packages/astropy/io/fits/_tiled_compression/tiled_compression.py", line 442, in decompress_hdu_section
    tile_data[blank_mask] = np.nan
    ~~~~~~~~~^^^^^^^^^^^^
ValueError: cannot convert float NaN to integer
```

### Expected behavior

The images from Pan-STARRS were loading without issues in pre-5.3

### How to Reproduce

```python
from astropy.io import fits
fits.getdata("http://ps1images.stsci.edu/rings.v3.skycell/1004/016/rings.v3.skycell.1004.016.stk.g.unconv.fits")
```

### Versions

Linux-4.18.0-372.9.1.el8.x86_64-x86_64-with-glibc2.28
Python 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0]
astropy 5.3.2
Numpy 1.25.2
pyerfa 2.0.0.3
Scipy 1.11.2
Matplotlib 3.7.2

**Comment by alchzh** [comment]
Submitted a quick fix to ignore `ZBLANK` in this case so the normal scaling code handles it as before. Note that according to the spec for tile compression, `ZBLANK` shouldn't be set on integer HDUs

https://fits.gsfc.nasa.gov/registry/tilecompression/tilecompression2.3.pdf

> If the uncompressed image has an integer datatype (ZBITPIX > 0) then the reserved BLANK keyword, which already serves this purpose, should be used instead of ZBLANK.

**Comment by genghisken** [comment]
Hi all - is there a plan to release this fix? Ran into the same issue today with Astropy 5.3.3. Tried upgrading to Astropy 6 with no luck. Ended up downgrading to Astropy 5.2.2 and all worked OK.

**Comment by pllim** [comment]
https://github.com/astropy/astropy/pull/15756 needs a rebase and final review, so unfortunately this problem still stands.

**Comment by jleagle94** [comment]
I just ran into this problem on astropy 5.3.4 and also 6.*. Downgrading to astropy 5.2.2 following @genghisken solved the problem.

**Comment by pllim** [comment]
Hmm! https://github.com/astropy/astropy/pull/16550 was marked as fixing this issue and should have been released in 6.1.2.

**Comment by jleagle94** [comment]
Ah, I think that is my real issue. I am pegged at astropy 6.0.1 working in python 3.9.16. Sorry for any confusion! Thanks.
