### ISSUE TITLE
Saving HDUList corrupts array data assigned to `BinTableHDU.data`

### ISSUE THREAD

**Issue by braingram** [astropy/astropy#15366]
### Description

If a record array with an unsigned dtype is assigned to the `data` attribute of a `BinTableHDU` the data in the original array is modified when the `BinTableHDU` is saved (as seen in the example below).

Tested with `5.3` and a recently build 'nightly' `6.0.dev697+gb9b552a68` in python 3.10 on mac os (M1).

### How to Reproduce

Running the following:

```python
from astropy.io import fits
import numpy as np

tbl = np.array([1, 2, 3], dtype=[('a', '<u2')])
hdulist = fits.HDUList()
hdulist.append(fits.PrimaryHDU())
hdulist.append(fits.BinTableHDU())
hdulist[-1].data = tbl
assert tbl['a'][0] == 1, tbl['a'][0]
hdulist.writeto('foo.fits', overwrite=True)
assert tbl['a'][0] == 1, tbl['a'][0]
```

Fails with: `AssertionError: 32769`

### Versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
import scipy; print("Scipy", scipy.__version__)
import matplotlib; print("Matplotlib", matplotlib.__version__)

**Comment by alchzh** [comment]
This is expected behavior for unsigned 16 bit data that requires scaling to store https://docs.astropy.org/en/stable/io/fits/usage/image.html#scaled-data . Similar to the example given in the docs

> Caution must be exercised when using the [scale()](https://docs.astropy.org/en/stable/io/fits/api/images.html#astropy.io.fits.ImageHDU.scale) method. The [data](https://docs.astropy.org/en/stable/io/fits/api/images.html#astropy.io.fits.ImageHDU.data) attribute of an image HDU, after the [scale()](https://docs.astropy.org/en/stable/io/fits/api/images.html#astropy.io.fits.ImageHDU.scale) call, will become the storage values, not the physical values. So, only call [scale()](https://docs.astropy.org/en/stable/io/fits/api/images.html#astropy.io.fits.ImageHDU.scale) just before writing out to FITS files (i.e., calls of [writeto()](https://docs.astropy.org/en/stable/io/fits/api/hdulists.html#astropy.io.fits.HDUList.writeto), [flush()](https://docs.astropy.org/en/stable/io/fits/api/hdulists.html#astropy.io.fits.HDUList.flush), or [close()](https://docs.astropy.org/en/stable/io/fits/api/hdulists.html#astropy.io.fits.HDUList.close)). No further use of the [data](https://docs.astropy.org/en/stable/io/fits/api/images.html#astropy.io.fits.ImageHDU.data) should be exercised. Here is an example of what happens to the data attribute after the [scale()](https://docs.astropy.org/en/stable/io/fits/api/images.html#astropy.io.fits.ImageHDU.scale) call:

```
hdu = fits.PrimaryHDU(np.array([0., 1, 2, 3]))

print(hdu.data)  
[0. 1. 2. 3.]

hdu.scale('int16', bzero=32768)

print(hdu.data)  # now the data has storage values
[-32768 -32767 -32766 -32765]

hdu.writeto('new.fits')
```

I don't know if it's possible to do anything better here without un-scaling the original array after writing. Maybe a warning could be emitted if you try to access the `.data` array after writing, but that wouldn't do anything if you access it from the original numpy array instead of `.data`

**Comment by neutrinoceros** [comment]
We could also explicitly document that assigning `hdu.data` this way effectively gives owership of the data to the `hdu` object, and how to avoid this side effect (use copies).

**Comment by saimn** [comment]
@alchzh - No there is a real bug, `.scale` is necessary to scale manually the data but unsigned integer are supported out of box, without having to manually scale the data.

The problem happens only when setting the data to `.data`, passing the array to `BinTableHDU` works fine:
```
In [16]: tbl = np.array([1, 2, 3], dtype=[('a', '<u2')])
    ...: hdu = fits.BinTableHDU(tbl)
    ...: hdu.writeto("tmp.fits", overwrite=True)

In [17]: tbl
Out[17]: array([(1,), (2,), (3,)], dtype=[('a', '<u2')])

In [18]: np.shares_memory(hdu.data, tbl)
Out[18]: False
```
But when setting to `.data`  the scaling reflects on the input array:
```
In [19]: tbl = np.array([1, 2, 3], dtype=[('a', '<u2')])
    ...: hdu = fits.BinTableHDU()
    ...: hdu.data = tbl
    ...: hdu.writeto("tmp.fits", overwrite=True)

In [20]: tbl
Out[20]: array([(32769,), (32770,), (32771,)], dtype=[('a', '<u2')])

In [21]: np.shares_memory(hdu.data, tbl)
Out[21]: True
```

**Comment by cmarmo** [comment]
In fact, the issue is there even without writing the fits file on disk
```
In [1]: from astropy.io import fits

In [2]: import numpy as np

In [3]: tbl = np.array([1, 2, 3], dtype=[('a', '<u2')])

In [4]: hdu = fits.BinTableHDU(tbl)

In [5]: np.shares_memory(hdu.data, tbl)
Out[5]: False
```
with respect to
```
In [1]: from astropy.io import fits

In [2]: import numpy as np

In [3]: tbl = np.array([1, 2, 3], dtype=[('a', '<u2')])

In [4]: hdu = fits.BinTableHDU()

In [5]: hdu.data = tbl

In [6]: np.shares_memory(hdu.data, tbl)
Out[6]: True
```

**Comment by braingram** [comment]
Thanks all for taking a look at this.

I believe the following might be related but I'd be happy to open a separate issue if preferred.

Running the following example.
```python
from astropy.io import fits
import numpy as np

hdulist = fits.HDUList()
hdulist.append(fits.PrimaryHDU())

arr = np.arange(32 * 16).reshape((32, 16)).astype(dtype=[('col', 'f8')])

hdulist.append(fits.BinTableHDU())
hdulist[-1].data = arr

hdulist.writeto('foo.fits', overwrite=True)
```
Runs without errors or warnings. However, when attempting to open the file the following errors and warnings are produced:
```
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: Header block contains null bytes instead of spaces for padding, and is not FITS-compliant. Nulls may be replaced with spaces upon writing. [astropy.io.fits.header]
Traceback (most recent call last):
  File "/Users/bgraham/.pyenv/versions/stdatamodels/lib/python3.10/site-packages/astropy/io/fits/hdu/hdulist.py", line 1258, in _try_while_unread_hdus
    return func(*args, **kwargs)
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bgraham/.pyenv/versions/stdatamodels/lib/python3.10/site-packages/astropy/io/fits/hdu/base.py", line 439, in _readfrom_internal
    header_str, header = _BasicHeader.fromfile(data)
  File "/Users/bgraham/.pyenv/versions/stdatamodels/lib/python3.10/site-packages/astropy/io/fits/header.py", line 2056, in fromfile
    header_str, cards = parse_header(fileobj)
  File "astropy/io/fits/_utils.pyx", line 39, in astropy.io.fits._utils.parse_header
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 2: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bgraham/projects/src/stdatamodels/bar.py", line 16, in <module>
    ff.info()
  File "/Users/bgraham/.pyenv/versions/stdatamodels/lib/python3.10/site-packages/astropy/io/fits/hdu/hdulist.py", line 1099, in info
    for idx, hdu in enumerate(self):
  File "/Users/bgraham/.pyenv/versions/stdatamodels/lib/python3.10/site-packages/astropy/io/fits/hdu/hdulist.py", line 336, in __iter__
    yield self[idx]
  File "/Users/bgraham/.pyenv/versions/stdatamodels/lib/python3.10/site-packages/astropy/io/fits/hdu/hdulist.py", line 389, in __getitem__
    return self._try_while_unread_hdus(
  File "/Users/bgraham/.pyenv/versions/stdatamodels/lib/python3.10/site-packages/astropy/io/fits/hdu/hdulist.py", line 1260, in _try_while_unread_hdus
    if self._read_next_hdu():
  File "/Users/bgraham/.pyenv/versions/stdatamodels/lib/python3.10/site-packages/astropy/io/fits/hdu/hdulist.py", line 1302, in _read_next_hdu
    hdu = _BaseHDU.readfrom(fileobj, **kwargs)
  File "/Users/bgraham/.pyenv/versions/stdatamodels/lib/python3.10/site-packages/astropy/io/fits/hdu/base.py", line 365, in readfrom
    hdu = cls._readfrom_internal(
  File "/Users/bgraham/.pyenv/versions/stdatamodels/lib/python3.10/site-packages/astropy/io/fits/hdu/base.py", line 446, in _readfrom_internal
    header = Header.fromfile(data, endcard=not ignore_missing_end)
  File "/Users/bgraham/.pyenv/versions/stdatamodels/lib/python3.10/site-packages/astropy/io/fits/header.py", line 531, in fromfile
    return cls._from_blocks(block_iter, is_binary, sep, endcard, padding)[1]
  File "/Users/bgraham/.pyenv/versions/stdatamodels/lib/python3.10/site-packages/astropy/io/fits/header.py", line 615, in _from_blocks
    raise OSError("Header missing END card.")
OSError: Header missing END card.
```

tested with astropy 5.3 and 6.0
