### ISSUE TITLE
Version 5.3 fails to correctly read (some) rice-compressed files.

### ISSUE THREAD

**Issue by rmjarvis** [astropy/astropy#15477]
### Description

One of our GalSim tests, reading a Rice-compressed fits file using astropy.io.fits, is failing with astropy version 5.3.x.  It used to work on previous versions of astropy, but fails for 5.3.0 -- 5.3.4, where it raises an error about "Invalid TFORM4: 1PE(7)".

### Expected behavior

There should be no error reading this file.

### How to Reproduce

1. Download [testF.fits.fz](https://github.com/GalSim-developers/GalSim/blob/releases/2.4/tests/Image_comparison_images/testF.fits.fz) from the GalSim test directory.  (It's very small -- only 11KB.)

2. Run the following script:
```python
from astropy.io import fits

file_name = 'testF.fits.fz'

with fits.open(file_name, 'readonly') as hdu_list:
    hdu = hdu_list[1]
    hdu.data
```

3. With astropy 5.3.4, I get the following error:
```
$ python read_rice.py 
Traceback (most recent call last):
  File "/Users/Mike/GalSim/tests/Image_comparison_images/read_rice.py", line 7, in <module>
    hdu.data
  File "/Users/Mike/mambaforge/envs/py3.10/lib/python3.10/site-packages/astropy/utils/decorators.py", line 837, in __get__
    val = self.fget(obj)
  File "/Users/Mike/mambaforge/envs/py3.10/lib/python3.10/site-packages/astropy/io/fits/hdu/compressed.py", line 1558, in data
    data = self.section[...]
  File "/Users/Mike/mambaforge/envs/py3.10/lib/python3.10/site-packages/astropy/io/fits/hdu/compressed.py", line 2189, in __getitem__
    data = decompress_hdu_section(self.hdu, first_tile_index, last_tile_index)
  File "/Users/Mike/mambaforge/envs/py3.10/lib/python3.10/site-packages/astropy/io/fits/_tiled_compression/tiled_compression.py", line 294, in decompress_hdu_section
    _check_compressed_header(hdu._header)
  File "/Users/Mike/mambaforge/envs/py3.10/lib/python3.10/site-packages/astropy/io/fits/_tiled_compression/tiled_compression.py", line 212, in _check_compressed_header
    raise RuntimeError(f"Invalid TFORM{suffix}: {header[f'TFORM{suffix}']}")
RuntimeError: Invalid TFORM4: 1PE(7)
```
There is a different error with 5.3.0, but this is the error I get for 5.3.1 -- 5.3.4.  The same error occurs on python 3.9, 3.10, 3.11 and 3.12.

### Versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)

```
macOS-12.7-arm64-arm-64bit
Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ]
astropy 5.3.4
```

**Comment by pllim** [comment]
@astrofrog ?

**Comment by saimn** [comment]
Interesting, the issue is with the UNCOMPRESSED_DATA column, which is not described in the recent version of the Standard. So the code checks for the types allowed for COMPRESSED_DATA, which does not include PE. But for UNCOMPRESSED_DATA, PE should be allowed:

![image](https://github.com/astropy/astropy/assets/311639/d0c1a44d-a5e0-4641-8f83-2a750c9da4ce)

https://fits.gsfc.nasa.gov/registry/tilecompression/tilecompression2.3.pdf

**Comment by saimn** [comment]
Actually UNCOMPRESSED_DATA is just not supported currently in the code. It should not be difficult to support (similar to GZIP COMPRESSED DATA but even easier since data is not compressed), and even if it's only described in the old convention and not included in the Standard, it would be nice to be able to read old files.

**Comment by rmjarvis** [comment]
Thank you!  
I believe this file was originally written by astropy many versions ago.  Possibly even before the transition from pyfits.  But I suspect it's not the only fits file around with the old format, so probably worth continuing to support reading it.

**Comment by DaveBuckingham** [comment]
Hey I took a stab at this and it seems to be working:
https://github.com/DaveBuckingham/astropy/tree/uncompressed
Please lmk if this looks good / works before I do a PR cause I'm brand new here and unfamiliar with this code and the data formats.

**Comment by pllim** [comment]
Thanks! To save others a few clicks, the diff is here: https://github.com/astropy/astropy/compare/main...DaveBuckingham:astropy:uncompressed

**Comment by saimn** [comment]
@DaveBuckingham - Seems a good start, thanks. Could you open a PR so it would be easier to discuss and make suggestions ?

**Comment by DaveBuckingham** [comment]
For sure, will do in a few days: what I did previously doesn't work.

**Comment by astrofrog** [comment]
@rmjarvis - this should now be fixed in ``main`` - let me know if not

**Comment by rmjarvis** [comment]
Confirmed.  Thanks Thomas!
