### ISSUE TITLE
astropy wcs not working

### ISSUE THREAD

**Issue by dan-adi** [astropy/astropy#15558]
### Description

I have a fits file and I'm trying to read the wcs data from the header, using the simple example:

```
hdulist = fits.open('arp1.fits')  
hdu = hdulist[0]  
wcs1 = WCS(hdu.header)  
wcs1
```

When I run this in jupyter notebook the kernel breaks and restarts. No output error is produced.

The following code simply looks at the header and extracts wcs keywords:
```
def read_and_print_wcs_keywords(filename):
    # Open the FITS file 
    with fits.open(filename) as hdulist:
        header = hdulist[0].header  

        # List of WCS-related keywords to print
        wcs_keywords = [
            'RA', 'DEC', 'EPOCH', 'EQUINOX', 'RADECSYS',
            'SECPIX', 'SECPIX1', 'SECPIX2',
            'CTYPE1', 'CTYPE2',
            'CRPIX1', 'CRPIX2',
            'CRVAL1', 'CRVAL2',
            'CDELT1', 'CDELT2',
            'CROTA1', 'CROTA2',
            'CD1_1', 'CD1_2', 'CD2_1', 'CD2_2',
            'PC1_1', 'PC1_2', 'PC2_1', 'PC2_2',
            'PC001001', 'PC001002', 'PC002001', 'PC002002',
            'LATPOLE', 'LONPOLE',
            'IMWCS',
            'CO1_1', 'CO1_2', 'CO1_3', 'CO1_4', 'CO1_5', 'CO1_6',
            'CO1_7', 'CO1_8', 'CO1_9', 'CO1_10', 'CO1_11', 'CO1_12',
            'CO2_1', 'CO2_2', 'CO2_3', 'CO2_4', 'CO2_5', 'CO2_6',
            'CO2_7', 'CO2_8', 'CO2_9', 'CO2_10', 'CO2_11', 'CO2_12',
            'PROJP0', 'PROJP1', 'PROJP2', 'PROJP3', 'PROJP4', 'PROJP5',
            'PROJP6', 'PROJP7', 'PROJP8', 'PROJP9',
            'PV1_0', 'PV1_1', 'PV1_2', 'PV1_3', 'PV1_4', 'PV1_5',
            'PV1_6', 'PV1_7', 'PV1_8', 'PV1_9',
            'PV2_0', 'PV2_1', 'PV2_2', 'PV2_3', 'PV2_4', 'PV2_5',
            'PV2_6', 'PV2_7', 'PV2_8', 'PV2_9',
        ]

        # Print the values associated with the specified keywords
        for keyword in wcs_keywords:
            if keyword in header:
                value = header[keyword]
                print(f"{keyword}: {value}")

if __name__ == '__main__':
    read_and_print_wcs_keywords('arp1.fits')
```

The output is:

```
RA: 338.974147188621
DEC: 33.949555651896
EPOCH: 2000
EQUINOX: 2000.0
RADECSYS: ICRS
CTYPE1: RA---TAN
CTYPE2: DEC--TAN
CRPIX1: 2262.0
CRPIX2: 1812.0
CRVAL1: 338.9738871881
CRVAL2: 33.94984779463
CD1_1: 8.716526805617e-06
CD1_2: -0.0002569530746059
CD2_1: 0.0002569530746059
CD2_2: 8.716526805617e-06
PV1_0: 2.642091799416e-05
PV1_1: 1.000181516711
PV1_2: 9.21477448475e-05
PV1_4: -0.0002481853283131
PV1_5: 6.769504088432e-05
PV1_6: 8.920065601519e-05
PV2_0: -3.66087612969e-06
PV2_1: 1.000296390968
PV2_2: -9.137330118738e-05
PV2_4: -9.904881495992e-08
PV2_5: -0.0002789818367347
PV2_6: 0.0001093752471468
```

### Expected behavior

Shouldn't  `WCS(hdu.header)` provide the same output?

### How to Reproduce

```
hdulist = fits.open('arp1.fits')  
hdu = hdulist[0]  
wcs1 = WCS(hdu.header)  
wcs1
```
Link to the arp1.fits file:

[https://drive.google.com/file/d/1-r4mJhMO8o0212YlUFwOnGn7W1eMg9Zq/view?usp=sharing](url)

### Versions

Linux-6.5.6-76060506-generic-x86_64-with-glibc2.35
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
astropy 5.3.4
Numpy 1.26.1
pyerfa 2.0.1.1
Scipy 1.11.3
Matplotlib 3.8.0

**Comment by byrdie** [comment]
Hi @dan-adi, thanks for raising this issue. Can you run your code snippet using the terminal version of Python? I think this will allow us to see the full traceback of the issue.

**Comment by dan-adi** [comment]
> Hi @dan-adi, thanks for raising this issue. Can you run your code snippet using the terminal version of Python? I think this will allow us to see the full traceback of the issue.

Great idea! Running in terminal gave some hints. It seems maybe it's the fits header that doesn't comply with what astropy.wcs standard or astropy fits standard?

here is the output:

```
dan@linuxbox:~/Desktop/notebooks/autophotN$ /home/dan/Desktop/notebooks/autophotN/.venv/bin/python /home/dan/Desktop/notebooks/autophotN/test.py
WARNING: Header block contains null bytes instead of spaces for padding, and is not FITS-compliant. Nulls may be replaced with spaces upon writing. [astropy.io.fits.header]
WARNING: FITSFixedWarning: CDELTM1 = 0.006000000000 /Size of a pixel (x) in mm 
keyword looks very much like CDELTia but isn't. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: CDELTM2 = 0.006000000000 /Size of a pixel (y) in mm 
keyword looks very much like CDELTia but isn't. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: 'datfix' made the change 'Set MJD-OBS to 60247.823167 from DATE-OBS'. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: 'celfix' made the change 'Invalid parameter value'. [astropy.wcs.wcs]
Traceback (most recent call last):
  File "/home/dan/Desktop/notebooks/autophotN/test.py", line 8, in <module>
    w = wcs.WCS(hdulist[0].header)
  File "/home/dan/Desktop/notebooks/autophotN/.venv/lib/python3.10/site-packages/astropy/wcs/wcs.py", line 612, in __init__
    self.wcs.set()
ValueError: ERROR 5 in wcsset() at line 2775 of file cextern/wcslib/C/wcs.c:
Invalid parameter value.
ERROR 4 in linset() at line 737 of file cextern/wcslib/C/lin.c:
Failed to initialize distortion functions.
ERROR 3 in dssset() at line 2697 of file cextern/wcslib/C/dis.c:
Coefficient scale for DSS on axis 1 is zero..
```
At least I'm getting somewhere, spent all day troubleshooting

**Comment by byrdie** [comment]
These warnings:
```
WARNING: FITSFixedWarning: CDELTM1 = 0.006000000000 /Size of a pixel (x) in mm 
keyword looks very much like CDELTia but isn't. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: CDELTM2 = 0.006000000000 /Size of a pixel (y) in mm 
keyword looks very much like CDELTia but isn't. [astropy.wcs.wcs]
```
and this error
```
ERROR 3 in dssset() at line 2697 of file cextern/wcslib/C/dis.c:
Coefficient scale for DSS on axis 1 is zero..
```
Make it seem like the problem might be that your fits file does not specify `CDELT1` and `CDELT2`, which are needed for the WCS to work. What is the source of this file? Did you expect `CDELT1`/`CDELT2` or equivalent to be specified?

**Comment by dan-adi** [comment]
> These warnings:
> 
> ```
> WARNING: FITSFixedWarning: CDELTM1 = 0.006000000000 /Size of a pixel (x) in mm 
> keyword looks very much like CDELTia but isn't. [astropy.wcs.wcs]
> WARNING: FITSFixedWarning: CDELTM2 = 0.006000000000 /Size of a pixel (y) in mm 
> keyword looks very much like CDELTia but isn't. [astropy.wcs.wcs]
> ```
> 
> and this error
> 
> ```
> ERROR 3 in dssset() at line 2697 of file cextern/wcslib/C/dis.c:
> Coefficient scale for DSS on axis 1 is zero..
> ```
> 
> Make it seem like the problem might be that your fits file does not specify `CDELT1` and `CDELT2`, which are needed for the WCS to work. What is the source of this file? Did you expect `CDELT1`/`CDELT2` or equivalent to be specified?

This is how the fits file gets created by the observatory software. I tested another fits file , and run it through the script.
This is my fits header:
```
SIMPLE  =                    T /FITS header                                     
BITPIX  =                  -32 /No.Bits per pixel                               
NAXIS   =                    2 /No.dimensions                                   
NAXIS1  =                 4524 /Length X axis                                   
NAXIS2  =                 3624 /Length Y axis                                   
DATE    = '2023-10-07T18:56:53.904600' /Date of FITS file creation              
SWCREATE= 'PRISM,  Version  11.4.16.34,  9/21/2023' /Software Name and version  
ORIGIN  = 'Lumina            ' /Origin place of FITS image                      
OBSERVER= 'Dan Cioc          ' /Observer name                                   
SITELAT = '+44:17:42:99      ' /Latitude observatory                            
SITELONG= '+28:34:31:99      ' /Longitude observatory                           
DATE-OBS= '2023-10-07T18:51:27.825600' /UT date of Observation                  
UT      = '18:51:27.82       ' /UT begining of observation                      
EXPOSURE=            300.00000 /Exposure time seconds                           
XPIXELSZ=                 6.00 /X pixel size microns                            
CDELTM1 =       0.006000000000 /Size of a pixel (x) in mm                       
XPIXSZ  =                  6.0 /X Binned pixel size as microns                  
YPIXELSZ=                 6.00 /Y pixel size microns                            
CDELTM2 =       0.006000000000 /Size of a pixel (y) in mm                       
YPIXSZ  =                  6.0 /X Binned pixel size as microns                  
INSTRUME= 'G3-16200'           / Instrument                                     
FILTERS = 'Infrared          ' /Filters                                         
CVF     =                0.600 /Conversion factor (e-/adu)                      
READOUTT=                23.66 /Image readout time (sec)                        
X1      =                    1 /X1 image windowing                              
Y1      =                    1 /Y1 image windowing                              
X2      =                 4524 /X2 image windowing                              
Y2      =                 3624 /Y2 image windowing                              
COMPRESS=                    0 /Number of compression                           
TELESCOP= 'CFF203            ' /Telescope                                       
FOCAL   =               1336.0 /Focal length in mm                              
DIAMETER=                203.0 /Diameter in mm                                  
OBJCTRA = '22 35 51.430      ' /Object Right Ascension (J2000)                  
OBJCTDEC= '+33 57 03.29      ' /Object Declinaison (J2000)                      
RA      =     338.964292886054 /Telescope RA                                    
DEC     =      33.950914101325 /Telescope DEC                                   
CRVAL1  =     338.964292886054 /approx coord. in RA                             
CRVAL2  =      33.950914101325 /approx coord. in DEC                            
CDELT1  =       0.000257316375 /ScaleX in deg/pix                               
CDELT2  =       0.000257316375 /ScaleY in deg/pix                               
DATAMAX =              1902.00 /Maximum data value                              
DATAMIN =               887.00 /Minimum data value                              
PIERSIDE= 'WEST              ' /Side of the tube wrt to Pier                    
CCD-TEMP=                -10.0 /CCD temperature as Celsius degrees              
FOCUSADU=                62630 /Focuser position as encoder steps               
FOCUSTMP=                 17.0 /Focuser temperature as Celsius degrees          
BITCAMPX=                   16 /Native camera dynamic in bits per pixel         
STACKNB =                    1 /Amount of stacked images                        
STARCNT =                    0 /Amount of extracted stars                       
GAIN_ELE=                    0 /Camera electronic gain (arbitrary units)        
OFFSET_E=                    0 /Camera electronic offset (arbitrary units)      
TEMPEXT =                 18.7 /External temperature, unit is degrees C         
PRESSURE=               1026.5 /Atm. Pressure, unit is Hpa                      
DEWPOINT=                  3.9 /Dewpoint temperature, unit is degrees C         
HUMIDITY=                 37.5 /Relative humidity, unit is percent              
WINSPEED=                  8.7 /Wind speed, unit is km/h                        
WINDIR  =                  0.0 /Wind direction, North 0deg, East 90d            
IMGTYPE = 'STD_IMAGE         ' /Image type, like flat, bias or dark             
BAYERIND=                    0 /Bayer color Index                               
CCDBIN1 =                    1                                                  
CCDBIN2 =                    1                                                  
COMMENT  Clouds cover Clear Sky                                                 
HISTORY none                                                                    
END                            
```

This is the script:
```
from astropy import wcs
from astropy.io import fits


hdulist = fits.open('ARP.fits')  
hdu = hdulist[0]  
wcs1 = wcs.WCS(hdu.header)  
wcs1







```

And the output:
```
WARNING: FITSFixedWarning: CDELTM1 = 0.006000000000 /Size of a pixel (x) in mm 
keyword looks very much like CDELTia but isn't. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: CDELTM2 = 0.006000000000 /Size of a pixel (y) in mm 
keyword looks very much like CDELTia but isn't. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: 'datfix' made the change 'Set MJD-OBS to 60224.785739 from DATE-OBS'. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: 'celfix' made the change 'Invalid parameter value'. [astropy.wcs.wcs]
Traceback (most recent call last):
  File "/home/dan/Desktop/notebooks/autophotN/test.py", line 8, in <module>
    w = wcs.WCS(hdulist[0].header)
  File "/home/dan/Desktop/notebooks/autophotN/.venv/lib/python3.10/site-packages/astropy/wcs/wcs.py", line 612, in __init__
    self.wcs.set()
ValueError: ERROR 5 in wcsset() at line 2775 of file cextern/wcslib/C/wcs.c:
Invalid parameter value.
ERROR 4 in linset() at line 737 of file cextern/wcslib/C/lin.c:
Failed to initialize distortion functions.
ERROR 3 in dssset() at line 2697 of file cextern/wcslib/C/dis.c:
Coefficient scale for DSS on axis 1 is zero..
```
I see the CDELT1 and CDELT2 are in the header.

**Comment by pllim** [comment]
Are `CDELTM1` and `CDELTM2` proper WCS keywords? Try deleting them?

**Comment by dan-adi** [comment]
> Are `CDELTM1` and `CDELTM2` proper WCS keywords? Try deleting them?

Tried deleting them to no effect.

Here is a link to google drive with 2 fits for testing.
science01.fits is just as it came out of the CCD camera
science01_solved.fits is science01.fits astrometrically solved with ASTAP and the WCS info automatically inserted in the fits header.

[https://drive.google.com/drive/folders/1GGDTyvgPsK1n6DGt0HT-BPwhWB8y_ArS?usp=sharing](url)

If the link doesn't work I also attached the solved image as zip file
[science01_solved.zip](https://github.com/astropy/astropy/files/13220539/science01_solved.zip)
 the fits compressed as zip files

**Comment by dan-adi** [comment]
And the science01.fits
[science01.zip](https://github.com/astropy/astropy/files/13220553/science01.zip)

**Comment by pllim** [comment]
The keywords you listed in https://github.com/astropy/astropy/issues/15558#issuecomment-1787598503 are different from the original post. Which observatory is this? Is the data from their public archive?

**Comment by dan-adi** [comment]
> The keywords you listed in [#15558 (comment)](https://github.com/astropy/astropy/issues/15558#issuecomment-1787598503) are different from the original post. Which observatory is this? Is the data from their public archive?

Yes they are different, I used a different astrometric solver, to see if it makes a difference. It is my own observatory :)

> The keywords you listed in [#15558 (comment)](https://github.com/astropy/astropy/issues/15558#issuecomment-1787598503) are different from the original post. Which observatory is this? Is the data from their public archive?

Yes they are, I used a different solver to see if it makes a difference. It is my own observatory :). 
I tried loading the wcs data in ds9 from the science01_solved.fits and it reads it no issue. Confusing ...
<img width="1440" alt="Screenshot 2023-10-31 at 23 44 25" src="https://github.com/astropy/astropy/assets/74410940/bf2ed36e-9e2e-49dd-b6df-5f90d3d146ae">

**Comment by dan-adi** [comment]
Finally got it .... spent all day 
I have to delete the following:
```
h.remove('XPIXELSZ')
h.remove('YPIXELSZ')
h.remove('CDELTM1')
h.remove('CDELTM2')
```
then  I ran:
```
hdulist2 = fits.open('ARP_Solved.fits')  
hdut = hdulist[0]  
wcs = WCS(hdulist2[0].header)  
wcs

```
AND VOILA
```
WCS Keywords

Number of WCS axes: 2
CTYPE : 'RA---TAN'  'DEC--TAN'  
CRVAL : 338.9776673617  33.94929211956  
CRPIX : 2262.5  1812.5  
CD1_1 CD1_2  : -8.023616067367e-06  -0.0002569870529751  
CD2_1 CD2_2  : -0.0002570335859688  7.94778752437e-06  
NAXIS : 4524  3624
```

If only every developer would respect the FITS standard ....

**Comment by pllim** [comment]
Glad you figured it out and thanks for reporting back!

**Comment by dan-adi** [comment]
@pllim Thanks for your support!
