### ISSUE TITLE
error creating a new FITS image with data & header

### ISSUE THREAD

**Issue by mrawls** [astropy/astropy#1559]
(UPDATE BY @embray: @mrawls found that ndarrays with an 'object' dtype were mistakenly being used to write FITS images. That said, PyFITS should catch unsupported data types sooner and raise a more helpful error message (I think there are places where it _does_ do this, but this particular corner case slips through the cracks).

I am attempting to create a new FITS image file with a single column of spectral data and a header. I'm relatively new to python and astropy, so any help is appreciated. I'm using Python 2.7 and astropy version 0.2.4 on my Macbook Pro, which is running Mountain Lion 10.8.5.

```
import numpy as np
import matplotlib.pyplot as plt
from astropy.io import fits
from astropy.io.fits import getdata
from astropy.io.fits import getheader

headernote = 'Data and wavelength scale modified w/2nd order telluric correction.'
wavestart = 3550.
dwave = 0.0455
infiles = "infiles_9246715.txt"
f1 = open(infiles) # open a text file containing a list of FITS filenames

# NOTE brandnewspeclist is a previously-defined list of numpy arrays.
# Each array is ~155000 values long, and contains floats between -0.17 and 2.0.
# I tried adding 1.0 to all values so everything was > 0, but there was no change.

i = 0
# Loop over each file, this time to create new versions in new files.
for line in f1:
    infile = line.rstrip()
    outfile = 'new_' + infile

    # Read in the original FITS header
    head = getheader(infile)

    # Make a new FITS file with the new data and old header
    n = np.arange(100.0)
    #hdu = n #works with this
    hdu = brandnewspeclist[i] #doesn't work with this
    #print type(n), type(hdu) # I checked, and both are numpy.ndarrays
    fout = open('test' + str(i) + '.txt', 'w')
    for j in range(len(brandnewspeclist[i])):
        fout.write('%f \n' % brandnewspeclist[i][j]) # outfile doesn't have any nans

    # This is where it breaks and gives me a KeyError: 'object'
    # (unless I've set hdu = n instead of brandnewspeclist[i])
    fits.writeto(outfile, hdu, header=head)

    # I tried this approach instead, but got the same error
    #hdu = fits.PrimaryHDU(brandnewspeclist[i])
    #hdu.writeto(outfile, header=head)

    # Next step: create a new header object
    newhead = getheader(outfile)
    # Update the two header values to change the wavelength solution
    # Note: this isn't working either. The code ran when I used 'n' instead of
    # 'brandnewspeclist[i]' as hdu, but these header values didn't change.
    # At the moment, however, this is a secondary concern.
    newhead['cdelt1'] = (dwave, headernote)
    newhead['crval1'] = (wavestart, headernote)

    i = i + 1
f1.close()
```

And the error this generates is...

```
ERROR: KeyError: 'object' [astropy.io.fits.hdu.image]
Traceback (most recent call last):
  File "telluric.py", line 230, in <module>
    fits.writeto(outfile, hdu, header=head)
  File "/Library/Python/2.7/site-packages/astropy/io/fits/convenience.py", line 402, in writeto
    hdu = _makehdu(data, header)
  File "/Library/Python/2.7/site-packages/astropy/io/fits/convenience.py", line 756, in _makehdu
    hdu = _BaseHDU(data, header)
  File "/Library/Python/2.7/site-packages/astropy/io/fits/hdu/image.py", line 795, in __init__
    scale_back=scale_back)
  File "/Library/Python/2.7/site-packages/astropy/io/fits/hdu/image.py", line 139, in **init**
    self.data = data
  File "/Library/Python/2.7/site-packages/astropy/utils/misc.py", line 262, in **set**
    self._fset(obj, val)
  File "/Library/Python/2.7/site-packages/astropy/io/fits/hdu/image.py", line 215, in data
    self._bitpix = _ImageBaseHDU.ImgCode[data.dtype.name]
KeyError: 'object'
```

**Comment by aishrimc** [comment]
Hello. I ran into a similar problem while trying to create a new fits file. I am getting the error when I tried to create a new fits file as follows : 
`x = some_array of shape [384,384,1]
hdr = fits.Header()
hdr['BTYPE']   = 'some_type'                                                           
hdr['OBJECT']  = ' something'                                                            
hdr['BUNIT']   = 'some_unit' 
hdu = fits.PrimaryHDU(data=x, header=hdr)`

This is giving the error:

`KeyError                                  Traceback (most recent call last)
<ipython-input-50-0a2272a0b8eb> in <module>()
----> 1 exec(open('write_fits.py').read())

<string> in <module>()

/home/vvv/anaconda2/lib/python2.7/site-packages/astropy/utils/decorators.pyc in wrapper(*args, **kwargs)
    506                         # one with the name of the new argument to the function
    507                         kwargs[new_name[i]] = value
--> 508             return function(*args, **kwargs)
    509 
    510         return wrapper

/home/vvv/anaconda2/lib/python2.7/site-packages/astropy/io/fits/convenience.pyc in writeto(filename, data, header, output_verify, overwrite, checksum)
    427     """
    428 
--> 429     hdu = _makehdu(data, header)
    430     if hdu.is_image and not isinstance(hdu, PrimaryHDU):
    431         hdu = PrimaryHDU(data, header=header)

/home/vvv/anaconda2/lib/python2.7/site-packages/astropy/io/fits/convenience.pyc in _makehdu(data, header)
   1015             hdu = ImageHDU(data, header=header)
   1016         else:
-> 1017             raise KeyError('Data must be a numpy array.')
   1018     return hdu
   1019 
KeyError: 'Data must be a numpy array.'
`
The outputs for x.shape, x.dtype, x.dtype.name, and x.dtype.type are (384, 384, 1), dtype('float32'), 'float32' and numpy.float32 respectively. 

The funny thing is when I do:

`im1 = fits.open('an_image_I_have.fits')
hdr = im1[0].header
x = some_array of shape [384,384,1]
fits.writeto('name_of_file', x,hdr)
`
no such error is shown, the fits file is generated.

**Comment by pllim** [comment]
@aishrimc , how exactly did you create that "some_array of shape [384,384,1]"?

**Comment by aishrimc** [comment]
`some_array of shape [384,384,1]` was created from a binary file of shape [384,384,384], by picking out a slice from the third axis, namely: `some_array=initial_array[:,:,192]`.
I will upgrade and try in Astropy latest release under 3.x. Thanks @pllim

**Comment by MSeifert04** [comment]
@aishrimc This seems to be a different issue altogether. Could you [open a new issue](https://github.com/astropy/astropy/issues/new) with a **reproducible example**?
