### ISSUE TITLE
Adding empty quantity to time raises misleading error in 6.0rc1

### ISSUE THREAD

**Issue by maxnoe** [astropy/astropy#15601]
### Description

Testing the 6.0rc1, there was a change in behavior for adding empty quantities to time:
5.x:

```
 >>> Time.now() + [] * u.s
 <Time object: scale='utc' format='datetime' value=[]>
```

6.0 raises an error that is misleading, as the problem is the dimensionality of the quantity, not the missing function implementation:

```
 >>> Time.now() + [] * u.s
 Traceback (most recent call last):
   File "/home/maxnoe/.local/conda/envs/astropy5/lib/python3.11/site-packages/astropy/units/quantity_helper/converters.py", line 196, in converters_and_unit
     if can_have_arbitrary_unit(args[i]):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/maxnoe/.local/conda/envs/astropy5/lib/python3.11/site-packages/astropy/units/quantity_helper/converters.py", line 138, in can_have_arbitrary_unit
     return np.all(np.logical_or(np.equal(value, 0.0), ~np.isfinite(value)))
                                                        ^^^^^^^^^^^^^^^^^^
 TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/home/maxnoe/.local/conda/envs/astropy5/lib/python3.11/site-packages/astropy/units/quantity.py", line 691, in __array_ufunc__
     raise e
   File "/home/maxnoe/.local/conda/envs/astropy5/lib/python3.11/site-packages/astropy/units/quantity.py", line 636, in __array_ufunc__
     converters, unit = converters_and_unit(function, method, *inputs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/maxnoe/.local/conda/envs/astropy5/lib/python3.11/site-packages/astropy/units/quantity_helper/converters.py", line 207, in converters_and_unit
     raise TypeError(
 TypeError: Unsupported operand type(s) for ufunc add: 'Time,Quantity'
```

### Expected behavior

Either stick with the 5.x behavior (empty time object) or raise a more helpful error message.

### How to Reproduce

```python
Time.now() + [] * u.s
```

### Versions

astropy 6.0.0rc1

**Comment by pllim** [comment]
Does this block release? Please update https://github.com/astropy/astropy/wiki/v6.0-RC-Testing accordingly. Thanks!

**Comment by maxnoe** [comment]
Not sure if this should Block release, certainly prevents us from being compatible without changes,  but since it's a major version bump...

**Comment by mhvk** [comment]
Definitely a bug. Even though the previous behaviour is a bit odd, it is what numpy does too, so we should go back to it.

**Comment by mhvk** [comment]
The problem underlying this is that the following now breaks:
```
TimeDelta([]*u.s)
# ValueError: cannot guess format from input values with zero-size array or all elements masked
```
Before #15264 this used to work. The error message is confusing become first one has `TimeDelta.__add__([] * u.s)` which internally gets the above error and then returns `NotImplemented`, and then one gets `Quantity.__radd__(td)`, which also errors (logically, since it cannot do anything with a `TimeDelta`). 

See #15604 for a fix.
