### ISSUE TITLE
Incompatibilities with SpectralCube

### ISSUE THREAD

**Issue by HumbleSituation164** [astropy/astropy#15666]
### Description

Ran into an issue trying to generate moment maps in `spectral-cube` where the files were imported as follows:

```
from glob import glob
from spectral_cube import SpectralCube

pbfits = glob('*pb*.fits')
```

### Expected behavior

Running `SpectralCube.read` confirms the the files are being read, however once the moment function is applied, it yields an error.

```
for x in pbfits:
	if 'pbcor' in x:
		cube = SpectralCube.read(x)
		moment_0 = cube.moment(order=0)
	else:
		cube = SpectralCube.read(x)
		moment_1 = cube.moment(order=1)
```

```
Traceback (most recent call last):
  File "/home/hnscolati/alma-ml/scripts/make_flats.py", line 33, in <module>
    moment_1 = cube.moment(order=1)
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/hnscolati/miniconda3/envs/alma/lib/python3.11/site-packages/spectral_cube/spectral_cube.py", line 1665, in moment
    out = dispatch[how](self, order, axis)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hnscolati/miniconda3/envs/alma/lib/python3.11/site-packages/spectral_cube/_moments.py", line 188, in moment_auto
    return strategy[iterator_strategy(cube, axis)](cube, order, axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hnscolati/miniconda3/envs/alma/lib/python3.11/site-packages/spectral_cube/_moments.py", line 97, in moment_slicewise
    return _slice1(cube, axis)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/hnscolati/miniconda3/envs/alma/lib/python3.11/site-packages/spectral_cube/_moments.py", line 77, in _slice1
    pix_cen = cube._pix_cen()[axis]
              ^^^^^^^^^^^^^^^
  File "/home/hnscolati/miniconda3/envs/alma/lib/python3.11/site-packages/spectral_cube/utils.py", line 18, in wrapper
    self._cache[(func, args)] = func(self, *args)
                                ^^^^^^^^^^^^^^^^^
  File "/home/hnscolati/miniconda3/envs/alma/lib/python3.11/site-packages/spectral_cube/spectral_cube.py", line 1456, in _pix_cen
    from astropy.coordinates.angle_utilities import angular_separation
ModuleNotFoundError: No module named 'astropy.coordinates.angle_utilities'

```

Based on the spectral-cube.readthedocs, this should work. We are suspecting that the `astropy.coordinates.angular_separation` module was removed in the latest update and our current work around was to downgrade to `astropy v5.3.3`

### How to Reproduce

We checked if the module could be imported in the terminal:

```
>>> from astropy.coordinates.angle_utilities import angular_separation
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'astropy.coordinates.angle_utilities'
``` 

### Versions

`Python (v3.11.5)`
`spectral-cube (v0.6.3)`
`astropy (v6.0.0)`

**Comment by pllim** [comment]
@neutrinoceros , I think @keflavich already has a patch at https://github.com/radio-astro-tools/spectral-cube/pull/893 and it looks correct. `angle_formats` was removed.

**Comment by neutrinoceros** [comment]
Oh thanks, I missed that! Still, I don't see any mention of this removal in the changelog. Is it okay if I add it in a PR aimed at 6.0.1 ?

**Comment by pllim** [comment]
There were a bunch of refactoring across multiple PRs. The authors are usually very vigilant in what they put in the change logs, so if it was indeed omitted, I think it was done on purpose. Should ask @eerovaher or @nstarman to start.

**Comment by nstarman** [comment]
``from astropy.coordinates import angle_formats`` is now ``from astropy.coordinates.angles import formats``

This module is a private library (see the module docstring). Sorry for the confusion, I know it's hard to tell what's public vs private, leading to these issues.

**Comment by neutrinoceros** [comment]
thank you !

**Comment by eerovaher** [comment]
@nstarman is basically correct, but I'll add some details.

> running `from astropy.coordinates import angle_formats` fails on astropy 6.0. I've bisected this to [Consolidate angle modules #15220](https://github.com/astropy/astropy/pull/15220) (ping @nstarman), but for reasons I do not understand, the removal of this module isn't visible in the diff.

If you have used `git bisect` to find the commit id (d56526ba3ec29edb181b198b7565d7b8940654e0 in this case) then it should be simple to see what happened with the file you are interested in:
```shell
$ git show --name-status d56526ba3ec29edb181b198b7565d7b8940654e0 | grep angle_formats
R098	astropy/coordinates/angle_formats.py	astropy/coordinates/angles/formats.py
```
So the file was renamed.

As for the change log entry, there is one present:
https://github.com/astropy/astropy/blob/d56526ba3ec29edb181b198b7565d7b8940654e0/docs/changes/coordinates/15220.api.rst
It deliberately avoids mentioning `angle_formats` by name because the existence of that module was an implementation detail that was never supposed to used by outsiders. Admittedly, it was not obvious that this module was for internal use only, but there's an proposed APE (APE 22) that tries to address that.

**Comment by neutrinoceros** [comment]
Thank you, I'll check APE 22 out !
