### ISSUE TITLE
dep_util is Deprecated

### ISSUE THREAD

**Issue by mariel-lm** [astropy/astropy#15700]
### Description

I'm trying to install a module that uses astropy, but there seems to be a problem with astropy, concretely with module wcs.

### How to Reproduce

1. Get package from https://github.com/SSDataLab/psfmachine
2. Then run pip install psfmachine
3. An error occurs.

Collecting psfmachine
  Using cached psfmachine-1.1.0-py3-none-any.whl (47 kB)
Collecting astropy<5.0,>=4.2 (from psfmachine)
  Using cached astropy-4.3.1.tar.gz (7.6 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [45 lines of output]
  astropy\wcs\setup_package.py:12: SetuptoolsDeprecationWarning: dep_util is Deprecated. Use functions from setuptools.modified instead.
  !!
  
          ********************************************************************************
          Please use `setuptools.modified` instead of `setuptools.dep_util`.
  
          By 2024-May-21, you need to update your project and remove deprecated calls
          or your builds will no longer be supported.
  
          See https://github.com/pypa/setuptools/pull/4069 for details.
          ********************************************************************************
  
  !!
    from setuptools.dep_util import newer_group
  Traceback (most recent call last):
    File "C:\Users\LARESM\AppData\Local\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\LARESM\AppData\Local\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\LARESM\AppData\Local\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\LARESM\AppData\Local\Temp\pip-build-env-f_71zz6w\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\LARESM\AppData\Local\Temp\pip-build-env-f_71zz6w\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "C:\Users\LARESM\AppData\Local\Temp\pip-build-env-f_71zz6w\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 70, in <module>
    File "C:\Users\LARESM\AppData\Local\Temp\pip-build-env-f_71zz6w\overlay\Lib\site-packages\extension_helpers\_setup_helpers.py", line 67, in get_extensions
      ext_modules.extend(setuppkg.get_extensions())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
    File ".\astropy\modeling\setup_package.py", line 59, in get_extensions
      from jinja2 import Environment, FileSystemLoader
    File "C:\Users\LARESM\AppData\Local\Temp\pip-build-env-f_71zz6w\overlay\Lib\site-packages\jinja2\__init__.py", line 33, in <module>
      from jinja2.environment import Environment, Template
    File "C:\Users\LARESM\AppData\Local\Temp\pip-build-env-f_71zz6w\overlay\Lib\site-packages\jinja2\environment.py", line 15, in <module>
      from jinja2 import nodes
    File "C:\Users\LARESM\AppData\Local\Temp\pip-build-env-f_71zz6w\overlay\Lib\site-packages\jinja2\nodes.py", line 19, in <module>
      from jinja2.utils import Markup
    File "C:\Users\LARESM\AppData\Local\Temp\pip-build-env-f_71zz6w\overlay\Lib\site-packages\jinja2\utils.py", line 642, in <module>
      from markupsafe import Markup, escape, soft_unicode
  ImportError: cannot import name 'soft_unicode' from 'markupsafe' (C:\Users\LARESM\AppData\Local\Temp\pip-build-env-f_71zz6w\overlay\Lib\site-packages\markupsafe\__init__.py)
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by pllim** [comment]
Hi. This psfmachine was max-pinning astropy. And looks like they have v1.1.4 tag so maybe ask them how to install that one? I see that they might have removed the max pin in the source code. `astropy` is now at 6.0.0 and unfortunately your problem isn't something we can fix here. Good luck!

```
Collecting astropy<5.0,>=4.2 (from psfmachine)
Using cached astropy-4.3.1.tar.gz (7.6 MB)
```

**Comment by hugobuddel** [comment]
FWIW, it seems that 5.3.4 is the first astropy version that works w.r.t. this deprecation.
