### ISSUE TITLE
BUG: indexing a `QTable` with a `Quantity` column doesn't work as expected

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#16036]
```python
import astropy.units as u
from astropy.table import QTable

t = QTable({"a": u.Quantity([0], unit="m")})
t.add_index(["a"])
t.loc[t["a"][0]]
```
fails with
```python-traceback
Traceback (most recent call last):
  File "/Users/clm/dev/astropy-project/coordinated/astropy/t.py", line 6, in <module>
    t.loc[t["a"][0]]
    ~~~~~^^^^^^^^^^^
  File "/Users/clm/dev/astropy-project/coordinated/astropy/astropy/table/index.py", line 888, in __getitem__
    rows = self._get_rows(item)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/clm/dev/astropy-project/coordinated/astropy/astropy/table/index.py", line 867, in _get_rows
    for key in item:
  File "/Users/clm/dev/astropy-project/coordinated/astropy/astropy/units/quantity.py", line 1283, in __iter__
    raise TypeError(
TypeError: 'Quantity' object with a scalar value is not iterable
```

In contrast, the following works
```python
import astropy.units as u
from astropy.table import QTable

t = QTable({"a": u.Quantity([0], unit="m")})
t.add_index(["a"])
t.loc[t["a"][0].value]  # passing `.value` instead of the full quantity
```

Using a `Table` instead of a `QTable` also works as expected
```python
import astropy.units as u
from astropy.table import Table

t = Table({"a": u.Quantity([0], unit="m")})
t.add_index(["a"])
t.loc[t["a"][0]]
```

I'm not 100% sure the current behaviour is actually buggy: this is a matter of intent.
This was first discussed in #15826 where @taldcroft found that multi-indexing wouldn't work seamlessly for `Quantity` indices, as he assumed.

This report is adapted from my comment https://github.com/astropy/astropy/issues/15826#issuecomment-1942541936_

**Comment by mhvk** [comment]
Note that for non-scalar input, the error is different,
```
t = QTable({"a": u.Quantity([20., 21., 22.], unit="m")})
t.add_index(["a"])
t.loc[t["a"][1:]]
# KeyError: 'No matches found for key 21.0 m'
```

**Comment by neutrinoceros** [comment]
> For an implementation, possibly easiest is not to pass in columns to Index but rather a Table/QTable with the desired columns (since the columns are going to be added to a table anyway).

I think it's feasible but it isn't as easy as I first thought. I'm game to try it out again if no objection is raised !

**Comment by mhvk** [comment]
Sure!

**Comment by neutrinoceros** [comment]
I gave this another try but I'm stuck again. Here's what I tried
```patch
diff --git a/astropy/table/index.py b/astropy/table/index.py
index f390ab7616..36c5b2cbb6 100644
--- a/astropy/table/index.py
+++ b/astropy/table/index.py
@@ -31,13 +31,20 @@ Notes
     array.view(Column) -> no indices
 """
 
+from __future__ import annotations
+
 from copy import deepcopy
+from typing import TYPE_CHECKING
 
 import numpy as np
 
 from .bst import MaxValue, MinValue
 from .sorted_array import SortedArray
 
+if TYPE_CHECKING:
+    from astropy.table import Table
+    from astropy.table._typing import MixinColumn
+
 
 class QueryError(ValueError):
     """
@@ -54,7 +61,7 @@ class Index:
 
     Parameters
     ----------
-    columns : list or None
+    columns : list, or Table, or None
         List of columns on which to create an index. If None,
         create an empty index for purposes of deep copying.
     engine : type, instance, or None
@@ -65,13 +72,15 @@ class Index:
         Whether the values of the index must be unique
     """
 
-    def __init__(self, columns, engine=None, unique=False):
+    def __init__(
+        self, columns: list[MixinColumn] | Table | None, engine=None, unique=False
+    ):
         # Local imports to avoid import problems.
         from astropy.time import Time
 
         from .table import Column, Table
 
-        if columns is not None:
+        if columns is not None and not isinstance(columns, Table):
             columns = list(columns)
 
         if engine is not None and not isinstance(engine, type):
@@ -81,13 +90,17 @@ class Index:
             self.columns = columns
             return
 
-        # by default, use SortedArray
-        self.engine = engine or SortedArray
-
         if columns is None:  # this creates a special exception for deep copying
             columns = []
             data = []
             row_index = []
+        elif isinstance(columns, Table):
+            table = columns
+            table_cls = type(table)
+            col = table.columns[0]
+            row_index = Column(col.argsort(kind="stable"))
+            data = table_cls([col[row_index]])
+            columns = list(table.columns.values())
         elif len(columns) == 0:
             raise ValueError("Cannot create index without at least one column")
         elif len(columns) == 1:
@@ -119,6 +132,8 @@ class Index:
             data = lines[lines.colnames[:-1]]
             row_index = lines[lines.colnames[-1]]
 
+        # by default, use SortedArray
+        self.engine = engine or SortedArray
         self.data = self.engine(data, row_index, unique=unique)
         self.columns = columns
 
diff --git a/astropy/table/table.py b/astropy/table/table.py
index f3937c8da2..d6deea5940 100644
--- a/astropy/table/table.py
+++ b/astropy/table/table.py
@@ -1095,10 +1095,10 @@ class Table:
                     "cannot be used as an index."
                 )
 
-        is_primary = not self.indices
-        index = Index(columns, engine=engine, unique=unique)
+        table = type(self)(data=list(columns), names=colnames)
+        index = Index(table, engine=engine, unique=unique)
         sliced_index = SlicedIndex(index, slice(0, 0, None), original=True)
-        if is_primary:
+        if not self.indices:
             self.primary_key = colnames
         for col in columns:
             col.info.indices.append(sliced_index)
```

This has the benefit of aligning errors we see in both test cases (with a scalar column VS a non-scalar one) to
```
...
TypeError: 'Quantity' object with a scalar value is not iterable
```
so I thought I was halfway there; but the problem is that this change also create multiple failure modes in the test suite (`ValueError`, `TypeError`, or even `RecursionError`). Overall this looks more and more like a can of worms to me, and given *I* reported the original issue (as opposed to an actual user), I'm tempted to give it low priority.

**Comment by mhvk** [comment]
Looking just above where the error in the indexing occurs, at https://github.com/astropy/astropy/blob/03c4f78d6fc3ea7ef13cda3e8f1b7f6601ac6231/astropy/table/index.py#L851-L855

One sees that non-ndarray are transformed to a list, while a scalar `Quantity` remains a subclass of `ndarray`. We could perhaps do this generally for `not isiterable(item)` - I think that might solve the bug, with the slight risk that some other things (not sure which) may break at a different place.

**Comment by neutrinoceros** [comment]
Just tried it. Either by itself or combined with my other patch, this doesn't pass the test suite.
The only patch that passes both tests is the combination of https://github.com/astropy/astropy/issues/16036#issuecomment-2449921114 with https://github.com/astropy/astropy/issues/16036#issuecomment-2453506923, but alas, it also breaks a lot of other things.

**Comment by mhvk** [comment]
Trying it myself, I see the problem is `str` items - so, `not isiterable` is too much. But checking for a `shape` works - see #17329.

**Comment by Jitenndra03** [comment]
Hi @neutrinoceros  @taldcroft ft, I'd like to work on this if it's still up for grabs.

From the traceback, the failure is in `Table.loc.__getitem__` → `_get_rows()` in `astropy/table/index.py`, where `for key in item:` assumes `item` is iterable. A scalar `Quantity` isn't iterable the way a plain Python/NumPy scalar is, so it raises instead of being treated as a single lookup key.

Before I open a PR, I want to confirm the intended fix, since the issue notes this might be a matter of intent rather than a straightforward bug:
- Should a scalar `Quantity` be unwrapped (e.g. via `.item()` or `.value`) and treated like any other scalar key?
- Or would you rather this raise a clearer, more informative error telling the user to pass `.value` instead?

Happy to go with whichever you prefer. Could someone assign this to me? This would be my first contribution to astropy.

**Comment by taldcroft** [comment]
@Jitenndra03 - thanks but this is not a good issue for a first-time contributor.
