### ISSUE TITLE
BUG: crash when instantiating a `Longitude` from large angle with `dtype=int`

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#16217]
### Description

We have at least one test showing that instantiating `Longitude` with an integer value is explicitly supported,
however it doesn't exercise wrapping, which is actually broken.
This came up while digging into #13479

### Expected behavior

No crash.
Alternatively, we could drop support for integer-valued angles altogether, but this seems uncalled for at this point.

### How to Reproduce

```python
import numpy as np
import astropy.units as u
from astropy.coordinates import Longitude

# this is explicitly tested in astropy/coordinates/tests/test_angles::test_longitude
assert Longitude(0, u.deg, dtype=int).dtype == np.dtype("int")

# but this crashes
Longitude(1234, u.deg, dtype=int).dtype
```

```python-traceback
Traceback (most recent call last):
  File "/Users/clm/dev/astropy-project/coordinated/astropy/untitled.py", line 9, in <module>
    Longitude(1234, u.deg, dtype=int).dtype
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/clm/dev/astropy-project/coordinated/astropy/astropy/coordinates/angles/core.py", line 716, in __new__
    self.wrap_angle = wrap_angle  # angle-like b/c property setter
    ^^^^^^^^^^^^^^^
  File "/Users/clm/dev/astropy-project/coordinated/astropy/astropy/coordinates/angles/core.py", line 733, in wrap_angle
    self._wrap_at(self.wrap_angle)
  File "/Users/clm/dev/astropy-project/coordinated/astropy/astropy/coordinates/angles/core.py", line 422, in _wrap_at
    self_angle -= wraps * a360
numpy._core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'subtract' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

### Versions

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
try:
    import scipy
    print("Scipy", scipy.__version__)
except ImportError:
    print("Scipy not installed")
try:
    import matplotlib
    print("Matplotlib", matplotlib.__version__)
except ImportError:
    print("Matplotlib not installed")
```
```
astropy 6.1.dev627+gce7673a9db.d20240319
Numpy 2.1.0.dev0+git20240318.6924f8b
pyerfa 2.0.1.2.dev19+g4a637c2
Scipy not installed
Matplotlib not installed
```

**Comment by neutrinoceros** [comment]
The following patch resolves the crash:
```patch
diff --git a/astropy/coordinates/angles/core.py b/astropy/coordinates/angles/core.py
index 3b6d1516b6..ab6cacdad5 100644
--- a/astropy/coordinates/angles/core.py
+++ b/astropy/coordinates/angles/core.py
@@ -404,7 +404,7 @@ class Angle(SpecificTypeQuantity):
         # than Quantity objects for speed.
         a360 = u.degree.to(self.unit, 360.0)
         wrap_angle = wrap_angle.to_value(self.unit)
-        self_angle = self.view(np.ndarray)
+        self_angle = self.view(np.ndarray).astype("float64", copy=False)
         if NUMPY_LT_2_0:
             # Ensure ndim>=1 so that comparison is done using the angle dtype.
             self_angle = self_angle[np.newaxis]
```
I'm not 100% confident that it won't decrease perfs, which is my original goal, but let's open a PR and run benchmarks against it.

**Comment by neutrinoceros** [comment]
I'll open a PR to document this limitation and fix this issue tomorrow !
