### ISSUE TITLE
BUG: crash when offsetting SkyCoord object out of angular bounds

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#16219]
The following example is inspired from `astropy/coordinates/tests/test_frame/test_spherical_offsets_by_broadcast`, with the crucial difference that I'm intentionally asking for a transformation that requires a wrap.

```python
import numpy as np
import astropy.units as u
from astropy.coordinates import SkyCoord

sc = SkyCoord(ra=np.array([123]), dec=np.array([90]), unit=u.deg)
sc.spherical_offsets_by(-2 * u.deg, 0 * u.deg)
```

traceback:
```python-traceback
Traceback (most recent call last):
  File "/Users/clm/dev/astropy-project/coordinated/astropy/untitled.py", line 6, in <module>
    sc.spherical_offsets_by(-2 * u.deg, 0 * u.deg)
  File "/Users/clm/dev/astropy-project/coordinated/astropy/astropy/coordinates/sky_coordinate.py", line 1242, in spherical_offsets_by
    SkyOffsetFrame(d_lon, d_lat, origin=self.frame).transform_to(self)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/clm/dev/astropy-project/coordinated/astropy/astropy/coordinates/builtin_frames/skyoffset.py", line 174, in __init__
    self._set_skyoffset_data_lon_wrap_angle(self.data)
  File "/Users/clm/dev/astropy-project/coordinated/astropy/astropy/coordinates/builtin_frames/skyoffset.py", line 179, in _set_skyoffset_data_lon_wrap_angle
    data.lon.wrap_angle = 180.0 * u.deg
    ^^^^^^^^^^^^^^^^^^^
  File "/Users/clm/dev/astropy-project/coordinated/astropy/astropy/coordinates/angles/core.py", line 733, in wrap_angle
    self._wrap_at(self.wrap_angle)
  File "/Users/clm/dev/astropy-project/coordinated/astropy/astropy/coordinates/angles/core.py", line 422, in _wrap_at
    self_angle -= wraps * a360
ValueError: output array is read-only
```

**Comment by neutrinoceros** [comment]
The following minimal patch avoids the crash (but is not fixing the underlying issue)
```patch
diff --git a/astropy/coordinates/angles/core.py b/astropy/coordinates/angles/core.py
index 3b6d1516b6..e5ad974caa 100644
--- a/astropy/coordinates/angles/core.py
+++ b/astropy/coordinates/angles/core.py
@@ -405,6 +405,7 @@ class Angle(SpecificTypeQuantity):
         a360 = u.degree.to(self.unit, 360.0)
         wrap_angle = wrap_angle.to_value(self.unit)
         self_angle = self.view(np.ndarray)
+        self_angle.flags.writeable = True
         if NUMPY_LT_2_0:
             # Ensure ndim>=1 so that comparison is done using the angle dtype.
             self_angle = self_angle[np.newaxis]
```

More inquiry needed.

**Comment by mhvk** [comment]
On my office machine, which has an older astropy 5.2/numpy 1.24, I actually get a different error
```
ValueError: attribute origin should be scalar or have shape (), but it has shape (1,) and could not be broadcast.
```
While that clearly is a bug that has been solved, it suggests the origin is in a `broadcast` - this generally gives a read-only view because elements may be sharing memory. This is of course fine as long as one does not need to modify the data... The broadcasting happens here: https://github.com/astropy/astropy/blob/476358be1827dcb5b13771a097f47f0dee6eb907/astropy/coordinates/baseframe.py#L347-L349

Note that the example in this case is somewhat weird: it is broadcasting from `()` to `(1,)` and instead one could just do `data.shape = self._shape` with some carefully chosen condition. But there may be other cases where that goes wrong...  The simpler solution may be to make a copy after the broadcast (if `copy` is set). Though a bit silly since a copy make have been made already in `self._infer_data` - but, then, the broadcasting case is fairly rare.
