### ISSUE TITLE
fitsdiff raises a KeyError for lowercase HIERARCH keywords

### ISSUE THREAD

**Issue by hugobuddel** [astropy/astropy#16355]
### Description

Fitsdiff raises a Keyerror exception when comparing FITS files with a lowercase HIERARCH keyword because it tries to compare the uppercase keyword which does not exist.

### Expected behavior

No exception being raised.

### How to Reproduce

1. Install astropy. I tried 5.3.4 and 6.0.1 from conda-forge.

2. Then run

```python
from astropy.io import fits
from astropy.io.fits.scripts.fitsdiff import main

# Does not work, raises "KeyError: 'LOWER'":
myheader = fits.Header([("HIERARCH lower", 42)])
myhdu = fits.hdu.PrimaryHDU(header=myheader)
myhdus = fits.HDUList([myhdu])
fits.diff.FITSDiff(myhdus, myhdus)
```

3. An error occurs.
```
Traceback (most recent call last):
  File "fitsdiffhierarchlowerminimal.py", line 8, in <module>
    fits.diff.FITSDiff(myhdus, myhdus)
  File ".../python3.12/site-packages/astropy/io/fits/diff.py", line 331, in __init__
    super().__init__(a, b)
  File ".../python3.12/site-packages/astropy/io/fits/diff.py", line 87, in __init__
    self._diff()
  File ".../python3.12/site-packages/astropy/io/fits/diff.py", line 369, in _diff
    hdu_diff = HDUDiff.fromdiff(self, self.a[idx], self.b[idx])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./site-packages/astropy/io/fits/diff.py", line 120, in fromdiff
    return cls(a, b, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File ".../python3.12/site-packages/astropy/io/fits/diff.py", line 570, in __init__
    super().__init__(a, b)
  File ".../python3.12/site-packages/astropy/io/fits/diff.py", line 87, in __init__
    self._diff()
  File ".../python3.12/site-packages/astropy/io/fits/diff.py", line 588, in _diff
    self.diff_headers = HeaderDiff.fromdiff(
                        ^^^^^^^^^^^^^^^^^^^^
  File ".../python3.12/site-packages/astropy/io/fits/diff.py", line 120, in fromdiff
    return cls(a, b, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File ".../python3.12/site-packages/astropy/io/fits/diff.py", line 822, in __init__
    super().__init__(a, b)
  File ".../python3.12/site-packages/astropy/io/fits/diff.py", line 87, in __init__
    self._diff()
  File ".../python3.12/site-packages/astropy/io/fits/diff.py", line 890, in _diff
    counta = len(valuesa[keyword])
                 ~~~~~~~^^^^^^^^^
KeyError: 'LOWER'
```

### Versions

```
Linux-5.4.0-177-generic-x86_64-with-glibc2.31
Python 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:38:13) [GCC 12.3.0]
astropy 6.0.1
Numpy 1.26.4
pyerfa 2.0.1.4
Scipy not installed
Matplotlib not installed
```

**Comment by hugobuddel** [comment]
See https://github.com/astropy/astropy/blob/ef98d460a31470e417a51053d5f7c9d8df85724c/astropy/io/fits/diff.py#L846-L849

Maybe we should just remove these `upper()`s? I'd like to know differences in the capitalization as well.
