### ISSUE TITLE
ITRF to ITRS conversion fails

### ISSUE THREAD

**Issue by trufanov-nok** [astropy/astropy#16520]
### Description

I'm launching this example: https://stackoverflow.com/a/46493336/841424
on my machinge and getting:
```
$ python3
Python 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import astropy.coordinates as coord

>>> import astropy.units as u
>>> itrs = coord.ITRS(x=150*u.km, y=300*u.km, z=-210*u.km)
>>> icrs = itrs.transform_to(coord.ICRS)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/astropy/coordinates/baseframe.py", line 1272, in transform_to
    raise ConvertError(msg.format(self.__class__, new_frame.__class__))
astropy.coordinates.errors.ConvertError: Cannot transform from <class 'astropy.coordinates.builtin_frames.itrs.ITRS'> to <class 'abc.ABCMeta'>

```

### Expected behavior

code shouldn't crash

### How to Reproduce

1. Get package from sudo apt install python3-astropy'
2. Then run 'python3'
3. An error occurs.

```python
# Put your Python code snippet here.
import astropy.coordinates as coord
import astropy.units as u
itrs = coord.ITRS(x=150*u.km, y=300*u.km, z=-210*u.km)
icrs = itrs.transform_to(coord.ICRS)
```

### Versions

```
# Paste the result here
Linux-6.8.0-31-generic-x86_64-with-glibc2.39
Python 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0]
astropy 6.0.0
Numpy 1.26.4
pyerfa 2.0.1.1
Scipy 1.11.4
Matplotlib 3.6.3
```

also:
```
Operating System: Kubuntu 24.04
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.13
Kernel Version: 6.8.0-31-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3632QM CPU @ 2.20GHz
Memory: 15.5 ГиБ of RAM
Graphics Processor: Mesa Intel® HD Graphics 4000
Manufacturer: LENOVO
Product Name: Lenovo G780
System Version: Lenovo G780
```
```
$ dpkg -l '*astropy*'

ii  python3-astropy               6.0.0-1ubuntu2          amd64        Core functionality for performing astrophysics with Python
ii  python3-astropy-iers-data     0.2024.01.01.00.33.39-1 all          IERS Earth Rotation and Leap Second tables for Astropy
ii  python3-pytest-astropy        0.11.0-1                all          Pytest dependencies for Astropy and affiliated packages
ii  python3-pytest-astropy-header 0.2.2-1                 all          Include basic system dependencies in the header of pytest output
```

**Comment by trufanov-nok** [comment]
I guess it was working until I upgraded Kubuntu 23.10 -> 24.04

**Comment by mhvk** [comment]
Thankfully, I think this is simple: since some versions ago, we decided to be stricter about what to require for arguments in lower-level coordinate classes such as frames: it now has to be a frame instance, i.e., you need to do `itrs.transform_to(coord.ICRS())` (for ICRS, there is no ambiguity, but, say, `AltAz` makes no sense without extra information).

Note that we generally suggest to use `SkyCoord`, which allows passing in strings (or classes):
```
itrs = coord.SkyCoord(x=150*u.km, y=300*u.km, z=-210*u.km, frame='itrs')
icrs = itrs.transform_to('icrs')  # Or .transform_to(coord.ICRS)
```
This is because a `SkyCoord` can carry the extra frame parameters that are needed to initialize, e.g., an `AltAz`.

What is still a bit surprising is that you didn't get a deprecation warning in 23.10...
