### ISSUE TITLE
Cannot fit models that have input units: "astropy.units.core.UnitsError: ModelName: Units of input 'x', (dimensionless), could not be converted to required input units of..."

### ISSUE THREAD

**Issue by lpsinger** [astropy/astropy#16906]
### Description

Models that have input units cannot be used for fitting. See traceback below.

This is strange because the fitter is smart enough to temporarily strip off the units from the parameters.

The reproducer below is a bit contrived, but the real application here is fitting dimensionful dust extinction models (see https://github.com/karllark/dust_extinction/issues/237).

### Expected behavior

Fitting should succeed. The fitter should create a new temporary model that has the input units stripped out, run the fitting on that, and then restore the units and return the original model.

### Dimensionless: works fine

This code, in which the input data is dimensionless, works fine:

```python
from astropy.modeling import Fittable1DModel, Parameter
from astropy.modeling.fitting import LevMarLSQFitter
from astropy import units as u
import numpy as np


class DimensionlessFoobar1D(Fittable1DModel):

    n_inputs = 1
    n_outputs = 1
    input_units = {"x": u.dimensionless_unscaled}
    return_units = {"y": u.dimensionless_unscaled}
    _input_units_strict = True

    a = Parameter(default=1.0)

    def _parameter_units_for_data_units(self, inputs_unit, outputs_unit):
        # Declare that all of the parameters are dimensionless,
        # regardless of the input units.
        return dict.fromkeys(self.param_names)

    @staticmethod
    def evaluate(x, a):
        return np.tanh(x * a)

    def fit_deriv(self, x, a):
        return [x * (1 - np.square(self.evaluate(x, a)))]


xdata = np.linspace(-10, 10)
ydata = DimensionlessFoobar1D(a=3.14)(xdata) + 0.01 * np.random.randn(len(xdata))

model_init = DimensionlessFoobar1D()
fitter = LevMarLSQFitter()
fitter(model_init, xdata, ydata)
```

The output is:

```
<DimensionlessFoobar1D(a=3.17953878)>
```

### Dimensionful: fails

This version fails:

```python
from astropy.modeling import Fittable1DModel, Parameter
from astropy.modeling.fitting import LevMarLSQFitter
from astropy import units as u
import numpy as np


class DimensionfulFoobar1D(Fittable1DModel):

    n_inputs = 1
    n_outputs = 1
    input_units = {"x": u.yottaHenry}
    return_units = {"y": u.dimensionless_unscaled}
    _input_units_strict = True

    a = Parameter(default=1.0)

    def _parameter_units_for_data_units(self, inputs_unit, outputs_unit):
        # Declare that all of the parameters are dimensionless,
        # regardless of the input units.
        return dict.fromkeys(self.param_names)

    @staticmethod
    def evaluate(x, a):
        return np.tanh((x / u.yottaHenry).to_value(u.dimensionless_unscaled) * a)

    def fit_deriv(self, x, a):
        return [x / u.yottaHenry * (1 - np.square(self.evaluate(x, a)))]


xdata = np.linspace(-10, 10) * u.yottaHenry
ydata = DimensionfulFoobar1D(a=3.14)(xdata) + 0.01 * np.random.randn(len(xdata))

model_init = DimensionfulFoobar1D()
fitter = LevMarLSQFitter()
fitter(model_init, xdata, ydata)
```

The traceback is:

```
Traceback (most recent call last):
  File "/Users/lpsinger/src/m4opt/test.py", line 35, in <module>
    fitter(model_init, xdata, ydata)
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/astropy/modeling/fitting.py", line 286, in wrapper
    model_new = func(self, model, xdata, ydata, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/astropy/modeling/fitting.py", line 1366, in __call__
    init_values, fitparams, cov_x = self._run_fitter(
                                    ^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/astropy/modeling/fitting.py", line 1432, in _run_fitter
    fitparams, cov_x, dinfo, mess, ierr = optimize.leastsq(
                                          ^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/scipy/optimize/_minpack_py.py", line 426, in leastsq
    shape, dtype = _check_func('leastsq', 'func', func, x0, args, n)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/scipy/optimize/_minpack_py.py", line 23, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/astropy/modeling/fitting.py", line 1137, in objective_function
    value = np.ravel(model(*args[2:-1]) - meas)
                     ^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/astropy/modeling/core.py", line 417, in __call__
    new_call = make_function_with_signature(
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/astropy/modeling/core.py", line 394, in __call__
    return super(cls, self).__call__(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/astropy/modeling/core.py", line 417, in __call__
    new_call = make_function_with_signature(
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/astropy/modeling/core.py", line 394, in __call__
    return super(cls, self).__call__(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/astropy/modeling/core.py", line 1123, in __call__
    evaluate, inputs, broadcasted_shapes, kwargs = self._pre_evaluate(
                                                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/astropy/modeling/core.py", line 970, in _pre_evaluate
    inputs, broadcasted_shapes = self.prepare_inputs(*args, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/astropy/modeling/core.py", line 2093, in prepare_inputs
    inputs = self._validate_input_units(inputs, equivalencies, inputs_map)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/astropy/modeling/core.py", line 2189, in _validate_input_units
    raise UnitsError(
astropy.units.core.UnitsError: DimensionfulFoobar1D: Units of input 'x', (dimensionless), could not be converted to required input units of YH (inductance)
```

### Versions

```
macOS-14.6.1-arm64-arm-64bit
Python 3.11.9 (main, Apr  3 2024, 23:19:16) [Clang 15.0.0 (clang-1500.1.0.2.5)]
astropy 6.1.2
Numpy 2.1.0
pyerfa 2.0.1.4
Scipy 1.14.1
Matplotlib 3.9.2
```

**Comment by pllim** [comment]
Did you forget to put a different repo for `#237` link above? 🤔

**Comment by lpsinger** [comment]
> Did you forget to put a different repo for `#237` link above? 🤔

Whoops! Fixed.

**Comment by pllim** [comment]
cc @astropy/modeling @astrofrog @karllark
