### ISSUE TITLE
Cannot vstack Tables with SkyCoord columns that have undergone a change of representation

### ISSUE THREAD

**Issue by lpsinger** [astropy/astropy#17030]
### Description

When you try to concatenate to two `Table` instances that have `SkyCoord` columns, the concatenation fails if the SkyCoord instances in either table have ever undergone a change of representation.

### Expected behavior

The script below should finish without raising any exceptions.

### How to Reproduce

```python
from astropy.table import Table, vstack
from astropy.coordinates import CartesianRepresentation, SkyCoord, UnitSphericalRepresentation
from astropy import units as u

# This is fine
coords = SkyCoord([0] * u.deg, [90] * u.deg, representation_type=UnitSphericalRepresentation)
t1 = Table({"a": coords})
coords = SkyCoord([0] * u.deg, [0] * u.deg, representation_type=UnitSphericalRepresentation)
t2 = Table({"a": coords})
vstack((t1, t2))

# This raises an exception
coords = SkyCoord([0], [0], [1], unit=u.m, representation_type=CartesianRepresentation)
coords.representation_type = UnitSphericalRepresentation
t1 = Table({"a": coords})
coords = SkyCoord([0] * u.deg, [0] * u.deg, representation_type=UnitSphericalRepresentation)
t2 = Table({"a": coords})
vstack((t1, t2))
```

This script raises the following error:

```pytb
Traceback (most recent call last):
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/astropy/coordinates/baseframe.py", line 282, in new_like
    out[0] = coord[0]
    ~~~^^^
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/astropy/coordinates/sky_coordinate.py", line 388, in __setitem__
    self._sky_coord_frame[item] = value._sky_coord_frame
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/astropy/coordinates/baseframe.py", line 1787, in __setitem__
    raise TypeError(
TypeError: can only set from object of same class: CartesianRepresentation vs. UnitSphericalRepresentation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/lpsinger/src/m4opt/test.py", line 18, in <module>
    vstack((t1, t2))
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/astropy/table/operations.py", line 718, in vstack
    out = _vstack(tables, join_type, metadata_conflicts)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/astropy/table/operations.py", line 1494, in _vstack
    col = col_cls.info.new_like(cols, n_rows, metadata_conflicts, out_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/src/m4opt/.vscode/env/lib/python3.11/site-packages/astropy/coordinates/baseframe.py", line 284, in new_like
    raise ValueError("Input coords are inconsistent.") from err
ValueError: Input coords are inconsistent.
```

### Versions

```
platform
--------
platform.platform() = 'macOS-14.6.1-arm64-arm-64bit'
platform.version() = 'Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6031'
platform.python_version() = '3.11.10'

packages
--------
astropy              7.0.0.dev875+g6d66aa4884
numpy                2.1.1
scipy                1.14.1
matplotlib           3.9.2
pandas               --
pyerfa               2.0.1.4
```

**Comment by mhvk** [comment]
The underlying problem is that setting the representation after the fact does not in fact change the underlying data, i.e., one can go back to `CartesianRepresentation` and recover the data that was put in. Since this cannot be true for the merged `SkyCoord`, the code refuses to do it.

Obviously, a solution is just to take account of the current `representation_type` in merging; that seems OK to me, especially in the case that the `representation_type` of both `SkyCoord` are the same (and `differential_type` if given).

A larger question is whether perhaps the underlying data should be changed when one sets `representation_type`. This may not be unreasonable either, though it kind of breaks the current symmetry with `Time.format`, which only affects the way data is shown/processed, but not how it is stored. That said, for `Time` it is easier, since one always just stores `jd1, jd2`, while for coordinates it really is a requirement to be able to store coordinates in different formats/representations (e.g., to represent missing distances).
