### ISSUE TITLE
`filebytes` doesn't work on `CompImageHDU`

### ISSUE THREAD

**Issue by TallJimbo** [astropy/astropy#17050]
### Description

The `CompImageHDU.filebytes` method fails with an exception, in logic that looks like it's trying to write the HDU or at least perform the compression, even if the HDU has just been written.

### Expected behavior

I would have expected the number of bytes just written to have been cached in the HDU object, and for that to have been returned without any extra computation.  I'm not sure what I would expect to happen if calling `filebytes` before writing the HDU (though failling gracefully would probably be better than silently compressing the data and then discarding the compressed bytes after determining the predicted size of the HDU).

### How to Reproduce

Script to reproduce:

```python
import numpy as np
import astropy.io.fits

array = np.random.randn(50, 50)
hdu = astropy.io.fits.CompImageHDU(array)

hdu_list = astropy.io.fits.HDUList()
hdu_list.append(astropy.io.fits.PrimaryHDU())
hdu_list.append(hdu)
hdu_list.writeto("test.fits", overwrite=True)
print(hdu.filebytes())

```
output:
```
Traceback (most recent call last):
  File "/home/jbosch/LSST/src/astropy/fail.py", line 14, in <module>
    print(hdu.filebytes())
          ^^^^^^^^^^^^^^^
  File "/home/jbosch/LSST/src/astropy/astropy/io/fits/hdu/base.py", line 978, in filebytes
    return self._writeheader(f)[1] + self._writedata(f)[1]
                                     ^^^^^^^^^^^^^^^^^^
  File "/home/jbosch/LSST/src/astropy/astropy/io/fits/hdu/compressed/compressed.py", line 909, in _writedata
    return super()._writedata(fileobj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbosch/LSST/src/astropy/astropy/io/fits/hdu/base.py", line 659, in _writedata
    size += self._writedata_internal(fileobj)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbosch/LSST/src/astropy/astropy/io/fits/hdu/table.py", line 941, in _writedata_internal
    with _binary_table_byte_swap(self.data) as data:
  File "/home/jbosch/LSST/install/conda/envs/astropy-dev/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/jbosch/LSST/src/astropy/astropy/io/fits/hdu/table.py", line 1521, in _binary_table_byte_swap
    for idx, name in enumerate(orig_dtype.names):
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Versions

Tested with latest `main` branch on Python 3.12, as well as Astropy 6.1.2 for Python 3.12 from conda-forge.
```
platform
--------
platform.platform() = 'Linux-5.15.0-119-generic-x86_64-with-glibc2.35'
platform.version() = '#129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024'
platform.python_version() = '3.12.5'

packages
--------
astropy              7.0.0.dev892+g32a6b7582f
numpy                2.1.1
scipy                1.14.1
matplotlib           3.9.2
pandas               2.2.3
pyerfa               2.0.1.4
```

**Comment by saimn** [comment]
I agree that writing the file in memory just to get its size is not great, but it's been like this for 14 years (https://github.com/spacetelescope/PyFITS/commit/bfc170fcd6f8f85ffbca8dca73e16e8d84bf684a).
We could probably use the header information first, if it's available.
Also the example above works with the big refactor branch (#15474).

**Comment by pllim** [comment]
I don't even recognize `stsci_jtaylor2`. That predated my time. 😅

**Comment by saimn** [comment]
Fixed by #15474.
