### ISSUE TITLE
VOTable reader does not accept array-like PARAMs from Topcat

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#17098]
### Description

We have a VOTable that was created by Topcat (I guess from a FITS file) that looks (shortened to the problematic content):
```xml
<?xml version='1.0'?>
<VOTABLE version="1.4" xmlns="http://www.ivoa.net/xml/VOTable/v1.3">
<RESOURCE>
<TABLE name="Foo" nrows="1">
<PARAM arraysize="31x9" datatype="char" name="COMMENT" value="                               *** End of mandatory fields ***                                                              *** Column formats ***                                                                       *** Column names ***                                          ">
<DESCRIPTION>FITS COMMENT card values</DESCRIPTION>
</PARAM>
<FIELD datatype="long" name="foo"/>
<DATA><TABLEDATA><TR><TD>0</TD></TR></TABLEDATA></DATA>
</TABLE>
</RESOURCE>
</VOTABLE>
```
Trying to read this with Astropy gives:
```python
>>> from astropy.table import Table
>>> tbl = Table.read("test.vot")
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/astropy/io/votable/converters.py", line 328, in __init__
    self.arraysize = int(field.arraysize)
                     ^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '31x9'

During handling of the above exception, another exception occurred:
[…]
  File "/usr/lib/python3/dist-packages/astropy/io/votable/exceptions.py", line 124, in vo_raise
    raise exception_class(args, config, pos)
astropy.io.votable.exceptions.E01: test.vot:?:?: E01: Invalid size specifier '31x9' for a char field (in field 'COMMENT')
```
Obviously, multiple **COMMENT** fields in FITS were translated into a twodimensional character array here.

I interpret the [VOTable specs](https://www.ivoa.net/documents/VOTable/20190403/WD-VOTable-1.4-20190403.html#ToC26) as that the **arraysize** attribute has the same format as in the **FIELD** element and there is no restriction for a **PARAM** element to not contain multi-dimensional arrays, so I would say that it is a bug (or missing feature?) in Astropy.

Cc: @mbtaylor @kimakan

### Expected behavior

It would be great if Topcat and Astropy would be interoperable here.

### How to Reproduce

```python
>>> from astropy.table import Table
>>> tbl = Table.read("test.vot")
```

### Versions

This is in Astropy 6.1.4, but also in older versions (not sure which).

**Comment by mbtaylor** [comment]
Actually, I don't think the problem is to do with the handling specific to `PARAM`s, it looks to me like the VOTable reader can't handle multi-dimensional character arrays (in `FIELD`s or `PARAM`s), though multi-dimensional numeric arrays are OK.  I see effectively the same error in the following VOTable:
```xml
<?xml version='1.0'?>
<VOTABLE version="1.4" xmlns="http://www.ivoa.net/xml/VOTable/v1.3">
<RESOURCE>
<TABLE name="Foo" nrows="1">
<FIELD datatype="long" name="foo"/>
<FIELD datatype="int" arraysize="3x2" name="bar"/>
<FIELD datatype="char" arraysize="3x2" name="baz"/>
<DATA><TABLEDATA><TR>
  <TD>0</TD>
  <TD>1 2 3 4 5 6</TD>
  <TD>ABCDEF</TD>
</TR></TABLEDATA></DATA>
</TABLE>
</RESOURCE>
</VOTABLE>
```
If the `3x2` is replaced with `6` for column `baz` the table gets loaded correctly.

Reading *N*-dimensional character values (as *N-1*-dimensional string arrays) from VOTable is a bit of a pain, but at the least it would be good if it didn't scupper the entire table read operation.

**Comment by pllim** [comment]
@tomdonaldson , are you able to advise further or c/c those who could? Thanks!

**Comment by tomdonaldson** [comment]
At first look, I agree with @mbtaylor.  This seems to be a bug in the parser.  I'm surprised we haven't noticed before.  I can take a deeper look with an eye towards fixing it, but not before I get around to resolving #16856.

**Comment by pllim** [comment]
Please review https://github.com/astropy/astropy/pull/19974 . Thanks, all!

**Comment by hectorcanovas** [comment]
Dear all,

A proposal to fix this problem has been presented in [issue#19974](https://github.com/astropy/astropy/pull/19974). As stated in my 
comment in that thread:

I would like to add that this issue is highly relevant to both the ESA Gaia and Euclid Archives. Gaia DR4 and Euclid DR1 Foundation will include tables containing variable-length fields with this "offending" arraysize. Due to this Astropy-VOTable issue, data retrieval from tables containing such fields is currently not possible through the Astroquery.Gaia and Astroquery.Euclid packages, as the error reported at the beginning of this thread causes the workflow to fail.

For this reason, resolving this issue would be of significant benefit to both the Gaia and Euclid Astroquery user communities, and would help ensure seamless access to the upcoming data releases.

Kind regards,

Héctor Cánovas
(Support) Archive Scientist for the ESA Gaia & Euclid Archives
