### ISSUE TITLE
Error transforming from ICRS to AltAz after applying space motion

### ISSUE THREAD

**Issue by maxnoe** [astropy/astropy#17103]
### Description

Transformation to `AltAz` fails after applying space motion to ICRS coordinates of different epoch.

### Expected behavior

Transformation works.

### How to Reproduce

```python
from astropy.coordinates import EarthLocation, AltAz, SkyCoord
from astropy.time import Time
import astropy.units as u

icrs = SkyCoord(
    ra=5 * u.deg,
    dec=2 * u.deg,
    pm_ra_cosdec=2 * u.mas / u.year,
    pm_dec=1 * u.mas / u.year,
    frame="icrs",
    obstime=Time("J1991.25"),
)

obstime = Time.now()
location = EarthLocation.of_site("Roque de los Muchachos")
icrs_now = icrs.apply_space_motion(obstime)


# this fails
altaz = icrs_now.transform_to(AltAz(obstime=obstime, location=location))
```

The last step fails with the following error:

```python
/home/maxnoe/.local/conda/envs/cta-dev/lib/python3.11/site-packages/erfa/core.py:133: ErfaWarning: ERFA function "pmsafe" yielded 1 of "distance overridden (Note 6)"
  warn(f'ERFA function "{func_name}" yielded {wmsg}', ErfaWarning)
Traceback (most recent call last):
  File "/home/maxnoe/example.py", line 20, in <module>
    altaz = icrs_now.transform_to(AltAz(obstime=obstime, location=location))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxnoe/.local/conda/envs/cta-dev/lib/python3.11/site-packages/astropy/coordinates/sky_coordinate.py", line 722, in transform_to
    new_coord = trans(self.frame, generic_frame)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxnoe/.local/conda/envs/cta-dev/lib/python3.11/site-packages/astropy/coordinates/transformations/composite.py", line 113, in __call__
    curr_coord = t(curr_coord, curr_toframe)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxnoe/.local/conda/envs/cta-dev/lib/python3.11/site-packages/astropy/coordinates/transformations/function.py", line 189, in __call__
    fromcoord_cart = fromcoord.cartesian
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/maxnoe/.local/conda/envs/cta-dev/lib/python3.11/site-packages/astropy/coordinates/baseframe.py", line 1942, in cartesian
    return self.represent_as("cartesian", in_frame_units=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maxnoe/.local/conda/envs/cta-dev/lib/python3.11/site-packages/astropy/coordinates/baseframe.py", line 1156, in represent_as
    raise u.UnitConversionError(
astropy.units.core.UnitConversionError: need a distance to retrieve a cartesian representation when both radial velocity and proper motion are present, since otherwise the units cannot match.
```

I found that copying the ra/dec coordinates into a new skycoord discarding all additional information before transforming to `AltAz` works:
```python
icrs_now = SkyCoord(icrs_now.ra, icrs_now.dec, obstime=obstime)
altaz = icrs_now.transform_to(AltAz(obstime=obstime, location=location))
```

@adrn provided this more detailed workaround:

```python
icrs_now.data.differentials["s"] = icrs_now.data.differentials["s"].represent_as(
    coord.UnitSphericalCosLatDifferential
)
``` 

### Versions

```
Linux-6.10.10-arch1-1-x86_64-with-glibc2.40
Python 3.11.10 | packaged by conda-forge | (main, Sep 22 2024, 14:10:38) [GCC 13.3.0]
astropy 6.1.4
Numpy 2.0.2
pyerfa 2.0.1.4
Scipy 1.14.1
Matplotlib 3.9.2
```

**Comment by adrn** [comment]
Just connecting some dots: relevant #11761 #11932 #12329

**Comment by PieterVuylsteke** [comment]
With the suggested workaround, the proper motion is not applied anymore  ?
Issue is thus not solved if one does want to apply proper motion ?

**Comment by PieterVuylsteke** [comment]
This fix seems to work, adding a distance to icrs :

from astropy.coordinates import EarthLocation, AltAz, SkyCoord
from astropy.time import Time
import astropy.units as u

icrs = SkyCoord(
    ra=5 * u.deg,
    dec=2 * u.deg,
    pm_ra_cosdec=2 * u.mas / u.year,
    pm_dec=1 * u.mas / u.year,
    distance = 1 * u.pc,
    frame="icrs",
    obstime=Time("J1991.25"),
)

obstime = Time.now()
location = EarthLocation.of_site("Roque de los Muchachos")
icrs_now = icrs.apply_space_motion(obstime)


# this fails (not any more)
altaz = icrs_now.transform_to(AltAz(obstime=obstime, location=location))
