### ISSUE TITLE
Time support fails for matplotlib plotting functions plt.errorbar and plt.imshow

### ISSUE THREAD

**Issue by ddobie** [astropy/astropy#17152]
### Description

Astropy should support passing `Time` objects to matplotlib plotting functions via `astropy.visualization.time_support` - see [docs](https://docs.astropy.org/en/v6.0.1/visualization/matplotlib_integration.html#plotting-times). This works fine for calls to `plot()`, but breaks when trying to use `errorbar()` and `imshow()` (and possibly other plotting functions that I haven't tested).

Example error output:
```
Traceback (most recent call last):
  File "/import/ada2/ddob1600/.conda/envs/dstools-dev-py310/lib/python3.10/site-packages/matplotlib/axis.py", line 1769, in convert_units
    ret = self.converter.convert(x, self.units, self)
  File "/import/ada2/ddob1600/.conda/envs/dstools-dev-py310/lib/python3.10/site-packages/astropy/visualization/time.py", line 229, in convert
    scaled = getattr(value, self.scale)
AttributeError: 'numpy.ndarray' object has no attribute 'utc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/import/ada2/ddob1600/dstools/dstools/astropy_time_support_debugging.py", line 12, in <module>
    plt.errorbar(Time([58000, 59000, 62000], format='mjd'), [1.2, 3.3, 2.3])
  File "/import/ada2/ddob1600/.conda/envs/dstools-dev-py310/lib/python3.10/site-packages/matplotlib/pyplot.py", line 3027, in errorbar
    return gca().errorbar(
  File "/import/ada2/ddob1600/.conda/envs/dstools-dev-py310/lib/python3.10/site-packages/matplotlib/__init__.py", line 1465, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/import/ada2/ddob1600/.conda/envs/dstools-dev-py310/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 3591, in errorbar
    self.add_line(data_line)
  File "/import/ada2/ddob1600/.conda/envs/dstools-dev-py310/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 2309, in add_line
    self._update_line_limits(line)
  File "/import/ada2/ddob1600/.conda/envs/dstools-dev-py310/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 2332, in _update_line_limits
    path = line.get_path()
  File "/import/ada2/ddob1600/.conda/envs/dstools-dev-py310/lib/python3.10/site-packages/matplotlib/lines.py", line 1032, in get_path
    self.recache()
  File "/import/ada2/ddob1600/.conda/envs/dstools-dev-py310/lib/python3.10/site-packages/matplotlib/lines.py", line 668, in recache
    xconv = self.convert_xunits(self._xorig)
  File "/import/ada2/ddob1600/.conda/envs/dstools-dev-py310/lib/python3.10/site-packages/matplotlib/artist.py", line 279, in convert_xunits
    return ax.xaxis.convert_units(x)
  File "/import/ada2/ddob1600/.conda/envs/dstools-dev-py310/lib/python3.10/site-packages/matplotlib/axis.py", line 1771, in convert_units
    raise munits.ConversionError('Failed to convert value(s) to axis '
matplotlib.units.ConversionError: Failed to convert value(s) to axis units: array([<Time object: scale='utc' format='mjd' value=58000.0>,
       <Time object: scale='utc' format='mjd' value=59000.0>,
       <Time object: scale='utc' format='mjd' value=62000.0>],
      dtype=object)
```

### Expected behavior

Plotting `Time` objects with `errorbar()` and `imshow()` should work in the same way as plotting them with `plot()`.

### How to Reproduce

The failure for plt.errorbar can be reproduced by using the example in the [documentation](https://docs.astropy.org/en/v6.0.1/visualization/matplotlib_integration.html#plotting-times) and switching `plt.plot` to `plt.errorbar`, i.e.

```python
from matplotlib import pyplot as plt
from astropy.time import Time
from astropy.visualization import time_support

time_support()

plt.figure(figsize=(5,3))
plt.errorbar(Time([58000, 59000, 62000], format='mjd'), [1.2, 3.3, 2.3])
```

The failure for plt.imshow can be reproduced using something similar:
```python
data = [[1.2, 3.3, 2.3],[2.2, 4.3, 1.3],[2.4, 0.3, 3.3]]
times = Time([58000, 59000, 62000], format='mjd')

plt.figure(figsize=(5,3))
im = plt.imshow(
    data,
    extent=[times[0], times[-1], 0, 1],
    aspect="auto",
    origin="lower",
)
```

### Versions

Linux-5.14.0-427.33.1.el9_4.x86_64-x86_64-with-glibc2.34
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0]
astropy 6.0.0
Numpy 1.26.4
pyerfa 2.0.1.1
Scipy 1.12.0
Matplotlib 3.8.2

**Comment by astrofrog** [comment]
I think when we first developed this class it didn't work with errorbar anyway due to https://github.com/matplotlib/matplotlib/issues/14554 but that's been fixed now so we should look into this.

**Comment by mhvk** [comment]
@nirajlambe - indeed, one can work around the issue as you note (and I do that too...), but ideally we ensure that one doesn't have to! So, it would be good to know where in matplotlib this goes wrong.

FWIW, this also affects `quantity_support` (at least for the `extent` on `imshow`).

**Comment by nirajlambe** [comment]
@mhvk Yep! I am curious about such behavior of these functions too. I looked at the Matplotlib repo and user guide but couldn't find a reason. Probably a bit more searching would help.
