### ISSUE TITLE
u.one has an incorrect string representation in vounit

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#17228]
### Description

The VOUnit standard 1.1 states in Section 2.2:

> In each of the grammars here, the empty string is not a valid units string - in particular, it is not taken to indicate a dimensionless quantity. […] The VOUnits syntax, though it also deems the empty string to be invalid, recognises the string 1 as positively indicating a dimensionless quantity.

(this was changed relative to standard 1.0)

**u.one** however puts an empty string for the vounit format.

### Expected behavior

From the VOUnit standard 1.1, I would expect that the format is a `1`.

### How to Reproduce

```python
>>> import astropy.units as u
>>> u.one.to_string("vounit")
''
```

### Versions

Astropy 6.1.4

**Comment by neutrinoceros** [comment]
nevermind, conversion to `"vounit"` is explicitly requested in https://github.com/astropy/astropy/blob/a378c5e37698ad044e25bbebb4a38e275ec4ffc5/astropy/wcs/wcsapi/fitswcs.py#L290
Here's the other half of the fix:
```patch
diff --git a/astropy/wcs/wcsapi/fitswcs.py b/astropy/wcs/wcsapi/fitswcs.py
index 751eaf02ac..469718282d 100644
--- a/astropy/wcs/wcsapi/fitswcs.py
+++ b/astropy/wcs/wcsapi/fitswcs.py
@@ -294,6 +294,12 @@ class FITSWCSAPIMixin(BaseLowLevelWCS, HighLevelWCSMixin):
                 unit = ""
             elif isinstance(unit, u.Unit):
                 unit = unit.to_string(format="vounit")
+            elif unit == "":
+                # some CompositeUnit objects may compare == to the empty string,
+                # but we should not convert them to string in the else branch
+                # because the emtpy string signals an unknown unit, and would
+                # be converted to '1' by the VO standard
+                unit = ""
             else:
                 try:
                     unit = u.Unit(unit).to_string(format="vounit")
```

**Comment by eerovaher** [comment]
Should `astropy` implement separate `VOUnit` 1.0 and `VOUnit` 1.1 formatters?

**Comment by pllim** [comment]
Err... That is question for pyvo people. Lemme link this issue on their channel on Astropy Slack.

**Comment by olebole** [comment]
One additional obstacle here is that the `"1"` (probably) breaks FITS compatibility of the VOUnit, and our FITS unit parser doesn't recognize it as well:
```Python
>>> import astropy.units as u
>>> u.Unit("1", format="fits")
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/astropy/units/format/generic.py", line 585, in _do_parse
    return cls._parse_unit(s, detailed_exception=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/astropy/units/format/fits.py", line 98, in _parse_unit
    cls._validate_unit(unit, detailed_exception=detailed_exception)
  File "/usr/lib/python3/dist-packages/astropy/units/format/fits.py", line 89, in _validate_unit
    raise ValueError()
ValueError

[…]
```
I am unsure whether this was intended and wrote a comment for the IVOA, https://github.com/ivoa-std/VOUnits/issues/37#issuecomment-2431337164; a resolution should be here somehow coordinated.
