### ISSUE TITLE
Pickling a WCS with SIP coefficients results in a WCS with small numerical difference in the coefficients

### ISSUE THREAD

**Issue by braingram** [astropy/astropy#17334]
### Description

Pickling a WCS with SIP coefficients results in a WCS with small numerical difference in the coefficients.

There may be more than 1 issue here. Since:
- during pickling the wcs hdulist is [written](https://github.com/astropy/astropy/blob/19f5aa99321ddb42e5b01dc79159321762e0b2c5/astropy/wcs/wcs.py#L3235) to a `BytesIO` (losing precision as noted https://docs.astropy.org/en/stable/io/fits/appendix/faq.html#why-am-i-losing-precision-when-i-assign-floating-point-values-in-the-header)
- during WCS.__init__ if provided a header the header is [converted](https://github.com/astropy/astropy/blob/19f5aa99321ddb42e5b01dc79159321762e0b2c5/astropy/wcs/wcs.py#L473C17-L473C30) to a string and then [converted](https://github.com/astropy/astropy/blob/19f5aa99321ddb42e5b01dc79159321762e0b2c5/astropy/wcs/wcs.py#L518) back before reading the SIP keywords

### Expected behavior

No loss of precision.

### How to Reproduce

```python
import numpy as np
from astropy.wcs import WCS, Sip
import pickle

rng = np.random.default_rng(42)
wcs = WCS(naxis=2)
wcs.wcs.crval = [251.29, 57.58]
wcs.wcs.cdelt = [1, 1]
wcs.wcs.crpix = [507, 507]
wcs.wcs.pc = np.array([[7.7e-6, 3.3e-5], [3.7e-5, -6.8e-6]])
wcs._naxis = [1014, 1014]
wcs.wcs.ctype = ["RA---TAN-SIP", "DEC--TAN-SIP"]

# Generate random SIP coefficients
a = rng.uniform(low=-1e-5, high=1e-5, size=(5, 5))
b = rng.uniform(low=-1e-5, high=1e-5, size=(5, 5))

# Assign SIP coefficients
wcs.sip = Sip(a, b, None, None, wcs.wcs.crpix)
wcs.wcs.set()

pwcs = pickle.loads(pickle.dumps(wcs))
np.testing.assert_equal(wcs.sip.a, pwcs.sip.a)
```
Fails with:
```
Arrays are not equal

Mismatched elements: 23 / 25 (92%)
Max absolute difference: 9.41396049e-06
Max relative difference: 4.45193698e-14
 x: array([[ 5.479121e-06, -1.222431e-06,  7.171958e-06,  3.947361e-06,
        -8.116453e-06],
       [ 9.512447e-06,  5.222794e-06,  5.721286e-06, -7.437727e-06,...
 y: array([[ 5.479121e-06, -1.222431e-06,  7.171958e-06,  3.947361e-06,
        -8.116453e-06],
       [ 9.512447e-06,  5.222794e-06,  5.721286e-06, -7.437727e-06,...
```

### Versions

```
## -- End pasted text --
macOS-14.5-arm64-arm-64bit
Python 3.10.6 (main, Oct  3 2022, 15:35:33) [Clang 14.0.0 (clang-1400.0.29.102)]
astropy 6.1.2
Numpy 1.24.0
pyerfa 2.0.1.4
Scipy 1.13.1
Matplotlib not installed
```

**Comment by pllim** [comment]
If this comes from wcslib , then it needs upstream fix. @mcara , is it?

**Comment by mcara** [comment]
> If this comes from wcslib , then it needs upstream fix. @mcara , is it?

SIP is handled by `astropy` and not by WCSLIB. Probably this line will need to get a `relax` argument: https://github.com/astropy/astropy/blob/19f5aa99321ddb42e5b01dc79159321762e0b2c5/astropy/wcs/wcs.py#L3232

Also, relevant: https://github.com/astropy/astropy/issues/3375 Basically, using default format, we currently loose 2 digits.

**Comment by mcara** [comment]
So, I investigated this more. Basically:

1. My previous point was wrong.
2. The root cause is that floating point values are written from position 11 to 30 in a FITS card.

To test that `wcs.to_header()` does not reduce the accuracy of SIP coefficients, simply look at the coefficient value itself: `wcs.to_header()["B_4_0"]`. The problem is in the FITS standard and that `astropy.io.fits` complies with it (there is no option as far as I can see to increase precision).

**Comment by pllim** [comment]
So should we document this as known limitation and leave it at that?

**Comment by mcara** [comment]
> So should we document this as known limitation and leave it at that?

I don't know what is the best approach. Even if, in principle, we can use "free-form" for floating point numbers, I guess this is not done for compatibility reasons. For example, what if DS9 does not support this? Probably we do not want to create files that do not work well with other readers.

I think it would be great to get opinion of `astropy.io.fits` experts on this.

**Comment by braingram** [comment]
Is it necessary to convert the `HDUList` to bytes for pickling?

If not, the hdulist produced by `to_fits` doesn't lose the precision and is pickleable. (extending the above example)
```python
>> hdulist = wcs.to_fits(relax=True)
>> hdulist[0].header['A_0_0'] == wcs.sip.a[0, 0]
True
```

Also, is it necessary to convert the header to a string during `WCS.__init__`? There's also a loss of precision there:
```python
>> hdulist[0].header['A_0_0']
5.479120971119269e-06
>> wcs2 = WCS(hdulist[0].header, hdulist)
>> wcs2.sip.a[0, 0]
5.47912097111926e-06
>> wcs2.sip.a[0, 0] == hdulist[0].header['A_0_0']
False
```

**Comment by braingram** [comment]
> However, there is still the issue that accuracy will be lost once this WCS object is converted to a header (and written to a file) and so, wcs transformations will give different results when they are run on the original object compared to running them on an object re-created from a serialized header.

Good point. That is currently the case when a wcs with SIP coefficients is pickled as in the above example:
(extending the above example where `pwcs` is the pickled then unpickled wcs)
```python
>> wcs.pixel_to_world(0, 0) == pwcs.pixel_to_world(0, 0)
False
```

**Comment by marscode-agent** [comment]
The following script was generated by MarsCode Agent to reproduce the bug in this issue:

```python
# astropy__astropy/reproduce.py
import numpy as np
from astropy.wcs import WCS, Sip
import pickle

def test_wcs_sip_pickle():
    rng = np.random.default_rng(42)
    wcs = WCS(naxis=2)
    wcs.wcs.crval = [251.29, 57.58]
    wcs.wcs.cdelt = [1, 1]
    wcs.wcs.crpix = [507, 507]
    wcs.wcs.pc = np.array([[7.7e-6, 3.3e-5], [3.7e-5, -6.8e-6]])
    wcs._naxis = [1014, 1014]
    wcs.wcs.ctype = ["RA---TAN-SIP", "DEC--TAN-SIP"]

    # Generate random SIP coefficients
    a = rng.uniform(low=-1e-5, high=1e-5, size=(5, 5))
    b = rng.uniform(low=-1e-5, high=1e-5, size=(5, 5))

    # Assign SIP coefficients
    wcs.sip = Sip(a, b, None, None, wcs.wcs.crpix)
    wcs.wcs.set()
    pwcs = pickle.loads(pickle.dumps(wcs))

    try:
        np.testing.assert_equal(wcs.sip.a, pwcs.sip.a)
        print("Test passed successfully with no errors!")
    except AssertionError as e:
        raise AssertionError(e)

if __name__ == "__main__":
    test_wcs_sip_pickle()
```

How to run:
```shell
python3 astropy__astropy/reproduce.py
```

Expected Result:
```
Traceback (most recent call last):
  File "astropy__astropy/reproduce.py", line 25, in test_wcs_sip_pickle
    np.testing.assert_equal(wcs.sip.a, pwcs.sip.a)
  File "/usr/local/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 337, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/numpy/_utils/__init__.py", line 85, in wrapper
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 1025, in assert_array_equal
    assert_array_compare(operator.__eq__, actual, desired, err_msg=err_msg,
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 889, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

Mismatched elements: 23 / 25 (92%)
Max absolute difference among violations: 9.41396049e-06
Max relative difference among violations: 4.45193698e-14
 ACTUAL: array([[ 5.479121e-06, -1.222431e-06,  7.171958e-06,  3.947361e-06,
        -8.116453e-06],
       [ 9.512447e-06,  5.222794e-06,  5.721286e-06, -7.437727e-06,...
 DESIRED: array([[ 5.479121e-06, -1.222431e-06,  7.171958e-06,  3.947361e-06,
        -8.116453e-06],
       [ 9.512447e-06,  5.222794e-06,  5.721286e-06, -7.437727e-06,...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "astropy__astropy/reproduce.py", line 31, in <module>
    test_wcs_sip_pickle()
  File "astropy__astropy/reproduce.py", line 28, in test_wcs_sip_pickle
    raise AssertionError(e)
AssertionError: 
Arrays are not equal

Mismatched elements: 23 / 25 (92%)
Max absolute difference among violations: 9.41396049e-06
Max relative difference among violations: 4.45193698e-14
 ACTUAL: array([[ 5.479121e-06, -1.222431e-06,  7.171958e-06,  3.947361e-06,
        -8.116453e-06],
       [ 9.512447e-06,  5.222794e-06,  5.721286e-06, -7.437727e-06,...
 DESIRED: array([[ 5.479121e-06, -1.222431e-06,  7.171958e-06,  3.947361e-06,
        -8.116453e-06],
       [ 9.512447e-06,  5.222794e-06,  5.721286e-06, -7.437727e-06,...
```

Please review the usefulness of this reproduction script. We hope this script is helpful for maintainers to reproduce, localize and fix the issue, and has the potential to enhance the test suite.
> Note that the script are generated by large language models. Use the generated code with cautions.
