### ISSUE TITLE
vstack fails for tables of zero length that have SkyCoord columns

### ISSUE THREAD

**Issue by lpsinger** [astropy/astropy#17378]
### Description

vstack fails for tables of zero rows that have SkyCoord columns.

### Expected behavior

The code below should succeed, and `table2` should be a new table with zero rows.

### How to Reproduce

```pycon
>>> from astropy.coordinates import SkyCoord
>>> from astropy.table import Table, vstack
>>> table1 = Table({'foo': SkyCoord([], [], unit='deg')})
>>> table2 = vstack((table1, table1))
Traceback (most recent call last):
  File "/Users/lpsinger/Library/Python/3.11/lib/python/site-packages/astropy/coordinates/sky_coordinate.py", line 181, in new_like
    out[0] = skycoord[0]
             ~~~~~~~~^^^
  File "/Users/lpsinger/Library/Python/3.11/lib/python/site-packages/astropy/utils/shapes.py", line 234, in __getitem__
    return self._apply("__getitem__", item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/Library/Python/3.11/lib/python/site-packages/astropy/coordinates/sky_coordinate.py", line 475, in _apply
    new._sky_coord_frame = self._sky_coord_frame._apply(method, *args, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/Library/Python/3.11/lib/python/site-packages/astropy/coordinates/baseframe.py", line 1605, in _apply
    new._data = apply_method(self.data)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/Library/Python/3.11/lib/python/site-packages/astropy/coordinates/baseframe.py", line 1574, in apply_method
    return value._apply(method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/Library/Python/3.11/lib/python/site-packages/astropy/coordinates/representation/base.py", line 992, in _apply
    rep = super()._apply(method, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/Library/Python/3.11/lib/python/site-packages/astropy/coordinates/representation/base.py", line 369, in _apply
    setattr(new, "_" + component, apply_method(getattr(self, component)))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/Library/Python/3.11/lib/python/site-packages/astropy/units/quantity.py", line 1302, in __getitem__
    out = super().__getitem__(key)
          ^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: index 0 is out of bounds for axis 0 with size 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lpsinger/Library/Python/3.11/lib/python/site-packages/astropy/table/operations.py", line 684, in vstack
    out = _vstack(tables, join_type, col_name_map, metadata_conflicts)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/Library/Python/3.11/lib/python/site-packages/astropy/table/operations.py", line 1478, in _vstack
    col = col_cls.info.new_like(cols, n_rows, metadata_conflicts, out_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/Library/Python/3.11/lib/python/site-packages/astropy/coordinates/sky_coordinate.py", line 183, in new_like
    raise ValueError("Input skycoords are inconsistent.") from err
ValueError: Input skycoords are inconsistent.
```

### Versions

```
macOS-14.7.1-arm64-arm-64bit
Python 3.11.10 (main, Sep  7 2024, 05:47:53) [Clang 15.0.0 (clang-1500.1.0.2.5)]
astropy 6.1.5
Numpy 2.1.3
pyerfa 2.0.1.4
Scipy 1.14.1
Matplotlib 3.9.2
```

**Comment by mhvk** [comment]
Wow, you're really putting tables through the wringer! But again it exposed some unexpected bugs - see #17380 for a fix.
