### ISSUE TITLE
"from astropy.visualization.lupton_rgb import AsinhMapping" broken in v7.0.0 without deprecation

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#17528]
As reported in https://github.com/astropy/astropy/pull/15081#issuecomment-2504803896 by @timj 

* ~Best case scenario: Add back missing "from astropy.visualization.lupton_rgb import AsinhMapping" and deprecate it properly.~
* ~Worst case scenario: Revert #15081 (milestoned to v7.0.0)~
* The only scenario offered by Tom R: The only solution is to add back compatibility classes and we can then decide whether to deprecate them or keep them around.

<hr/>

For the record this PR broke Rubin in v7 and the breaking change was not in the change log so we didn't notice.

We do this a lot:

```python
from astropy.visualization.lupton_rgb import AsinhMapping
```

<hr/>

Then @astrofrog said it might be an oversight: *I agree that any public classes should have been formally deprecated (if needed) rather than just removed, I think this was an oversight. I need to look into this in more detail but weirdly it seems test_saturated still uses AsinhMapping. Is that the only thing that broke for you or did other imports break too?*

**Comment by astrofrog** [comment]
Reverting is not an option as that would then break API for 7.0.0 users. The only solution is to add back compatibility classes and we can then decide whether to deprecate them or keep them around.

**Comment by neutrinoceros** [comment]
If I were to guess, I'd say these class were removed without notice because they were assumed to be private (which is usually considered true for namespaces at least 2 levels beyond `astropy`), but they arguably were not, since they were also re-exposed in the parent namespace (`astropy.visualization`).
I'm happy to implement @astrofrog's suggested solution. I'm just touching base to make sure we don't step on each other's toes first :)

**Comment by astrofrog** [comment]
I don't have time right now so please feel free to try! See the original PR for some discussion on how to add this class back.

**Comment by sedonaprice** [comment]
As a note: only `make_lupton_rgb` was exposed in the parent namespace (`astropy.visualization`) in v6.1 (the only entry in `__all__` in `lupton_rgb.py`, and the only entry in the documentation reference API). There was a similarly named `AsinhStretch` class from `stretch.py` exposed in the parent namespace.

**Comment by neutrinoceros** [comment]
Good to know ! this means we absolutely want to have these classes reinstated in their original namespace. I'll get around to it tomorrow then. Thanks !

**Comment by sedonaprice** [comment]
👍 
(Based on the testing functions for `AsinhMapping` in v6.1, the backwards-compatibility class inheriting from the new `RGBImageMappingLupton` that I posted in the other issue should provide the needed functionality of initiating the class and having the method `AsinhMapping.make_rgb_image()`, so hopefully this should be straightforward for you.  Happy to help with writing the analogous class for `AsinhZScaleMapping` if that should be added as well.)

**Comment by marscode-agent** [comment]
The following script was generated by MarsCode Agent to reproduce the bug in this issue:

```python
# astropy__astropy/reproduce.py
import pytest

def test_asinh_mapping_import():
    try:
        from astropy.visualization.lupton_rgb import AsinhMapping
    except ImportError as e:
        raise AssertionError("ImportError raised: AsinhMapping is missing, it should either be reintroduced or properly deprecated.") from e

if __name__ == "__main__":
    try:
        test_asinh_mapping_import()
    except AssertionError as e:
        raise AssertionError(e)
    else:
        print("Test passed successfully with no errors!")
```

How to run:
```shell
python3 astropy__astropy/reproduce.py
```

Expected Result:
```
Traceback (most recent call last):
  File "astropy__astropy/reproduce.py", line 5, in test_asinh_mapping_import
    from astropy.visualization.lupton_rgb import AsinhMapping
ImportError: cannot import name 'AsinhMapping' from 'astropy.visualization.lupton_rgb' (astropy__astropy/astropy/visualization/lupton_rgb.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "astropy__astropy/reproduce.py", line 11, in <module>
    test_asinh_mapping_import()
  File "astropy__astropy/reproduce.py", line 7, in test_asinh_mapping_import
    raise AssertionError("ImportError raised: AsinhMapping is missing, it should either be reintroduced or properly deprecated.") from e
AssertionError: ImportError raised: AsinhMapping is missing, it should either be reintroduced or properly deprecated.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "astropy__astropy/reproduce.py", line 13, in <module>
    raise AssertionError(e)
AssertionError: ImportError raised: AsinhMapping is missing, it should either be reintroduced or properly deprecated.
```

Please review the usefulness of this reproduction script. We hope this script is helpful for maintainers to reproduce, localize and fix the issue, and has the potential to enhance the test suite.
> Note that the script are generated by large language models. Use the generated code with cautions.

**Comment by astrofrog** [comment]
> Note that the script are generated

I thought LLMs were better at grammar...

**Comment by neutrinoceros** [comment]
I opened #17531 to address this issue.
