### ISSUE TITLE
Can't display table data of specific fits with numpy >= 2

### ISSUE THREAD

**Issue by niu541412** [astropy/astropy#17583]
### Description

I've upgrade numpy to version>2. 
When I try to display table data of a fits file, it raise error 
```python
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    f3[1].data
  File "/usr/local/python3_venv/lib/python3.13/site-packages/astropy/io/fits/fitsrec.py", line 485, in __repr__
    return np.ndarray.__repr__(self)
           ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/python3_venv/lib/python3.13/site-packages/numpy/_core/arrayprint.py", line 1591, in _array_repr_implementation
    lst = array2string(arr, max_line_width, precision, suppress_small,
                       ', ', prefix, suffix=")")
  File "/usr/local/python3_venv/lib/python3.13/site-packages/numpy/_core/arrayprint.py", line 784, in array2string
    return _array2string(a, options, separator, prefix)
  File "/usr/local/python3_venv/lib/python3.13/site-packages/numpy/_core/arrayprint.py", line 557, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/python3_venv/lib/python3.13/site-packages/numpy/_core/arrayprint.py", line 590, in _array2string
    lst = _formatArray(a, format_function, options['linewidth'],
                       next_line_prefix, separator, options['edgeitems'],
                       summary_insert, options['legacy'])
  File "/usr/local/python3_venv/lib/python3.13/site-packages/numpy/_core/arrayprint.py", line 943, in _formatArray
    return recurser(index=(),
                    hanging_indent=next_line_prefix,
                    curr_width=line_width)
  File "/usr/local/python3_venv/lib/python3.13/site-packages/numpy/_core/arrayprint.py", line 881, in recurser
    word = recurser(index + (i,), next_hanging_indent, next_width)
  File "/usr/local/python3_venv/lib/python3.13/site-packages/numpy/_core/arrayprint.py", line 847, in recurser
    return format_function(a[index])
  File "/usr/local/python3_venv/lib/python3.13/site-packages/numpy/_core/arrayprint.py", line 1460, in __call__
    format_function(field)
    ~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/local/python3_venv/lib/python3.13/site-packages/numpy/_core/arrayprint.py", line 1298, in __call__
    return self.format.format(x)
           ~~~~~~~~~~~~~~~~~~^^^
ValueError: Unknown format code 'd' for object of type 'float'
```
I've confirmed this error comes from the incompatibility with numpy >=2.
Astropy <7 also raises the same error. 

### Expected behavior

Display table data without error

### How to Reproduce

```python
from astropy.io import fits
ff=fits.open("mkf.fits")
ff[1].data

```
example fits file : [NICER mkf file](https://heasarc.gsfc.nasa.gov/FTP/nicer/data/obs/2022_11//5142010115/auxil/ni5142010115.mkf.gz).

### Versions

platform
--------
platform.platform() = 'macOS-15.2-arm64-arm-64bit-Mach-O'
platform.version() = 'Darwin Kernel Version 24.2.0: Fri Dec  6 19:03:40 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T6041'
platform.python_version() = '3.13.1'

packages
--------
astropy              7.0.0
numpy                2.2.1
scipy                1.14.1
matplotlib           3.10.0
pandas               2.2.3
pyerfa               2.0.1.5

**Comment by neutrinoceros** [comment]
Hi, thank you for reporting this !
I couldn't find the problem yet, but a couple quick observations:
- I assume the example script was taken from a REPL session. Reproducing the issue with an actual script requires changing `ff[1].data` to `repr(ff[1].data)`
- I confirm that this broke as soon as numpy 2.0.0
- `FITS_rec` is a subclass of `np.recarray` but uses `np.ndarray.__repr__` under the hood for backward compatibility reasons (see #3419). I naively thought this might be the root cause (it's very likely not tested upstream), but that turned out to be a red herring; even commenting out `FIT_rec.__repr__` we end up on the same failing path.

I'll probably try to bisect the breaking change in numpy next, but I may not be able to do it just today.

**Comment by neutrinoceros** [comment]
Bisection done: the breaking change was https://github.com/numpy/numpy/pull/24191

**Comment by neutrinoceros** [comment]
Update: I'm currently leaning towards this being a bug or regression in numpy. Let me give some more insight for the next person to pick it up (which will likely be me again, later today or tomorrow).
Essentially the change in the aforementioned upstream PR changed the string interpolation method used in `IntegerFormat` from a basic `%`-style to a combination of fstring + `str.format`. Ideally they should be equivalent, but do not actually behave the same in the presence of a format specifier like `d` (equiv. to `i`, short for "integer"):
the old style, e.g. `'%3d' % 2.18984375`, silently rounds off the decimal part and gives `'  2'`, while `'{:-3d}'.format(2.18984375)` raises the value error that was reported (`ValueError: Unknown format code 'd' for object of type 'float'`).
What I don't know yet is whether it is expected that we even end up on this path with a floating point number; it seems odd that numpy even tries to format it as an integer, maybe it's taking a wrong turn at some point (yet to be found), and the change in string interpolation method merely made the real bug apparent. I also don't know yet if this can be reproduced without astropy, though I suspect it's possible.

**Comment by neutrinoceros** [comment]
numpy 1.26 indeed takes the same (suspicious) path, but survives it due to a more robust string interpolation method. Now let me try to understand how we end up there at all.

**Comment by neutrinoceros** [comment]
I'm getting closer: I think I've indentified `"ST_VIDEO_VDC"` as the problematic field in the attached data file
```python
>>> ff[1].data["ST_VIDEO_VDC"].dtype
dtype('float64')
>>> ff[1].data.dtype["ST_VIDEO_VDC"]
dtype('uint8')
```
(this is with numpy 1.26)
I think this clear inconsistency explains how numpy is able to "take a wrong turn" and select an incorrect formatting function for this column. Next step will be to understand where this inconsistency comes from, and in particular if a defect in astropy is causing it.

**Comment by neutrinoceros** [comment]
I'm still digging down the rabbit hole, searching for where exactly `dtype`s are being set. In the meantime, here's the relevant part of the header
```
TTYPE45 = 'ST_VIDEO_VDC'       / Star tracker video voltage                     
TFORM45 = '1B      '           / format of field                                
TUNIT45 = 'V       '           / physical unit of field   
TZERO45 =                  0.1 / zero baseline offset                           
TSCAL45 =           0.01953125 / data scaling                                   
TDISP45 = 'F6.3    '           / display format
```

I may be reading this wrong, but I *think* this might be where the inconsistency is originated:
- `TFORM` specifies that values are written as 1 unsigned byte each
- `TDISP` recommends a floating point-like representation
- quoting from the [fits 4.0 sepcification](https://fits.gsfc.nasa.gov/standard40/fits_standard40aa-le.pdf), regarding `TDISP` (section 7.3.2)
> If the table value has been scaled, the physical value, derived using Eq. 7, shall be displayed. 

Confusingly enough, the following sentence can be found almost immediately after the one I just quoted
> For purposes of display, each byte of bit (Type X) and byte (Type B) arrays is treated as an unsigned integer

but my interpretation is that we can ignore this part here; in the presence of `TSCAL`, it seems more natural to read the data as a floating point type, as we currently do. So, this *seems* to indicate that astropy does two separate operations to parse the datatype of the HDU, once at the field level, and once at the HDU level, but does so inconsistently:
- `hdu.data["ST_VIDEO_VDC"].dtype`, apparently inferred from `TSCAL` (and possibly `TDISP`), is correct
- `hdu.data.dtype["ST_VIDEO_VDC"]`, apparently inferred from `TFORM` alone, is incorrect

I need to find where these inferences happen, and study if we could unify them. If not, we could at least add some validation step and raise an exception or a warning when an inconsistency is detected.

**Comment by mhvk** [comment]
@neutrinoceros - you're surely correct that somehow the formatting of the compressed-using-integer data is used for the expanded floats (which are cached). Which means the problem is on our side, just hidden previously by python being arguably too generous with its string interpolation of floats.

But the code that deals with storing interpreted FITS data and ensuring it stays consistent with the underlying true data is not particularly transparent...

**Comment by neutrinoceros** [comment]
> `hdu.data.dtype["ST_VIDEO_VDC"]`, apparently inferred from `TFORM` alone, is incorrect

With another hour down the rabbit hole, I think I was able to confirm this conclusion.
- `hdu.data` is a `lazyproperty` and gets its `dtype` directly from `hdu.columns.dtype`
- `hdu.columns` is yet another `lazyproperty`
- in this instance, we get it from `_TableBaseHDU.columns`, which in turn calls `ColDefs._init_from_table`. Now here's the relevant part where `format` is inferred from a `TFORM` keyword.

https://github.com/astropy/astropy/blob/d6c92e0d76c393e38d9b5863a628dbaaf931ed5a/astropy/io/fits/column.py#L1602

So the problem is that, as I suspected, only `TFORM` is taken into account to infer a corresponding `dtype`, because each keyword is processed independently. I assume a possible fix would be to add another loop after the one I linked above, which would check and update specifically `format` keywords by taking *other* keywords into account (`TSCAL` in this instance). At this point, I would love to get some input from experts, because I don't know if my proposed solution is acceptable or how general it is, or should be. Since it's still the holiday season (I'm actually on vacation myself, just scratching this itch for an hour or two at a time), I'll avoid pinging anyone just yet, but I'll plan on doing so next week !

**Comment by neutrinoceros** [comment]
⬆️ Ping @saimn and @astrofrog ⬆️

**Comment by saimn** [comment]
The problem is that `array2string` computes the format function based on the unscaled array (`asarray(a)` where `a` is the FITS_rec object) but format the scaled array by using the FITS_rec object itself:

https://github.com/numpy/numpy/blob/2126e3c1aedc214032fc43bfda0a867f9b093c38/numpy/_core/arrayprint.py#L568-L593

Maybe that was hidden before if format functions were more tolerant.

So maybe we can make sure `array2string` is called with a scaled array, but I'm not sure what's the most efficient way is to get this scaled array... do you have any idea @mhvk ?

**Comment by mhvk** [comment]
I don't have a brilliant idea, sadly. For `Masked`, I ended up copying much of the numpy code - see around https://github.com/astropy/astropy/blob/b2d2e911eea5ccb6b4c9d48568c4cf4830b34afc/astropy/utils/masked/function_helpers.py#L1202

Here, that may be best too, as it allows avoiding calculating the whole scaled array for large ones, where only a piece is shown.

That said, perhaps the quickest fix is to do the calculation and pass that on for the `repr`...

Actually possibly another option is to set the integer format function by hand using `printoptions` to the one for float.

Yes another option may be to use `n.0f` as a format wherever we currently use `nd` - integers can be typeset using float (this will go wrong for very large integers, but those are not very common in fits files).

**Comment by neutrinoceros** [comment]
>  another option may be to use `n.0f` as a format wherever we currently use `nd` - integers can be typeset using float (this will go wrong for very large integers, but those are not very common in fits files).

This sounds like a bad idea to me, especially because it will go wrong *silently*. I don't have strong opinions about other options.

**Comment by saimn** [comment]
Thanks @mhvk, I tried a basic conversion to a scaled array but this fails for VLA columns and am not sure how to handle that. Maybe a custom `array2string` is needed then, I will have a look.
