### ISSUE TITLE
Some CASA-produced FITS units are not supported

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#2491]
CASA produces headers with `BUNIT   = 'JY/BEAM'`, which leads to this error when parsed:

```
In [13]: u.Unit('JY/BEAM', format='fits')
Traceback (most recent call last):
  File "<ipython-input-13-2fad9266289b>", line 1, in <module>
    u.Unit('JY/BEAM', format='fits')
  File "/Users/adam/repos/astropy/astropy/units/core.py", line 1717, in __call__
    raise ValueError(msg)
ValueError: 'JY/BEAM' did not parse as fits unit: At col 0, Unit u'JY' not supported by the FITS standard. Did you mean Jy, YJy, ZJy, yJy or zJy?


In [14]: u.Unit('JY/BEAM')
Traceback (most recent call last):
  File "<ipython-input-14-19aa1b146594>", line 1, in <module>
    u.Unit('JY/BEAM')
  File "/Users/adam/repos/astropy/astropy/units/core.py", line 1717, in __call__
    raise ValueError(msg)
ValueError: 'JY/BEAM' did not parse as unit: At col 0, JY is not a valid unit. Did you mean Jy, YJy, ZJy, yJy or zJy?
```

Is there a format that can deal with CASA's output?  Is CASA violating the FITS standard?

**Comment by keflavich** [comment]
The original issue has been fixed upstream.  Should we close this, or keep it open as the reference for a future "units exceptions" capability?

**Comment by mhvk** [comment]
My sense is that the issue of using units from fits headers is sufficiently bigger than this one that we might as well close this.  So, I'm doing that...
