### ISSUE TITLE
Astropy doesn't build if there are non-ASCII characters in path

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#2564]
Example, running in ``tëst directory"

```
astropy tom$ python setup.py build
running build
running build_py
copying astropy/wcs/include/wcslib/cel.h -> build/lib.macosx-10.8-x86_64-2.7/astropy/wcs/include/wcslib
copying astropy/wcs/include/wcslib/lin.h -> build/lib.macosx-10.8-x86_64-2.7/astropy/wcs/include/wcslib
copying astropy/wcs/include/wcslib/prj.h -> build/lib.macosx-10.8-x86_64-2.7/astropy/wcs/include/wcslib
copying astropy/wcs/include/wcslib/spc.h -> build/lib.macosx-10.8-x86_64-2.7/astropy/wcs/include/wcslib
copying astropy/wcs/include/wcslib/spx.h -> build/lib.macosx-10.8-x86_64-2.7/astropy/wcs/include/wcslib
copying astropy/wcs/include/wcslib/tab.h -> build/lib.macosx-10.8-x86_64-2.7/astropy/wcs/include/wcslib
copying astropy/wcs/include/wcslib/wcs.h -> build/lib.macosx-10.8-x86_64-2.7/astropy/wcs/include/wcslib
copying astropy/wcs/include/wcslib/wcserr.h -> build/lib.macosx-10.8-x86_64-2.7/astropy/wcs/include/wcslib
copying astropy/wcs/include/wcslib/wcsmath.h -> build/lib.macosx-10.8-x86_64-2.7/astropy/wcs/include/wcslib
copying astropy/wcs/include/wcslib/wcsprintf.h -> build/lib.macosx-10.8-x86_64-2.7/astropy/wcs/include/wcslib
running build_ext
building 'astropy._compiler' extension
/Users/tom/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c astropy/_compiler.c -o build/temp.macosx-10.8-x86_64-2.7/astropy/_compiler.o
clang: warning: argument unused during compilation: '-I /opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7'
/Users/tom/usr/bin/clang -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names -L/opt/local/lib/db46 build/temp.macosx-10.8-x86_64-2.7/astropy/_compiler.o -o build/lib.macosx-10.8-x86_64-2.7/astropy/_compiler.so
cythoning astropy/table/_np_utils.pyx to astropy/table/_np_utils.c

Error compiling Cython file:
------------------------------------------------------------
...

import numpy as np
import numpy.ma as ma
from numpy.lib.recfunctions import drop_fields

cimport cython
       ^
------------------------------------------------------------

astropy/table/_np_utils.pyx:12:8: Compiler crash in AnalyseDeclarationsTransform

File 'ModuleNode.py', line 101, in analyse_declarations: ModuleNode(_np_utils.pyx:1:0,
    doc = u'\nCython utilities for numpy structured arrays.\n\njoin_inner():  Do the inner-loop cartesian product for np_utils.join() processing.\n               (The "inner" is about the inner loop, not inner join).\n',
    full_module_name = 'astropy.table._np_utils')
File 'Nodes.py', line 383, in analyse_declarations: StatListNode(_np_utils.pyx:8:0)
File 'Nodes.py', line 383, in analyse_declarations: StatListNode(_np_utils.pyx:12:8)
File 'Nodes.py', line 6785, in analyse_declarations: CImportStatNode(_np_utils.pyx:12:8,
    module_name = u'cython')

Compiler crash traceback from this point on:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 6785, in analyse_declarations
    module_scope = env.find_module(self.module_name, self.pos)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Cython/Compiler/Symtab.py", line 1089, in find_module
    module_name, relative_to = self.parent_module, pos = pos)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 132, in find_module
    pxd_pathname = self.find_pxd_file(qualified_name, pos)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 184, in find_pxd_file
    pxd = self.search_include_directories(qualified_name, ".pxd", pos, sys_path=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 225, in search_include_directories
    tuple(self.include_directories), qualified_name, suffix, pos, include, sys_path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Cython/Utils.py", line 16, in wrapper
    res = cache[args] = f(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Cython/Utils.py", line 101, in search_include_directories
    path = os.path.join(dir, dotted_filename)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)
building 'astropy.table._np_utils' extension
/Users/tom/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/tom/Library/Python/2.7/lib/python/site-packages/numpy/core/include -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c astropy/table/_np_utils.c -o build/temp.macosx-10.8-x86_64-2.7/astropy/table/_np_utils.o
astropy/table/_np_utils.c:1:2: error: Do not use this file, it is the result of a failed Cython compilation.
#error Do not use this file, it is the result of a failed Cython compilation.
 ^
1 error generated.
error: command '/Users/tom/usr/bin/clang' failed with exit status 1

```

**Comment by embray** [comment]
Went to see if this is still an issue.  On Python 3.4+ it doesn't seem to be a problem.  On Python 2.7 however I just get:

```python
$ python2.7 setup.py build
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    import astropy
  File "/home/embray/src/astropy/tëst/astropy/__init__.py", line 115, in <module>
    from . import config as _config
ImportError: cannot import name config
```
So that's a problem....

**Comment by embray** [comment]
And the problem seems to be caused, in this case, by the same issue.  Which is that `os.path.join` blows up when mixing unicode and non-unicode paths.  So we have to be careful about that.  I will fix the issue on the Astropy end, and then we'll see if it still blows up Cython too...

**Comment by embray** [comment]
Yeah, still a problem in Cython too.  Though I need to double check whether it's because of something we're passing in to Cython, or just a problem internal to Cython.

**Comment by bsipocz** [comment]
I'm closing this issue, as building astropy in a ``tëst`` directory now works for me, at least when using python3.
