### ISSUE TITLE
Document creating non-trivial frames and the usage of realize_frame()

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#2741]
Hi,

I am trying to do this:

``` python
import astropy.units as u
from astropy.coordinates import SkyCoord

import sunpy.coordinates

sk = SkyCoord(10*u.deg, -10*u.deg, dateobs='2014-07-14 11:24:26', frame='helioprojective')

s4 = sk.transform_to('heliographicstonyhurst')
```

under the hood this transform goes from HelioProjective -> HelioCentric -> HelioGraphicStonyhurst

However it produces this error:

``` python
ERROR: TypeError: argument of type 'NoneType' is not iterable [sunpy.time.time]
Traceback (most recent call last):
  File "/home/stuart/untitled1.py", line 25, in <module>
    s4 = sk.transform_to('heliographicstonyhurst')
  File "/home/stuart/GitHub/astropy/astropy/coordinates/sky_coordinate.py", line 318, in transform_to
    new_coord = trans(self.frame, generic_frame)
  File "/home/stuart/GitHub/astropy/astropy/coordinates/transformations.py", line 920, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "/home/stuart/GitHub/astropy/astropy/coordinates/transformations.py", line 708, in __call__
    res = self.func(fromcoord, toframe)
  File "/home/stuart/GitHub/sunpy/sunpy/coordinates/frames.py", line 338, in hcc_to_hgs
    l0_deg = _carrington_offset(helioccoord.dateobs) * u.deg
  File "/home/stuart/GitHub/sunpy/sunpy/coordinates/frames.py", line 93, in _carrington_offset
    return s.heliographic_solar_center(dateobs)[0]
  File "/home/stuart/GitHub/sunpy/sunpy/sun/sun.py", line 231, in heliographic_solar_center
    jd = julian_day(t)
  File "/home/stuart/GitHub/sunpy/sunpy/time/julian.py", line 19, in julian_day
    time = parse_time(t)
  File "/home/stuart/GitHub/sunpy/sunpy/time/time.py", line 180, in parse_time
    if '.' in time_string:
TypeError: argument of type 'NoneType' is not iterable
```

which as far as I can ascertain is because it is using the default value of `dateobs=None` rather than `dateobs` specified in the `SkyCoord` instance.

If I do the double hop manually:

``` python
s2 = sk.transform_to('heliocentric')

print s2
<SkyCoord (HelioCentric): dateobs=2014-07-14 11:24:26, D0=149597870.7 km, x=25582742.589 km, y=-25977397.6299 km, z=4510927.75896 km>

s3 = s2.transform_to('heliographicstonyhurst')

print s3
<SkyCoord (HelioGraphicStonyhurst): dateobs=2014-07-14 11:24:26, hlon=-142.587146541 deg, hlat=-44.1359593613 deg, rad=36737588.0434 km>
```

it completes the transform ok.

**Comment by adrn** [comment]
👋 hey @Cadair -- could you check out the coordinates documentation and see if this is still relevant?

**Comment by adrn** [comment]
@Cadair Even better - if you still think there is an issue, please reopen this!
