### ISSUE TITLE
Writing ASCII table to temporary file in Python 3 fails

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#2913]
The following example fails in Python 3:

```
import tempfile
from astropy.table import Table

t = Table()
t['a'] = [1,2,3]

f = tempfile.NamedTemporaryFile(suffix='.html')
t.write(f, format='ascii.basic')
```

The error is:

```
Traceback (most recent call last):
  File "test_table.py", line 8, in <module>
    t.write(f, format='ascii.basic')
  File "/Users/tom/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev9662-py3.4-macosx-10.8-x86_64.egg/astropy/table/table.py", line 1731, in write
    io_registry.write(self, *args, **kwargs)
  File "/Users/tom/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev9662-py3.4-macosx-10.8-x86_64.egg/astropy/io/registry.py", line 378, in write
    writer(data, *args, **kwargs)
  File "/Users/tom/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev9662-py3.4-macosx-10.8-x86_64.egg/astropy/io/ascii/connect.py", line 42, in io_write
    return write(table, filename, format=format, **kwargs)
  File "/Users/tom/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev9662-py3.4-macosx-10.8-x86_64.egg/astropy/io/ascii/ui.py", line 285, in write
    output.write(outstr)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tempfile.py", line 399, in func_wrapper
    return func(*args, **kwargs)
TypeError: 'str' does not support the buffer interface
```

I'll look into it.

**Comment by fred3m** [comment]
I'm not sure whether this should be a new issue or if it fits into this one, but I noticed that writing a Table to a temporary fits file does not work. For example:

    import tempfile
    from astropy.table import Table
    from astropy.io import fits
    
    t = Table()
    t['a'] = [1,2,3]
    
    f = tempfile.NamedTemporaryFile(suffix='.fits', mode='rb+')
    t.write(f, format='fits')
    hdulist = fits.open(f, mode='update')
    len(hdulist)

which prints `0`, because hdulist is an empty HDUList.

**Comment by embray** [comment]
@fred3m Adding an `f.seek(0)` after `t.write(...)` will do it.  This is because the `NamedTemporaryFile` is a stream/file-like object.  When passed to `fits.open()` it will be read from wherever the current file pointer is set to, which is the end of the file (and hence appears empty).  @josePhoenix recently posted something about this: https://gist.github.com/josePhoenix/079da6455286c80aa5f2

**Comment by fred3m** [comment]
@embray Thanks for the tip.

**Comment by taldcroft** [comment]
Closing this issue. I think what we understand now is that it is just wrong to pass a binary file handle to a function that is writing text (unicode strings). I don't see a reason to support that since it is against modern practices IMO. The correct practice is easy, namely `with tempfile.NamedTemporaryFile(suffix='.html', mode='w') as fh: ...`.
