### ISSUE TITLE
FITS reader thinks some filenames are URLs

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#3122]
I have had trouble opening files with certain names.  In the below example, `blah.fits` and `APEXHET.2014-04-01T15:18:01.000.fits` are the same file (`blah` is a hardlink).  

```
In [1]: f = fits.open('blah.fits')

In [2]: f = fits.open('APEXHET.2014-04-01T15:18:01.000.fits')
Traceback (most recent call last):
  File "<ipython-input-2-ebc6bf24211f>", line 1, in <module>
    f = fits.open('APEXHET.2014-04-01T15:18:01.000.fits')
  File "/Users/adam/repos/astropy/astropy/io/fits/hdu/hdulist.py", line 119, in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, **kwargs)
  File "/Users/adam/repos/astropy/astropy/io/fits/hdu/hdulist.py", line 251, in fromfile
    save_backup=save_backup, **kwargs)
  File "/Users/adam/repos/astropy/astropy/io/fits/hdu/hdulist.py", line 768, in _readfrom
    ffo = _File(fileobj, mode=mode, memmap=memmap)
  File "/Users/adam/repos/astropy/astropy/io/fits/file.py", line 114, in __init__
    self.name, _ = urllib.request.urlretrieve(fileobj)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/urllib.py", line 205, in open
    return self.open_unknown(fullurl, data)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/urllib.py", line 217, in open_unknown
    raise IOError, ('url error', 'unknown url type', type)
IOError: [Errno url error] unknown url type: 'apexhet.2014-04-01t15'
```

The problem is that the filename apparently looks like a URL in line 113 of `file.py`:
`len(urllib.parse.urlparse(fileobj).scheme) > 1): # This is an URL` 

cc @embray

**Comment by embray** [comment]
Fixed by #3167--thanks @rashoodkhan
