### ISSUE TITLE
Time failure with input 'B1950'

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#3278]
Some recent change has resulted in a broken WCS initialization, I think.  See https://travis-ci.org/radio-astro-tools/pvextractor/jobs/46076758.

The problem within astropy is in `astropy/coordinates/earth_orientation.py` line 19:

```
>>> jd1950 = Time('B1950', scale='tai').jd
Traceback (most recent call last):
  File "<ipython-input-3-8d2a57ce36e9>", line 1, in <module>
    jd1950 = Time('B1950', scale='tai').jd
  File "astropy/time/core.py", line 194, in __init__
    self._init_from_vals(val, val2, format, scale, copy)
  File "astropy/time/core.py", line 236, in _init_from_vals
    self._time = self._get_time_fmt(val, val2, format, scale)
  File "astropy/time/core.py", line 274, in _get_time_fmt
    raise ValueError('Input values did not match {0}'.format(err_msg))
ValueError: Input values did not match any of the formats where the format keyword is optional [u'astropy_time', u'datetime', u'jyear_str', u'iso', u'isot', u'yday', u'byear_str']
```

It looks like perhaps the `byear_str` detection is broken?

```
>>> jd1950 = Time('B1950', scale='tai', format='byear_str').jd
Traceback (most recent call last):
  File "<ipython-input-5-d93058d619af>", line 1, in <module>
    jd1950 = Time('B1950', scale='tai', format='byear_str').jd
  File "astropy/time/core.py", line 194, in __init__
    self._init_from_vals(val, val2, format, scale, copy)
  File "astropy/time/core.py", line 236, in _init_from_vals
    self._time = self._get_time_fmt(val, val2, format, scale)
  File "astropy/time/core.py", line 274, in _get_time_fmt
    raise ValueError('Input values did not match {0}'.format(err_msg))
ValueError: Input values did not match the format class byear_str
```

**Comment by taldcroft** [comment]
I have seen this and could always resolve it with a `git clean -fxd` to entirely wipe all non-tracked files and recompile.  I don't know the precise culprit.

**Comment by keflavich** [comment]
@taldcroft -  thanks, I can confirm that `clean` and re-building fixes the problem.  It doesn't explain the issue I was seeing on travis.  I'll try rebuilding there.

**Comment by keflavich** [comment]
I can't reproduce the travis issues locally.  At the very least, the issue I've reported here is solved; there may be another hiding somewhere.
