### ISSUE TITLE
Problem building docs in v1.0rc1

### ISSUE THREAD

**Issue by migueldvb** [astropy/astropy#3387]
There is a problem in `coordinates/earth_orientation.py` in the lines

```python
jd1950 = Time('B1950', scale='tai').jd
jd2000 = Time('J2000', scale='utc').jd
```

 that breaks the building of the documentation. I have tried to rpovide the format string to Time but it does not solve the problem. This is the sphinx error log obtained fom the output of `python setup.py build_sphinx`:

```
 Sphinx version: 1.2.3
# Python version: 3.4.2
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/usr/lib/python3.4/site-packages/sphinx/application.py", line 147, in __init__
    self._init_builder(buildername)
  File "/usr/lib/python3.4/site-packages/sphinx/application.py", line 209, in _init_builder
    self.emit('builder-inited')
  File "/usr/lib/python3.4/site-packages/sphinx/application.py", line 408, in emit
    results.append(callback(self, *args))
  File "/home/mdevalbo/.local/lib/python3.4/site-packages/astropy_helpers-1.0.dev360-py3.4.egg/astropy_helpers/sphinx/ext/automodsumm.py", line 230, in process_automodsumm_generation
    lines = automodsumm_to_autosummary_lines(sfn, app)
  File "/home/mdevalbo/.local/lib/python3.4/site-packages/astropy_helpers-1.0.dev360-py3.4.egg/astropy_helpers/sphinx/ext/automodsumm.py", line 291, in automodsumm_to_autosummary_lines
    filestr = automodapi_replace(fr.read(), app, True, fn, False)
  File "/home/mdevalbo/.local/lib/python3.4/site-packages/astropy_helpers-1.0.dev360-py3.4.egg/astropy_helpers/sphinx/ext/automodapi.py", line 241, in automodapi_replace
    ispkg, hascls, hasfuncs = _mod_info(modnm, toskip, onlylocals=onlylocals)
  File "/home/mdevalbo/.local/lib/python3.4/site-packages/astropy_helpers-1.0.dev360-py3.4.egg/astropy_helpers/sphinx/ext/automodapi.py", line 325, in _mod_info
    for localnm, fqnm, obj in zip(*find_mod_objs(modname, onlylocals=onlylocals)):
  File "/home/mdevalbo/.local/lib/python3.4/site-packages/astropy_helpers-1.0.dev360-py3.4.egg/astropy_helpers/sphinx/ext/utils.py", line 38, in find_mod_objs
    __import__(modname)
  File "/home/mdevalbo/.local/lib/python3.4/site-packages/astropy-1.0rc1-py3.4-linux-x86_64.egg/astropy/coordinates/__init__.py", line 17, in <module>
    from .builtin_frames import *
  File "/home/mdevalbo/.local/lib/python3.4/site-packages/astropy-1.0rc1-py3.4-linux-x86_64.egg/astropy/coordinates/builtin_frames/__init__.py", line 28, in <module>
    from .fk5 import FK5
  File "/home/mdevalbo/.local/lib/python3.4/site-packages/astropy-1.0rc1-py3.4-linux-x86_64.egg/astropy/coordinates/builtin_frames/fk5.py", line 10, in <module>
    from .. import earth_orientation as earth
  File "/home/mdevalbo/.local/lib/python3.4/site-packages/astropy-1.0rc1-py3.4-linux-x86_64.egg/astropy/coordinates/earth_orientation.py", line 19, in <module>
    jd1950 = Time('B1950', format='byear_str', scale='tai').jd
  File "/home/mdevalbo/.local/lib/python3.4/site-packages/astropy-1.0rc1-py3.4-linux-x86_64.egg/astropy/time/core.py", line 198, in __init__
    self._init_from_vals(val, val2, format, scale, copy)
  File "/home/mdevalbo/.local/lib/python3.4/site-packages/astropy-1.0rc1-py3.4-linux-x86_64.egg/astropy/time/core.py", line 240, in _init_from_vals
    self._time = self._get_time_fmt(val, val2, format, scale)
  File "/home/mdevalbo/.local/lib/python3.4/site-packages/astropy-1.0rc1-py3.4-linux-x86_64.egg/astropy/time/core.py", line 280, in _get_time_fmt
    raise ValueError('Input values did not match {0}'.format(err_msg))
ValueError: Input values did not match the format class byear_str
```

**Comment by astrofrog** [comment]
I've seen that error before and it usually indicated that there were old files present. Can you try and do a ``git clean -fxd`` or try in a clean clone to see if you still have that error?

**Comment by migueldvb** [comment]
I'm still getting this error after running git clean -fxd on one of my
machines, but the doc building works well on another computer which
skips the rst tests.

**Comment by migueldvb** [comment]
The problem was fixed by cleaning the docs build directory in the git repo, sorry about the false alarm.

**Comment by embray** [comment]
Unless I'm trying to build/test a specific page in the docs, when I'm building the docs just in general I usually run `./setup.py build_sphinx --clean-docs`

**Comment by migueldvb** [comment]
Thanks, that is working well also.
