### ISSUE TITLE
astropy help not working on mac

### ISSUE THREAD

**Issue by dgavel** [astropy/astropy#3457]
the help package does not work for astropy modules. It bugs out with an error about encoding, but does not say what encoding is the problem

```
>>> help(astropy)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 446, in __call__
    return pydoc.help(*args, **kwds)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1787, in __call__
    self.help(request)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1834, in help
    else: doc(request, 'Help on %s:')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1571, in doc
    pager(render_doc(thing, title, forceload))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1566, in render_doc
    return title % desc + '\n\n' + text.document(object, name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 360, in document
    if inspect.ismodule(object): return self.docmodule(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1140, in docmodule
    contents.append(self.document(value, key, name))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 361, in document
    if inspect.isclass(object): return self.docclass(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1271, in docclass
    lambda t: t[1] == 'method')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1221, in spill
    name, mod, object))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 362, in document
    if inspect.isroutine(object): return self.docroutine(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 1332, in docroutine
    doc = getdoc(object) or ''
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 84, in getdoc
    result = _encode(result)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pydoc.py", line 205, in _encode
    return text.encode(encoding or _encoding, 'xmlcharrefreplace')
LookupError: unknown encoding: 
>>> 
```

**Comment by mdboom** [comment]
I can't reproduce.  This traceback goes deep within the Python standard library where it is encoding some text using `locale.getpreferredencoding()`.  Can you do:

```
>>> import locale
>>> locale.getpreferredencoding()
'UTF-8'
```

If you see `None` or an empty string returned, that indicates an environmental configuration error with the Python on your system, and I would expect `help()` of anything to fail.

**Comment by astrofrog** [comment]
If it turns out that there is an environment variable issue, it might be worth trying the fix here: http://docs.astropy.org/en/latest/known_issues.html#locale-errors

**Comment by embray** [comment]
A bit odd too--I did a search through the output of `help(astropy)` and there aren't even any non-ASCII characters (though there are a couple unicode strings that need to be displayed, but again only containing characters in ASCII).
Anyways this really sounds like a local configuration issue.  I'll leave it open if there's anything that needs to be added to known_issues.

**Comment by dgavel** [comment]
Thanks guys for the quick response. That fixed it.
It was indeed a locale issue; setting LANG, LC_ALL, and LC_CTYPE as suggested fixed the help problem. Rather obscure problem though, so I suggest adding a note in the "known issues#locale-errors" section about its affect on help so a search for "help" and "encoding" will find it. It only affects the help on astropy packages. It happened on 2 macs, a MacBook Air running Yosemite and a MacMini running Maverics, both with new MacPorts installs of python2.7 and astropy. Thanks again.

**Comment by astrofrog** [comment]
@dgavel - great to hear it worked, thanks for confirming!

**Comment by embray** [comment]
I don't know--I think it's useful to try to provide a decent amount of troubleshooting.  The encoding issue would have eventually cropped up somewhere else involving strings--maybe reading a FITS file or a VOTable or something entirely else.  The fact that it occurred in `help()` is odd, but not in any way particular to Astropy. So I think we have to draw the line somewhere when it comes to documenting known issues with Python *in general*.

**Comment by embray** [comment]
Surprisingly, this issue isn't showing up yet on a Google search though.  At least not when I search 'astropy LookupError: uknown encoding'.  Though I do get [this issue](https://github.com/astropy/astropy/issues/2481) in that search.
