### ISSUE TITLE
astropy.io.ascii.write: comment=False parameter yields an error with format=''commented_header'

### ISSUE THREAD

**Issue by mrkite92** [astropy/astropy#3562]
Hi Astropy gurus,

Using the latest 1.0 release, I experience the following:
- I read data from an ascii file, format='commented_header'
- I add some_columns, with indexes all null. Then, the header is updated.
- I write the resulting table in another ascii file, format='commented_header'
- the original header is written in this resulting table as comment just after the new commented header. This is quite unfortunate, as TOPCAT is unable to properly manage it, then the header is lost and all columns appear as "coln'
- using the option comment=False to write the table yields this error:

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 2222, in <module>
    globals = debugger.run(setup['file'], None, None)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1648, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/marquett/PycharmProjects/DGDF2014/match_blue.py", line 254, in <module>
    ascii.write(blue_data, blue_file[:-3] + 'calib.dat', format='commented_header', comment=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/io/ascii/ui.py", line 443, in write
    writer.write(table, output)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/io/ascii/fastbasic.py", line 234, in write
    self._write(table, output, {}, header_output='comment')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/io/ascii/fastbasic.py", line 138, in _write
    writer.write(output, header_output, output_types)
  File "astropy/io/ascii/cparser.pyx", line 952, in astropy.io.ascii.cparser.FastWriter.write (astropy/io/ascii/cparser.c:17215)
  File "astropy/io/ascii/cparser.pyx", line 927, in astropy.io.ascii.cparser.FastWriter._write_header (astropy/io/ascii/cparser.c:16557)
TypeError: expected a character buffer object

Then, it seems there is no way no to write this comment, as this original header is fully useless.

Any hint welcome,
Cheers,
JB

**Comment by taldcroft** [comment]
This looks like a bug.

The workaround is to remove the comments from your table before writing using:
```
del t.meta['comments']
```
or with a bigger hammer:
```
t.meta.clear()
```
The latter will always work even if there are no comments originally.

**Comment by embray** [comment]
Or, wouldn't a simpler option be to not use the fast writer?  (I mean obviously in principle it should just work, but this probably isn't an issue with the "slow" writer).

**Comment by taldcroft** [comment]
I had tried the slow reader and it shares the same feature, though by a slightly different pathway.

**Comment by mrkite92** [comment]
Hi Tom & Eric,

Workaround works fine, thanks!
