### ISSUE TITLE
visualization.mpl_normalize.ImageNormalize error

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#3569]
I tried using `visualization.mpl_normalize.ImageNormalize` and received the following error:

```
Traceback (most recent call last):
  File "/Users/adam/work/apex_cmz_h2co/plot_codes/dust_figures.py", line 57, in <module>
    cb = pl.colorbar(mappable=ims, cax=cax)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2154, in colorbar
    ret = gcf().colorbar(mappable, cax = cax, ax=ax, **kw)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/figure.py", line 1500, in colorbar
    cb = cbar.colorbar_factory(cax, mappable, **kw)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/colorbar.py", line 1316, in colorbar_factory
    cb = Colorbar(cax, mappable, **kwargs)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/colorbar.py", line 892, in __init__
    ColorbarBase.__init__(self, ax, **kw)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/colorbar.py", line 321, in __init__
    self.draw_all()
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/colorbar.py", line 342, in draw_all
    self._process_values()
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/colorbar.py", line 662, in _process_values
    b = self.norm.inverse(self._uniform_y(self.cmap.N + 1))
  File "/Users/adam/repos/astropy/astropy/visualization/mpl_normalize.py", line 88, in inverse
    values_norm = self.inverse_stretch(values, clip=False)
TypeError: 'property' object is not callable
```

The code that results in this is:

```
    cm = matplotlib.cm.RdYlBu_r
    cm.set_bad('#888888')

    fig1 = pl.figure(1, figsize=figsize)
    fig1.clf()
    ax = wcsaxes.WCSAxesSubplot(fig1, 1,1,1, wcs=wcs)
    fig1.add_axes(ax)
    norm = mpl_normalize.ImageNormalize(vmin=vmin, vmax=vmax, stretch=stretch)
    ims = ax.imshow(im, cmap=cm, vmin=vmin, vmax=vmax, norm=norm)
```

where `stretch` is `astropy.visualization.stretch.AsinhStretch` and all the other values are numbers, images, wcs's, etc.

cc @astrofrog

**Comment by astrofrog** [comment]
@keflavich - in your example, what is ``stretch`` set to?

**Comment by keflavich** [comment]
Visualization.asinhstretch

**Comment by astrofrog** [comment]
@keflavich - ah, you need to pass an *instance* of the stretch class, not the class itself. Can you check that fixes it? If so we should have an error if a class is passed.

**Comment by keflavich** [comment]
Using an instance, I ran into a problem when creating the colorbar:
```
Traceback (most recent call last):
  File "/Users/adam/work/apex_cmz_h2co/plot_codes/dust_figures.py", line 65, in <module>
    cb = pl.colorbar(mappable=ims, cax=cax)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2154, in colorbar
    ret = gcf().colorbar(mappable, cax = cax, ax=ax, **kw)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/figure.py", line 1500, in colorbar
    cb = cbar.colorbar_factory(cax, mappable, **kw)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/colorbar.py", line 1316, in colorbar_factory
    cb = Colorbar(cax, mappable, **kwargs)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/colorbar.py", line 892, in __init__
    ColorbarBase.__init__(self, ax, **kw)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/colorbar.py", line 321, in __init__
    self.draw_all()
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/colorbar.py", line 342, in draw_all
    self._process_values()
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/colorbar.py", line 662, in _process_values
    b = self.norm.inverse(self._uniform_y(self.cmap.N + 1))
  File "/Users/adam/repos/astropy/astropy/visualization/mpl_normalize.py", line 88, in inverse
    values_norm = self.inverse_stretch(values, clip=False)
TypeError: inverse() got an unexpected keyword argument 'clip'
```

I did indeed misread the docs, so you're right that an appropriate error would be helpful.

**Comment by larrybradley** [comment]
@keflavich `ImageNormalize` will now raise an error if a class is input instead of an instance (see https://github.com/astropy/astropy/pull/5669).

I can't reproduce your second issue when creating a colorbar (`TypeError: inverse() got an unexpected keyword argument 'clip'`).  All of the defined stretch classes have a `clip` keyword in their `inverse` methods.  Is this still an issue or can I close this?  Thanks.

**Comment by keflavich** [comment]
This is thoroughly ancient.  I think it's time to close, and we'll see if anyone re-encounters it in the future.
