### ISSUE TITLE
Can't install astropy 1.0.1 in Python 2.7 

### ISSUE THREAD

**Issue by hebl** [astropy/astropy#3576]
OS: Mac OS, 
Python: 2.7.9
Python3: 3.4.3

I use `pip3 install astropy`. it is correct. but when `pip2 install astropy`, has the error below:

```
Collecting astropy
  Using cached astropy-1.0.1.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/jt/dnbgpcyn2rj152hsp6yh1ssw0000gn/T/pip-build-wc6vWN/astropy/setup.py", line 8, in <module>
        import ah_bootstrap
      File "ah_bootstrap.py", line 921, in <module>
        BOOTSTRAPPER = _Bootstrapper.main()
      File "ah_bootstrap.py", line 217, in main
        bootstrapper.run()
      File "ah_bootstrap.py", line 290, in run
        dist = method()
      File "ah_bootstrap.py", line 371, in get_local_directory_dist
        upgrade = self._do_upgrade(dist)
      File "ah_bootstrap.py", line 524, in _do_upgrade
        next_version = _next_version(dist.parsed_version)
      File "ah_bootstrap.py", line 810, in _next_version
        for part in version:
    TypeError: 'Version' object is not iterable
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/private/var/folders/jt/dnbgpcyn2rj152hsp6yh1ssw0000gn/T/pip-build-wc6vWN/astropy/setup.py", line 8, in <module>

        import ah_bootstrap

      File "ah_bootstrap.py", line 921, in <module>

        BOOTSTRAPPER = _Bootstrapper.main()

      File "ah_bootstrap.py", line 217, in main

        bootstrapper.run()

      File "ah_bootstrap.py", line 290, in run

        dist = method()

      File "ah_bootstrap.py", line 371, in get_local_directory_dist

        upgrade = self._do_upgrade(dist)

      File "ah_bootstrap.py", line 524, in _do_upgrade

        next_version = _next_version(dist.parsed_version)

      File "ah_bootstrap.py", line 810, in _next_version

        for part in version:

    TypeError: 'Version' object is not iterable

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jt/dnbgpcyn2rj152hsp6yh1ssw0000gn/T/pip-build-wc6vWN/astropy
```

**Comment by astrofrog** [comment]
@hebl - just to check, do you also see the error if you do ``pip2 install astropy==1.0``?

**Comment by embray** [comment]
They wouldn't.

**Comment by embray** [comment]
I see.  This can happen if and only if the user has setuptools v10.x.  Upgrading setuptools should fix it.  I'll add a workaround for now, but eventually it will be good to institute a minimum version of setuptools (10.x isn't that old though--it was just the first version to introduce some new APIs...)

**Comment by eastofaether** [comment]
@hebl I'm also having this issue. Did you ever find a fix?

**Comment by bsipocz** [comment]
@eastofaether - what version of setuptools and pip do you have?

@embray - Can we close this? If not what are the todos, maybe I'll have a chance to do them this week.

**Comment by bsipocz** [comment]
Closing as this there were quite a few helpers release since, and this hasn't been reproduced given we never got the follow-up informations. 

Please feel free to reopen if you still run into it, and please report the setuptools and pip versions, too.
