### ISSUE TITLE
Latex angstrom unit fails in matplotlib by default

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#3617]
The Latex formatting for 'angstrom' fails in matplotlib:

```
import matplotlib.pyplot as plt
from astropy import units as u
ang = u.Unit('Angstrom')
plt.xlabel(ang.to_string(format='Latex'))
plt.show()


Traceback (most recent call last):
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/figure.py", line 1079, in draw
    func(*args)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2092, in draw
    a.draw(renderer)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/axis.py", line 1117, in draw
    self.label.draw(renderer)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/text.py", line 538, in draw
    bbox, info, descent = self._get_layout(renderer)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/text.py", line 320, in _get_layout
    ismath=ismath)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 158, in get_text_width_height_descent
    self.mathtext_parser.parse(s, self.dpi, prop)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/mathtext.py", line 3005, in parse
    box = self._parser.parse(s, font_output, fontsize, dpi)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/mathtext.py", line 2339, in parse
    six.text_type(err)]))
ValueError:
\mathrm{\overset{\circ}{A}}
        ^
Unknown symbol: \overset (at char 8), (line:1, col:9)
```

Can we just replace it with `\AA`, which (at least on my system) works?  It seems to be supported by matplotlib: http://pythondammit.blogspot.de/2012/08/the-angstrom-symbol.html .  Or is there another acceptable alternative? (e.g., http://pythondammit.blogspot.de/2012/08/the-angstrom-symbol.html)

this came up in https://github.com/pyspeckit/pyspeckit/issues/17

**Comment by embray** [comment]
@keflavich See #2286 for the reason for the current formatting.

I'm surprised it doesn't work in matplotlib though.  What latex renderer are you using?

**Comment by keflavich** [comment]
@embray the default installed by anaconda on travis

**Comment by mdboom** [comment]
`\overset` has never been implemented in matplotlib -- it's an extension to TeX, and matplotlib more-or-less just implements the core.  But mathjax doesn't support `\AA`.  I can see how much work adding overset to matplotlib might be...

**Comment by mdboom** [comment]
The best way to get cross-renderer support across LaTeX, MathJax and matplotlib (assuming MathJax is hard to fix and a matplotlib developer is sitting right here), is to add `\mathring` support to matplotlib and use that.  See matplotlib/matplotlib#4274.
