### ISSUE TITLE
Babel hidden dependency

### ISSUE THREAD

**Issue by drudd** [astropy/astropy#3698]
Installing via pip fails if Babel was not installed (possibly only when Sphinx was installed, triggering AstropyBuildSphinx) Sphinx was installed as a wheel, v. 1.3.1. https://pypi.python.org/packages/2.7/S/Sphinx/Sphinx-1.3.1-py2.py3-none-any.whl#md5=9abda702fcb41e475b9771fbb4bfe371

```
  Downloading from URL https://pypi.python.org/packages/source/a/astropy/astropy-1.0.2.tar.gz#md5=94d56d831dfbd7f511e22ea93813ae72 (from https://pypi.python.org/simple/astropy/)
  Running setup.py (path:/tmp/pip_build_drudd/astropy/setup.py) egg_info for package astropy
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_drudd/astropy/setup.py", line 45, in <module>
        cmdclassd = register_commands(NAME, VERSION, RELEASE)
      File "/tmp/pip_build_drudd/astropy/astropy_helpers/astropy_helpers/setup_helpers.py", line 281, in register_commands
        from .commands.build_sphinx import AstropyBuildSphinx
      File "/tmp/pip_build_drudd/astropy/astropy_helpers/astropy_helpers/commands/build_sphinx.py", line 14, in <module>
        from sphinx.setup_command import BuildDoc as SphinxBuildDoc
      File "/software/python-2.7-2015q2-el6-x86_64/lib/python2.7/site-packages/sphinx/setup_command.py", line 23, in <module>
        from sphinx.application import Sphinx
      File "/software/python-2.7-2015q2-el6-x86_64/lib/python2.7/site-packages/sphinx/application.py", line 37, in <module>
        from sphinx.builders import BUILTIN_BUILDERS
      File "/software/python-2.7-2015q2-el6-x86_64/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 23, in <module>
        from sphinx.util import i18n, path_stabilize
      File "/software/python-2.7-2015q2-el6-x86_64/lib/python2.7/site-packages/sphinx/util/i18n.py", line 15, in <module>
        from babel.messages.pofile import read_po
    ImportError: No module named babel.messages.pofile
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_drudd/astropy/setup.py", line 45, in <module>

    cmdclassd = register_commands(NAME, VERSION, RELEASE)

  File "/tmp/pip_build_drudd/astropy/astropy_helpers/astropy_helpers/setup_helpers.py", line 281, in register_commands

    from .commands.build_sphinx import AstropyBuildSphinx

  File "/tmp/pip_build_drudd/astropy/astropy_helpers/astropy_helpers/commands/build_sphinx.py", line 14, in <module>

    from sphinx.setup_command import BuildDoc as SphinxBuildDoc

  File "/software/python-2.7-2015q2-el6-x86_64/lib/python2.7/site-packages/sphinx/setup_command.py", line 23, in <module>

    from sphinx.application import Sphinx

  File "/software/python-2.7-2015q2-el6-x86_64/lib/python2.7/site-packages/sphinx/application.py", line 37, in <module>

    from sphinx.builders import BUILTIN_BUILDERS

  File "/software/python-2.7-2015q2-el6-x86_64/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 23, in <module>

    from sphinx.util import i18n, path_stabilize

  File "/software/python-2.7-2015q2-el6-x86_64/lib/python2.7/site-packages/sphinx/util/i18n.py", line 15, in <module>

    from babel.messages.pofile import read_po

ImportError: No module named babel.messages.pofile
```

**Comment by eteq** [comment]
@drudd - When I look at the ``setup.py`` for sphinx v1.3.1 it says ``babel>=1.3`` is a *requirement*.  So it's presumably failing because sphinx considers that to be a requirement, and that dependence isn't satisfied.  Is it possible you've installed sphinx in some way that circumvents it's machinery for computing dependencies?

**Comment by drudd** [comment]
@eteq It was installed using the --no-deps flag (this is a system package install where dependencies need to be carefully tracked), however that should have prevented it from being installed. I wonder if the wheel has a different set of dependencies than the tarball.

**Comment by drudd** [comment]
Rereading the pip documentation I may be misusing that flag, it may be skipping the dependency check rather than preventing an install if dependencies aren't already satisfied. Seems this is my installation problem, closing the ticket.
