### ISSUE TITLE
HIERARCH keywords don't work with CONTINUE cards

### ISSUE THREAD

**Issue by Knusper** [astropy/astropy#3746]
The `astropy.io.fits` manual states, that we can use header keywords longer than 8-characters. In this case [HIERARCH cards will be created](http://docs.astropy.org/en/stable/io/fits/usag/headers.html#hierarch-cards). The manual also states, that if we want to store keyword-value pairs longer than 80-characters, [continue cards will automatically be created](http://docs.astropy.org/en/stable/io/fits/usag/headers.html#continue-cards).

However, in practice it seems that both definitions work only mutually exclusive, i.e. we can not create a FITS file containing a keyword value pair, where the keyword is longer than 8-characters (i.e. a HIERARCH keyword) and the value is a  very long string.

An example:

```
from astropy.io import fits

header1 = fits.Header()
header2 = fits.Header()
header3 = fits.Header()

header1['TEST'] = 'superlongstring'*10
header2['TEST TEST'] = 'superlongstring'
header3['TEST TEST'] = 'superlongstring'*10
```

Here `header1` and `header2` will be correct, but when calling `repr(header3)` or attempting to save a FITS file with such a header, the error `ValueError: The keyword TEST TEST with its value is too long` is raised.

Looking at the `astropy` source code, it is explicitly ruled out to use CONTINUE cards in a value belonging to a HIERARCH keyword.

In the source code we find ([astropy/io/fits/card.py#L1227-1236](https://github.com/astropy/astropy/blob/v1.0.x/astropy/io/fits/card.py#L1227-1236)):

```
keywordvalue_length = len(keyword) + len(delimiter) + len(value)
if (keywordvalue_length > self.length and
        keyword.startswith('HIERARCH')):
    if (keywordvalue_length == self.length + 1 and keyword[-1] == ' '):
        output = ''.join([keyword[:-1], delimiter, value, comment])
    else:
        # I guess the HIERARCH card spec is incompatible with CONTINUE
        # cards
        raise ValueError('The keyword %s with its value is too long' %
                         self.keyword)
```

The comment is from 2011, and was put there during a redesign of pyfits. Before that, pyfits could also read or write exlusively either HIERARCH cards or cards with CONTINUE statement, and apparently it was kept like that. The relevant [old PyFITS code is](https://github.com/spacetelescope/PyFITS/blob/2ae676b84060d78fd59e6b843995dfec74b5c0a7/lib/pyfits/card.py#L383-387):

```
if cardimage[:8].upper() == 'HIERARCH':
    card = _HierarchCard()
    # for card image longer than 80, assume it contains CONTINUE card(s).
elif len(cardimage) > Card.length:
    card = _ContinueCard()
```

Both, the HIERARCH and the CONTINUE keywords are not part of the official [FITS standard (Pence, W.D. et al. 2010, Astronomy & Astrophysics Vol. 524, A42)](http://dx.doi.org/10.1051/0004-6361/201015362). The HIERARCH keyword convention is given in [Wiecencec, A. et al. 2009, "The ESO HIERARCH Keyword Convention")](http://fits.gsfc.nasa.gov/registry/hierarch_keyword.html) and the CONTINUE convention is given by the [HEASARC FITS Working Group, 2007. "The CONTINUE Long String Keyword Convention"](http://fits.gsfc.nasa.gov/registry/continue/continue.pdf). Reading carefully both of these definitions, I see absolutely no reason why they should be mutually exclusive. Hence, `astropy` should support `HIERARCH` keywords with `CONTINUE` values.

**Comment by embray** [comment]
Hi, thanks for taking the time to look into this.  However, I stand by the comment that these conventions are mutually incompatible.  The comparison to the old PyFITS code is not particularly useful since a lot of that code was not as carefully considered.  However, when I was rewriting it I came to the conclusion that these conventions cannot be used for the same card.  I wish now that my comment went into more detail as to why, since I don't remember the exact reason.  But I do remember looking at this carefully and determining that there was an inconsistency between the two.

I think if one were to really dig in to the specifics, the issue is that the CONTINUE convention is *strictly* limited to extending the value of cards with string values (i.e. it does not apply to cards with different types of values).  However, formally speaking, cards using the HIERARCH convention do not have any value at all, and so the CONTINUE convention does not apply to it, unless one were to implicitly support the CONTINUE convention within parsing of cards using the HIERARCH convention.  Because there are ambiguities in how to do this (for example what is the maximum length of a keyword?) and because the HIERARCH convention does not explicitly allow for this interpretation (it gives a specific set of guidelines for how to interpret the contents of a HIERARCH card) we can't add any implicit support for some undocumented interpretation of HIERARCH cards.

What you *could* do is lobby the authors of the ESO HIERARCH convention to update their convention for explicit mutual compatibility with the CONTINUE convention, at which time I'd definitely accept a patch to update that as well.  But in the meantime the issue is too fraught with difficulties, even if it seems "obvious" that they could work together.

Welcome to the wild and wacky world of FITS, where ad-hoc, mutually exclusive conventions were developed at different spacetime coordinates to do things that the format wasn't originally designed to allow, thus leaving otherwise reasonable people to have to fight with the format just to write their data out to disk :)

**Comment by Knusper** [comment]
OK. But for now I think this issue should be mentioned in the documentation.

**Comment by embray** [comment]
I think it's maybe a little specific, though I guess it could go somewhere in the docs for hierarch cards.

Might be nice if somewhere there were docs for the FITS format itself.  I mean readable docs giving the big picture, including discussion of conventions, WCS, etc.  (The FITS Standard itself isn't too bad in terms of readability, but a higher-level documentation of FITS would be nice too.  The PyFITS docs have a little to this effect but there could be more.)

**Comment by Knusper** [comment]
Well - since on the page HIERARCH and CONTINUE cards are mentioned directly next to each other, a little box that the former cannot be paired with the latter would suffice in this particular case. 

Indeed, I don't think that it is something "very specific". After reading the documentation as of now, I was under the impression I can use keywords of arbitary length with arbitary lentgh values. This wasbecause the section of CONTINUE cards is immediately followed by HIERARCH cards....

**Comment by embray** [comment]
I see now.  Yeah, I'll clarify that.

**Comment by olebole** [comment]
I agree that strictly spoken the `CONTINUE` extension is to be applied (only) to string values, while `HIERARCH` headers have no value (in the standard FITS meaning) at all.

However, when reading both conventions ([`HIERARCH`](http://fits.gsfc.nasa.gov/registry/hierarch/hierarch.pdf) and [`CONTINUE`](http://fits.gsfc.nasa.gov/registry/continue/continue.pdf)), I would guess it is more an extension to `CONTINUE` than to `HIERARCH`. However, in my opinion the `CONTINUE` extension is made in a way that extending it would be compatible with all possible cases of FITS reader. Specifically, the `CONTINUE` extension says:

>If a FITS reader encounters a CONTINUE keyword that is not preceded by a string keyword (or another CONTINUE keyword) whose value string ends with the `&' character, then that CONTINUE keyword should be ignored (i.e., it should be interpreted the same as a COMMENT keyword).

Lets look for a possible header:
```
HIERARCH ASTROPY EXAMPLE = 'this is a very &'
CONTINUE 'long string value'
```

For the possible cases of standard conform FITS readers this means:

1. FITS reader that don't support `HIERARCH` and also not `CONTINUE`: They will ignore all `HIERARCH` and `CONTINUE` values, as expected;
2. FITS reader that support `HIERARCH`, but not `CONTINUE`: they will shorten all strings (be them `HIERARCH` or not) to the first line, which is what one would expect,
3. FITS reader that support `CONTINUE`, but not `HIERARCH`: They will ignore the `CONTINUE` line after a `HIERARCH` line (and the `HIERARCH` line itself), which is again what expected
4. FITS reader that support mutually both keywords mutually exclusive: They will read the first line for `HIERARCH` keywords, but ignore a following `CONTINUE` card, again what one would expect
5. A hypothetical FITS reader that supports both keywords at the same time, would get the full string.

Also, the extension to support `CONTINUE` cards after `HIERARCH` cards would be quite natural, there is not much danger that someone comes up with a alternative idea. Therefore, I could imagine that it would be not a mistake to just support this (maybe when a special flag is set). There is the danger that the long value may not be read by other readers, but there is no danger of misinterpretation.

**Comment by embray** [comment]
@olebole has some good points here and the analysis is reasonable.  However, there are still ambiguities.  For example what about something like:

```
HIERARCH ESO LONG KEYWORD LONG KEYWORD LONG KEYWORD LONG KEYWORD LONG KEYWORD LO
CONTINUE NG KEYWORD LONG KEYWORD LONG KEYWORD = 'hello'
```

should this in effect allow very long keywords to be continued into a keyword card?  I would argue no, and that this should be invalid.  But I don't think that's necessarily obvious, least of all to users.

I'm not saying you couldn't find a way to use these conventions simultaneously in a way that makes sense--not at all.  I think the solutions are for the most part "obvious" from an implementation perspective.  But I'm wary of implicitly creating new conventions just by adding support in software for a use case that never existed by design for some specific local use case.  There's of things you *could* do with a FITS file and still have it be a valid FITS file.  Anything, really.  But once you start down that road it's a slippery slope.  

To give another example, we deliberately don't write special support for the `WAT_NNNN` keywords that are used by a few IRAF tasks, even though it would be "easy" and "obvious" to see how to do it.  But these are keywords that are used by a few specialized applications for their own use, and so it's up to those applications to determine how to process them, not baked into the core of the FITS library.  That's not a door we want to open.

**Comment by perrygreenfield** [comment]
I'm not in favor of cooking up implied behaviors that weren't well defined in the convention either. This may be something that eventually the astropy community feels should be supported if there is a groundswell of support for it. But I hate to encourage that sort of thing. Seems to me that the onus should be on the convention maintainers to specifically define such extensions. They've had a long time to do so and haven't (from what I see the first use of HIERARCH predates CONTINUE by a few years).

**Comment by olebole** [comment]
OK, to this sounds reasonable.

**Comment by Knusper** [comment]
@embray According to the HIERARCH convention your example would be invalid, as the keyword can run only to byte 80 and then an equal sign must follow. Keywords longer than 80 characters are not allowed.

**Comment by embray** [comment]
There is a (mailing list)[https://listmgr.nrao.edu/mailman/listinfo/fitsbits] for FITS.  It is very low volume, but usually gets responses when issues like this are raised.  It seems less often that issues raised result in action, but it has been known to happen?

**Comment by Knusper** [comment]
Hey, I just saw that in version 4.0 of the FITS standard (22 May 2016) there is a new section on continue lines for long-string values and comments.
https://fits.gsfc.nasa.gov/fits_standard.html - Sect. 4.2.1.2
Does this apply here?

**Comment by saimn** [comment]
@Knusper - Hi, I think they just included the CONTINUE convention (and a few others), but there is nothing new about the relation with HIERARCH keyword I think.

Also it seems that version 4.0 is no more a draft, good news.

**Comment by astrofrog** [comment]
It might be worth emailing the fitsbits mailing list to ask for confirmation that CONTINUE and HIERARCH are incompatible.

**Comment by t-brandt** [comment]
Having just encountered this issue, I was struck that astropy does not give a warning while creating a header entry when the combination of header and value is too long; the error only appears when attempting to write the fits file to disk.  In contrast, astropy does issue a VerifyWarning when adding a card that requires hierarch.  I would advocate the same warning in the other case as well to make it easier to catch while building or adding to a header.  It's much harder to recover gracefully when you're already trying to write the file.  You could also warn when using 'continue' and either warn or raise an error when both 'hierarch' and 'continue' are used; this last error or warning would be easy to drop when/if hierarch and continue become compatible in the future.

**Comment by embray** [comment]
@t-brandt I agree.  It should catch this case earlier.  It looks like we also never did add a note to the [relevant documentation](https://docs.astropy.org/en/stable/io/fits/usage/headers.html#continue-cards) that HIERARCH and CONTINUE are not compatible (I think there is some reasonable debate on that point, but unless it's resolved it's best to document the present behavior).

While I look at those docs, it would also be nice to update the examples with some more realistic-looking examples from actual FITS files, instead of just values like "asdfasdfasdfasdf" (I think I'm to blame for that).

**Comment by kbwestfall** [comment]
I just ran into this issue.  Here is a somewhat practical example:

```
import os
from astropy.io import fits

if os.path.isfile('test.fits'):
    os.remove('test.fits')

# This is saving the full path to a file to the header and works fine
# because it doesn't need to use both HIERARCH and CONTINUE
hdr = fits.Header()
hdr['MASKFILE'] = '/home/xavier/Projects/PypeIt-development-suite/RAW_DATA/keck_deimos/830G_M_8500/DE.20100913.57006.fits.gz'
# Printing is fine
print(hdr)
# Keyword selection is fine
print(hdr['MASKFILE'])
# Writing to a file is fine
fits.HDUList([fits.PrimaryHDU(header=hdr)]).writeto('test.fits', overwrite=True)
hdu = fits.open('test.fits')
# And it's appropriately recovered
print(hdu[0].header['MASKFILE'])

# Here, I'm using what we originally had for the header keyword.
# There's a rather trivial work around as shown above; this is just to
# illustrate the problem.

hdr = fits.Header()
# Defining the header card doesn't cause a fault
hdr['MASKDEF_FILE'] = '/home/xavier/Projects/PypeIt-development-suite/RAW_DATA/keck_deimos/830G_M_8500/DE.20100913.57006.fits.gz'
# And you can print the value
print(hdr['MASKDEF_FILE'])

try:
    # But printing the whole header faults
    print(hdr)
except Exception as e:
    print(str(e))

try:
    # As does trying to write it to a file
    fits.HDUList([fits.PrimaryHDU(header=hdr)]).writeto('test.fits', overwrite=True)
except Exception as e:
    print(str(e))

if os.path.isfile('test.fits'):
    os.remove('test.fits')

```

**Comment by embray** [comment]
I'm starting to wonder if it wasn't a mistake to make use of HIERARCH cards automatic by default.  I implemented that years ago in an attempt to transparently "lift" the restriction on keyword length for users (attempting as much as possible to abstract away limitations of the FITS format).  However, I wonder if it can lead to a certain kind of carelessness (albeit not the user's fault) w.r.t. naming of keywords in a manner that's expected to "just work".

I wonder how much effort it would be to draft a new FITS convention that combines the HIERARCH and CONTINUE conventions in a consistent manner.

**Comment by Knusper** [comment]
As mentioned earlier, the fitsbits mailing list could be the place to
discuss this:

https://listmgr.nrao.edu/mailman/listinfo/fitsbits

**Comment by Jiangxuejian** [comment]
Seeing the same issue recently, I had to look at the source code and saw in the comment that `"HIERARCH card spec is incompatible with CONTINUE"`. But the error only appears when I try to write the fits file (as already mentioned by  @[t-brandt](https://github.com/t-brandt)), and the error only say that `"The header keyword {!r} with its value is too long"`.

So I suggest we at least change the return error to something like `"The header keyword {!r} with its value is too long, as HIERARCH card spec is incompatible with CONTINUE in the current version."` So that general users like me then know how to modify our code to get a workaround (like shortening the keyword).

This is very easy to do while we can still keep the Astropy codes intact. Then the next TODO improvement can be raising a warning to the user when creating the header card that's both too long in keyword AND value.

**Comment by timj** [comment]
I just ran into this today when I switched from a customized cfitsio writer to astropy.io.fits.  We were writing HIERARCH+CONTINUE and you get something like but now I don't think I can switch to astropy.

```
HIERARCH LSST CALIB UUID OPTICSTRANSMISSION= 'a732ca27-e9d5-45ea-81e1-40a742b9&'
CONTINUE  '1965'
HIERARCH LSST CALIB DATE OPTICSTRANSMISSION = 'Unknown Unknown'
HIERARCH LSST CALIB RUN SENSORTRANSMISSION = 'HSC/calib/unbounded'
HIERARCH LSST CALIB UUID SENSORTRANSMISSION= 'e3af0e45-3d7a-4a5b-aea5-e7421393&'
CONTINUE  '227a'
```

**Comment by erykoff** [comment]
For the record, `fitsio` (a python wrapper for `cfitsio`) serializes these just fine.  And astropy can read the long headers without complaining!  It just can't write them.

Also it'll give a warning when making HIERARCH even though you can't fix that warning without breaking round-tripping.

```
import numpy as np
import fitsio
import astropy.io.fits


data = np.zeros((10, 10))

hdr_dict = {
    "A VERY LONG KEY HERE": "A VERY VERY VERY VERY LONG STRING THAT SOMETHING WILL BE MAD ABOUT PERSISTING BECAUSE ASTROPY CAN'T HANDLE THE TRUTH",
}

fitsio.write("test_file_fitsio.fits", data, header=hdr_dict)

hdr_read = fitsio.read_header("test_file_fitsio.fits", ext=0)

print(hdr_read["A VERY LONG KEY HERE"])

hdr_read2 = astropy.io.fits.getheader("test_file_fitsio.fits", ext=0)

print(hdr_read2["A VERY LONG KEY HERE"])

# This crashes
astropy.io.fits.writeto("test_file_astropy.fits", data, header=hdr_dict)

# As does this:
hdr = astropy.io.fits.Header(hdr_dict)
```

**Comment by hugobuddel** [comment]
Interesting example @erykoff.

In my little experiment, this line on it's own does not crash:
```python
hdr = astropy.io.fits.Header(hdr_dict)
```
Only using `hdr` to save a fits file crashes.

And once you have successfully read a HIERARCH+CONTINUE header, then it can be saved.

E.g. this works:
```python
import fitsio
import astropy.io.fits

long_key = "A VERY LONG KEY HERE"
long_value =  "A VERY VERY VERY VERY LONG STRING THAT SOMETHING WILL BE MAD ABOUT PERSISTING BECAUSE ASTROPY CAN'T HANDLE THE TRUTH"

hdr_dict = {
    "HELLO": 42,
    long_key: long_value,
}


# Write with fitsio once
fitsio.write("test_file_fitsio.fits", data=None, header=hdr_dict)

# Then continue reading and writing through astropy.
hdr_read2 = astropy.io.fits.getheader("test_file_fitsio.fits", ext=0)
hdr_read2["HELLO"] = 43
astropy.io.fits.writeto("test_file_astropy.fits", data=None, header=hdr_read2)

# Read it back in to verify the key is still correct.
hdr_read3 = astropy.io.fits.getheader("test_file_astropy.fits", ext=0)
assert hdr_read3[long_key] == long_value
assert hdr_read3["HELLO"] == 43
```

So you only need a single detour through `fitsio` to write HIERARCH+CONTINUE headers.

The difference is that `_image` of the relevant card is set:
```
>>> hdr_read3.cards[-1]._image
"HIERARCH A VERY LONG KEY HERE= 'A VERY VERY VERY VERY LONG STRING THAT SOMETHI&'CONTINUE  'NG WILL BE MAD ABOUT PERSISTING BECAUSE ASTROPY CAN''T HANDLE THE T&'CONTINUE  'RUTH'                                                                "
```

Setting that manually will also work.

Sharing this because it might help for others who want to make HIERARCH+CONTINUE keywords.

FWIW, I'm also considering bringing the `CONTINUE` keyword up with ESO. Now `CONTINUE` is part of the FITS spec, it might be worthwhile to try to get the HIERARCH convention adapted too.

**Comment by mhvk** [comment]
In trying to investigate, it may help to have an even more minimal example that breaks
```
import astropy.io.fits as fits

long_key = "A VERY LONG KEY HERE"
long_value =  "A VERY VERY VERY VERY LONG STRING THAT SOMETHING WILL BE MAD ABOUT PERSISTING BECAUSE ASTROPY CAN'T HANDLE THE TRUTH"

hdr_short = fits.Header({"short": long_value})
hdr_long = fits.Header({long_key: long_value})

hdr_short
# SHORT   = 'A VERY VERY VERY VERY LONG STRING THAT SOMETHING WILL BE MAD ABOUT &'
# CONTINUE  'PERSISTING BECAUSE ASTROPY CAN''T HANDLE THE TRUTH'                  
hdr_long
# ValueError: The header keyword 'A VERY LONG KEY HERE' with its value is too long
```

**Comment by mhvk** [comment]
Actually, an even shorter minimal example:
```
import astropy.io.fits as fits

long_key = "A VERY LONG KEY HERE"
long_value =  "A VERY VERY VERY VERY LONG STRING THAT SOMETHING WILL BE MAD ABOUT PERSISTING BECAUSE ASTROPY CAN'T HANDLE THE TRUTH"

long_card = fits.Card(long_key, long_value)
long_card.verify()
# ValueError: The header keyword 'A VERY LONG KEY HERE' with its value is too long
```

**Comment by hugobuddel** [comment]
> Given that astropy can read these and code in the wild is writing these, and given that this can lead to code working with certain values and then crashing in confusing ways (as happened to us at Rubin), I think astropy should be able to write them.

> I don't think we should be waiting for ESO to add a sentence to their HIERARCH convention.

Just for the record: I agree that astropy should write HIERARCH+CONTINUE headers. Maybe behind some kind of "I-understand-this-produces-FITS-files-that-might-cause-problems"-flag.

But I also appreciate the concerns. So a workaround would be okayish for me for now.

Maybe it would be interesting to collect possible problems. E.g. see how existing FITS libraries read HIERARCH+CONTINUE cards. Apparently astropy and cfitsio read them just fine; if all libraries read such files in the same way, then there is not actually a practical problem.

**Comment by mhvk** [comment]
A fix is in #17748. Note that I went for a blanket allowing of long cards, which perhaps is not ideal. But good to at least understand where the problem is.

**Comment by hugobuddel** [comment]
The problem does not seem to be so much in the technical aspects of the implementation, but in whether it is actually desirable to have this feature (I vote yes), and that it is not immediately obvious how this feature should be implemented. E.g.

https://github.com/astropy/astropy/issues/3746#issuecomment-98175115

> For example what about something like:
> 
> ```
> HIERARCH ESO LONG KEYWORD LONG KEYWORD LONG KEYWORD LONG KEYWORD LONG KEYWORD LO
> CONTINUE NG KEYWORD LONG KEYWORD LONG KEYWORD = 'hello'
> ```
> 
> should this in effect allow very long keywords to be continued into a keyword card? I would argue no, and that this should be invalid. But I don't think that's necessarily obvious, least of all to users.

A proposed implementation might have more chance of being accepted if it would contain well defined behavior for such edge cases.

**Comment by timj** [comment]
CONTINUE is not compatible with a >72 character long keyword because there is no way to put the `&` marker inside a string. I'm perfectly okay with this being disallowed because the use code would fail in a predictable way when the code is written. The problem with a long keyword some times working but sometimes not working based on the length of the string value is that it happens in an unpredictable way at run time.

**Comment by mhvk** [comment]
My solution in #17748 only changes the code to allow continued values, not long keywords. The goal is just to support standard usage, not to stretch the definitions further!

**Comment by hugobuddel** [comment]
Thank you for getting this in @mhvk and @saimn !

We're not entirely there though, a long value with no spaces (e.g. a filename) will raise a VerifyError:

```python
from astropy.io import fits

value_no_spaces = "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ" * 3
key_long = "A VERY LONG KEY HERE"

card = fits.Card(key_long, value_no_spaces)
card.verify()
```
raises
```python
WARNING: VerifyWarning: Keyword name 'A VERY LONG KEY HERE' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created. [astropy.io.fits.card]
Traceback (most recent call last):
  File ".../HIERARCHCONTINUE/hiercont6.py", line 7, in <module>
    card.verify()
  File ".../lib/python3.12/site-packages/astropy/io/fits/verify.py", line 82, in verify
    errs = self._verify(opt)
           ^^^^^^^^^^^^^^^^^
  File ".../lib/python3.12/site-packages/astropy/io/fits/card.py", line 1165, in _verify
    keyword, valuecomment = self._split()
                            ^^^^^^^^^^^^^
  File ".../lib/python3.12/site-packages/astropy/io/fits/card.py", line 846, in _split
    for card in self._itersubcards():
  File ".../lib/python3.12/site-packages/astropy/io/fits/card.py", line 1239, in _itersubcards
    if not isinstance(card.value, str):
                      ^^^^^^^^^^
  File ".../lib/python3.12/site-packages/astropy/io/fits/card.py", line 293, in value
    value = self._value = self._parse_value()
                          ^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.12/site-packages/astropy/io/fits/card.py", line 764, in _parse_value
    raise VerifyError(
astropy.io.fits.verify.VerifyError: Unparsable card (A VERY LONG KEY HERE), fix it first with .verify('fix').

```
Everything is fine when inserting some spaces in the value, or making the key short .

**Comment by timj** [comment]
Interesting. So the error is complaining about the KEY even though it's the value that affects whether it works at all or not...

**Comment by hugobuddel** [comment]
I think the problem is in `_words_group()`, because the first sub card is too long:
```
>>> card._format_long_image()
"HIERARCH A VERY LONG KEY HERE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNO&'CONTINUE  'PQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCD&'CONTINUE  'EFGHIJKLMNOPQRSTUVWXYZ'                                              "
```

As I commented in https://github.com/astropy/astropy/pull/17748/files#r1956737640 , setting `offset` at the start of `_words_group()` does not actually accomplish anything, because `offset` is reset in the while loop below.

I'm too tired to investigate this in more detail right now.

**Comment by hugobuddel** [comment]
Unrelated to the problem above, I'm worried about the magic number 10 in the if-statement on line https://github.com/astropy/astropy/blob/b817ec3f90463b4dba3ae94372792445fd4cc235/astropy/io/fits/card.py#L1032 because it makes no reference to the key length.

So if a key is long, with a long value, and a comment, but the length of the value would fit in a normal keyword, then it breaks.

Code is perhaps clearer than words. This assert fails:

```python
from astropy.io import fits

value = "ABCDE FGHIJK LMNOPQ RSTUVW XYZ" * 3
value = value[:50]
key = "A VERY LONG KEY HERE"
comment = "a long comment"
card = fits.Card(key, value, comment)
card.verify()

assert card.value == value
```
The value has spaces in it, so the `_word_groups()` problem is not triggered. However, the length of the value is carefully selected that it would fit in a normal keyword, but not with the long key. The if-statement mentioned above then incorrectly triggers.

**Comment by mhvk** [comment]
Oops, both clearly are oversights from my fix. But thankfully we can still get this right before the next release. If anyone would like to have a go, please go ahead! Otherwise, I should get around to it...

**Comment by hugobuddel** [comment]
With the CONTINUE keyword part of the FITS standard, is it ever desirable to truncate the comment? I would personally prefer that a CONTINUE card is used and the comment is kept in tact, because comments often contain useful information. 

That is, I would be happy if we replace this code with the magic number 10
```python
            # longstring case (CONTINUE card)
            # try not to use CONTINUE if the string value can fit in one line.
            # Instead, just truncate the comment
            if isinstance(self.value, str) and len(value) > (self.length - 10):
                output = self._format_long_image()
            else:
                warnings.warn(
                    "Card is too long, comment will be truncated.", VerifyWarning
                )
                output = output[: Card.length]
```
with simply
```python
            # longstring case (CONTINUE card)
            output = self._format_long_image()
```

**Comment by mhvk** [comment]
I agree that we should keep the comment.

**Comment by mhvk** [comment]
Fixes in #17782. Note that I did not change that comments are dropped if without them a card fits in 80 characters. Since that is really separate from this issue (which will now hopefully be closed by #17782), I opened a new issue at #17783.
