### ISSUE TITLE
2D models don't work with np.ogrid

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3917]
As raised in [this thread](https://github.com/astropy/astropy/pull/3909/files#r33900322), it should be possible to use [`np.ogrid`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ogrid.html) to return a grid on which to evaluate a 2D model such as Gaussian2D.  However, trying to do so appears to crash:

``` python
>>> y, x = np.ogrid[:100, :100]
>>> g = Gaussian2D(amplitude=1, x_mean=50, y_mean=50, x_stddev=10, y_stddev=10)
>>> g(x, y)
ERROR: ValueError: total size of new array must be unchanged [astropy.modeling.core]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/internal/1/root/src/astropy/astropy/astropy/modeling/core.py", line 311, in __call__
    __call__, args, [('model_set_axis', None)])
  File "/internal/1/root/src/astropy/astropy/astropy/modeling/core.py", line 307, in __call__
    return super(cls, self).__call__(*inputs, **kwargs)
  File "/internal/1/root/src/astropy/astropy/astropy/modeling/core.py", line 582, in __call__
    return self.prepare_outputs(format_info, *outputs, **kwargs)
  File "/internal/1/root/src/astropy/astropy/astropy/modeling/core.py", line 795, in prepare_outputs
    return _prepare_outputs_single_model(self, outputs, format_info)
  File "/internal/1/root/src/astropy/astropy/astropy/modeling/core.py", line 2296, in _prepare_outputs_single_model
    outputs[idx] = output.reshape(broadcast_shape)
ValueError: total size of new array must be unchanged
```

In principle this should be able to detect that `x` and `y` are broadcastable and proceed accordingly.  Indeed, using `Gaussian2D.evaluate` on these inputs works as expected:

``` python
>>> Gaussian2D.evaluate(x, y, 1, 50, 50, 10, 10, 0)
array([[  1.38879439e-11,   2.27831475e-11,   3.70038187e-11, ...,
          5.95026659e-11,   3.70038187e-11,   2.27831475e-11],
       [  2.27831475e-11,   3.73757133e-11,   6.07046994e-11, ...,
          9.76140186e-11,   6.07046994e-11,   3.73757133e-11],
       [  3.70038187e-11,   6.07046994e-11,   9.85950558e-11, ...,
          1.58542249e-10,   9.85950558e-11,   6.07046994e-11],
       ..., 
       [  5.95026659e-11,   9.76140186e-11,   1.58542249e-10, ...,
          2.54938188e-10,   1.58542249e-10,   9.76140186e-11],
       [  3.70038187e-11,   6.07046994e-11,   9.85950558e-11, ...,
          1.58542249e-10,   9.85950558e-11,   6.07046994e-11],
       [  2.27831475e-11,   3.73757133e-11,   6.07046994e-11, ...,
          9.76140186e-11,   6.07046994e-11,   3.73757133e-11]])
```

which, as expected, also gives the exact same result as using `np.mgrid`.  So it seems there's just a bug somewhere in the Model input validation / broadcast handling that falls over on this case for some reason.  Should probably be easy enough to fix.

**Comment by nden** [comment]
I've looked at this issue during the coordination meeting. Indeed, there's a bug in `prepare_inputs`. Although I fixed it for this particular case, the issue may be a bit more general. In the case of `Gaussian2D.evaluate` this works because the transform is not separable. For transforms which are separable I am assuming the grid should be returned with the desired output shape. If so this needs to be reconsidered after `Model.separable` (#6013) is implemented.

**Comment by nden** [comment]
Fixed.
