### ISSUE TITLE
astropy/tests/test_logger.py::test_exception_logging_argless_exception fails

### ISSUE THREAD

**Issue by jlec** [astropy/astropy#4246]
```python
Internet access disabled
==================================================================== test session starts ====================================================================
platform linux -- Python 3.4.3 -- py-1.4.30 -- pytest-2.7.3 -- /usr/bin/python3.4
rootdir: /var/tmp/portage/dev-python/astropy-1.0.5/work/astropy-1.0.5, inifile: setup.cfg
plugins: cov, pythonpath, catchlog

Running tests with Astropy version 1.0.5.
Running tests in astropy/tests/test_logger.py.

Platform: Linux-4.1.9-lh-x86_64-Intel-R-_Core-TM-_i7-2600_CPU_@_3.40GHz-with-gentoo-2.2

Executable: /usr/bin/python3.4

Full Python Version: 
3.4.3 (default, Aug 21 2015, 10:51:23) 
[GCC 4.9.3]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.9.3
Scipy: 0.16.0
Matplotlib: 1.4.3
h5py: 2.5.0

collected 29 items 

astropy/tests/test_logger.py::test_warnings_logging_disable_no_enable PASSED
astropy/tests/test_logger.py::test_warnings_logging_enable_twice PASSED
astropy/tests/test_logger.py::test_warnings_logging_overridden PASSED
astropy/tests/test_logger.py::test_warnings_logging PASSED
astropy/tests/test_logger.py::test_warnings_logging_with_custom_class PASSED
astropy/tests/test_logger.py::test_warning_logging_with_io_votable_warning PASSED
astropy/tests/test_logger.py::test_import_error_in_warning_logging PASSED
astropy/tests/test_logger.py::test_exception_logging_disable_no_enable PASSED
astropy/tests/test_logger.py::test_exception_logging_enable_twice PASSED
astropy/tests/test_logger.py::test_exception_logging_overridden PASSED
astropy/tests/test_logger.py::test_exception_logging PASSED
astropy/tests/test_logger.py::test_exception_logging_origin PASSED
astropy/tests/test_logger.py::test_exception_logging_argless_exception FAILED
astropy/tests/test_logger.py::test_log_to_list[None] PASSED
astropy/tests/test_logger.py::test_log_to_list[DEBUG] PASSED
astropy/tests/test_logger.py::test_log_to_list[INFO] PASSED
astropy/tests/test_logger.py::test_log_to_list[WARN] PASSED
astropy/tests/test_logger.py::test_log_to_list[ERROR] PASSED
astropy/tests/test_logger.py::test_log_to_list_level PASSED
astropy/tests/test_logger.py::test_log_to_list_origin1 PASSED
astropy/tests/test_logger.py::test_log_to_list_origin2 PASSED
astropy/tests/test_logger.py::test_log_to_file[None] PASSED
astropy/tests/test_logger.py::test_log_to_file[DEBUG] PASSED
astropy/tests/test_logger.py::test_log_to_file[INFO] PASSED
astropy/tests/test_logger.py::test_log_to_file[WARN] PASSED
astropy/tests/test_logger.py::test_log_to_file[ERROR] PASSED
astropy/tests/test_logger.py::test_log_to_file_level PASSED
astropy/tests/test_logger.py::test_log_to_file_origin1 PASSED
astropy/tests/test_logger.py::test_log_to_file_origin2 PASSED

========================================================================= FAILURES ==========================================================================
_________________________________________________________ test_exception_logging_argless_exception __________________________________________________________

    @pytest.mark.skipif(sys.version_info[:2] >= (3, 5),
                        reason="Infinite recursion on Python 3.5")
    @pytest.mark.xfail(str("ip is not None"))
    def test_exception_logging_argless_exception():
        """
        Regression test for a crash that occurred on Python 3 when logging an
        exception that was instantiated with no arguments (no message, etc.)
    
        Regression test for https://github.com/astropy/astropy/pull/4056
        """
    
        try:
            log.enable_exception_logging()
            with log.log_to_list() as log_list:
                raise Exception()
        except Exception as exc:
            sys.excepthook(*sys.exc_info())
        else:
            assert False  # exception should have been raised
        assert len(log_list) == 1
        assert log_list[0].levelname == 'ERROR'
>       assert log_list[0].message == 'Exception [astropy.tests.test_logger]'
E       assert 'Exception' == 'Exception [astropy.tests.test_logger]'
E         - Exception
E         + Exception [astropy.tests.test_logger]

astropy/tests/test_logger.py:285: AssertionError
----------------------------------------------------------------------- Captured log ------------------------------------------------------------------------
logger.py                  282 ERROR    Exception
------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------
ERROR: Exception [astropy.tests.test_logger]
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/astropy-1.0.5/work/astropy-1.0.5/astropy/tests/test_logger.py", line 278, in test_exception_logging_argless_exception
    raise Exception()
Exception
============================================================ 1 failed, 28 passed in 0.52 seconds ============================================================
```

**Comment by embray** [comment]
Out of curiosity, how did you *start* this test run?

**Comment by jlec** [comment]
py.test -vv astropy/tests/test_logger.py

**Comment by embray** [comment]
Right now running the py.test command directly isn't supported.  Instead run:

```
$ ./setup.py test --test=astropy/tests/test_logger.py
```

**Comment by jlec** [comment]
Same error:

```python
==================================================================================================================================================== test session starts ====================================================================================================================================================
platform linux -- Python 3.4.3, pytest-2.8.2, py-1.4.30, pluggy-0.3.1

Running tests with Astropy version 1.0.5.
Running tests in astropy/tests/test_logger.py.

Platform: Linux-4.1.9-lh-x86_64-Intel-R-_Core-TM-_i7-2600_CPU_@_3.40GHz-with-gentoo-2.2

Executable: /usr/bin/python3.4

Full Python Version: 
3.4.3 (default, Aug 21 2015, 10:51:23) 
[GCC 4.9.3]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.10.1
Scipy: 0.16.0
Matplotlib: 1.4.3
h5py: 2.5.0

rootdir: /var/tmp/portage/dev-python/astropy-1.0.5/temp/astropy-test-641ya0sx, inifile: setup.cfg
plugins: cov-2.2.0, pythonpath-0.7, catchlog-1.1
collected 29 items

astropy/tests/test_logger.py ............F................

========================================================================================================================================================= FAILURES ==========================================================================================================================================================
_________________________________________________________________________________________________________________________________________ test_exception_logging_argless_exception __________________________________________________________________________________________________________________________________________

    @pytest.mark.skipif(sys.version_info[:2] >= (3, 5),
                        reason="Infinite recursion on Python 3.5")
    @pytest.mark.xfail(str("ip is not None"))
    def test_exception_logging_argless_exception():
        """
        Regression test for a crash that occurred on Python 3 when logging an
        exception that was instantiated with no arguments (no message, etc.)
    
        Regression test for https://github.com/astropy/astropy/pull/4056
        """
    
        try:
            log.enable_exception_logging()
            with log.log_to_list() as log_list:
                raise Exception()
        except Exception as exc:
            sys.excepthook(*sys.exc_info())
        else:
            assert False  # exception should have been raised
        assert len(log_list) == 1
        assert log_list[0].levelname == 'ERROR'
>       assert log_list[0].message == 'Exception [astropy.tests.test_logger]'
E       assert 'Exception' == 'Exception [astropy.tests.test_logger]'
E         - Exception
E         + Exception [astropy.tests.test_logger]

astropy/tests/test_logger.py:285: AssertionError
------------------------------------------------------------------------------------------------------------------------------------------------------- Captured log --------------------------------------------------------------------------------------------------------------------------------------------------------
logger.py                  282 ERROR    Exception
--------------------------------------------------------------------------------------------------------------------------------------------------- Captured stderr call ----------------------------------------------------------------------------------------------------------------------------------------------------
ERROR: Exception [astropy.tests.test_logger]
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/astropy-1.0.5/temp/astropy-test-641ya0sx/lib.linux-x86_64-3.4/astropy/tests/test_logger.py", line 278, in test_exception_logging_argless_exception
    raise Exception()
Exception
================================================================================================================================== 1 failed, 28 passed, 1 pytest-warnings in 0.55 seconds ==================================================================================================================================
```

**Comment by embray** [comment]
I wonder if it's something to do with the "catchlog" plugin that you have installed.  I've never used that before and don't know what it does but I wouldn't be surprised if it's related.

Anyways, thanks for the report, but I don't think this just seems to be an issue in how the tests are being run (and is admittedly a test that's already pretty sensitive to begin with) so I don't think it's worth pursuing.

**Comment by jlec** [comment]
@embray I will test this and report back.

**Comment by bsipocz** [comment]
Same error here, and I can confirm that it disappears with ``pytest-capturelog`` being removed.
