### ISSUE TITLE
io.ascii.read fails with "unexpected keyword argument" error

### ISSUE THREAD

**Issue by hombit** [astropy/astropy#4258]
I've got an error with this code:
```python
from astropy.io import ascii
ascii.read('ccdm.dat', readme='ReadMe')
```
Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/astropy/io/ascii/ui.py", line 258, in read
    dat = _guess(table, new_kwargs, format, fast_reader_param)
  File "/usr/local/lib/python3.4/dist-packages/astropy/io/ascii/ui.py", line 360, in _guess
    reader = get_reader(**read_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/astropy/io/ascii/ui.py", line 154, in get_reader
    reader = core._get_reader(Reader, Inputter=Inputter, Outputter=Outputter, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/astropy/io/ascii/core.py", line 1242, in _get_reader
    reader = Reader(**reader_kwargs)
TypeError: __init__() got an unexpected keyword argument 'readme'
```

I use astropy 1.0.5, numpy 1.10.1, and python 3.4.3. My system is Ubuntu 14.04 64bit, numpy and astropy are installed from pip

**Comment by taldcroft** [comment]
@hombit - 

First, can you try adding `format='cds', guess=False` to your function call?  My guess is that the file is incorrectly formatted.

For a sanity check you can try the test CDS file with the following (within ipython):
```
import os
os.chdir(os.path.join(os.path.dirname(ascii.__file__), 'tests', 't', 'cds', 'multi'))
ls  # Should show : lhs2065.dat  lp944-20.dat  ReadMe
ascii.read('lp944-20.dat', readme='ReadMe')
```

**Comment by taldcroft** [comment]
BTW, if not for the #4120 problem, this would have given a more normal error message that the file was not guessable with any of the known formats.

**Comment by hombit** [comment]
@taldcroft Test of CDS works correctly.

I got my files from [this page](http://cdsarc.u-strasbg.fr/viz-bin/Cat?cat=I%2F274&target=http&). I unpacked dat.gz and used it with ReadMe.
```python
from astropy.io import ascii
ascii.read('ccdm.dat', readme='ReadMe, format='cds', guess=False' )
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/astropy/io/ascii/core.py", line 841, in _convert_vals
    converter_func, converter_type = col.converters[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/astropy/io/ascii/ui.py", line 361, in _guess
    return reader.read(table)
  File "/usr/local/lib/python3.4/dist-packages/astropy/io/ascii/cds.py", line 321, in read
    return super(Cds, self).read(table)
  File "/usr/local/lib/python3.4/dist-packages/astropy/io/ascii/core.py", line 1076, in read
    table = self.outputter(cols, self.meta)
  File "/usr/local/lib/python3.4/dist-packages/astropy/io/ascii/core.py", line 868, in __call__
    self._convert_vals(cols)
  File "/usr/local/lib/python3.4/dist-packages/astropy/io/ascii/core.py", line 855, in _convert_vals
    raise ValueError('Column %s failed to convert' % col.name)
ValueError: Column pmRA failed to convert

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/astropy/io/ascii/ui.py", line 258, in read
    dat = _guess(table, new_kwargs, format, fast_reader_param)
  File "/usr/local/lib/python3.4/dist-packages/astropy/io/ascii/ui.py", line 384, in _guess
    raise core.InconsistentTableError('\n'.join(lines))
astropy.io.ascii.core.InconsistentTableError: 
ERROR: Unable to guess table format with the guesses listed below:
Reader:Cds fill_values: [('', '0'), ('', 'nan', 'dRAs'), ('', 'nan', 'dDEs'), ('', '0', 'r_dRAs'), ('', '0', 'Year'), ('', 'nan', 'rho'), ('', '0', 'Obs'), ('', 'nan', 'Vmag'), ('', '0', 'pmRA'), ('', '0', 'pmDE'), ('', '0', 'HIC'), ('', 'nan', 'dRAs'), ('', 'nan', 'dDEs'), ('', '0', 'r_dRAs'), ('', '0', 'Year'), ('', 'nan', 'rho'), ('', '0', 'Obs'), ('', 'nan', 'Vmag'), ('', '0', 'pmRA'), ('', '0', 'pmDE'), ('', '0', 'HIC')] readme: 'ReadMe'
Reader:Cds fill_values: [('', '0'), ('', 'nan', 'dRAs'), ('', 'nan', 'dDEs'), ('', '0', 'r_dRAs'), ('', '0', 'Year'), ('', 'nan', 'rho'), ('', '0', 'Obs'), ('', 'nan', 'Vmag'), ('', '0', 'pmRA'), ('', '0', 'pmDE'), ('', '0', 'HIC'), ('', 'nan', 'dRAs'), ('', 'nan', 'dDEs'), ('', '0', 'r_dRAs'), ('', '0', 'Year'), ('', 'nan', 'rho'), ('', '0', 'Obs'), ('', 'nan', 'Vmag'), ('', '0', 'pmRA'), ('', '0', 'pmDE'), ('', '0', 'HIC')] readme: 'ReadMe'

************************************************************************
** ERROR: Unable to guess table format with the guesses listed above. **
**                                                                    **
** To figure out why the table did not read, use guess=False and      **
** appropriate arguments to read().  In particular specify the format **
** and any known attributes like the delimiter.                       **
************************************************************************
```

**Comment by taldcroft** [comment]
The file `ccdm.dat` has an error in it.  On line 36027 the field value for `pmRA` is `-` which cannot be converted to an integer (format is `I5`).  I edited this to be `-0` and the file reads in OK.  However since the `pmDec` field has a value of `+0005` that means the value `0` is most likely wrong and you might want to contact the authors to get the right value and have them correct the Vizier database table.

I'm closing as there does not appear to be any problem in the reading code.

**Comment by astrofrog** [comment]
@hombit - in the mean time, note that you can also download tables from CDS in FITS table format.
