### ISSUE TITLE
Cannot run ``python setup.py install``

### ISSUE THREAD

**Issue by jakevdp** [astropy/astropy#4326]
Trying to review one of the blocking PRs, and I get this on the current master branch:

```
jakevdp$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 52, in <module>
    package_info = get_package_info()
  File "/Users/jakevdp/Opensource/astropy/astropy_helpers/astropy_helpers/setup_helpers.py", line 539, in get_package_info
    ext_modules.extend(setuppkg.get_extensions())
  File "astropy/wcs/setup_package.py", line 253, in get_extensions
    generate_c_docstrings()
  File "astropy/wcs/setup_package.py", line 126, in generate_c_docstrings
    from astropy.wcs import docstrings
  File "/Users/jakevdp/Opensource/astropy/astropy/wcs/__init__.py", line 30, in <module>
    from .wcs import *
  File "/Users/jakevdp/Opensource/astropy/astropy/wcs/wcs.py", line 57, in <module>
    _parsed_version = _wcs.__version__.split('.')
AttributeError: 'module' object has no attribute '__version__'
```

I've cleared build/dist directories, made sure my git repo is clean, and removed all old astropy installations in site-packages. Any ideas? I need to be able to do this to build docs locally with the branch I'm reviewing.

**Comment by jakevdp** [comment]
Fixed by removing ``astropy/wcs/_wcs.so``. Sorry for the noise.
