### ISSUE TITLE
Doctest failures

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#4457]
When running `python setup.py test -R -V` I get these failures : 

```
================================================================================================================== FAILURES ===================================================================================================================
_____________________________________________________________________________________________ [doctest] astropy.time.core.Time.get_delta_ut1_utc ______________________________________________________________________________________________
1164             >>> status == TIME_BEFORE_IERS_RANGE
1165             array([ True, False], dtype=bool)
1166 
1167         To use an updated IERS A bulletin to calculate UT1-UTC
1168         (see also ``astropy.utils.iers``)::
1169 
1170             >>> from astropy.utils.iers import IERS_A, IERS_A_URL
1171             >>> from astropy.utils.data import download_file
1172             >>> t = Time(['1974-01-01', '2000-01-01'], scale='utc')
1173             >>> iers_a_file = download_file(IERS_A_URL,
UNEXPECTED EXCEPTION: URLError(timeout('timed out',),)
Traceback (most recent call last):

  File "/usr/lib64/python2.7/doctest.py", line 1315, in __run
    compileflags, 1) in test.globs

  File "<doctest astropy.time.core.Time.get_delta_ut1_utc[7]>", line 2, in <module>

  File "astropy/utils/data.py", line 1104, in download_file
    raise urllib.error.URLError(e)

URLError: <urlopen error timed out>

astropy/time/core.py:1173: UnexpectedException
______________________________________________________________________________________________________ [doctest] docs/io/ascii/read.rst _______________________________________________________________________________________________________
212   Tues     --   --
213    Wed    1.1 snow
214 
215 If you want to replace the masked (missing) values with particular values, set the masked
216 column ``fill_value`` attribute and then get the "filled" version of the table.  This
217 looks like the following::
218 
219   >>> dat['precip'].fill_value = -999
220   >>> dat['type'].fill_value = 'N/A'
221   >>> print(dat.filled())
Differences (unified diff with -expected +actual):
    @@ -2,4 +2,4 @@
     ---- ------ ----
      Mon    1.5 rain
    -Tues -999.0  N/A
    +Tues    -99  N/A
      Wed    1.1 snow

/tmp/simon/astropy-test-XKzZAA/docs/io/ascii/read.rst:221: DocTestFailure
_____________________________________________________________________________________________________ [doctest] docs/table/operations.rst _____________________________________________________________________________________________________
268 Any time this happens then `~astropy.table.groups.TableGroups.aggregate`
269 will issue a warning and then
270 drop that column from the output result.  Note that the ``name``
271 column is one of the ``keys`` used to determine the grouping so
272 it is automatically ignored from aggregation.
273 
274 From a grouped table it is possible to select one or more columns on which
275 to perform the aggregation::
276 
277   >>> print(obs_by_name['mag_b'].groups.aggregate(np.mean))
UNEXPECTED EXCEPTION: TypeError(u"Cannot aggregate column 'mag_b' with type '|S4'",)
Traceback (most recent call last):

  File "/usr/lib64/python2.7/doctest.py", line 1315, in __run
    compileflags, 1) in test.globs

  File "<doctest operations.rst[22]>", line 1, in <module>

  File "astropy/table/groups.py", line 262, in aggregate
    par_col.info.dtype))

TypeError: Cannot aggregate column 'mag_b' with type '|S4'

/tmp/simon/astropy-test-XKzZAA/docs/table/operations.rst:277: UnexpectedException
================================================================================ 3 failed, 10188 passed, 100 skipped, 43 xfailed, 2 xpassed in 433.32 seconds =================================================================================
```

Though I can't reproduce if I run only the tests for the files failing above with `python setup.py test -V -t docs/io/ascii/read.rst` or `python setup.py test -V -t docs/table/operations.rst`

**Comment by saimn** [comment]
Forgot to put some environment details:
```
platform linux2 -- Python 2.7.11 -- py-1.4.30 -- pytest-2.7.3 -- /home/simon/.virtualenvs/astropy/bin/python
rootdir: /tmp/simon/astropy-test-_Ngvzw, inifile: setup.cfg

Running tests with Astropy version 1.1.dev14301.
Running tests in lib.linux-x86_64-2.7/astropy docs.

Date: 2016-01-08T12:30:10

Platform: Linux-4.3.3-2-ARCH-x86_64-with-glibc2.2.5

Executable: /home/simon/.virtualenvs/astropy/bin/python

Full Python Version: 
2.7.11 (default, Dec  6 2015, 15:43:46) 
[GCC 5.2.0]

encodings: sys: ascii, locale: UTF-8, filesystem: UTF-8, unicode bits: 20
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.10.1
Scipy: 0.16.1
Matplotlib: 1.5.0
h5py: 2.5.0
Pandas: 0.16.2
Using Astropy options: remote_data.
```

**Comment by saimn** [comment]
The failure in `docs/io/ascii/read.rst` is probably the same as #4363. If I get into a pdb and print the table:
```
(Pdb) test.globs['dat']
<Table masked=True length=3>
day  precip type
str4  str3  str4
---- ------ ----
 Mon    1.5 rain
Tues     --   --
 Wed    1.1 snow
(Pdb) test.globs['dat']['precip'].fill_value
'-99'
```
`precip` is str column whereas it should be float.

**Comment by saimn** [comment]
And the same for `docs/table/operations.rst`:
```
(Pdb) test.globs['obs_by_name']
<Table length=10>
name  obs_date  mag_b mag_v
str4   str10     str4  str4
---- ---------- ----- -----
M101 2012-01-02  15.1  13.5
M101 2012-02-14  15.0  13.6
M101 2012-03-26  15.1  13.5
M101 2012-03-26  14.8  14.3
 M31 2012-01-02  17.0  17.5
 M31 2012-01-02  17.1  17.4
 M31 2012-02-14  16.9  17.3
 M82 2012-02-14  16.2  14.5
 M82 2012-02-14  15.2  15.5
 M82 2012-03-26  15.7  16.5
```

**Comment by embray** [comment]
Yes, this is the same as  #4363.  The timeout error is probably ephemeral.

**Comment by embray** [comment]
(Thanks for the report though--it occurs to me #4363 doesn't specify which tests failures were associated with it, so it's good to have that documented)
