### ISSUE TITLE
pytest pastebin: py3 incompatible before v2.8.3

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#4475]
I've tried using the `--pastebin='failed'` functionality running tests in astroquery, and I get the following traceback/dump:
```
======================================================================================== Sending information to Paste Service ========================================================================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/folders/_r/c4nkvmpn4vx6qc91qygz8h740000gr/T/astroquery-test-g65uipac/lib.macosx-10.5-x86_64-3.5/astroquery/_astropy_init.py", line 114, in test
    coverage=coverage, open_files=open_files, **kwargs)
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/astropy-1.1.1-py3.5-macosx-10.5-x86_64.egg/astropy/tests/runner.py", line 253, in run_tests
    return pytest.main(args=all_args, plugins=plugins)
  File "_pytest.config", line 41, in main
  File "_pytest.core", line 521, in __call__
  File "_pytest.core", line 528, in _docall
  File "_pytest.core", line 394, in execute
  File "_pytest.main", line 116, in pytest_cmdline_main
  File "_pytest.main", line 109, in wrap_session
  File "_pytest.core", line 521, in __call__
  File "_pytest.core", line 528, in _docall
  File "_pytest.core", line 393, in execute
  File "_pytest.core", line 109, in wrapped_call
  File "_pytest.terminal", line 360, in pytest_sessionfinish
  File "_pytest.core", line 521, in __call__
  File "_pytest.core", line 528, in _docall
  File "_pytest.core", line 394, in execute
  File "_pytest.pastebin", line 87, in pytest_terminal_summary
  File "_pytest.pastebin", line 64, in create_new_paste
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/urllib/request.py", line 463, in open
    req = meth(req)
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/urllib/request.py", line 1170, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.
sys:1: ResourceWarning: unclosed <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('134.171.35.27', 55017), raddr=('131.142.185.10', 80)>
sys:1: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('134.171.35.27', 54991)>
sys:1: ResourceWarning: unclosed <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('134.171.35.27', 54992)>
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('134.171.35.27', 54988), raddr=('104.244.42.1', 443)>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='w' encoding='UTF-8'>
```

It turns out this is a bug that was fixed only a few months ago: https://github.com/pytest-dev/pytest/issues/1198.  The first release that includes this fix is 2.8.3.  So we could include a warning in astropy about this, or this issue can just serve as a 'heads up' in case anyone tries using the pastebin feature and lands here.  conda still has 2.8.1 as its latest.

**Comment by keflavich** [comment]
I'm just closing this because I found the solution immediately after writing the problem, but I think it's worth having the information available for search.
