### ISSUE TITLE
FITS I/O bug

### ISSUE THREAD

**Issue by profxj** [astropy/astropy#4580]
Am pretty sure the following represent a bug in the FITS I/O,
but am not certain.  The failing code is below.  The write statement
works and the read fails with an:

IOError
: Header missing END card.

======
dum = np.empty((5,100), dtype=[('w','>f8'),('f','>f4')])
prihdu = fits.PrimaryHDU()
tblhdu = fits.BinTableHDU(dum, name='DATA’)
hdulist = fits.HDUList([prihdu, tblhdu])

hdulist.writeto(‘file.fits', clobber=True) # Does not fail

tmp = fits.open(‘file.fits’)  # Fails

**Comment by AMAN3003** [comment]
@profxj  i am working on this

**Comment by AMAN3003** [comment]
@cdeil @profxj  @astrofrog please review this

**Comment by AMAN3003** [comment]
@astrofrog  i usually got travis error but could n't find any help how to correct it

**Comment by pllim** [comment]
Just use

```python
tmp = fits.open('file.fits', ignore_missing_end=True)
```

Also see #4351 and related issues.

**Comment by AMAN3003** [comment]
@plim i have already mentioned it in the commit.with relevant code

**Comment by weaverba137** [comment]
```python
dum = np.empty((5,100), dtype=[('w','>f8'),('f','>f4')])
```
Sorry, but how many rows is the table supposed to have?  5? 100? 500?

**Comment by cdeil** [comment]
This bug report started on the astropy-dev mailing list.

Here's the comment by @embray that suggests some extra check should be added on BinTableHDU construction:

> I agree with Benjamin here--the np.empty((5, 100), ...) doesn't make 
any sense for a table. 
> I am surprised, however, that it was accepted at all as the data for a 
BinTableHDU.  I'm not sure what exactly it *would* do with something 
like that passed in.  But it probably should not have accepted it in 
the first place.  I'm surprised something didn't crash sooner.

**Comment by AMAN3003** [comment]
@weaverba137  its has 5 rows and 10 column
which can bee seen by dum.shape

**Comment by weaverba137** [comment]
Uh,

```python
>>> import numpy as np
>>> dum = np.empty((5,100), dtype=[('w','>f8'),('f','>f4')])
>>> dum.shape
(5, 100)
>>> dum['w'].shape
(5, 100)
>>> dum['f'].shape
(5, 100)
```

How does a 5x100 object fit into a FITS binary table with *two* columns?  The columns are named 'w' and 'f'.

**Comment by AMAN3003** [comment]
@weaverba137 Sorry it has 100 columns

**Comment by profxj** [comment]
As I seem to have confused the crowd with the concept
of a Table of arrays, I’ve generated a Notebook to explain:

https://dl.dropboxusercontent.com/u/6285549/Python/Notebooks/dum_table.ipynb
http://nbviewer.jupyter.org/urls/dl.dropboxusercontent.com/u/6285549/Python/Notebooks/dum_table.ipynb <http://nbviewer.jupyter.org/urls/dl.dropboxusercontent.com/u/6285549/Python/Notebooks/dum_table.ipynb>

Looks like I’m making fitsio generate junk too.
I’m willing to allow that I’m doing something I 
shouldn’t be, but this seems a bit limiting.

Maybe it is time to head to hdf5 (although I
may have found an astropy bug there too)..

Cheers,

X


> On Feb 8, 2016, at 11:51 PM, Christoph Deil <notifications@github.com> wrote:
> 
> This bug report started on the astropy-dev mailing list.
> 
> Here's the comment by @embray <https://github.com/embray> that suggests some extra check should be added on BinTableHDU construction:
> 
> I agree with Benjamin here--the np.empty((5, 100), ...) doesn't make 
> any sense for a table. 
> I am surprised, however, that it was accepted at all as the data for a 
> BinTableHDU. I'm not sure what exactly it would do with something 
> like that passed in. But it probably should not have accepted it in 
> the first place. I'm surprised something didn't crash sooner.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/astropy/astropy/issues/4580#issuecomment-181750528>.
> 
> !DSPAM:826,56b99a8d197682248823650!

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/pyigm/pyigm
https://github.com/linetools/linetools

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by weaverba137** [comment]
It appears you are trying to create a Table with 5 rows and two columns named 'w' and 'f', each of which is an array of 100 values.

```python
dum = np.empty((5,), dtype=[('w','>f8',(100,)),('f','>f4',(100,))])
```

That will create a perfectly valid FITS file.  If that's *not* what you're trying to do, could you please add some explanatory text to your notebook?  It might also be useful to see the FITS header cards that you are *expecting* but not seeing.

**Comment by profxj** [comment]
Works indeed.

Thanks a bunch,

X

> On Feb 10, 2016, at 10:02 AM, Benjamin Alan Weaver <notifications@github.com> wrote:
> 
> It appears you are trying to create a Table with 5 rows and two columns named 'w' and 'f', each of which is an array of 100 values.
> 
> dum = np.empty((5,), dtype=[('w','>f8',(100,)),('f','>f4',(100,))])
> That will create a perfectly valid FITS file. If that's not what you're trying to do, could you please add some explanatory text to your notebook? It might also be useful to see the FITS header cards that you are expecting but not seeing.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/astropy/astropy/issues/4580#issuecomment-182505401>.
> 
> !DSPAM:826,56bb7b29140918291022!

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/pyigm/pyigm
https://github.com/linetools/linetools

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by embray** [comment]
Basically, `np.zeros((5, 100), dtype=[('a', 'f8'), ('b', 'f8')])` or anything else like this is like creating an array of structs in C (specifically a 5x100 array in this case).  So it's a like a 5x100 array of pairs of floats.  Just because there are two fields does *not* mean that it represents a table.  A table should be thought of (in this case) as a 1-D array of structs.  So `np.zeros((100,), dtype=[('a', 'f8'), ('b', 'f8')])` creates a 100-row table of pairs, where each element in the pair corresponds to an item in a column.  

Incidentally, this is specifically a *row oriented* table.  A column oriented table would consist of a list or other sequence of 1-D arrays of different dtypes.

I think @weaverba137's example is good too.  That creates a 5-row table of structs that consist of two 100-element float arrays.

The bug here, as far is Astropy is concerned, is that it was accepting Numpy arrays that do *not* represent row-oriented tables as the HDU data (currently this is the only type of array that would be accepted).  Note also that it does *sort of* accept column-oriented tables via `BinTableHDU.from_columns`.

**Comment by neutrinoceros** [comment]
> I am surprised, however, that it was accepted at all as the data for a BinTableHDU. 

> The bug here, as far is Astropy is concerned, is that it was accepting Numpy arrays that do not represent row-oriented tables as the HDU data (currently this is the only type of array that would be accepted)

I don't know exactly when behavior changed but as of astropy 6.0.1, OP's script tracebacks as
```
Traceback (most recent call last):
  File "/Users/clm/dev/astropy-project/coordinated/astropy/issues/4580/t.py", line 6, in <module>
    tblhdu = fits.BinTableHDU(dum, name='DATA')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/clm/dev/astropy-project/coordinated/astropy/issues/4580/.venv/lib/python3.12/site-packages/astropy/io/fits/hdu/table.py", line 872, in __init__
    super().__init__(
  File "/Users/clm/dev/astropy-project/coordinated/astropy/issues/4580/.venv/lib/python3.12/site-packages/astropy/io/fits/hdu/table.py", line 351, in __init__
    self.data = self._data_type.from_columns(data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/clm/dev/astropy-project/coordinated/astropy/issues/4580/.venv/lib/python3.12/site-packages/astropy/io/fits/fitsrec.py", line 470, in from_columns
    outarr[:n] = inarr.ravel()
    ~~~~~~^^^^
ValueError: could not broadcast input array from shape (500,) into shape (5,)
```

It seems that we're de-facto not accepting the ill-formed input array anymore (good !), so maybe all we need now is a slightly clearer error message.
@saimn @astrofrog do you think that'd be sufficient to close this issue ?
