### ISSUE TITLE
conftest.py fails on my system.

### ISSUE THREAD

**Issue by barun511** [astropy/astropy#4584]
This is probably just a minor, completely system-specific bug, but I figured I ought to raise it anyway.

While running the full test suite, my system failed on astropy/conftest.py, with the following error message:
```python
skipping 'astropy/cosmology/scalar_inv_efuncs.c' Cython extension (up-to-date)
Traceback (most recent call last):
  File "_pytest.config", line 546, in importconftest
    mod = conftestpath.pyimport()
  File "py._path.local", line 650, in pyimport
    __import__(modname)
  File "astropy/conftest.py", line 8, in <module>
    import matplotlib
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 975, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url
    encoding = locale.getdefaultlocale()[1]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
ERROR: could not load /private/tmp/astropy-test-CMHpLH/lib.macosx-10.10-x86_64-2.7/astropy/conftest.py
```

 Please feel free to ignore if its not worth mention! I'm still relatively new, and getting started on working and contributing to the astropy codebase.

**Comment by anchitjain1234** [comment]
check this http://stackoverflow.com/questions/19961239/pelican-3-3-pelican-quickstart-error-valueerror-unknown-locale-utf-8

**Comment by pllim** [comment]
This looks like a `matplotlib` problem, see matplotlib/matplotlib#5481

**Comment by astrofrog** [comment]
I think this may actually be the following known issue: http://docs.astropy.org/en/stable/known_issues.html#locale-errors-in-macos-x-and-linux

@barun511 - can you try the instructions there to fix it?

**Comment by barun511** [comment]
Allright, so I uninstalled matplotlib, and that led to all the tests passing but one, and that one was the ValueError raised, that astrofrog's fix worked on. All tests pass now, thank you very much!

**Comment by ntessore** [comment]
I actually encountered the matplotlib problem through this astropy problem. The fix was just merged, FYI.
