### ISSUE TITLE
BUG: cparser read errors with commented_header

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy#4610]
When using the `astropy.io.ascii` fast reader for `commented_header` files; the combination of setting the header to the last commented line (`header_start=-1`) and `guess=False` results in somewhat random errors, looking like some kind of memory corruption (or possibly wrong `map_len` passed to `get_line`):
```
Python 3.4.4 (default, Jan  5 2016, 04:46:23) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from astropy.io import ascii
>>> tb1 = ascii.read('mt2.txt', format='commented_header', header_start=2, guess=False)
>>> tb1[:3]
<Table length=3>
   A       B        C   
float64 float64  float64
------- -------- -------
 1.0048 21.00001 3.14004
 1.0075 21.00001 3.14005
 1.0108 21.00002 3.14006
>>> tb2 = ascii.read('mt2.txt', format='commented_header', header_start=-1, guess=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/ui.py", line 326, in read
    dat = fast_reader.read(table)
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/fastbasic.py", line 229, in read
    out = super(FastCommentedHeader, self).read(table)
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/fastbasic.py", line 99, in read
    conversion_info = self._read_header()
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/fastbasic.py", line 244, in _read_header
    for line in tmp.splitlines():
  File "astropy/io/ascii/cparser.pyx", line 159, in splitlines (astropy/io/ascii/cparser.c:3177)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 3849: ordinal not in range(128)
```
The errors, again, occur in a not quite deterministic way, but quite inevitably with longer text files and frequently result in a Segmentation fault right away.
Seen in 1.1.1 and current master.

[mt2.txt](https://github.com/astropy/astropy/files/133350/mt2.txt)

**Comment by mvnnn** [comment]
For Table Column name ```format='commented_header'``` expect to Column names in a commented line in your data. you print Table using ```header_start=2``` that means your Table Column name set from your file's 3rd line(index is 2) . if you set ```header_start=-1``` that means your Table column name set from  your last line(index is -1) and ```format='commented_header'``` expect to Column names in a commented line so definitely it's raise Error.
if you want to print Table using ```header_start=-1```  then use ```format='fixed_width'``` or ```format='tab' ```
```
>>> tb1 = ascii.read('mt2.txt', format='fixed_width', header_start=-1, guess=False)
>>> tb1[:3]
<Table length=3>
3.080800E+00  2.206121E+01  3.191000E+00
                 str40                  
----------------------------------------
1.004800E+00  2.100001E+01  3.140040E+00
1.007500E+00  2.100001E+01  3.140050E+00
1.010800E+00  2.100002E+01  3.140060E+00
```

**Comment by dhomeier** [comment]
No, a negative index is counting from the last *commented* line, so `2` and `-1` are referring to identical line positions here. That case is even included in `test_c_reader.py:test_commented_header`
```
    text = '# first commented line\n # second commented line\n\n' + text
    t2 = read_commented_header(text, header_start=2, data_start=0, parallel=parallel)
    assert_table_equal(t2, expected)
    t3 = read_commented_header(text, header_start=-1, data_start=0, parallel=parallel) # negative indexing allowed
    assert_table_equal(t3, expected)
```
and for short enough files (and seemingly any strings in memory) it generally works. But with this line length, between about 50-100 lines I am regularly seeing those errors and segfaults.
With `fixed_width` it is interpreting the last data line as column names as your example shows, which is not at all what I want (and it also gets the data type wrong, probably because it includes the blanks in the fields).
The easiest workaround is of course setting `guess=True` at the expense of the small performance penalty implied, but this seems to hint at a more serious bug (well, Segmentation faults usually do, I think).

**Comment by dhomeier** [comment]
To illustrate what I mean by "erratically failing":
```
Python 3.4.4 (default, Jan  5 2016, 04:46:23) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> from astropy.io import ascii
>>> os.system('head -63 mt2.txt > mt2s.txt')
0
>>> tb2 = ascii.read('mt2s.txt', format='commented_header', header_start=-1, guess=False)
>>> tb2[:3]
<Table length=3>
   A       B        C   
float64 float64  float64
------- -------- -------
 1.0048 21.00001 3.14004
 1.0075 21.00001 3.14005
 1.0108 21.00002 3.14006
>>> 
>>> os.system('head -68 mt2.txt > mt2s.txt')
0
>>> tb2 = ascii.read('mt2s.txt', format='commented_header', header_start=-1, guess=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/ui.py", line 326, in read
    dat = fast_reader.read(table)
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/fastbasic.py", line 229, in read
    out = super(FastCommentedHeader, self).read(table)
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/fastbasic.py", line 99, in read
    conversion_info = self._read_header()
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/fastbasic.py", line 244, in _read_header
    for line in tmp.splitlines():
  File "astropy/io/ascii/cparser.pyx", line 159, in splitlines (astropy/io/ascii/cparser.c:3177)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 1215: ordinal not in range(128)
>>> tb2 = ascii.read('mt2s.txt', format='commented_header', header_start=-1, guess=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/ui.py", line 326, in read
    dat = fast_reader.read(table)
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/fastbasic.py", line 229, in read
    out = super(FastCommentedHeader, self).read(table)
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/fastbasic.py", line 99, in read
    conversion_info = self._read_header()
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/fastbasic.py", line 244, in _read_header
    for line in tmp.splitlines():
  File "astropy/io/ascii/cparser.pyx", line 159, in splitlines (astropy/io/ascii/cparser.c:3177)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x84 in position 1255: ordinal not in range(128)
>>> tb2 = ascii.read('mt2s.txt', format='commented_header', header_start=-1, guess=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/ui.py", line 326, in read
    dat = fast_reader.read(table)
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/fastbasic.py", line 229, in read
    out = super(FastCommentedHeader, self).read(table)
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/fastbasic.py", line 99, in read
    conversion_info = self._read_header()
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/fastbasic.py", line 244, in _read_header
    for line in tmp.splitlines():
  File "astropy/io/ascii/cparser.pyx", line 159, in splitlines (astropy/io/ascii/cparser.c:3177)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 1215: ordinal not in range(128)
>>> os.system('head -103 mt2.txt > mt2s.txt')
0
>>> tb2 = ascii.read('mt2s.txt', format='commented_header', header_start=-1, guess=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/ui.py", line 326, in read
    dat = fast_reader.read(table)
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/fastbasic.py", line 229, in read
    out = super(FastCommentedHeader, self).read(table)
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/fastbasic.py", line 99, in read
    conversion_info = self._read_header()
  File "/sw/lib/python3.4/site-packages/astropy/io/ascii/fastbasic.py", line 244, in _read_header
    for line in tmp.splitlines():
  File "astropy/io/ascii/cparser.pyx", line 159, in splitlines (astropy/io/ascii/cparser.c:3177)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 3806: ordinal not in range(128)
>>> tb2 = ascii.read('mt2s.txt', format='commented_header', header_start=-1, guess=False)
Segmentation fault 
```
For most file lengths between 60 and 100 lines there seems to be a pattern of finding an invalid character at a position switching back and forth by 40 bytes (this is independent of line length). This was on Mac OS X 10.10; FWIW the same experiment on a Linux machine with a (icc-compiled) `astropy-1.0.5` immediately results in a `Memory fault (core dump)` for files longer than ~50 lines.
