### ISSUE TITLE
ValueError when importing SkyCoord

### ISSUE THREAD

**Issue by nhurleywalker** [astropy/astropy#4680]
I originally found this error when trying to run:

`from astropy.modeling import models`

and traced the error messages to find the base problem is running:

`from astropy.coordinates import SkyCoord`

Here's the error message:

>Traceback (most recent call last):
>  File "duh.py", line 2, in <module>
>    from astropy.coordinates import SkyCoord
>  File "/usr/local/lib/python2.7/dist-packages/astropy/coordinates/__init__.py", line 13, in <module>
>    from .baseframe import *
>  File "/usr/local/lib/python2.7/dist-packages/astropy/coordinates/baseframe.py", line 1181, in <module>
>    from .earth import EarthLocation
>  File "/usr/local/lib/python2.7/dist-packages/astropy/coordinates/earth.py", line 11, in <module>
>    from .builtin_frames import ITRS
>  File "/usr/local/lib/python2.7/dist-packages/astropy/coordinates/builtin_frames/__init__.py", line 28, in <module>
>    from .fk5 import FK5
>  File "/usr/local/lib/python2.7/dist-packages/astropy/coordinates/builtin_frames/fk5.py", line 10, in <module>
>    from .. import earth_orientation as earth
>  File "/usr/local/lib/python2.7/dist-packages/astropy/coordinates/earth_orientation.py", line 19, in <module>
>    jd1950 = Time('B1950', scale='tai').jd
>  File "/usr/local/lib/python2.7/dist-packages/astropy/time/core.py", line 220, in __init__
>    self._init_from_vals(val, val2, format, scale, copy)
>  File "/usr/local/lib/python2.7/dist-packages/astropy/time/core.py", line 262, in _init_from_vals
>    self._time = self._get_time_fmt(val, val2, format, scale)
>  File "/usr/local/lib/python2.7/dist-packages/astropy/time/core.py", line 306, in _get_time_fmt
>    raise ValueError('Input values did not match {0}'.format(err_msg))
>ValueError: Input values did not match any of the formats where the format keyword is optional [u'datetime', u'iso', u'isot', u'yday', u'fits', u'byear_str', u'jyear_str']

I am running Ubuntu 14.04.
Python is version '2.7.6 (default, Jun 22 2015, 17:58:13) \n[GCC 4.8.2]'.
Numpy is version '1.10.4' (auto-installed as a dependency via pip).
Astropy is version u'1.1.1' (installed via pip).

I saw this thread: #4161 , but it was from September 2015, and the problem was with a dev branch, whereas I'm using the release version from pip. Do I have to switch to a dev branch to fix this? Or downgrade back to 0.4.1? (Shame, the functionality I wanted was in 1.1.1).

**Comment by nhurleywalker** [comment]
Fixed by totally uninstalling and reinstalling astropy. Some kind of pip issue, I guess.
