### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy#4695]
When I merged #4689, it apparently caused the overall build to fail despite all checks passing for that contribution.  Form travis, it looks like the 'build_sphinx -w' option is failing and from what I can tell it is due to: 

    /home/travis/build/astropy/astropy/docs/wcs/index.rst:237: WARNING: Exception occurred in plotting index-1
    from /home/travis/build/astropy/astropy/docs/wcs/index.rst:
    Traceback (most recent call last):
     File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in run_code
     six.exec_(code, ns)
     File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/matplotlib/externals/six.py", line 672, in exec_
     exec("""exec _code_ in _globs_, _locs_""")
     File "<string>", line 1, in <module>
     File "<string>", line 7, in <module>
     File "/home/travis/build/astropy/astropy/build/lib.linux-x86_64-2.7/astropy/utils/data.py", line 1103, in download_file
     raise urllib.error.URLError(e) 
    URLError: <urlopen error timed out>

Although if there is something else that is wrong, please let me know.  It doesn't look like it is complaining about anything from that pull request though.

**Comment by mwcraig** [comment]
I'll restart that build since the issue appears to be a timeout error.

**Comment by crawfordsm** [comment]
Sorry, I should have mentioned I tried that.  Is there a good way to know what is causing the time out to check on that?

**Comment by mwcraig** [comment]
Not sure...I am able to download the file needed for that sphinx plot without a problem.

**Comment by mwcraig** [comment]
In any event, third time is the charm for that test, apparently. It passed, so closing....
