### ISSUE TITLE
IPAC ascii table read errors

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#4749]
A colleague of mine is getting errors from the [astropy.io.ascii.Ipac] (http://docs.astropy.org/en/latest/api/astropy.io.ascii.Ipac.html) reader.

This one works:
```
$ cat testipac2.dat 
|  ID|energy|energy_edge_lo|energy_edge_hi|           flux|  flux_error_lo|  flux_error_hi|
|long|double|        double|        double|         double|         double|         double|
|    |   TeV|           TeV|           TeV|1 / (cm2 s TeV)|1 / (cm2 s TeV)|1 / (cm2 s TeV)|
    0 0.1804        0.01529        0.04709     	 6.654e-10     	 8.112e-11     	 8.066e-11 

$ python -c 'from astropy.io import ascii; ascii.read("testipac2.dat", format="ipac")'
```

This one looks the same, but fails with an error message that isn't very helpful:
```
$ cat testipac3.dat 
|  ID|energy|energy_edge_lo|energy_edge_hi|	      flux|  flux_error_lo|  flux_error_hi|
|long|double|        double|        double|         double|         double|         double|
|    |   TeV|           TeV|           TeV|1 / (cm2 s TeV)|1 / (cm2 s TeV)|1 / (cm2 s TeV)|
    0 0.1804        0.01529        0.04709     	 6.654e-10     	 8.112e-11     	 8.066e-11 

$ python -c 'from astropy.io import ascii; ascii.read("testipac3.dat", format="ipac")'
Traceback (most recent call last):
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/astropy-1.2.dev14786-py3.5-macosx-10.11-x86_64.egg/astropy/io/ascii/core.py", line 934, in _convert_vals
    converter_func, converter_type = col.converters[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/astropy-1.2.dev14786-py3.5-macosx-10.11-x86_64.egg/astropy/io/ascii/ui.py", line 341, in read
    dat = reader.read(table)
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/astropy-1.2.dev14786-py3.5-macosx-10.11-x86_64.egg/astropy/io/ascii/core.py", line 1169, in read
    table = self.outputter(cols, self.meta)
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/astropy-1.2.dev14786-py3.5-macosx-10.11-x86_64.egg/astropy/io/ascii/core.py", line 961, in __call__
    self._convert_vals(cols)
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/astropy-1.2.dev14786-py3.5-macosx-10.11-x86_64.egg/astropy/io/ascii/core.py", line 948, in _convert_vals
    raise ValueError('Column %s failed to convert' % col.name)
ValueError: Column flux_error_lo failed to convert
```

We tried to find the issue by making the `testipac3.dat` smaller and smaller and ended up with a different ValueError:
```
$ cat testipac.dat 
|     a |   b    | 
|double | double |

$ python -c 'from astropy.io import ascii; ascii.read("testipac.dat", format="ipac")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/astropy-1.2.dev14786-py3.5-macosx-10.11-x86_64.egg/astropy/io/ascii/ui.py", line 341, in read
    dat = reader.read(table)
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/astropy-1.2.dev14786-py3.5-macosx-10.11-x86_64.egg/astropy/io/ascii/core.py", line 1169, in read
    table = self.outputter(cols, self.meta)
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/astropy-1.2.dev14786-py3.5-macosx-10.11-x86_64.egg/astropy/io/ascii/core.py", line 968, in __call__
    meta=meta['table'])
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/astropy-1.2.dev14786-py3.5-macosx-10.11-x86_64.egg/astropy/table/table.py", line 360, in __init__
    init_func(data, names, dtype, n_cols, copy)
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/astropy-1.2.dev14786-py3.5-macosx-10.11-x86_64.egg/astropy/table/table.py", line 624, in _init_from_list
    self._init_from_cols(cols)
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/astropy-1.2.dev14786-py3.5-macosx-10.11-x86_64.egg/astropy/table/table.py", line 697, in _init_from_cols
    self._make_table_from_cols(self, newcols)
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/astropy-1.2.dev14786-py3.5-macosx-10.11-x86_64.egg/astropy/table/table.py", line 729, in _make_table_from_cols
    raise ValueError('Duplicate column names')
ValueError: Duplicate column names
```

I think the issue with `testipac3.dat` is that there's a tab.
I'm not sure what the issue with `testipac.dat` is.

@taldcroft - Is there a bug? Or is it possible / worth the effort to improve the reader to give better error messages?

**Comment by taldcroft** [comment]
@cdeil - the `testipac3.dat` file is malformed since the format is fixed-width and the spacing of the vertical `|` bars in the column names row sets the spacing for the data.  The specific failure here is when it tries to parse `-10       8.112` as a `double`.  I'll look in to improving the error message, that might be possible.

**Comment by taldcroft** [comment]
The `testipac.dat` file has a trailing whitespace on the column-specifier row, and this caused the parser to throw out that line.  This is too strict so I am putting in a PR to `rstrip()` header lines.  I don't think it would be correct to strip leading whitespace though, since the header rows should visually be aligned. 

See #4758.

**Comment by taldcroft** [comment]
With #4759 testipac3.dat now fails with:
```
ValueError: Column flux_error_lo failed to convert: invalid literal for float(): -10       8.112
```
Hopefully that would help out a bit.

**Comment by taldcroft** [comment]
Closed by #4758 and #4759.

@cdeil - feel free to re-open if you feel otherwise.

**Comment by cdeil** [comment]
Personally I'm starting to use ECSV and also recommending it to others.

But still ... thank you very much for taking the time to improve the behaviour and error message for IPAC!

**Comment by taldcroft** [comment]
> Personally I'm starting to use ECSV and also recommending it to others.

Even better!
