### ISSUE TITLE
DeprecationWarning from ipython when importing astropy

### ISSUE THREAD

**Issue by duncanmmacleod** [astropy/astropy#4780]
With `macports` installs of `python`/`ipython`/`astropy`, for a while now I've been getting a `DeprecationWarning` when importing astropy, related to something in ipython. Here is the traceback when I escalate it to an error:

```
$ python -c "import warnings; warnings.simplefilter('error', DeprecationWarning); import astropy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/__init__.py", line 284, in <module>
    from .logger import _init_log, _teardown_log
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/logger.py", line 17, in <module>
    from .utils.console import color_print
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/utils/console.py", line 29, in <module>
    from IPython import get_ipython
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core.profiledir import ProfileDir, ProfileDirError
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/profiledir.py", line 29, in <module>
    class ProfileDir(LoggingConfigurable):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/profiledir.py", line 52, in ProfileDir
    `profile` option.""",
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/traitlets/traitlets.py", line 421, in __init__
    DeprecationWarning, stacklevel=stacklevel)
DeprecationWarning: metadata {'config': True} was set from the constructor.  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
```

Can anyone offer a reason why this is, whether it has been reported before, or whether I can disable the astropy logger in some way (I just want astropy.units!)?

For the record, I have the following versions:

````
$ port installed | egrep " python27 | py27-ipython | py27-astropy " | grep "(active)"
  py27-astropy @1.1.1_2 (active)
  py27-ipython @4.1.2_0 (active)
  python27 @2.7.11_2 (active)
```

**Comment by pllim** [comment]
I cannot reproduce this on Linux, so must be a Mac-specific thing. I used dev Astropy, Python 2.7.11, and IPython 4.1.2.

**Comment by astrofrog** [comment]
@duncanmmacleod - can you try and move ``~/.ipython`` to ``~/.ipython.old`` temporarily to see if it's an issue related to something in your configuration files?

**Comment by astrofrog** [comment]
@duncanmmacleod - do you see the same warning/error if you do:

```python
from IPython import get_ipython
```

?

**Comment by duncanmmacleod** [comment]
@astrofrog::

```
$ python -c "import warnings; warnings.simplefilter('error', DeprecationWarning); from IPython import get_ipython"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core.profiledir import ProfileDir, ProfileDirError
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/profiledir.py", line 29, in <module>
    class ProfileDir(LoggingConfigurable):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/profiledir.py", line 52, in ProfileDir
    `profile` option.""",
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/traitlets/traitlets.py", line 421, in __init__
    DeprecationWarning, stacklevel=stacklevel)
DeprecationWarning: metadata {'config': True} was set from the constructor.  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
```

which confirms this isn't an astropy issue at the core.

But, moving `~/.ipython` to `~/.ipython.old` doesn't change the error, so probably not a config problem.

A bit more digging suggests the problem present [here](https://github.com/ipython/ipython/blob/rel-4.1.2/IPython/core/profiledir.py#L50) in IPython, so I can go and post this instead on ipython/ipython.

**Comment by duncanmmacleod** [comment]
This seems to be related to ipython/ipython#9288, which has been acknowledged by the ipython people. sorry for the spam here.
