### ISSUE TITLE
Cannot read gzipped CDS tables requiring a ReadMe

### ISSUE THREAD

**Issue by pkgw** [astropy/astropy#4871]
Certain data tables provided by the CDS come gzipped. For instance, [the data from McQuillan et al 2014](http://cdsarc.u-strasbg.fr/viz-bin/Cat?cat=J%2FApJS%2F211%2F24&target=http&).

It would be nice to be able to read these on-the-fly by using Python's `gzip.GzipFile` class.

However, this is not currently possible when the table's format is described in a separate `ReadMe` file. In those cases, the reader needs to know the filename of the table that it's reading in order to know what format to use. However, because it was passed a file handle, not a file name, it doesn't know this, resulting in this crash:

```
  File "/a/lib/python2.7/site-packages/astropy/io/ascii/ui.py", line 339, in read
    dat = reader.read(table)
  File "/a/lib/python2.7/site-packages/astropy/io/ascii/cds.py", line 322, in read
    return super(Cds, self).read(table)
  File "/a/lib/python2.7/site-packages/astropy/io/ascii/core.py", line 1133, in read
    self.data.get_data_lines(self.lines)
  File "/a/lib/python2.7/site-packages/astropy/io/ascii/core.py", line 708, in get_data_lines
    data_lines = self.process_lines(lines)
  File "/a/lib/python2.7/site-packages/astropy/io/ascii/cds.py", line 169, in process_lines
    if self.header.readme and self.table_name:
AttributeError: 'CdsData' object has no attribute 'table_name'
```

This can of course be worked around by just unzipping the data to disk, but it would be pretty cool to be able to avoid that.

The easiest solution might be to add an optional keyword argument to the constructor that lets you override/specify the table name. This would also be useful in case you want to rename the table data file away from the name encoded in the `ReadMe`. For instance, it could be useful to rename the files to something like `mcquillan14_ReadMe` and `mcquillan14_table1.dat.gz` if you want to have a single directory containing tables from a bunch of publications.

**Comment by fockez** [comment]
I got this problem too. We can set data_start and data_end to specify the part to read, but it's still slow. I can use seek and read to read the part first, but cannot parse the data using ReadMe file. Maybe the CDS class can be optimized or add a table_name keyword.

**Comment by fockez** [comment]
I found a solution for myself, first get_reader, then  set reader.data.table_name. It tricks.

**Comment by warrickball** [comment]
I thought I'd bump this because I've just run into the same issue and can't seem to create a workaround. Like @pkgw, I want to retrieve a gzipped CDS table using the standard call. e.g.

    from astropy.io import ascii
    remote_dir = 'ftp://cdsarc.u-strasbg.fr/pub/cats/I/239/'
    data = ascii.read(remote_dir+'hip_main.dat.gz', readme=remote_dir+'ReadMe', format='cds')

which gives the error

    Downloading ftp://cdsarc.u-strasbg.fr/pub/cats/I/239/hip_main.dat.gz
    |============================================================================================================================================================================|  14M/ 14M (100.00%)         0s
    Downloading ftp://cdsarc.u-strasbg.fr/pub/cats/I/239/ReadMe
    |============================================================================================================================================================================|  69k/ 69k (100.00%)         0s
    ---------------------------------------------------------------------------
    InconsistentTableError                    
    Traceback (most recent call last)
    <ipython-input-2-d1162705b883> in <module>()
    ----> 1 import codecs, os;__pyfile = codecs.open('''/tmp/py6914Qee''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/tmp/py6914Qee''');exec(compile(__code, ''\
    '/home/wball/work/python/astropy_gz_mwe.py''', 'exec'));

    ~/work/python/astropy_gz_mwe.py in <module>()
          5 remote_dir = 'ftp://cdsarc.u-strasbg.fr/pub/cats/I/239/'
          6 data = ascii.read(remote_dir+'hip_main.dat.gz',
    ----> 7                   readme=remote_dir+'ReadMe', format='cds')                                                                                                                                                
          8

    ~/.local/lib/python3.6/site-packages/astropy/io/ascii/ui.py in read(table, guess, **kwargs)
        383                                              ' with fast (no guessing)'})
        384         else:
    --> 385             dat = reader.read(table)
        386             _read_trace.append({'kwargs': new_kwargs,
        387                                 'Reader': reader.__class__,

    ~/.local/lib/python3.6/site-packages/astropy/io/ascii/cds.py in read(self, table)
        317                     return table
        318         else:
    --> 319             return super().read(table)

    ~/.local/lib/python3.6/site-packages/astropy/io/ascii/core.py in read(self, table)
       1153
       1154         # Get the table column definitions
    -> 1155         self.header.get_cols(self.lines)
       1156
       1157         # Make sure columns are valid

    ~/.local/lib/python3.6/site-packages/astropy/io/ascii/cds.py in get_cols(self, lines)
         85             else:
         86                 raise core.InconsistentTableError("Can't find table {0} in {1}".format(
    ---> 87                     self.data.table_name, self.readme))                                                                                                                                                    
         88
         89         found_line = False

    InconsistentTableError: Can't find table hip_main.dat.gz in ftp://cdsarc.u-strasbg.fr/pub/cats/I/239/ReadMe

As noted above, the issue could probably be fixed by somehow passing the (known) filename for the `ReadMe` as an argument but I'm not familiar enough with Astropy to try to add something just yet.

**Comment by warrickball** [comment]
I think this can be resolved by somehow allowing the user to specify the filename to look up in the specified readme. i.e. to use syntax like
````Python
from astropy.io import ascii
remote_dir = 'ftp://cdsarc.u-strasbg.fr/pub/cats/I/239/'
data = ascii.read(remote_dir+'hip_main.dat.gz', readme=remote_dir+'ReadMe', format='cds', table_name='hip_main.dat')
````
 I had a go at trying to add a keyword `table_name` to the class `Cds` (in `io/ascii/cds.py`) but I'm having a hard time working out how to then expose that argument to `ascii.read`.

A more brutal option would just be to strip `.gz` from the current name, on the assumption that CDS tables never end in `.gz` but I don't know how safe that assumption is.

**Comment by orionlee** [comment]
@pllim, I think this is a duplicate of #6549, which has been resolved.
