### ISSUE TITLE
Reading fits files using Table fails with masked columns on windows

### ISSUE THREAD

**Issue by philastrophist** [astropy/astropy#4874]
When I read this [test_fits_file.zip](https://github.com/astropy/astropy/files/261062/test_fits_file.zip) with:
```
from astropy import table
t  = table.Table.read('test_fits_file.fits')
```

I get an error related to failed masking on windows. If I run the same command on the same file on linux, the file is read correctly.

numpy version (same on both systems): 1.10.4
astropy version (same on both):  1.1.2

I use conda py27 installations and windows 10 & scientific linux

Here is the traceback:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.1\helpers\pydev\pydevd.py", line 1531, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.1\helpers\pydev\pydevd.py", line 938, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/User/Dropbox/TheFIRC3/tableio.py", line 69, in <module>
    T = get_data_fits()
  File "C:/Users/User/Dropbox/TheFIRC3/tableio.py", line 37, in get_data_fits
    t = Table.read('{}/data/merged_pacs_new_lofar.fits'.format(top), format='fits').to_pandas()
  File "C:\Users\User\Anaconda\lib\site-packages\astropy\table\table.py", line 2261, in read
    return io_registry.read(cls, *args, **kwargs)
  File "C:\Users\User\Anaconda\lib\site-packages\astropy\io\registry.py", line 344, in read
    data = reader(*args, **kwargs)
  File "C:\Users\User\Anaconda\lib\site-packages\astropy\io\fits\connect.py", line 140, in read_table_fits
    return read_table_fits(hdulist, hdu=hdu)
  File "C:\Users\User\Anaconda\lib\site-packages\astropy\io\fits\connect.py", line 158, in read_table_fits
    t[col.name].set_fill_value(col.null)
  File "C:\Users\User\Anaconda\lib\site-packages\numpy\ma\core.py", line 3536, in set_fill_value
    _fill_value[()] = target
ValueError: setting an array element with a sequence.
```

**Comment by taldcroft** [comment]
Using your debugger can you provide the values of `col.name`, `col.null`, and `target`?

**Comment by philastrophist** [comment]
`col.name == OBJID_1`
`col.null == -9223372036854775808`
`target == -9223372036854775808`
also `_fill_value` is an ndarray of `99999`

**Comment by philastrophist** [comment]
why is that bit there at all? (`_fill_value[()] = target`)

**Comment by philastrophist** [comment]
Hello??

**Comment by taldcroft** [comment]
@philastrophist - sorry for dropping off.  Those outputs don't really make a lot of sense to me.  Unfortunately I don't have a Windows setup to do any investigation, so I don't quite know how to advise you.  Maybe my only suggestion is to try reading the same file using the direct `astropy.io.fits` interface and see if you are able to isolate if the problem is there or in the `Table` conversion.

**Comment by philastrophist** [comment]
OK thanks for the tip. You can indeed read the file successfully using the `astropy.io.fits` interface but not with `astropy.table.Table.read` interface

**Comment by taldcroft** [comment]
@philastrophist - good news, that certainly narrows the problem down significantly and we now have a workaround.

**Comment by neutrinoceros** [comment]
Hi @taldcroft, I just failed to reproduce this on my own env (macOS 14 + python 3.12 installed via pyenv). I don't have access to a windows machine, but either way the ticket is so dated now that I'm not even sure it's worth keeping it open, unless we know someone who might be able to attempt an actual reproduction ? What would you advise ?

**Comment by pllim** [comment]
Okay, I ran this on Windows 10, Python 3.11, astropy 6.0.0, numpy 1.26.2. The provided file reads in fine without traceback. I don't know what is "scientific linux". I use Miniconda and pip installed the stack. I think we can close this now. Thanks for the ping, @neutrinoceros !

**Comment by neutrinoceros** [comment]
Good job, glad I could help !
