### ISSUE TITLE
search_around_sky fails for an empty list of coordinates

### ISSUE THREAD

**Issue by evertrol** [astropy/astropy#4875]
When one of the coordinates lists passed to `search_around_sky` is empty (length zero), the routine fails. It would be more appropriate to return empty lists of indices and distances.

Example (current astropy master):

``` python
>>> from astropy.coordinates import SkyCoord, search_around_sky
>>> from astropy import units
>>> c1 = SkyCoord(ra=[], dec=[], unit=units.deg)
>>> c2 = SkyCoord(ra=[0], dec=[0], unit=units.deg)
>>> search_around_sky(c1, c2, 1*units.deg)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/astropy-1.2.dev15081-py3.5-macosx-10.11-x86_64.egg/astropy/coordinates/matching.py", line 333, in search_around_sky
    kdt1 = _get_cartesian_kdtree(ucoords1, storekdtree)
  File "/usr/local/lib/python3.5/site-packages/astropy-1.2.dev15081-py3.5-macosx-10.11-x86_64.egg/astropy/coordinates/matching.py", line 435, in _get_cartesian_kdtree
    kdt = KDTree(flatxyz.value.T)
  File "scipy/spatial/ckdtree.pyx", line 495, in scipy.spatial.ckdtree.cKDTree.__init__ (scipy/spatial/ckdtree.cxx:5441)
  File "/usr/local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 2268, in amax
    out=out, keepdims=keepdims)
  File "/usr/local/lib/python3.5/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by pllim** [comment]
Hmm. Didn't expect someone to create a `SkyCoord` without RA and DEC. What would be a use case for that?

**Comment by evertrol** [comment]
This can easily in automated scripts. Much less likely in interactive sessions.
An astroquery table or similar might be empty, but a script would create a set of coordinates of the empty RA and Dec columns anyway.

It's obviously possible to have have an `if` statement before matching, but it'd be nicer if that is abstracted away in the interface. Empty array or list indices can still be used in numpy arrays for indexing (simply returning an empty array).
