### ISSUE TITLE
Test failures with remote_data=True

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#4896]
Someone should turn on `remote_data` and do a test before 1.2 release. I get the following failures on my machine (the last one cracks me up):

```python
================================== FAILURES ===================================
___________________ test_database_specify[ngc 3642-db_dict0] ___________________

name = 'ngc 3642'
db_dict = {'all': '# ngc3642    #Q22523722
#=S=Simbad (via url):    1
%@ 503952
%I.0 NGC 3642
%C.0 LIN
%C.N0 15.15.01.00
%J 170....V=VizieR (local):    1
%J 170.56 +59.08 = 11:22.2     +59:05
%I.0 {NGC} 3642



#====Done (2013-Feb-12,16:37:42z)===='}

    @remote_data
    @pytest.mark.parametrize(("name", "db_dict"), [('ngc 3642', _cached_ngc3642),
                                                   ('castor', _cached_castor)])
    def test_database_specify(name, db_dict):
        # First check that at least some sesame mirror is up
        for url in sesame_url.get():
            if urllib.request.urlopen(url).getcode() == 200:
                break
        else:
            pytest.skip("All SESAME mirrors appear to be down, skipping "
                        "test_name_resolve.py:test_database_specify()...")
    
        for db in db_dict.keys():
            with sesame_database.set(db):
                try:
                    icrs = SkyCoord.from_name(name)
                except NameResolveError:
>                   ra, dec = db_dict[db]
E                   ValueError: too many values to unpack

.../astropy/coordinates/tests/test_name_resolve.py:160: ValueError___________________ test_database_specify[ngc 3642-db_dict0] ___________________

name = 'ngc 3642'
db_dict = {'all': '# ngc3642    #Q22523722\n#=S=Simbad (via url):    1\n%@ 503952\n%I.0 NGC 3642\n%C.0 LIN\n%C.N0 15.15.01.00\n%...eR (local):    1\n%J 170.56 +59.08 = 11:22.2     +59:05\n%I.0 {NGC} 3642\n\n\n\n#====Done (2013-Feb-12,16:37:42z)===='}

    @remote_data
    @pytest.mark.parametrize(("name", "db_dict"), [('ngc 3642', _cached_ngc3642),
                                                   ('castor', _cached_castor)])
    def test_database_specify(name, db_dict):
        # First check that at least some sesame mirror is up
        for url in sesame_url.get():
            if urllib.request.urlopen(url).getcode() == 200:
                break
        else:
            pytest.skip("All SESAME mirrors appear to be down, skipping "
                        "test_name_resolve.py:test_database_specify()...")
    
        for db in db_dict.keys():
            with sesame_database.set(db):
                try:
                    icrs = SkyCoord.from_name(name)
                except NameResolveError:
>                   ra, dec = db_dict[db]
E                   ValueError: too many values to unpack

.../astropy/coordinates/tests/test_name_resolve.py:160: ValueError
_____________________ test_constellations_with_nameresolve _____________________

    @remote_data
    def test_constellations_with_nameresolve():
        assert SkyCoord.from_name('And I').get_constellation(short_name=True) == 'And'
    
        #you'd think "And ..." should be in Andromeda.  But you'd be wrong.
        assert SkyCoord.from_name('And VI').get_constellation() == 'Pegasus'
    
        #maybe it's because And VI isn't really a galaxy?
        assert SkyCoord.from_name('And XXII').get_constellation() == 'Pisces'
        assert SkyCoord.from_name('And XXX').get_constellation() == 'Cassiopeia'
        #ok maybe not
    
        #ok, but at least some of the others do make sense...
        assert SkyCoord.from_name('Coma Cluster').get_constellation(short_name=True) == 'Com'
>       assert SkyCoord.from_name('UMa II').get_constellation() == 'Ursa Major'

.../astropy/coordinates/tests/test_sky_coord.py:1162: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.../astropy/coordinates/sky_coordinate.py:1174: in from_name
    icrs_coord = get_icrs_coordinates(name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'UMa II'

    def get_icrs_coordinates(name):
        """
        Retrieve an ICRS object by using an online name resolving service to
        retrieve coordinates for the specified name. By default, this will
        search all available databases until a match is found. If you would like
        to specify the database, use the science state
        ``astropy.coordinates.name_resolve.sesame_database``. You can also
        specify a list of servers to use for querying Sesame using the science
        state ``astropy.coordinates.name_resolve.sesame_url``. This will try
        each one in order until a valid response is returned. By default, this
        list includes the main Sesame host and a mirror at vizier.  The
        configuration item `astropy.utils.data.Conf.remote_timeout` controls the
        number of seconds to wait for a response from the server before giving
        up.
    
        Parameters
        ----------
        name : str
            The name of the object to get coordinates for, e.g. ``'M42'``.
    
        Returns
        -------
        coord : `astropy.coordinates.ICRS` object
            The object's coordinates in the ICRS frame.
    
        """
    
        database = sesame_database.get()
        # The web API just takes the first letter of the database name
        db = database.upper()[0]
    
        # Make sure we don't have duplicates in the url list
        urls = []
        domains = []
        for url in sesame_url.get():
            domain = urllib.parse.urlparse(url).netloc
    
            # Check for duplicates
            if domain not in domains:
                domains.append(domain)
    
                # Add the query to the end of the url, add to url list
                fmt_url = os.path.join(url, "{db}?{name}")
                fmt_url = fmt_url.format(name=urllib.parse.quote(name), db=db)
                urls.append(fmt_url)
    
        for url in urls:
            try:
                # Retrieve ascii name resolve data from CDS
                resp = urllib.request.urlopen(url, timeout=data.conf.remote_timeout)
                resp_data = resp.read()
                break
            except urllib.error.URLError as e:
                # This catches a timeout error, see:
                #   http://stackoverflow.com/questions/2712524/handling-urllib2s-timeout-python
                if isinstance(e.reason, socket.timeout):
                    # If it was a timeout, try with the next URL
                    continue
                else:
                    raise NameResolveError(
                        "Unable to retrieve coordinates for name '{0}'; "
                        "connection timed out".format(name))
            except socket.timeout:
                # There are some cases where urllib2 does not catch socket.timeout
                # especially while receiving response data on an already previously
                # working request
                raise NameResolveError(
                    "Unable to retrieve coordinates for name '{0}'; connection "
                    "timed out".format(name))
    
        # All Sesame URL's timed out...
        else:
            raise NameResolveError("All Sesame queries timed out. Unable to "
                                   "retrieve coordinates.")
    
        ra, dec = _parse_response(resp_data)
    
        if ra is None and dec is None:
            if db == "A":
                err = "Unable to find coordinates for name '{0}'".format(name)
            else:
                err = "Unable to find coordinates for name '{0}' in database {1}"\
                      .format(name, database)
    
>           raise NameResolveError(err)
E           NameResolveError: Unable to find coordinates for name 'UMa II'

.../astropy/coordinates/name_resolve.py:173: NameResolveError
___________________ TestFileFunctions.test_open_nonexistent ____________________

self = <astropy.io.fits.tests.test_core.TestFileFunctions object at 0x7f6b58687cd0>

    def test_open_nonexistent(self):
        """Test that trying to open a non-existent file results in an
            IOError (and not some other arbitrary exception).
            """
    
        try:
            fits.open(self.temp('foobar.fits'))
        except IOError as e:
>           assert 'No such file or directory' in str(e)
E           assert 'No such file or directory' in "[Errno 2] Datei oder Verzeichnis nicht gefunden: '/tmp/fits-test-Y2tDbp/foobar.fits'"
E            +  where "[Errno 2] Datei oder Verzeichnis nicht gefunden: '/tmp/fits-test-Y2tDbp/foobar.fits'" = str(IOError(2, 'Datei oder Verzeichnis nicht gefunden'))

.../astropy/io/fits/tests/test_core.py:598: AssertionError
======= 4 failed, 9850 passed, 73 skipped, 42 xfailed in 262.66 seconds ========
1
```

**Comment by bsipocz** [comment]
hmm, I saw the coordinates ones before (there is also an issue somewhere), and started to have a look, but didn't have time to get anywhere with the fix.

**Comment by astrofrog** [comment]
What? Why is there an error message in German? 🇩🇪

**Comment by pllim** [comment]
ich weiß es nicht ¯\_(ツ)_/¯

**Comment by pllim** [comment]
By the way, my locale is:
```
> echo $LANG
en_US.UTF-8
```

**Comment by eteq** [comment]
There's actually two problems in the first two name resolve errors: one is that the "real" error is hidden (see #4925), and the second is whatever the underlying error is (hard to diagnose without #4925).  But I see the same.

The last two are baffling, though.  I have no idea what's up with the :de:... But the other one is especially strange because it works *fine* for me - just tried right now. 

I wonder if it's a network thing?  I've seen hints of this before where sesame name resolve calls seem to go to different servers depending on where you are, and they aren't always synced.  But that's strange given that @pllim and I should be on very similar networks, as we're in the same city... As a wild guess, @pllim, did you do this from a computer *inside* the STScI network?  Can you try from outside the network if so (or inside the network if not)?

**Comment by pllim** [comment]
@eteq , it was done on RHEL6 64-bit, Python 2, Anaconda, internal network.

Regarding the non-German error that you didn't get (I assume you're talking about "UMa II"), did you do your test on Python 3? If so, could it be a `unicode_literals` thing? I recently run into troubles with that import in my other projects.

I cannot hook this RHEL6 on external network, but I can try that on a Windows laptop...

**Comment by pllim** [comment]
Update: No luck on my Windows laptop. I get "Python has stopped working" at `io/fits/test_checksum.py`... :see_no_evil:

**Comment by pllim** [comment]
Back to my Linux machine, using #4925.

This is what I get when running `astropy.test(remote_data=True)` in a Python session (not IPython) that is started outside of the source directory (3 errored tests): 
[astropy_test_err.txt](https://github.com/astropy/astropy/files/266915/astropy_test_err.txt)

This is what I get when running `python setup.py test --remote-data` from the source directory (4 errorred tests): 
[astropy_test_err_codedir.txt](https://github.com/astropy/astropy/files/266917/astropy_test_err_codedir.txt)

**Comment by MSeifert04** [comment]
> I get "Python has stopped working" at io/fits/test_checksum.py... :see_no_evil:

I can confirm this.

**Comment by pllim** [comment]
I still don't know why my FITS test error message is not in English, because it is English when I try to open a non-existing file manually:

```python
Python 2.7.11 |Anaconda 2.3.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import astropy
>>> astropy.__version__
u'1.2.dev15333'
>>> from astropy.io import fits
>>> fits.open('/tmp/nosuchfile.fits')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../astropy/io/fits/hdu/hdulist.py", line 139, in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, cache, **kwargs)
  File ".../astropy/io/fits/hdu/hdulist.py", line 281, in fromfile
    save_backup=save_backup, cache=cache, **kwargs)
  File ".../astropy/io/fits/hdu/hdulist.py", line 802, in _readfrom
    ffo = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File ".../astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, clobber)
  File ".../astropy/io/fits/file.py", line 502, in _open_filename
    self._file = fileobj_open(self.name, PYFITS_MODES[mode])
  File ".../astropy/io/fits/util.py", line 403, in fileobj_open
    return open(filename, mode)
IOError: [Errno 2] No such file or directory: '/tmp/nosuchfile.fits'
```

**Comment by pllim** [comment]
In my Python 3 environment, it is even more bizzare... It just stops half-way with no error whatsoever and returns to prompt: 
[astropy_test_py3_codedir.txt](https://github.com/astropy/astropy/files/266973/astropy_test_py3_codedir.txt)

**Comment by pllim** [comment]
Update: Okay, at least there is an explanation for Python 3 when I run the test manually, which has nothing to do with remote data, but something about "MKL".

```python
>>> from astropy.modeling.tests.test_constraints import TestNonLinearConstraints
>>> t = TestNonLinearConstraints()
>>> t.setup_class()
>>> t.test_fixed_par()
Intel MKL FATAL ERROR: Cannot load libmkl_mc3.so or libmkl_def.so.
```

**Comment by MSeifert04** [comment]
@pllim If you are using conda make sure you update your mkl. They had a bugfix release today. At least on my computer your example works fine. (using mkl 11.3.3 build **1**)

**Comment by pllim** [comment]
Just to make sure that all the errors I am seeing locally are not just my German-loving machine, I enabled `--remote-data` on my branch based on #4925. There are still failures -- https://travis-ci.org/pllim/astropy/builds/130842940

I don't know whether they are supposed to fail or not. If so, they should be marked as `xfail`. At the very least, the one with `ImportError: No module named 'jplephem'` should be marked as optional like how we do with stuff that depends on `scipy`.

**Comment by pllim** [comment]
Here is another try with `--remote-data`, as above.

Travis CI: https://travis-ci.org/pllim/astropy/builds/130850347

Appveyor: https://ci.appveyor.com/project/pllim/astropy/build/job/gdk0wjsq0djrvfa6

**Comment by bsipocz** [comment]
I see the same mkl issue as @pllim  above in a conda py3.5 env with v1.1.2 astropy. The mkl version is 11.3.1., however I tried to install and use a patched numpy 1.11 (adding only one feature not yet merged to the released 1.11.0). Some modules can be imported, while others fail:

```
In [1]: from astropy.table import Table, Column, join, vstack, hstack

In [2]: from astropy.coordinates import SkyCoord
Intel MKL FATAL ERROR: Cannot load libmkl_mc3.so or libmkl_def.so.
```

**Comment by pllim** [comment]
Update: The German error message is gone using #4955 (thanks, @saimn!). So, I rebased that PR against `master` and ran the remote data tests again.

Here is the result using `setup.py test --remote-data` locally:
[errmsg.txt](https://github.com/astropy/astropy/files/279908/errmsg.txt)

Here is the result from Travis CI: https://travis-ci.org/pllim/astropy/builds/132605139

Here is the result from Appveyor CI (looks like linking is unreliable, so I attach the log file here): 
[appveyorlog.txt](https://github.com/astropy/astropy/files/280005/appveyorlog.txt). This is similar with Linux results, except for a socket timeout test in `test_api_lookup`.

My recommendations for failed remote data tests:

* Update tests to reflect whatever changed to the results that caused "too many values to unpack" and MJD comparison error.
* Either disable `doctest` for `get_moon` or mark it to only run if `jplephem` is installed.
* For Windows, mark `test_api_lookup` as `skipif` or `xfail`, unless someone knows how to fix it. This failure either was caused by temporary latency or a real problem that prevents Windows from finding the file. I have no time to investigate further.

**Comment by astrofrog** [comment]
Fixed by https://github.com/astropy/astropy/pull/4955 - thanks @saimn!

**Comment by pllim** [comment]
Wait... #4955 only fixed the German one. What about the others?

**Comment by astrofrog** [comment]
@eteq - I'm still seeing this on master (systematically, not intermittently):

```
__________________ test_database_specify[ngc 3642-db_dict0] ___________________

name = 'ngc 3642'
db_dict = {'all': '# ngc3642    #Q22523722\n#=S=Simbad (via url):    1\n%@ 503952\n%I.0 NGC 3642\n%C.0 LIN\n%C.N0 15.15.01.00\n%...eR (local):    1\n%J 170.56 +59.08 = 11:22.2     +59:05\n%I.0 {NGC} 3642\n\n\n\n#====Done (2013-Feb-12,16:37:42z)===='}

    @remote_data
    @pytest.mark.parametrize(("name", "db_dict"), [('ngc 3642', _cached_ngc3642),
                                                   ('castor', _cached_castor)])
    def test_database_specify(name, db_dict):
        # First check that at least some sesame mirror is up
        for url in sesame_url.get():
            if urllib.request.urlopen(url).getcode() == 200:
                break
        else:
            pytest.skip("All SESAME mirrors appear to be down, skipping "
                        "test_name_resolve.py:test_database_specify()...")
    
        for db in db_dict.keys():
            with sesame_database.set(db):
>               icrs = SkyCoord.from_name(name)

astropy/coordinates/tests/test_name_resolve.py:157: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astropy/coordinates/sky_coordinate.py:1254: in from_name
    icrs_coord = get_icrs_coordinates(name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'ngc 3642'

    def get_icrs_coordinates(name):
        """
        Retrieve an ICRS object by using an online name resolving service to
        retrieve coordinates for the specified name. By default, this will
        search all available databases until a match is found. If you would like
        to specify the database, use the science state
        ``astropy.coordinates.name_resolve.sesame_database``. You can also
        specify a list of servers to use for querying Sesame using the science
        state ``astropy.coordinates.name_resolve.sesame_url``. This will try
        each one in order until a valid response is returned. By default, this
        list includes the main Sesame host and a mirror at vizier.  The
        configuration item `astropy.utils.data.Conf.remote_timeout` controls the
        number of seconds to wait for a response from the server before giving
        up.
    
        Parameters
        ----------
        name : str
            The name of the object to get coordinates for, e.g. ``'M42'``.
    
        Returns
        -------
        coord : `astropy.coordinates.ICRS` object
            The object's coordinates in the ICRS frame.
    
        """
    
        database = sesame_database.get()
        # The web API just takes the first letter of the database name
        db = database.upper()[0]
    
        # Make sure we don't have duplicates in the url list
        urls = []
        domains = []
        for url in sesame_url.get():
            domain = urllib.parse.urlparse(url).netloc
    
            # Check for duplicates
            if domain not in domains:
                domains.append(domain)
    
                # Add the query to the end of the url, add to url list
                fmt_url = os.path.join(url, "{db}?{name}")
                fmt_url = fmt_url.format(name=urllib.parse.quote(name), db=db)
                urls.append(fmt_url)
    
        for url in urls:
            try:
                # Retrieve ascii name resolve data from CDS
                resp = urllib.request.urlopen(url, timeout=data.conf.remote_timeout)
                resp_data = resp.read()
                break
            except urllib.error.URLError as e:
                # This catches a timeout error, see:
                #   http://stackoverflow.com/questions/2712524/handling-urllib2s-timeout-python
                if isinstance(e.reason, socket.timeout):
                    # If it was a timeout, try with the next URL
                    continue
                else:
                    raise NameResolveError(
                        "Unable to retrieve coordinates for name '{0}'; "
                        "connection timed out".format(name))
            except socket.timeout:
                # There are some cases where urllib2 does not catch socket.timeout
                # especially while receiving response data on an already previously
                # working request
                raise NameResolveError(
                    "Unable to retrieve coordinates for name '{0}'; connection "
                    "timed out".format(name))
    
        # All Sesame URL's timed out...
        else:
            raise NameResolveError("All Sesame queries timed out. Unable to "
                                   "retrieve coordinates.")
    
        ra, dec = _parse_response(resp_data)
    
        if ra is None and dec is None:
            if db == "A":
                err = "Unable to find coordinates for name '{0}'".format(name)
            else:
                err = "Unable to find coordinates for name '{0}' in database {1}"\
                      .format(name, database)
    
>           raise NameResolveError(err)
E           astropy.coordinates.name_resolve.NameResolveError: Unable to find coordinates for name 'ngc 3642' in database vizier

astropy/coordinates/name_resolve.py:173: NameResolveError
```

**Comment by eteq** [comment]
@pllim - can you check if #5048 and any other changes in the meantime may have fixed this for you?  If so, feel free to close.

**Comment by pllim** [comment]
Still have **TWO** failures on my machine:

```
...

Platform: Linux-2.6.32-642.el6.x86_64-x86_64-with-redhat-6.8-Santiago

Executable: /home/lim/anaconda/bin/python

Full Python Version: 
2.7.11 |Anaconda 2.3.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

encodings: sys: ascii, locale: UTF-8, filesystem: UTF-8, unicode bits: 20
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.11.0
Scipy: 0.17.1
Matplotlib: 1.5.1
h5py: 2.5.0
Pandas: 0.18.0
Using Astropy options: remote_data.

rootdir: /tmp/astropy-test-LAHrY6, inifile: setup.cfg
plugins: cov-2.2.1, json-0.4.0
collected 11330 items 

...

================================================================================================== FAILURES ===================================================================================================
__________________________________________________________________________________________ TestIERS_Auto.test_simple __________________________________________________________________________________________

self = <astropy.utils.iers.tests.test_iers.TestIERS_Auto instance at 0x7ff664385638>

    @remote_data
    def test_simple(self):
        iers_a_file_1 = os.path.join(os.path.dirname(__file__), 'finals2000A-2016-02-30-test')
        iers_a_file_2 = os.path.join(os.path.dirname(__file__), 'finals2000A-2016-04-30-test')
        iers_a_url_1 = 'file://' + os.path.abspath(iers_a_file_1)
        iers_a_url_2 = 'file://' + os.path.abspath(iers_a_file_2)
    
        iers.conf.iers_auto_url = iers_a_url_1
    
        dat = iers.IERS_Auto.open()
>       assert dat['MJD'][0] == 57359.0 * u.d
E       assert <Quantity 41684.0 d> == (57359.0 * Unit("d"))
E        +  where Unit("d") = u.d

astropy/utils/iers/tests/test_iers.py:164: AssertionError
_________________________________________________________________________________ [doctest] docs/coordinates/solarsystem.rst __________________________________________________________________________________
043 
044 Above, we used ``solar_system_ephemeris`` as a context, which sets the default
045 ephemeris while in the ``with`` clause, and resets it at the end.
046 
047 To get more precise positions, one could use the ``de430`` ephemeris mentioned
048 above, but between 1950 and 2050 one could also opt for the ``de432s``
049 ephemeris, which is stored in a smaller, ~10 MB, file (which will be
050 downloaded and cached when the ephemeris is set).::
051 
052   >>> solar_system_ephemeris.set('de432s') # doctest: +REMOTE_DATA, +IGNORE_OUTPUT
UNEXPECTED EXCEPTION: ImportError(u'Solar system JPL ephemeris calculations require the jplephem package (https://pypi.python.org/pypi/jplephem)',)
Traceback (most recent call last):

  File "/home/lim/anaconda/lib/python2.7/doctest.py", line 1315, in __run
    compileflags, 1) in test.globs

  File "<doctest solarsystem.rst[7]>", line 1, in <module>

  File "astropy/utils/state.py", line 64, in set
    value = cls.validate(value)

  File "astropy/coordinates/solar_system.py", line 114, in validate
    cls.get_kernel(value)

  File "astropy/coordinates/solar_system.py", line 125, in get_kernel
    kernel = _get_kernel(value)

  File "astropy/coordinates/solar_system.py", line 170, in _get_kernel
    raise ImportError("Solar system JPL ephemeris calculations require "

ImportError: Solar system JPL ephemeris calculations require the jplephem package (https://pypi.python.org/pypi/jplephem)

/tmp/astropy-test-LAHrY6/docs/coordinates/solarsystem.rst:52: UnexpectedException
====================================================================== 2 failed, 11198 passed, 88 skipped, 42 xfailed in 296.14 seconds =======================================================================
```

**Comment by astrofrog** [comment]
The second is because you need jplephem installed. The first, not sure!

**Comment by eteq** [comment]
@mhvk or @taldcroft - any idea on the *first* error in https://github.com/astropy/astropy/issues/4896#issuecomment-224959259 (it's in `IERSAuto`) - my hunch is that it's something like just a not up-to-date IERS file, but would be good to know..

**Comment by pllim** [comment]
The test should be *skipped* if `jplephem` is not installed, not failed, since that is an *optional* dependency?

**Comment by astrofrog** [comment]
@pllim - ah yes, indeed! I'll fix that directly in master and will backport to 1.2.x

**Comment by taldcroft** [comment]
@eteq @mhvk  - argh.  It *did* work when the PR was merged.  Could the IERS-B update have had an impact?  I'm investigating now.

**Comment by taldcroft** [comment]
Oddly I get a failure in a slightly different place:
```
============================================ FAILURES ============================================
___________________________________ TestIERS_Auto.test_simple ____________________________________

self = <astropy.utils.iers.tests.test_iers.TestIERS_Auto instance at 0x7f864c611488>

    @remote_data
    def test_simple(self):
        iers_a_file_1 = os.path.join(os.path.dirname(__file__), 'finals2000A-2016-02-30-test')
        iers_a_file_2 = os.path.join(os.path.dirname(__file__), 'finals2000A-2016-04-30-test')
        iers_a_url_1 = 'file://' + os.path.abspath(iers_a_file_1)
        iers_a_url_2 = 'file://' + os.path.abspath(iers_a_file_2)
    
        iers.conf.iers_auto_url = iers_a_url_1
    
        dat = iers.IERS_Auto.open()
        assert dat['MJD'][0] == 57359.0 * u.d
        assert dat['MJD'][-1] == 57539.0 * u.d
    
        # Pretend we are accessing at a time 7 days after start of predictive data
        predictive_mjd = dat.meta['predictive_mjd']
        dat._time_now = Time(predictive_mjd, format='mjd') + 7 * u.d
    
        # Look at times before and after the test file begins.
>       assert np.allclose(dat.ut1_utc(Time(50000, format='mjd').jd).value, 0.0262719)
E       assert <function allclose at 0x7f8656d4a230>(0.1292905, 0.0262719)
E        +  where <function allclose at 0x7f8656d4a230> = np.allclose
E        +  and   0.1292905 = <Quantity 0.1292905 s>.value
E        +    where <Quantity 0.1292905 s> = <bound method IERS_Auto.ut1_utc of <IERS_Auto length=181>\n year month  day    ...   16     7    30 57539.0           P ...        P 0.214232 0.442454         P>(2450000.5)
E        +      where <bound method IERS_Auto.ut1_utc of <IERS_Auto length=181>\n year month  day    ...   16     7    30 57539.0           P ...        P 0.214232 0.442454         P> = <IERS_Auto length=181>\n year month  day    MJD   PolPMFlag_A ... UT1Flag    PM...\n   16     7    30 57539.0           P ...        P 0.214232 0.442454         P.ut1_utc
E        +      and   2450000.5 = <Time object: scale='utc' format='mjd' value=50000.0>.jd
E        +        where <Time object: scale='utc' format='mjd' value=50000.0> = Time(50000, format='mjd')

astropy/utils/iers/tests/test_iers.py:172: AssertionError
```

**Comment by pllim** [comment]
I tested it in Python 2.7 with latest master, if it makes a difference.

**Comment by taldcroft** [comment]
See #5051 for IERS fix.

**Comment by astrofrog** [comment]
@pllim - can you confirm that everything is fixed on the latest master? (see #5072)

**Comment by pllim** [comment]
I can't test till Monday. If I'm holding up the release, just forge ahead. We can figure this out later if needed. Thanks!

**Comment by pllim** [comment]
Yes, IERS tests finally pass. Thanks! 

However, one Cone Search test is failing because some services are down (beyond my control) :sweat_smile: -- Do you want me to open a PR for this marking it as `xfail` or something?

```
_________ TestConeSearch.test_async_all ___________
self = <astropy.vo.client.tests.test_conesearch.TestConeSearch object at 0x7fcc6c82fdd0>

    def test_async_all(self):
        async_search_all = conesearch.AsyncSearchAll(
            SCS_CENTER, SCS_RADIUS, pedantic=self.pedantic)
    
        all_results = async_search_all.get(timeout=(data.conf.remote_timeout * 3))
    
>       assert async_search_all.done()
E       assert <bound method Future.done of <Future at 0x7fcc6c4f6790 state=running>>()
E        +  where <bound method Future.done of <Future at 0x7fcc6c4f6790 state=running>> = <astropy.vo.client.conesearch.AsyncSearchAll object at 0x7fcc6c8ce890>.done

astropy/vo/client/tests/test_conesearch.py:163: AssertionError
======= 1 failed, 11204 passed, 88 skipped, 42 xfailed in 430.89 seconds ======
```

**Comment by eteq** [comment]
@pllim - hmm, I'm not currently getting that error, so my *guess* is that it's a transient one (unstable server).  Might make sense to update the docstring to note that this particular test sometimes fails on the server-side... But in general we've been taking the view that it's better to have remote tests that fail sometimes for reasons outside our control than not have them get tested at all.  

So I'd say we just leave the test as-is, and only ``@mark.xfail`` or remove it if we can determine that it's *definitely* permanently down.

Another option is to try to figure out how to recognize that the test failed due to a server problem, and then do an in-line ``pytest.xfail()`` (although maybe that's what you meant now that I think about it?).  But I've had lots of problems reliably catching those sort of errors, so I think it's not critical unless you can easily figure out how to do it.

**Comment by bsipocz** [comment]
@eteq - I think it's easy to measure the execution time of the line ``all_results = ...``, and if it's longer than the timeout xfail the test?

**Comment by pllim** [comment]
Okay, closing this now. We can open a new issue about Cone Search async test being unstable if needed. Thanks, everyone!
