### ISSUE TITLE
Macports Python 2.7 LookupError: unknown encoding test error

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#4951]
I'm getting a few test collection errors from matplotlib like this:

```
______________________________________________ ERROR collecting lib.macosx-10.11-x86_64-2.7/astropy/units/tests/test_quantity.py _______________________________________________
astropy/units/tests/test_quantity.py:30: in <module>
    import matplotlib.pyplot as plt
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/pyplot.py:30: in <module>
    from matplotlib import style
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/style/__init__.py:3: in <module>
    from .core import use, context, available, library, reload_library
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/style/core.py:190: in <module>
    _base_library = load_base_library()
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/style/core.py:135: in load_base_library
    library.update(read_style_directory(BASE_LIBRARY_PATH))
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/style/core.py:168: in read_style_directory
    styles[name] = rc_params_from_file(path, use_default_template=False)
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py:1101: in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py:1018: in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py:17: in __enter__
    return self.gen.next()
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py:1003: in _open_file_or_url
    with io.open(fname, encoding=encoding) as f:
E   LookupError: unknown encoding:
```

And one test fail:

```

093     >>> quantity_support()  # doctest: +IGNORE_OUTPUT
094     <astropy.visualization.units.MplQuantityConverter ...>
095 
096 Then |quantity| objects can be passed to matplotlib plotting
097 functions.  The axis labels are automatically labeled with the unit of
098 the quantity:
099 
100 .. doctest-requires:: matplotlib
101 
102     >>> from matplotlib import pyplot as plt
UNEXPECTED EXCEPTION: LookupError('unknown encoding: ',)
Traceback (most recent call last):

  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1315, in __run
    compileflags, 1) in test.globs

  File "<doctest quantity.rst[19]>", line 1, in <module>

  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/pyplot.py", line 30, in <module>
    from matplotlib import style

  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/style/__init__.py", line 3, in <module>
    from .core import use, context, available, library, reload_library

  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/style/core.py", line 190, in <module>
    _base_library = load_base_library()

  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/style/core.py", line 135, in load_base_library
    library.update(read_style_directory(BASE_LIBRARY_PATH))

  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/style/core.py", line 168, in read_style_directory
    styles[name] = rc_params_from_file(path, use_default_template=False)

  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 1101, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)

  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:

  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()

  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 1003, in _open_file_or_url
    with io.open(fname, encoding=encoding) as f:

LookupError: unknown encoding: 

/private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/astropy-test-Tv4YJR/docs/units/quantity.rst:102: UnexpectedException
```

I don't understand this.
This works fine:

```
$ python2 -c 'import matplotlib.pyplot'
```

This is my encoding (that's also mentioned in the full log at the top):

```
$ python2 -c 'import locale; print(locale.getpreferredencoding())'
UTF-8
```
Full log: https://gist.github.com/cdeil/92f0ab2d10069d56797ad1a90f4e4157

**Comment by pllim** [comment]
Would it help if you apply [PEP 263](https://www.python.org/dev/peps/pep-0263/) to `test_quantity.py`?

**Comment by cdeil** [comment]
I'm not seeing this issue any more.

With Astropy master on both Python 2 and 3 all tests pass:
https://gist.github.com/cdeil/e8fe2eafe7a686099bd2e868e855e364

Closing this issue now.

---

I don't know if there was a real issue at some point, or if this was just a mis-configuration of my system. The fact that no-one else reported the same error points towards there not being a real issue.

---

@pllim - Thanks for your suggestion how to debug this! Apologies that I didn't follow up and do it at the time.
