### ISSUE TITLE
Gallery: Obs planning plot doesn't compile

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#4996]
I got this valid looking error message during the docs build with python3. I don't have much time now to investigate further.

```
plotting code blocks in ../examples/coordinates/plot_obs-planning.py
 - time elapsed : 0.0027 sec
plotting code blocks in ../examples/coordinates/plot_obs-planning.py
 - time elapsed : 8.7e-05 sec
plotting code blocks in ../examples/coordinates/plot_obs-planning.py
 - time elapsed : 0.22 sec
plotting code blocks in ../examples/coordinates/plot_obs-planning.py
 - time elapsed : 0.0033 sec
plotting code blocks in ../examples/coordinates/plot_obs-planning.py
Downloading http://maia.usno.navy.mil/ser7/finals2000A.all [Done]
M33's Altitude = 0.13 deg
 - time elapsed : 13 sec
plotting code blocks in ../examples/coordinates/plot_obs-planning.py
 - time elapsed : 0.06 sec
plotting code blocks in ../examples/coordinates/plot_obs-planning.py
 - time elapsed : 0.0023 sec
plotting code blocks in ../examples/coordinates/plot_obs-planning.py
 - time elapsed : 0.056 sec
plotting code blocks in ../examples/coordinates/plot_obs-planning.py
________________________________________________________________________________
../examples/coordinates/plot_obs-planning.py is not compiling:
Traceback (most recent call last):
  File "/sw/lib/python3.4/site-packages/sphinx_gallery/gen_rst.py", line 467, in execute_script
    exec(code_block, example_globals)
  File "<string>", line 6, in <module>
  File "/Users/bsipocz/munka/devel/astropy/build/lib.macosx-10.10-x86_64-3.4/astropy/coordinates/sky_coordinate.py", line 403, in transform_to
    new_coord = trans(self.frame, generic_frame)
  File "/Users/bsipocz/munka/devel/astropy/build/lib.macosx-10.10-x86_64-3.4/astropy/coordinates/transformations.py", line 915, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "/Users/bsipocz/munka/devel/astropy/build/lib.macosx-10.10-x86_64-3.4/astropy/coordinates/transformations.py", line 706, in __call__
    res = self.func(fromcoord, toframe)
  File "/Users/bsipocz/munka/devel/astropy/build/lib.macosx-10.10-x86_64-3.4/astropy/coordinates/builtin_frames/intermediate_rotation_transforms.py", line 56, in gcrs_to_cirs
    crepr = cartrepr_from_matmul(pmat, gcrs_coo2)
  File "/Users/bsipocz/munka/devel/astropy/build/lib.macosx-10.10-x86_64-3.4/astropy/coordinates/builtin_frames/utils.py", line 57, in cartrepr_from_matmul
    newxyz = np.sum(pmat * xyz.reshape(xyz.size//3, 1, 3), axis=-1).T
  File "/Users/bsipocz/munka/devel/astropy/build/lib.macosx-10.10-x86_64-3.4/astropy/units/quantity.py", line 830, in __rmul__
    return self.__mul__(other)
  File "/Users/bsipocz/munka/devel/astropy/build/lib.macosx-10.10-x86_64-3.4/astropy/units/quantity.py", line 814, in __mul__
    return super(Quantity, self).__mul__(other)
ValueError: operands could not be broadcast together with shapes (1000000,1,3) (1000,3,3) 

________________________________________________________________________________
 - time elapsed : 0 sec
plotting code blocks in ../examples/coordinates/plot_obs-planning.py
 - time elapsed : 0.16 sec
plotting code blocks in ../examples/coordinates/plot_obs-planning.py
________________________________________________________________________________
../examples/coordinates/plot_obs-planning.py is not compiling:
Traceback (most recent call last):
  File "/sw/lib/python3.4/site-packages/sphinx_gallery/gen_rst.py", line 467, in execute_script
    exec(code_block, example_globals)
  File "<string>", line 2, in <module>
NameError: name 'sunaltazs_July12_to_13' is not defined

```

ping @eteq @adrn

**Comment by astrofrog** [comment]
Marking this as critical since it won't look good if we release 1.2 with a big 'broken' icon in the gallery.

**Comment by eteq** [comment]
investigating this further... it looks like it's not just an error in the example, but an actual change in `coordinates` behavior.  I'm pretty sure it was an unintended side-effect of one of the recent PRs and am investigating further.

**Comment by eteq** [comment]
and it's not python3 specific
