### ISSUE TITLE
Package missing when running setup.py install

### ISSUE THREAD

**Issue by hettlage** [astropy/astropy#5143]
When I run the setup.py script with the install option,

`python3 setup.py install`

I get the error copied below. The workaround is to install the missing package,

`pip install jinja2`

and then re-run the setup.py script.

Here is the error:

```
pre_build_py_hook command hook build_py raised an exception: %s

Traceback (most recent call last):
  File "/Users/christian/Desktop/astropy2/astropy_helpers/astropy_helpers/setup_helpers.py", line 285, in run_command_hooks
    hook_obj(cmd_obj)
  File "astropy/_erfa/setup_package.py", line 24, in pre_build_py_hook
    preprocess_source()
  File "astropy/_erfa/setup_package.py", line 85, in preprocess_source
    verbose=False)
  File "astropy/_erfa/erfa_generator.py", line 359, in main
    from jinja2 import Environment, FileSystemLoader
ImportError: No module named 'jinja2'
```

**Comment by bsipocz** [comment]
``jinja2``, as well as ``Cython`` are required dependencies when building from source. See docs here: http://docs.astropy.org/en/latest/install.html?highlight=jinja2#building-from-source

**Comment by astrofrog** [comment]
Note that the proposed solution to avoid having to manually install these dependencies is discussed in https://github.com/astropy/astropy/pull/3229#issuecomment-225816422
