### ISSUE TITLE
Failing RTD build: "No module named matrix_utilities"

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#5230]
There is build failure on RTD, though I'm not sure why it started to show up just now. Maybe a wipe and rebuild will be enough.

https://readthedocs.org/projects/astropy/builds/4284616/

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python2.7/site-packages/Sphinx-1.3.5-py2.7.egg/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python2.7/site-packages/Sphinx-1.3.5-py2.7.egg/sphinx/application.py", line 284, in build
    self.emit('build-finished', None)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python2.7/site-packages/Sphinx-1.3.5-py2.7.egg/sphinx/application.py", line 508, in emit
    results.append(callback(self, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python2.7/site-packages/sphinx_gallery/gen_gallery.py", line 209, in sumarize_failing_examples
    "\n" + "-" * 79)
ValueError: Here is a summary of the problems encountered when running the examples

Unexpected failing examples:
../examples/coordinates/plot_sgr-coordinate-frame.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python2.7/site-packages/sphinx_gallery/gen_rst.py", line 520, in execute_code_block
    exec(code_block, example_globals)
  File "<string>", line 3, in <module>
ImportError: No module named matrix_utilities


-------------------------------------------------------------------------------

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python2.7/site-packages/sphinx_gallery/gen_gallery.py", line 209, in sumarize_failing_examples
    "\n" + "-" * 79)
ValueError: Here is a summary of the problems encountered when running the examples

Unexpected failing examples:
../examples/coordinates/plot_sgr-coordinate-frame.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python2.7/site-packages/sphinx_gallery/gen_rst.py", line 520, in execute_code_block
    exec(code_block, example_globals)
  File "<string>", line 3, in <module>
ImportError: No module named matrix_utilities
``

**Comment by pllim** [comment]
Sometimes I find that I need to wipe *several* times in a row before a project would rebuild properly. FYI.

**Comment by mhvk** [comment]
Just for reference, I added `matrix_utilities` in #5104; nothing is directly imported from it. But since the travis builds pass, I guess it is indeed some kind of readthedocs issue.

**Comment by pllim** [comment]
It is failing now with new error:

```
Running Sphinx v1.3.5
making output directory...
loading translations [en]... done
loading intersphinx inventory from http://docs.python.org/2/objects.inv...
loading intersphinx inventory from http://matplotlib.org/objects.inv...
loading intersphinx inventory from http://pandas.pydata.org/pandas-docs/stable/objects.inv...
loading intersphinx inventory from http://ipython.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from http://docs.scipy.org/doc/scipy/reference/objects.inv...
loading intersphinx inventory from http://pytest.org/latest/objects.inv...
loading intersphinx inventory from http://docs.h5py.org/en/latest/objects.inv...
loading intersphinx inventory from http://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from /home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python2.7/site-packages/astropy_helpers/sphinx/local/python2_local_links.inv...
[autosummary] generating autosummary for: analytic_functions/index.rst, changelog.rst, config/config_0_4_transition.rst, config/index.rst, constants/index.rst, convolution/index.rst, convolution/kernels.rst, convolution/using.rst, coordinates/angles.rst, coordinates/definitions.rst, ..., wcs/index.rst, wcs/relax.rst, whatsnew/0.1.rst, whatsnew/0.2.rst, whatsnew/0.3.rst, whatsnew/0.4.rst, whatsnew/1.0.rst, whatsnew/1.1.rst, whatsnew/1.2.rst, whatsnew/index.rst

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python2.7/site-packages/Sphinx-1.3.5-py2.7.egg/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python2.7/site-packages/Sphinx-1.3.5-py2.7.egg/sphinx/application.py", line 189, in __init__
    self._init_builder(self.buildername)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python2.7/site-packages/Sphinx-1.3.5-py2.7.egg/sphinx/application.py", line 252, in _init_builder
    self.emit('builder-inited')
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python2.7/site-packages/Sphinx-1.3.5-py2.7.egg/sphinx/application.py", line 508, in emit
    results.append(callback(self, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python2.7/site-packages/astropy_helpers/sphinx/ext/automodsumm.py", line 252, in process_automodsumm_generation
    lines = automodsumm_to_autosummary_lines(sfn, app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python2.7/site-packages/astropy_helpers/sphinx/ext/automodsumm.py", line 316, in automodsumm_to_autosummary_lines
    filestr = automodapi_replace(fr.read(), app, True, docname, False)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python2.7/site-packages/astropy_helpers/sphinx/ext/automodapi.py", line 263, in automodapi_replace
    ispkg, hascls, hasfuncs = _mod_info(modnm, toskip, onlylocals=onlylocals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python2.7/site-packages/astropy_helpers/sphinx/ext/automodapi.py", line 359, in _mod_info
    for localnm, fqnm, obj in zip(*find_mod_objs(modname, onlylocals=onlylocals)):
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python2.7/site-packages/astropy_helpers/sphinx/ext/utils.py", line 43, in find_mod_objs
    __import__(modname)
ImportError: No module named tabular

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python2.7/site-packages/astropy_helpers/sphinx/ext/utils.py", line 43, in find_mod_objs
    __import__(modname)
ImportError: No module named tabular
The full traceback has been saved in /tmp/sphinx-err-znTI4y.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Command time: 9s Return: 1
```

@nden?

**Comment by pllim** [comment]
@astrofrog -- who has access to astropy's RTD account and can do several wipes and rebuild? If you add me, I can do it (`pllim`).

**Comment by astrofrog** [comment]
@pllim - I've just tried wiping the builds several times and am re-building. I also added you as a maintainer for future.

**Comment by astrofrog** [comment]
Ok, so what changed on the date when builds started failing is that there was a new version of sphinx-gallery released. I think what that version does is that there is now a new ``abort_on_example_error`` option or at least that it's exposed in the main sphinx config now. I'll work on a PR.
