### ISSUE TITLE
Spurious doctest failure for time

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5316]
This failure is spurious. So for whatever reason, it sometimes attempts to call a remote resource but not marked as so.

```python
=== FAILURES ===
________________________ [doctest] docs/time/index.rst _________________________
891 heliocentre.
892 
893 Suppose you observed IP Peg from Greenwich and have a list of times in MJD form, in
894 the UTC timescale. You then create appropriate |Time| and |SkyCoord| objects and
895 calculate light travel times to the barycentre as follows::
896 
897     >>> from astropy import time, coordinates as coord, units as u
898     >>> ip_peg = coord.SkyCoord("23:23:08.55", "+18:24:59.3",
899     ...                         unit=(u.hourangle, u.deg), frame='icrs')
900     >>> greenwich = coord.EarthLocation.of_site('greenwich')
UNEXPECTED EXCEPTION: IOError(u'An attempt was made to connect to the internet'
'by a test that was not marked `remote_data`.',)
Traceback (most recent call last):

  File ".../doctest.py", line 1315, in __run
    compileflags, 1) in test.globs

  File "<doctest index.rst[137]>", line 1, in <module>

  File "astropy/coordinates/earth.py", line 260, in of_site
    registry = cls._get_site_registry()

  File "astropy/coordinates/earth.py", line 400, in _get_site_registry
    reg = get_downloaded_sites()

  File "astropy/coordinates/sites.py", line 130, in get_downloaded_sites
    jsondb = json.loads(get_file_contents(jsonurl, show_progress=False))

  File "astropy/utils/data.py", line 372, in get_file_contents
    with get_readable_fileobj(*args, **kwargs) as f:

  File ".../contextlib.py", line 17, in __enter__
    return self.gen.next()

  File "astropy/utils/data.py", line 197, in get_readable_fileobj
    timeout=remote_timeout)

  File "astropy/utils/data.py", line 1030, in download_file
    remote_url, timeout=timeout)) as remote:

  File ".../urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)

  File ".../urllib2.py", line 429, in open
    response = self._open(req, data)

  File ".../urllib2.py", line 447, in _open
    '_open', req)

  File ".../urllib2.py", line 407, in _call_chain
    result = func(*args)

  File ".../urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)

  File ".../urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)

  File ".../httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)

  File ".../httplib.py", line 1097, in _send_request
    self.endheaders(body)

  File ".../httplib.py", line 1053, in endheaders
    self._send_output(message_body)

  File ".../httplib.py", line 897, in _send_output
    self.send(msg)

  File ".../httplib.py", line 859, in send
    self.connect()

  File ".../httplib.py", line 836, in connect
    self.timeout, self.source_address)

  File "astropy/tests/disable_internet.py", line 68, in new_function
    raise IOError("An attempt was made to connect to the internet "

IOError: An attempt was made to connect to the internet by a test that was not marked
`remote_data`.

/tmp/astropy-test-Z8Ec3f/docs/time/index.rst:900: UnexpectedException
```

**Comment by pllim** [comment]
Now that we have remote data test on Travis CI, this will be obvious if it happens again.
