### ISSUE TITLE
WCS doc requiring wcsaxes gives Sphinx warning

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5388]
In the absence of `wcsaxes` package being installed while building the Sphinx doc locally, I see this warning:

```
.../docs/wcs/index.rst:237: WARNING: Exception occurred in plotting index-1
 from .../docs/wcs/index.rst:
Traceback (most recent call last):
  File ".../matplotlib/sphinxext/plot_directive.py", line 517, in run_code
    six.exec_(code, ns)
  File ".../matplotlib/externals/six.py", line 672, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "<string>", line 12, in <module>
  File ".../matplotlib/figure.py", line 987, in add_subplot
    self, *args, **kwargs)
  File ".../matplotlib/projections/__init__.py", line 100,
    in process_projection_requirements
    projection_class, extra_kwargs = projection._as_mpl_axes()
  File ".../astropy/wcs/wcs.py", line 3040, in _as_mpl_axes
    raise ImportError("Using WCS instances as Matplotlib projections "
ImportError: Using WCS instances as Matplotlib projections requires the
    WCSAxes package to be installed.
    See http://wcsaxes.readthedocs.io for more details.
```

Is it possible to mark it as "skip" or something, like how `coordinates/solarsystem.rst` handles its `jplephem` dependency (but that one does not have plot directive as this one)?

**Comment by bsipocz** [comment]
Now that wcsaxes got merged, this can be closed.
