### ISSUE TITLE
python2 html table file read failure

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#5409]
I cannot read [this](http://pastebin.com/fKniVLsv) table in python2, but I can read it in python3.  I can't figure out what's going on with it.  I think one of the astropy converters is introducing the non-ascii characters?

py2 error is:
```
Table.read('table.html', format='ascii.html')
Traceback (most recent call last):
  File "<ipython-input-19-ebca79cfd76a>", line 1, in <module>
    Table.read('table.html', format='ascii.html')
  File "/Users/adam/repos/astropy/astropy/table/table.py", line 2332, in read
    return io_registry.read(cls, *args, **kwargs)
  File "/Users/adam/repos/astropy/astropy/io/registry.py", line 350, in read
    data = reader(*args, **kwargs)
  File "/Users/adam/repos/astropy/astropy/io/ascii/connect.py", line 37, in io_read
    return read(filename, format=format, **kwargs)
  File "/Users/adam/repos/astropy/astropy/io/ascii/ui.py", line 341, in read
    dat = reader.read(table)
  File "/Users/adam/repos/astropy/astropy/io/ascii/html.py", line 333, in read
    return core.BaseReader.read(self, table)
  File "/Users/adam/repos/astropy/astropy/io/ascii/core.py", line 1180, in read
    table = self.outputter(cols, self.meta)
  File "/Users/adam/repos/astropy/astropy/io/ascii/html.py", line 167, in __call__
    return super(HTMLOutputter, self).__call__(new_cols, meta)
  File "/Users/adam/repos/astropy/astropy/io/ascii/core.py", line 972, in __call__
    self._convert_vals(cols)
  File "/Users/adam/repos/astropy/astropy/io/ascii/core.py", line 959, in _convert_vals
    raise ValueError('Column {} failed to convert: {}'.format(col.name, last_err))
ValueError: Column Archive File failed to convert: 'ascii' codec can't encode characters in position 28-29: ordinal not in range(128)
```

EDIT: astropy version is `1.3.dev15963` on both py2/py3

**Comment by taldcroft** [comment]
My first guess is the file contains non ASCII characters.  Have you explicitly checked this?

**Comment by keflavich** [comment]
Yes.  There are some in that file.  They were introduced by BeautifulSoup, because the original file had none.

**Comment by keflavich** [comment]
OK, I've updated the [file](https://gist.github.com/5d311d6baa52a087cef70853b9f3a871).  This one contains no non-ascii characters, but results in the same traceback:

```
In [23]: with open('/Users/adam/repos/astroquery/astroquery/nrao/tests/data/table.html','r') as fh:
    data = fh.read()
   ....:

In [24]: any(ord(c)>=128 for c in data)
Out[24]: False

In [25]: Table.read('/Users/adam/repos/astroquery/astroquery/nrao/tests/data/table.html', format='ascii.html')
Traceback (most recent call last):
  File "<ipython-input-25-ebca79cfd76a>", line 1, in <module>
    Table.read('/Users/adam/repos/astroquery/astroquery/nrao/tests/data/table.html', format='ascii.html')
  File "/Users/adam/repos/astropy/astropy/table/table.py", line 2332, in read
    return io_registry.read(cls, *args, **kwargs)
  File "/Users/adam/repos/astropy/astropy/io/registry.py", line 350, in read
    data = reader(*args, **kwargs)
  File "/Users/adam/repos/astropy/astropy/io/ascii/connect.py", line 37, in io_read
    return read(filename, format=format, **kwargs)
  File "/Users/adam/repos/astropy/astropy/io/ascii/ui.py", line 341, in read
    dat = reader.read(table)
  File "/Users/adam/repos/astropy/astropy/io/ascii/html.py", line 333, in read
    return core.BaseReader.read(self, table)
  File "/Users/adam/repos/astropy/astropy/io/ascii/core.py", line 1180, in read
    table = self.outputter(cols, self.meta)
  File "/Users/adam/repos/astropy/astropy/io/ascii/html.py", line 167, in __call__
    return super(HTMLOutputter, self).__call__(new_cols, meta)
  File "/Users/adam/repos/astropy/astropy/io/ascii/core.py", line 972, in __call__
    self._convert_vals(cols)
  File "/Users/adam/repos/astropy/astropy/io/ascii/core.py", line 959, in _convert_vals
    raise ValueError('Column {} failed to convert: {}'.format(col.name, last_err))
ValueError: Column Archive File failed to convert: 'ascii' codec can't encode characters in position 28-29: ordinal not in range(128)
```

I suspect `BeautifulSoup` is introducing these characters within the astropy table html reader, but I'm not sure.

**Comment by saimn** [comment]
You have a column (Archive File) with non-ascii values (non-breaking spaces : ` ... \xa0\xa0 correl:13-Mar-27 14:53:54\xa0 job:4', ....`), and on Python 2 the conversion uses `numpy.str`, which fails:
```
ipdb> convert_numpy(numpy.str)[0](col.str_vals)
*** UnicodeEncodeError: 'ascii' codec can't encode characters in position 28-29: ordinal not in range(128)

ipdb> convert_numpy(numpy.unicode)[0](col.str_vals)
array([u'VLA_XH78003_file15.dat', u'VLA_XH78003_file16.dat',
       u'VLA_XH78004_file4.dat', u'VLA_XH79004_file8.dat',
       u'VLA_XH79004_file8.dat', u'VLA_XH79004_file9.dat',
       u'VLA_XH79004_file10.dat', u'VLA_XH80008_file4.dat',
....
```

Adding a converter using `numpy.unicode` for Python 2 seems a sensible solution (and it works), but maybe @taldcroft has a better idea:

```
diff --git a/astropy/io/ascii/core.py b/astropy/io/ascii/core.py
index 0365ae4..5b01a39 100644
--- a/astropy/io/ascii/core.py
+++ b/astropy/io/ascii/core.py
@@ -971,6 +971,9 @@ class TableOutputter(BaseOutputter):
                           convert_numpy(numpy.float),
                           convert_numpy(numpy.str)]

+    if six.PY2:
+        default_converters.append(convert_numpy(numpy.unicode))
+
     def __call__(self, cols, meta):
         self._convert_vals(cols)
```

**Comment by taldcroft** [comment]
@saimn - I agree and independently had the idea, though only for the HTML reader.  See #5140. 

About your idea of adding the unicode convert to all readers for Py2, for every other reader that uses the Python csv module for splitting, unicode is not supported.  So I'm not sure about making this global for all readers.

**Comment by saimn** [comment]
@taldcroft - I added the converter here just because I saw this list in pdb, so it was easy to test, but without realizing that it was common to all readers ;-). So adding it only to `HTMLOutputter` seems much better.
