### ISSUE TITLE
In-place byte-swapping in astropy.io.fits

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5512]
I tried passing a read-only array to ``fits.writeto`` and got the following error:

```
Traceback (most recent call last):
  File "data_wcs.py", line 19, in <module>
    fits.writeto('image_ra.fits', image['Right Ascension'], clobber=True)
  File "/Users/tom/miniconda3/envs/dev/lib/python3.5/site-packages/astropy/io/fits/convenience.py", line 424, in writeto
    checksum=checksum)
  File "/Users/tom/miniconda3/envs/dev/lib/python3.5/site-packages/astropy/io/fits/hdu/base.py", line 367, in writeto
    checksum=checksum)
  File "/Users/tom/miniconda3/envs/dev/lib/python3.5/site-packages/astropy/io/fits/hdu/hdulist.py", line 693, in writeto
    hdu._writeto(hdulist._file)
  File "/Users/tom/miniconda3/envs/dev/lib/python3.5/site-packages/astropy/io/fits/hdu/base.py", line 650, in _writeto
    data_offset, data_size = self._writedata(fileobj)
  File "/Users/tom/miniconda3/envs/dev/lib/python3.5/site-packages/astropy/io/fits/hdu/base.py", line 587, in _writedata
    size += self._writedata_internal(fileobj)
  File "/Users/tom/miniconda3/envs/dev/lib/python3.5/site-packages/astropy/io/fits/hdu/image.py", line 634, in _writedata_internal
    output.byteswap(True)
```

We should probably not be modifying arrays passed to ``fits.writeto``. I haven't had a chance to make a minimal failing example yet.

**Comment by tanayag** [comment]
Hey @astrofrog I want to help with this,
Guide me please!
