### ISSUE TITLE
fitsdiff table crash

### ISSUE THREAD

**Issue by jaytmiller** [astropy/astropy#5520]
Recently I started seeing this:

```
% fitsdiff  test-source.fits   test-change-row1-valueLeft.fits

 fitsdiff: 1.3.dev16465
 a: data/test-source.fits
 b: data/test-change-row1-valueLeft.fits
 Maximum number of different data values to be reported: 10
 Data comparison level: 0.0

Extension HDU 1:

   Data contains differences:
Traceback (most recent call last):
  File "/Users/jmiller/anaconda/bin/fitsdiff", line 11, in <module>
    load_entry_point('astropy==1.3.dev16465', 'console_scripts', 'fitsdiff')()
  File "/Users/jmiller/anaconda/lib/python3.5/site-packages/astropy/io/fits/scripts/fitsdiff.py", line 285, in main
    diff.report(fileobj=out_file)
  File "/Users/jmiller/anaconda/lib/python3.5/site-packages/astropy/io/fits/diff.py", line 181, in report
    self._report()
  File "/Users/jmiller/anaconda/lib/python3.5/site-packages/astropy/io/fits/diff.py", line 373, in _report
    hdu_diff.report(self._fileobj, indent=self._indent + 1)
  File "/Users/jmiller/anaconda/lib/python3.5/site-packages/astropy/io/fits/diff.py", line 181, in report
    self._report()
  File "/Users/jmiller/anaconda/lib/python3.5/site-packages/astropy/io/fits/diff.py", line 488, in _report
    self.diff_data.report(self._fileobj, indent=self._indent + 1)
  File "/Users/jmiller/anaconda/lib/python3.5/site-packages/astropy/io/fits/diff.py", line 181, in report
    self._report()
  File "/Users/jmiller/anaconda/lib/python3.5/site-packages/astropy/io/fits/diff.py", line 1189, in _report
    self._writeln(u(' Column {} data differs in row {}:').format(indx))
IndexError: tuple index out of range

```

The table structure should be roughly:

```
% finfo data/test-source.fits data/test-change-row1-valueLeft.fits
--------------------------------------------------------------------------------
Filename: data/test-source.fits
No.    Name         Type      Cards   Dimensions   Format
  0  PRIMARY     PrimaryHDU       5   ()      
  1              BinTableHDU     18   9R x 5C   [5A, 5A, I, E, 18A]   

[1]:  modeUp modeDown valueLeft valueRight wordage
--------------------------------------------------------------------------------
Filename: data/test-change-row1-valueLeft.fits
No.    Name         Type      Cards   Dimensions   Format
  0  PRIMARY     PrimaryHDU       5   ()      
  1              BinTableHDU     18   9R x 5C   [5A, 5A, I, E, 18A]   

[1]:  modeUp modeDown valueLeft valueRight wordage

```

Test Data:

[fits_crash.zip](https://github.com/astropy/astropy/files/619375/fits_crash.zip)

This data supports a unit test and is several years old.  I did not construct the tables,  it's possible they're degenerate in some way because they have a limited test-only purpose.

**Comment by saimn** [comment]
Comes from aaaa6fb5 :
```
         # Finally, let's go through and report column data differences:
         for indx, values in self.diff_values:
-            self._writeln(u(' Column %s data differs in row %d:') % indx)
+            self._writeln(u(' Column {} data differs in row {}:').format(indx))
             report_diff_values(self._fileobj, values[0], values[1],
                                ind=self._indent + 1)
```
I guess `indx` is a 2-element tuple/list, so using `.format(*indx)` should work.

**Comment by pllim** [comment]
Good catch, @saimn ! Who wants to submit a PR? :smile_cat:

**Comment by pllim** [comment]
@jaytmiller , in the meantime, you can try the released version from AstroConda.

**Comment by pllim** [comment]
Here is the result:

```
 fitsdiff: 1.2.1
 a: test-source.fits
 b: test-change-row1-valueLeft.fits
 Maximum number of different data values to be reported: 10
 Data comparison level: 0.0

Extension HDU 1:

   Data contains differences:
     Column valueLeft data differs in row 1:
        a> 5748
        b> -1
     1 different table data element(s) found (2.22% different).
```

**Comment by saimn** [comment]
After a quick look, it seems that there other similar errors in `HDUDiff._report`, and this is not tested. PR will come later !

**Comment by bsipocz** [comment]
I knew that PR will brake things. I remember there were a few similar cases that broke tests, so I've fixed them. 
Are you @saimn working on this, or shall I?

**Comment by saimn** [comment]
@bsipocz - Yes, I started to work on this, the longest is to add tests ;-).

**Comment by pllim** [comment]
@jaytmiller , theoretically, the fix should be in conda-dev tomorrow.

**Comment by jaytmiller** [comment]
Awesome guys,  thanks!
