### ISSUE TITLE
RTD build affected by M33 timeout

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5862]
Has been failing via multiple tries in the past 12 hours for `latest`; `1.3.x` also has the same problem. This is a reminder to revisit when M33 look-up works again or find a more stable alternative.

Example: https://readthedocs.org/projects/astropy/builds/5111154/

```
Running Sphinx v1.3.5
making output directory...
loading translations [en]... done
loading intersphinx inventory from http://docs.python.org/3/objects.inv...
loading intersphinx inventory from http://pytest.org/latest/objects.inv...
loading intersphinx inventory from http://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from /home/docs/checkouts/readthedocs.org/user_builds/astropy/checkouts/latest/astropy_helpers/astropy_helpers/sphinx/local/python3_local_links.inv...
loading intersphinx inventory from http://docs.h5py.org/en/latest/objects.inv...
loading intersphinx inventory from http://matplotlib.org/objects.inv...
loading intersphinx inventory from http://pandas.pydata.org/pandas-docs/stable/objects.inv...
loading intersphinx inventory from http://ipython.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from http://docs.scipy.org/doc/scipy/reference/objects.inv...
/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/site-packages/sphinx_gallery/gen_rst.py:494: UserWarning: ________________________________________________________________________________
/home/docs/checkouts/readthedocs.org/user_builds/astropy/checkouts/latest/examples/coordinates/plot_obs-planning.py failed to execute correctly:Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/site-packages/astropy-2.0.dev17986-py3.5-linux-x86_64.egg/astropy/coordinates/name_resolve.py", line 139, in get_icrs_coordinates
    resp_data = resp.read()
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/http/client.py", line 458, in read
    s = self.fp.read()
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/site-packages/sphinx_gallery/gen_rst.py", line 475, in execute_code_block
    exec(code_block, example_globals)
  File "<string>", line 2, in <module>
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/site-packages/astropy-2.0.dev17986-py3.5-linux-x86_64.egg/astropy/coordinates/sky_coordinate.py", line 1295, in from_name
    icrs_coord = get_icrs_coordinates(name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/site-packages/astropy-2.0.dev17986-py3.5-linux-x86_64.egg/astropy/coordinates/name_resolve.py", line 157, in get_icrs_coordinates
    "timed out".format(name))
astropy.coordinates.name_resolve.NameResolveError: Unable to retrieve coordinates for name 'M33'; connection timed out
________________________________________________________________________________

  warnings.warn(fail_example_warning)

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/site-packages/astropy-2.0.dev17986-py3.5-linux-x86_64.egg/astropy/coordinates/name_resolve.py", line 139, in get_icrs_coordinates
    resp_data = resp.read()
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/http/client.py", line 458, in read
    s = self.fp.read()
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/application.py", line 189, in __init__
    self._init_builder(self.buildername)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/application.py", line 252, in _init_builder
    self.emit('builder-inited')
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/application.py", line 508, in emit
    results.append(callback(self, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/site-packages/sphinx_gallery/gen_gallery.py", line 139, in generate_gallery_rst
    seen_backrefs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/site-packages/sphinx_gallery/gen_rst.py", line 421, in generate_dir_rst
    generate_file_rst(fname, target_dir, src_dir, gallery_conf)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/site-packages/sphinx_gallery/gen_rst.py", line 600, in generate_file_rst
    gallery_conf)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/site-packages/sphinx_gallery/gen_rst.py", line 475, in execute_code_block
    exec(code_block, example_globals)
  File "<string>", line 2, in <module>
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/site-packages/astropy-2.0.dev17986-py3.5-linux-x86_64.egg/astropy/coordinates/sky_coordinate.py", line 1295, in from_name
    icrs_coord = get_icrs_coordinates(name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/site-packages/astropy-2.0.dev17986-py3.5-linux-x86_64.egg/astropy/coordinates/name_resolve.py", line 157, in get_icrs_coordinates
    "timed out".format(name))
astropy.coordinates.name_resolve.NameResolveError: Unable to retrieve coordinates for name 'M33'; connection timed out

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/conda/latest/lib/python3.5/site-packages/astropy-2.0.dev17986-py3.5-linux-x86_64.egg/astropy/coordinates/name_resolve.py", line 157, in get_icrs_coordinates
    "timed out".format(name))
astropy.coordinates.name_resolve.NameResolveError: Unable to retrieve coordinates for name 'M33'; connection timed out
The full traceback has been saved in /tmp/sphinx-err-w3yjplmu.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Generating gallery
Executing file /home/docs/checkouts/readthedocs.org/user_builds/astropy/checkouts/latest/examples/coordinates/plot_obs-planning.py
```

**Comment by pllim** [comment]
`latest` passed, for now. Can't find `1.3.x` in the RTD list.

**Comment by bsipocz** [comment]
@pllim - Last time I've inactivated it, as we didn't have the lts branch there either. Do you think it's needed? Normally we only backport to that branch before doing a bugfix release, and for the release there will be a build. (This time there were backports at several times, only because I wanted to get myself familiar with the infra a bit more).

**Comment by pllim** [comment]
@bsipocz , don't worry about it. I only mentioned it because it showed up as "failed" in build history. :smile:
