### ISSUE TITLE
SmoothlyBrokenPowerLaw1D local doc build gives ValueError

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5894]
I have `matplotlib` 2.0.0 installed. I see the following traceback when building the doc locally:
```
.../astropy/modeling/powerlaws.py:docstring
of astropy.modeling.powerlaws.SmoothlyBrokenPowerLaw1D:71:
WARNING: Exception occurred in plotting astropy-modeling-powerlaws-SmoothlyBrokenPowerLaw1D-1
 from .../docs/api/astropy.modeling.powerlaws.SmoothlyBrokenPowerLaw1D.rst:
Traceback (most recent call last):
  File ".../python3.5/site-packages/matplotlib/sphinxext/plot_directive.py", line 520, in run_code
    six.exec_(code, ns)
  File "<string>", line 13, in <module>
  File ".../python3.5/site-packages/matplotlib/pyplot.py", line 3179, in loglog
    ret = ax.loglog(*args, **kwargs)
  File ".../python3.5/site-packages/matplotlib/axes/_axes.py", line 1538, in loglog
    self.set_xscale('log', **dx)
  File ".../python3.5/site-packages/matplotlib/axes/_base.py", line 2948, in set_xscale
    ax.xaxis._set_scale(value, **kwargs)
  File ".../python3.5/site-packages/matplotlib/axis.py", line 710, in _set_scale
    self._scale.set_default_locators_and_formatters(self)
  File ".../python3.5/site-packages/matplotlib/scale.py", line 249, in set_default_locators_and_formatters
    axis.set_major_locator(LogLocator(self.base))
  File ".../python3.5/site-packages/matplotlib/axis.py", line 1543, in set_major_locator
    self.stale = True
  File ".../python3.5/site-packages/matplotlib/artist.py", line 279, in stale
    self.stale_callback(self, val)
  File ".../python3.5/site-packages/matplotlib/artist.py", line 76, in _stale_axes_callback
    self.axes.stale = val
  File ".../python3.5/site-packages/matplotlib/artist.py", line 279, in stale
    self.stale_callback(self, val)
  File ".../python3.5/site-packages/matplotlib/figure.py", line 56, in _stale_figure_callback
    self.figure.stale = val
  File ".../python3.5/site-packages/matplotlib/artist.py", line 279, in stale
    self.stale_callback(self, val)
  File ".../python3.5/site-packages/matplotlib/pyplot.py", line 576, in _auto_draw_if_interactive
    fig.canvas.draw_idle()
  File ".../python3.5/site-packages/matplotlib/backend_bases.py", line 2032, in draw_idle
    self.draw(*args, **kwargs)
  File ".../python3.5/site-packages/matplotlib/backends/backend_agg.py", line 464, in draw
    self.figure.draw(self.renderer)
  File ".../python3.5/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File ".../python3.5/site-packages/matplotlib/figure.py", line 1143, in draw
    renderer, self, dsu, self.suppressComposite)
  File ".../python3.5/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File ".../python3.5/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File ".../python3.5/site-packages/matplotlib/axes/_base.py", line 2409, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File ".../python3.5/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File ".../python3.5/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File ".../python3.5/site-packages/matplotlib/axis.py", line 1136, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File ".../python3.5/site-packages/matplotlib/axis.py", line 969, in _update_ticks
    tick_tups = [t for t in self.iter_ticks()]
  File ".../python3.5/site-packages/matplotlib/axis.py", line 969, in <listcomp>
    tick_tups = [t for t in self.iter_ticks()]
  File ".../python3.5/site-packages/matplotlib/axis.py", line 912, in iter_ticks
    majorLocs = self.major.locator()
  File ".../python3.5/site-packages/matplotlib/ticker.py", line 1938, in __call__
    return self.tick_values(vmin, vmax)
  File ".../python3.5/site-packages/matplotlib/ticker.py", line 1964, in tick_values
    "Data has no positive values, and therefore can not be "
ValueError: Data has no positive values, and therefore can not be log-scaled.
```

**Comment by pllim** [comment]
I don't see this in RTD build log and the plot actually appears in RTD. I must be going crazy... Closing this for now. But if someone else also encounters the same problem, we can re-open.
