### ISSUE TITLE
test failures on ppc64le Rhel VM 

### ISSUE THREAD

**Issue by ArchaB** [astropy/astropy#5957]
Hi,

I am trying to evalutate the Anaconda packages on ppc64le Rhel VM.
While running the tests on the package encountered the following error 
```
=============================================================== ERRORS ===============================================================
_________________________________________________________ ERROR collecting  __________________________________________________________
lib/python2.7/site-packages/py/_path/common.py:367: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
lib/python2.7/site-packages/py/_path/common.py:416: in gen
    for p in self.gen(subdir):
lib/python2.7/site-packages/py/_path/common.py:416: in gen
    for p in self.gen(subdir):
lib/python2.7/site-packages/py/_path/common.py:416: in gen
    for p in self.gen(subdir):
lib/python2.7/site-packages/py/_path/common.py:406: in gen
    if p.check(dir=1) and (rec is None or rec(p))])
lib/python2.7/site-packages/_pytest/main.py:682: in _recurse
    ihook = self.gethookproxy(path)
lib/python2.7/site-packages/_pytest/main.py:587: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
lib/python2.7/site-packages/_pytest/config.py:339: in _getconftestmodules
    mod = self._importconftest(conftestpath)
lib/python2.7/site-packages/_pytest/config.py:364: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   ConftestImportFailure: ImportError('Numpy version 1.7.0 or later must be installed to use Astropy',)
E     File "/root/anaconda2/lib/python2.7/site-packages/astropy/__init__.py", line 116, in <module>
E       _check_numpy()
E     File "/root/anaconda2/lib/python2.7/site-packages/astropy/__init__.py", line 110, in _check_numpy
E       raise ImportError(msg)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================================================== 1 error in 0.74 seconds =======================================================
```
The installed version of numpy is 1.12.1
```
bash-4.2# conda install numpy
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /root/anaconda2:
#
numpy                     1.12.1                   py27_0
```

Also tried setting PYTHONPATH, but faced similar errors
```
bash-4.2#  python ./lib/python2.7/site-packages/astropy/wcs/tests/extension/setup.py test
Traceback (most recent call last):
  File "./lib/python2.7/site-packages/astropy/wcs/tests/extension/setup.py", line 13, in <module>
    from astropy import wcs
  File "/root/anaconda2/lib/python2.7/site-packages/astropy/__init__.py", line 116, in <module>
    _check_numpy()
  File "/root/anaconda2/lib/python2.7/site-packages/astropy/__init__.py", line 110, in _check_numpy
    raise ImportError(msg)
ImportError: Numpy version 1.7.0 or later must be installed to use Astropy
```

Am I missing on something?

**Comment by pllim** [comment]
I generally discourage doing stuff in `root`. How about trying this in a new conda environment? Also, unset your PYTHONPATH.

```
conda create -n testenv numpy astropy
source activate testenv
```

Then in a Python session (not IPython) in that env, do this:

```python
>>> import astropy
>>> astropy.test()
```

**Comment by ArchaB** [comment]
@pllim Thanks for the quick response.

I tried in a clean conda environment. But still encountered the same failures. 
```
(testenv) bash-4.2# py.test
======================================================== test session starts =========================================================
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /root/anaconda2, inifile:
collected 0 items / 1 errors

=============================================================== ERRORS ===============================================================
_________________________________________________________ ERROR collecting  __________________________________________________________
lib/python2.7/site-packages/py/_path/common.py:367: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
lib/python2.7/site-packages/py/_path/common.py:416: in gen
    for p in self.gen(subdir):
lib/python2.7/site-packages/py/_path/common.py:416: in gen
    for p in self.gen(subdir):
lib/python2.7/site-packages/py/_path/common.py:416: in gen
    for p in self.gen(subdir):
lib/python2.7/site-packages/py/_path/common.py:406: in gen
    if p.check(dir=1) and (rec is None or rec(p))])
lib/python2.7/site-packages/_pytest/main.py:682: in _recurse
    ihook = self.gethookproxy(path)
lib/python2.7/site-packages/_pytest/main.py:587: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
lib/python2.7/site-packages/_pytest/config.py:339: in _getconftestmodules
    mod = self._importconftest(conftestpath)
lib/python2.7/site-packages/_pytest/config.py:364: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   ConftestImportFailure: ImportError('Numpy version 1.7.0 or later must be installed to use Astropy',)
E     File "/root/anaconda2/lib/python2.7/site-packages/astropy/__init__.py", line 116, in <module>
E       _check_numpy()
E     File "/root/anaconda2/lib/python2.7/site-packages/astropy/__init__.py", line 110, in _check_numpy
E       raise ImportError(msg)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================================================== 1 error in 0.72 seconds =======================================================
```

I have installed Numpy after connecting to the conda env as testuser

**Comment by pllim** [comment]
Why are you using `py.test`? Are you trying to test the local source checkout for your own changes to the code, or the installed version of Astropy?

Also, your path in traceback does not make sense. It is somehow calling Astropy installed in `root`. What is your `pwd`?

**Comment by ArchaB** [comment]
@pllim , I am actually trying to build the Anaconda packages on ppc64le.
One thing I observed is even on connecting to the container using the commands 
```
conda create -n testenv numpy astropy
source activate testenv
```

The user still is root
```
(testenv) bash-4.2# whoami
root
```

Thus all other installations happen in the root folder with root ownership.

**Comment by pllim** [comment]
Can you not logged in as root?

**Comment by astrofrog** [comment]
I'm going to close this for now due to inactivity - I think that this may have been an issue not specific to PPC but rather to the way Python environments were set up locally. If anyone sees the same issue, please re-open or open a new issue.
