### ISSUE TITLE
Model parameter values / defaults don't broadcast to model sets

### ISSUE THREAD

**Issue by jehturner** [astropy/astropy#6096]
Shouldn't this work (using the same default shift in each case as for a single model)?
```python
>>> from astropy.modeling.models import *
>>> s = Shift(n_models=3)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jturner/anaconda2/envs/spec/lib/python2.7/site-packages/astropy-2.0.dev18373-py2.7-linux-x86_64.egg/astropy/modeling/core.py", line 408, in __init__
    __init__, args, kwargs, varkwargs='kwargs')
  File "/home/jturner/anaconda2/envs/spec/lib/python2.7/site-packages/astropy-2.0.dev18373-py2.7-linux-x86_64.egg/astropy/modeling/core.py", line 405, in __init__
    return super(cls, self).__init__(*params, **kwargs)
  File "/home/jturner/anaconda2/envs/spec/lib/python2.7/site-packages/astropy-2.0.dev18373-py2.7-linux-x86_64.egg/astropy/modeling/core.py", line 667, in __init__
    self._initialize_parameters(args, kwargs)
  File "/home/jturner/anaconda2/envs/spec/lib/python2.7/site-packages/astropy-2.0.dev18373-py2.7-linux-x86_64.egg/astropy/modeling/core.py", line 1413, in _initialize_parameters
    min_ndim, model_set_axis, name, param_ndim))
astropy.modeling.parameters.InputParameterError: All parameter values must be arrays of dimension at least 1 for model_set_axis=0 (the value given for 'offset' is only 0-dimensional)
```
This does work for polynomial models (eg. `Chebyshev1D(1, n_models=3)`), as long as no coefficients are specified, but not when passing single parameter values (eg. `Chebyshev1D(1, n_models=3, c0=1)`).

**Comment by pllim** [comment]
I think you need to do this:
```python
s = Shift([0, 0, 0], n_models=3)
```
I vaguely remember there was a debate a long time ago on whether to auto-broadcast or not. And it was decided not to auto-broadcast in case of confusion for more complex cases. Maybe @nden or @embray remember.

**Comment by jehturner** [comment]
Thanks, yes, that would be the workaround. If this behaviour is really intentional then there's nothing more to do -- but FWIW I would argue that:

  1. It violates the principle of least surprise for the default to work for single models but not model sets.

  2. The call is going to be a bit unnecessarily cumbersome to write for variable or large numbers of models (eg. `Polynomial1D(2, n_models=nmodels, c0=[1,]*nmodels, c1=[1,]*nmodels)`).

It surprised me anyway, but if you all agree on this then the issue can be closed.

**Comment by saimn** [comment]
I'm with @jehturner here, it would be much more practical if scalar parameters were broadcasted by default. Currently I have to do something like this:
```
m = Gaussian2D(amplitude=[1] * nl, theta=[0] * nl,
               x_mean=[x0] * nl, y_mean=[y0] * nl,
               x_stddev=stddev, y_stddev=stddev, n_models=nl)
```

**Comment by pllim** [comment]
> it would be much more practical if scalar parameters were broadcasted by default

I vaguely remember a discussion about such things a long time ago. Erik B explained back then why it wouldn't be a good idea, but perhaps the code have changed enough to revisit this now.

**Comment by saimn** [comment]
Browsing old issues and PRs, I found  #2634 which introduced `model_set_axis` and probably explains the current behavior (which is a complicated business, I do not understand everything ;)). 
From a user perspective, the request here makes sense I think, but I can also understand that it's complicated to handle the possible use-cases. Maybe a solution could be to have a new keyword to tell explicitly that model parameters must be broadcasted ?

**Comment by Jerry-Ma** [comment]
Do we have any chancee of resolving this? I am working with the (composite) models extensively and found that it would be much more convenient if we can do the broadcast of the model parameter AND the n_models.

Say, I would like to have a model composed from the following models:

m1 = models.Shift(1, n_models=2)
m2 = models.Mapping([0, 0])
m3 = models.Identity(2)
m4 = models.Scale(2)   # n_models = 1 by default

And with the current implementation it is not possible:

1. m1 does not work be cause parameters does not broadcast.
2. m2 |( m1 & m1) does not work because m2 does not support n_models.
3 m1 & m2 does not work because m2 does not support n_models (`Identity` is inherited from `models.Mapping`)
4. m1 | m4 does not work because m1 and m4 does not have the same n_models.
