### ISSUE TITLE
2.0rc1: Sphinx build error

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#6322]
When building the documentation with `python setup.py build_sphinx`, I get the following error:
```
python setup.py build_sphinx
running build_sphinx
creating /build/python-astropy-2.0~rc1/docs/_build
creating /build/python-astropy-2.0~rc1/docs/_build/doctrees
creating /build/python-astropy-2.0~rc1/docs/_build/html
/usr/lib/python2.7/dist-packages/astropy_helpers/commands/build_sphinx.py:246: AstropyDeprecationWarning: The "build_sphinx" command is now deprecated. Use"build_docs" i
  '"build_docs" instead.', AstropyDeprecationWarning)
running build
running build_py
running pre_hook from astropy._erfa.setup_package for build_py command
running pre_hook from astropy.modeling.setup_package for build_py command
WARNING: The autogenerated wrappers in astropy.modeling._projections seem to be older than the source templates used to create them. Because this is a release version we
running build_ext
running pre_hook from astropy._erfa.setup_package for build_ext command
running pre_hook from astropy.modeling.setup_package for build_ext command
WARNING: The autogenerated wrappers in astropy.modeling._projections seem to be older than the source templates used to create them. Because this is a release version we
building 'astropy._compiler' extension
gcc -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O2 -fdebug-prefix-map=/build/python-astropy-2.0~rc1=. -fstack-protector-strong -Wformat -W
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D
Running Sphinx v1.4.9
WARNING: The sphinx_gallery extension is not installed, so the gallery will not be built.  You will probably see additional warnings about undefined references due to th
loading pickled environment... not yet created
loading intersphinx inventory from https://sphinx-automodapi.readthedocs.io/en/stable/objects.inv...
[...]
WARNING: intersphinx inventory 'http://data.astropy.org/intersphinx/scipy.inv' not fetchable due to <class 'urllib2.URLError'>: <urlopen error [Errno 111] Connection ref
loading intersphinx inventory from https://pytest.org/en/latest/objects.inv...
autosummary] generating autosummary for: analytic_functions/index.rst, changelog.rst, config/config_0_4_transition.rst, config/index.rst, constants/index.rst, convoluti
[automodsumm] vo/conesearch/index.rst: found 27 automodsumm entries to generate
Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 204, in __init__
    self._init_builder(self.buildername)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 279, in _init_builder
    self.emit('builder-inited')
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 551, in emit
    results.append(callback(self, *args))
  File "/build/python-astropy-2.0~rc1/astropy_helpers/astropy_helpers/extern/automodapi/automodsumm.py", line 266, in process_automodsumm_generation
    inherited_members=app.config.automodsumm_inherited_members)
  File "/build/python-astropy-2.0~rc1/astropy_helpers/astropy_helpers/extern/automodapi/automodsumm.py", line 504, in generate_automodsumm_docs
    template = template_env.get_template(tmplstr % 'base')
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python2.7/dist-packages/sphinx/jinja2glue.py", line 181, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: autosummary_core/base.rst
Sphinx Documentation subprocess failed with return code 1

```

**Comment by bsipocz** [comment]
could you please try it with a newer sphinx, too?  I don't yet see why it needs a never version, but while I cannot reproduce this locally, I run into a bunch of different issues with sphinx 1.4.9

**Comment by olebole** [comment]
Not so simple (since I depend on what is in Debian unstable). I will try tomorrow, after filing potential other problems on different platforms.

**Comment by bsipocz** [comment]
Sure. Also I believe 1.4.9 is still within the required minimum sphinx version, but I would like to see whether it's a reasonable assumption that we (or sphinx-automodapi) is supposed to be compatible with it.

**Comment by astrofrog** [comment]
I can reproduce the issue

**Comment by astrofrog** [comment]
See https://github.com/astropy/astropy/pull/6325 for a fix
