### ISSUE TITLE
CCDData without considering WCS

### ISSUE THREAD

**Issue by ysBach** [astropy/astropy#6499]
I have been working on reducing [FOCAS data](http://smoka.nao.ac.jp/search?resolver=NONE&object=KISSJ1100%2B4421&instruments=FCS&spectrographs=FCS&obs_mod=all&data_typ=OBJECT&dispcol=default&action=Search&diff=1000&asciitable=Table) for this semester's TA work. 

When I try to read any data with ``CCDData``, I get the following errors
```python
ccd = CCDData.read('FCSA00150629.fits')

WARNING: FITSFixedWarning: PC001001= 1.00000000 / Pixel Coordinate translation matrix 
this form of the PCi_ja keyword is deprecated, use PCi_ja. [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: PC001001= 1.00000000 / Pixel Coordinate translation matrix 
this form of the PCi_ja keyword is deprecated, use PCi_ja.
WARNING: FITSFixedWarning: PC001002= 0.00000000 / Pixel Coordinate translation matrix 
this form of the PCi_ja keyword is deprecated, use PCi_ja. [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: PC001002= 0.00000000 / Pixel Coordinate translation matrix 
this form of the PCi_ja keyword is deprecated, use PCi_ja.
WARNING: FITSFixedWarning: PC002001= 0.00000000 / Pixel Coordinate translation matrix 
this form of the PCi_ja keyword is deprecated, use PCi_ja. [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: PC002001= 0.00000000 / Pixel Coordinate translation matrix 
this form of the PCi_ja keyword is deprecated, use PCi_ja.
WARNING: FITSFixedWarning: PC002002= 1.00000000 / Pixel Coordinate translation matrix 
this form of the PCi_ja keyword is deprecated, use PCi_ja. [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: PC002002= 1.00000000 / Pixel Coordinate translation matrix 
this form of the PCi_ja keyword is deprecated, use PCi_ja.
WARNING: FITSFixedWarning: RADECSYS= 'FK5 ' / The equatorial coordinate system 
the RADECSYS keyword is deprecated, use RADESYSa. [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: RADECSYS= 'FK5 ' / The equatorial coordinate system 
the RADECSYS keyword is deprecated, use RADESYSa.
WARNING: FITSFixedWarning: 'unitfix' made the change 'Changed units: 'degree' -> 'deg''. [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: 'unitfix' made the change 'Changed units: 'degree' -> 'deg''.
WARNING: FITSFixedWarning: 'celfix' made the change 'Unmatched celestial axes'. [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: 'celfix' made the change 'Unmatched celestial axes'.
Traceback (most recent call last):

  File "<ipython-input-131-9ba40d7893f2>", line 1, in <module>
    ccd = CCDData.read('FCSA00150629.fits')

  File "/home/aaa/anaconda3/lib/python3.6/site-packages/astropy/nddata/mixins/ndio.py", line 29, in read
    return io_registry.read(cls, *args, **kwargs)

  File "/home/aaa/anaconda3/lib/python3.6/site-packages/astropy/io/registry.py", line 531, in read
    data = reader(*args, **kwargs)

  File "/home/aaa/anaconda3/lib/python3.6/site-packages/astropy/nddata/ccddata.py", line 521, in fits_ccddata_reader
    hdr, wcs = _generate_wcs_and_update_header(hdr)

  File "/home/aaa/anaconda3/lib/python3.6/site-packages/astropy/nddata/ccddata.py", line 406, in _generate_wcs_and_update_header
    wcs = WCS(hdr)

  File "/home/aaa/anaconda3/lib/python3.6/site-packages/astropy/wcs/wcs.py", line 503, in __init__
    self.wcs.set()

InconsistentAxisTypesError: ERROR 4 in wcs_types() at line 2516 of file cextern/wcslib/C/wcs.c:
Unmatched celestial axes.
```

Although it is due to the problem of WCS keywords of SMOKA archive service, I want to just load the data, without checking the validity of the WCS information in the header. 

I cannot proceed to making master bias, etc.

Is there a way to *ignore WCS* when reading FITS files using ``CCDData``?
Alternatively, is there a task similar to WCSRESET of IRAF in astropy?

**Comment by MSeifert04** [comment]
> Is there a way to ignore WCS when reading FITS files using CCDData?

No, something like that isn't implemented, but you could use something like that without using `read`

```
from astropy.io import fits
from astropy.nddata import CCDData
filename = ...
ccd = CCDData(fits.getdata(filename), meta=fits.getheader(filename))
```

that won't create a `WCS` as far as I know.

**Comment by MSeifert04** [comment]
Seems like ["WCS could not fail"](https://github.com/astropy/astropy/blob/master/astropy/nddata/ccddata.py#L404-L405) isn't actually correct! 😄

**Comment by MSeifert04** [comment]
@ysBach Do you know what part of the Header makes `WCS` throw the exception? I failed to find a small reproducible regression test. 

Could you maybe include the relevant parts of the Header (or all of it) in this thread?

**Comment by ysBach** [comment]
@MSeifert04 

>  but you could use something like that without using `read`

Thanks!! 

> Could you maybe include the relevant parts of the Header (or all of it) in this thread?

First, let me make a test FITS file which **raises WCS problem**.
I used 31 cards out of original 170 cards from the original header of "FCSA00150629.fits" from [here](http://smoka.nao.ac.jp/search?resolver=NONE&object=KISSJ1100%2B4421&instruments=FCS&spectrographs=FCS&obs_mod=all&data_typ=OBJECT&dispcol=default&action=Search&diff=1000&asciitable=Table) .

```python
from astropy.io.fits import Header
from astropy.io import fits
from astropy.nddata import CCDData
from astropy.wcs import InconsistentAxisTypesError
from astropy.utils.exceptions import AstropyWarning
import warnings
import numpy as np

# Ignore too many FITSFixedWarnings
warnings.simplefilter('ignore', category=AstropyWarning)

hdr_txt_example_WCS = '''
SIMPLE  =                    T / Fits standard
BITPIX  =                   16 / Bits per pixel
NAXIS   =                    2 / Number of axes
NAXIS1  =                 1104 / Axis length
NAXIS2  =                 4241 / Axis length
BSCALE  =             1.000000 / Real=fits-value*BSCALE+BZERO
BUNIT   = 'ADU     '           / Unit of original pixel values
BZERO   =         32768.000000 / Real=fits-value*BSCALE+BZERO
DATA-TYP= 'OBJECT  '           / Type / Characteristics of  this data
DATE-OBS= '2014-02-24'         / Observation start date  (yyyy-mm-dd)
CRVAL1  =         164.98110962 / Physical value of the reference pixel X
CRVAL2  =          44.34089279 / Physical value of the reference pixel Y
CRPIX1  =                -34.0 / Reference pixel in X (pixel)
CRPIX2  =               2041.0 / Reference pixel in Y (pixel)
CDELT1  =           0.10380000 / X Scale projected on detector (#/pix)
CDELT2  =           0.10380000 / Y Scale projected on detector (#/pix)
CTYPE1  = 'RA---TAN'           / Pixel coordinate system
CTYPE2  = 'WAVELENGTH'         / Pixel coordinate system
CUNIT1  = 'degree  '           / Units used in both CRVAL1 and CDELT1
CUNIT2  = 'nm      '           / Units used in both CRVAL2 and CDELT2
CD1_1   =           0.20760000 / Pixel Coordinate translation matrix
CD1_2   =           0.00000000 / Pixel Coordinate translation matrix
CD2_1   =           0.00000000 / Pixel Coordinate translation matrix
CD2_2   =           0.10380000 / Pixel Coordinate translation matrix
C2YPE1  = 'RA---TAN'           / Pixel coordinate system
C2YPE2  = 'DEC--TAN'           / Pixel coordinate system
C2NIT1  = 'degree  '           / Units used in both C2VAL1 and C2ELT1
C2NIT2  = 'degree  '           / Units used in both C2VAL2 and C2ELT2
RADECSYS= 'FK5     '           / The equatorial coordinate system
'''
hdr_WCS = Header.fromstring(hdr_txt_example_WCS, sep = '\n')
fits.writeto('test_WCS.fits', data = np.ones(1), header=hdr_WCS, overwrite=True)

try: 
    ccd_WCS = CCDData.read('test_WCS.fits')
except InconsistentAxisTypesError:
    print('The original header raised WCS problem as expected.')

# The original header raised WCS problem as expected.
```

Then run IRAF's WCSRESET (I used PyRAF 2.2.dev):
```
--> wcsreset test_WCS.fits world
Initializing wcs world for image test_WCS.fits
Image test_WCS.fits, axis 1: Cannot locate dec--tan axis
```
The header is now changed. The resulting header is generated by IRAF WCSRESET task, so some cards' comments are changed by IRAF. I copied and pasted the new header to make a test FITS file which does **NOT raise a WCS problem**, for in case you can't run IRAF on the machine:

```python
hdr_txt_example_noWCS = '''
SIMPLE  =                    T / Fits standard
BITPIX  =                   16 / Bits per pixel
NAXIS   =                    2 / Number of axes
NAXIS1  =                 1104 / Axis length
NAXIS2  =                 4241 / Axis length
BSCALE  =           1.000000E0 / REAL = TAPE*BSCALE + BZERO
BZERO   =           3.276800E4 /
ORIGIN  = 'NOAO-IRAF FITS Image Kernel July 2003' / FITS file originator
DATE    = '2017-09-01T13:08:01' / Date FITS file was generated
IRAF-TLM= '2017-09-01T13:08:05' / Time of last modification
BUNIT   = 'ADU     '           / Unit of original pixel values
DATA-TYP= 'OBJECT  '           / Type / Characteristics of  this data
DATE-OBS= '2014-02-24'         / Observation start date  (yyyy-mm-dd)
CUNIT1  = 'degree  '           / Units used in both CRVAL1 and CDELT1
CUNIT2  = 'nm      '           / Units used in both CRVAL2 and CDELT2
C2YPE1  = 'RA---TAN'           / Pixel coordinate system
C2YPE2  = 'DEC--TAN'           / Pixel coordinate system
C2NIT1  = 'degree  '           / Units used in both C2VAL1 and C2ELT1
C2NIT2  = 'degree  '           / Units used in both C2VAL2 and C2ELT2
RADECSYS= 'FK5     '           / The equatorial coordinate system
WCSDIM  =                    2
LTM1_1  =                   1.
LTM2_2  =                   1.
WAT0_001= 'system=physical'
WAT1_001= 'wtype=linear'
WAT2_001= 'wtype=linear'
'''

hdr_noWCS = Header.fromstring(hdr_txt_example_noWCS, sep = '\n')
fits.writeto('test_noWCS.fits', data = np.ones(1), header=hdr_noWCS, overwrite=True)

try:
    ccd_noWCS = CCDData.read('test_noWCS.fits')
    print('The initialized header did NOT raise WCS problem as expected.')
except:
    print('!!')

# The initialized header did NOT raise WCS problem as expected.
```

To see what has been changed by IRAF WCSRESET, I printed the `HeaderDiff`'s `report`:

```python
from astropy.io.fits import HeaderDiff

diff_WCS = HeaderDiff(hdr_WCS, hdr_noWCS)
print(diff_WCS.report())

# Headers have different number of cards:
#  a: 29
#  b: 26
# Extra keyword 'CD1_1'  in a: 0.2076
# Extra keyword 'CD1_2'  in a: 0.0
# Extra keyword 'CD2_1'  in a: 0.0
# Extra keyword 'CD2_2'  in a: 0.1038
# Extra keyword 'CDELT1' in a: 0.1038
# Extra keyword 'CDELT2' in a: 0.1038
# Extra keyword 'CRPIX1' in a: -34.0
# Extra keyword 'CRPIX2' in a: 2041.0
# Extra keyword 'CRVAL1' in a: 164.98110962
# Extra keyword 'CRVAL2' in a: 44.34089279
# Extra keyword 'CTYPE1' in a: 'RA---TAN'
# Extra keyword 'CTYPE2' in a: 'WAVELENGTH'
# Extra keyword 'DATE'   in b: '2017-09-01T13:08:01'
# Extra keyword 'IRAF-TLM' in b: '2017-09-01T13:08:05'
# Extra keyword 'LTM1_1' in b: 1.0
# Extra keyword 'LTM2_2' in b: 1.0
# Extra keyword 'ORIGIN' in b: 'NOAO-IRAF FITS Image Kernel July 2003'
# Extra keyword 'WAT0_001' in b: 'system=physical'
# Extra keyword 'WAT1_001' in b: 'wtype=linear'
# Extra keyword 'WAT2_001' in b: 'wtype=linear'
# Extra keyword 'WCSDIM' in b: 2
# Keyword BSCALE   has different comments:
#    a> Real=fits-value*BSCALE+BZERO
#    b> REAL = TAPE*BSCALE + BZERO
# Keyword BZERO    has different comments:
#    a> Real=fits-value*BSCALE+BZERO
```
