### ISSUE TITLE
UnicodeDecodeError Saving votables from astroquery searches

### ISSUE THREAD

**Issue by privong** [astropy/astropy#6836]
I am encountering `UnicodeDecodeError`s while attempting to write `astroquery` results to votables. An example query which fails upon trying to save to votable format is:

```
from astroquery.alma import Alma
import astropy.units as u
res = Alma.query_object('PKS1830-211', 1 * u.arcmin)
res.write('PKS1830-211.xml', format='votable')
```

The resulting error is:
```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-7-1afec7db28b5> in <module>()
----> 1 res.write('PKS1830-211.xml', format='votable')

/usr/lib/python3.6/site-packages/astropy/table/table.py in write(self, *args, **kwargs)
   2548         passed through to the underlying data reader (e.g. `~astropy.io.ascii.write`).
   2549         """
-> 2550         io_registry.write(self, *args, **kwargs)
   2551
   2552     def copy(self, copy_data=True):

/usr/lib/python3.6/site-packages/astropy/io/registry.py in write(data, *args, **kwargs)
    579
    580     writer = get_writer(format, data.__class__)
--> 581     writer(data, *args, **kwargs)
    582
    583

/usr/lib/python3.6/site-packages/astropy/io/votable/connect.py in write_table_votable(input, output, table_id, overwrite, tabledata_format)
    160
    161     # Write out file
--> 162     table_file.to_xml(output, tabledata_format=tabledata_format)
    163
    164

/usr/lib/python3.6/site-packages/astropy/io/votable/tree.py in to_xml(self, fd, compressed, tabledata_format, _debug_python_based_parser, _astropy_version)
   3484                 for element_set in element_sets:
   3485                     for element in element_set:
-> 3486                         element.to_xml(w, **kwargs)
   3487
   3488     def iter_tables(self):

/usr/lib/python3.6/site-packages/astropy/io/votable/tree.py in to_xml(self, w, **kwargs)
   3176                                 self.resources):
   3177                 for element in element_set:
-> 3178                     element.to_xml(w, **kwargs)
   3179
   3180     def iter_tables(self):

/usr/lib/python3.6/site-packages/astropy/io/votable/tree.py in to_xml(self, w, **kwargs)
   2753                 with w.tag('DATA'):
   2754                     if format == 'tabledata':
-> 2755                         self._write_tabledata(w, **kwargs)
   2756                     elif format == 'binary':
   2757                         self._write_binary(1, w, **kwargs)

/usr/lib/python3.6/site-packages/astropy/io/votable/tree.py in _write_tabledata(self, w, **kwargs)
   2778                 tablewriter.write_tabledata(
   2779                     w.write, array.data, array.mask, fields,
-> 2780                     supports_empty_values, indent, 1 << 8)
   2781             else:
   2782                 write = w.write

/usr/lib/python3.6/site-packages/astropy/io/votable/converters.py in output(self, value, mask)
    354             return ''
    355         if not isinstance(value, str):
--> 356             value = value.decode('ascii')
    357         return xml_escape_cdata(value)
    358

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 211: ordinal not in range(128)
```

A temporary workaround for me has been to exit `votable/converters.py` to all decode to `utf-8` instead of `ascii`, but I am not sure this is a robust fix. I saw there were some other issues relating to UnicodeDecodeErrors, but not seemed to specifically address this. But if I've missed a known fix or workaround, please let me know.

My software versions are:
* python: 3.6.3
* astropy: 2.0.2
* numpy: 1.13.3

**Comment by pllim** [comment]
Hi. Please run `volint` on that XML file and see if it gives any errors/warnings. Also, please attach a snippet of the table (enough to reproduce the error) for further investigation, if necessary. Thanks!

**Comment by privong** [comment]
I'm not quite sure which XML file you mean. The `write()` call results in a partially-written table. So running `volint` on that table fails and gives:

```
Validation report for PKS1830-211.xml

72: W06: Invalid UCD 'phys.polarization;meta.code': Primary word
  'meta.code' is not valid as a secondary word
   <FIELD ID="Pol_products" arraysize="64" datatype="char" name="Po...
   ^

96: W50: Invalid unit string 'mJy/beam'
   <FIELD ID="Continuum_sensitivity" datatype="double" name="Contin...
   ^

153: W06: Invalid UCD 'meta.flag': Unknown word 'meta.flag'
   <FIELD ID="QA2_Status" arraysize="1" datatype="char" name="QA2 S...
   ^

Traceback (most recent call last):
  File "/usr/bin/volint", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/astropy/io/votable/volint.py", line 18, in main
    table.validate(args.filename[0])
  File "/usr/lib/python3.6/site-packages/astropy/io/votable/table.py", line 278, in validate
    line = xml_lines[w['nline'] - 1]
IndexError: list index out of range
```

Running `volint` on the XML file that completely writes out (after my changing the `decode()` calls to `utf-8`) gives:

```
Validation report for PKS1830-211-complete.xml

72: W06: Invalid UCD 'phys.polarization;meta.code': Primary word
  'meta.code' is not valid as a secondary word
   <FIELD ID="Pol_products" arraysize="64" datatype="char" name="Po...
   ^

96: W50: Invalid unit string 'mJy/beam'
   <FIELD ID="Continuum_sensitivity" datatype="double" name="Contin...
   ^

153: W06: Invalid UCD 'meta.flag': Unknown word 'meta.flag'
   <FIELD ID="QA2_Status" arraysize="1" datatype="char" name="QA2 S...
   ^
```

Reading the XML file generated with the `utf-8` works fine:

```
In [1]: import astropy.io.votable as vot

In [2]: a = vot.parse('PKS1830-211-full.xml')
WARNING: W06: PKS1830-211-full.xml:72:3: W06: Invalid UCD 'phys.polarization;meta.code': Primary word 'meta.code' is not valid as a secondary word [astropy.io.votable.tree]
WARNING: W50: PKS1830-211-full.xml:96:3: W50: Invalid unit string 'mJy/beam' [astropy.io.votable.tree]
WARNING: W06: PKS1830-211-full.xml:153:3: W06: Invalid UCD 'meta.flag': Unknown word 'meta.flag' [astropy.io.votable.tree]
```

So I haven't been able to generate an output XML table that is broken upon reading back in. I only get the `UnicodeDecodeError` when trying to write a table directly from an ALMA query.

**Comment by privong** [comment]
For what it's worth, I think the character which causes the specific failure for this query is a "ü" in the Co-I list. Presumably it is something similar for the other ALMA queries which have resulted in votable saving issues.

**Comment by pllim** [comment]
I now recall that I fixed this problem over at `astroquery.vo_conesearch` back when it was part of `astropy.vo` at #4757. My recommendation is to have ALMA apply a similar fix downstream.

**Comment by bsipocz** [comment]
@pllim - can you open an issue for that (or a fix)?

**Comment by pllim** [comment]
@bsipocz , sure, I'll take a look over at `astroquery` soon.

**Comment by privong** [comment]
@pllim I think the bug is inside `astropy`, not `astoquery`? `astroquery.alma.Alma.query_object()` returns an astropy `Table` object (https://astroquery.readthedocs.io/en/latest/api/astroquery.alma.AlmaClass.html#astroquery.alma.AlmaClass.query_object and http://docs.astropy.org/en/latest/api/astropy.table.Table.html#astropy.table.Table). So the `write()` function is in `astropy`.

**Comment by pllim** [comment]
See https://github.com/astropy/astroquery/issues/718#issuecomment-353178471
