### ISSUE TITLE
test runner with -t option fails on python 3.5

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#6884]
Sometime in the last month or so, *something* has caused the ``-t`` command on the test runner to start failing in Python 3.5.  I've included a test run below.  A few relevant facts:

* It happens on Pytest 3.1.2 or 3.2.1
* It does *not* seem to happen if you give a path to a directory instead of a file.  E.g., the traceback below is for ``python setup.py test -t astropy/io/fits/tests/test_checksum.py``, but ``python setup.py test -t astropy/io/fits/tests`` works just fine.
* It works on Python 3.6.x
* It happens pretty much anywhere in the test suite, but the fail is always wherever the first relative import is.

```
platform darwin -- Python 3.5.2, pytest-3.1.1, py-1.4.32, pluggy-0.4.0

Running tests with Astropy version 3.0.dev20678.
Running tests in astropy/io/fits/tests/test_checksum.py.

...

plugins: doctestplus-0.1.1, openfiles-0.1.0, remotedata-0.2.0
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/erik/miniconda3/lib/python3.5/site-packages/_pytest/main.py", line 105, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/erik/miniconda3/lib/python3.5/site-packages/_pytest/main.py", line 140, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/Users/erik/miniconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/erik/miniconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/erik/miniconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/Users/erik/miniconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/erik/miniconda3/lib/python3.5/site-packages/_pytest/main.py", line 150, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/Users/erik/miniconda3/lib/python3.5/site-packages/_pytest/main.py", line 604, in perform_collect
INTERNALERROR>     items = self._perform_collect(args, genitems)
INTERNALERROR>   File "/Users/erik/miniconda3/lib/python3.5/site-packages/_pytest/main.py", line 623, in _perform_collect
INTERNALERROR>     parts = self._parsearg(arg)
INTERNALERROR>   File "/Users/erik/miniconda3/lib/python3.5/site-packages/_pytest/main.py", line 717, in _parsearg
INTERNALERROR>     parts[0] = self._tryconvertpyarg(parts[0])
INTERNALERROR>   File "/Users/erik/miniconda3/lib/python3.5/site-packages/_pytest/main.py", line 697, in _tryconvertpyarg
INTERNALERROR>     loader = pkgutil.find_loader(x)
INTERNALERROR>   File "/Users/erik/miniconda3/lib/python3.5/pkgutil.py", line 485, in find_loader
INTERNALERROR>     spec = importlib.util.find_spec(fullname)
INTERNALERROR>   File "/Users/erik/miniconda3/lib/python3.5/importlib/util.py", line 88, in find_spec
INTERNALERROR>     parent = __import__(parent_name, fromlist=['__path__'])
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
INTERNALERROR>   File "/Users/erik/miniconda3/lib/python3.5/site-packages/_pytest/assertion/rewrite.py", line 216, in load_module
INTERNALERROR>     py.builtin.exec_(co, mod.__dict__)
INTERNALERROR>   File "/private/var/folders/7_/0n3gbrls1sb2vn6xjprw8c280000gn/T/astropy-test-kk0nqpm2/lib.macosx-10.6-x86_64-3.5/astropy/io/fits/tests/test_checksum.py", line 9, in <module>
INTERNALERROR>     from .test_table import comparerecords
INTERNALERROR> SystemError: Parent module '' not loaded, cannot perform relative import
```

**Comment by eteq** [comment]
One other curious note: doing`python setup.py test -P coordinates --args="-k <testname>` works even if <testname> would resolve to the exact same set of tests as the `-t` invocation does.  So it's something about the `-t` option, not the test itself?
