### ISSUE TITLE
Length > 1 dimensionless arrays can't be cast to float

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#6974]
The following example fails, but I would expect x to be dimensionless and the casting to float to work fine:
```python
import astropy.units as u
import numpy as np

x = np.array([1, 2]) * u.m / (np.array([2, 4]) * u.m)
print(x)
print(float(x))
```

Output:
```python
[ 0.5  0.5]
Traceback (most recent call last):
  File "/Users/dstansby/miniconda3/lib/python3.6/site-packages/astropy/units/quantity.py", line 1201, in __float__
    return float(self.to_value(dimensionless_unscaled))
TypeError: only length-1 arrays can be converted to Python scalars

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "datetime64.py", line 6, in <module>
    print(float(x))
  File "/Users/dstansby/miniconda3/lib/python3.6/site-packages/astropy/units/quantity.py", line 1203, in __float__
    raise TypeError('only dimensionless scalar quantities can be '
TypeError: only dimensionless scalar quantities can be converted to Python scalars
```

**Comment by adrn** [comment]
This is because arrays can't be turned into scalar values. The Python builtin `float()` function can only operate on scalar values. You will get a similar error if you try, e.g.:
```python
float(np.array([1, 2]))
```

To get a plain array out from a dimensionless quantity array, you can do:
```python
x.astype(np.float)
```

**Comment by dstansby** [comment]
🤦‍♂️ thanks
