### ISSUE TITLE
Error building executable using pyinstaller

### ISSUE THREAD

**Issue by lzkelley** [astropy/astropy#7052]
Building executables which include `astropy` seem to have a history of issues (e.g. https://github.com/astropy/astropy/pull/960#issuecomment-355678708).  Initially I was getting an,
`ImportError: Astropy requires the 'six' module of minimum version 1.10`, which I solved by using a trick given in the above PR: 

> I was able to get this to work using PyInstaller with the following pyinstaller options` --exclude-module astropy` and `--add-data path_to/astropy:astropy` -- @fridgerator 

Now I get the new error:

```
Traceback (most recent call last):
  File "pyapi.py", line 10, in <module>
    import cosmopy
  File "/Users/lzkelley/Programs/cosmo/ve_test/vetest/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/cosmopy/__init__.py", line 9, in <module>
  File "/var/folders/wr/_dhmn18x1dj6t8ytjjd9rsxh0000gn/T/_MEIhGawWS/astropy/constants/__init__.py", line 28, in <module>
    from .constant import Constant, EMConstant
  File "/var/folders/wr/_dhmn18x1dj6t8ytjjd9rsxh0000gn/T/_MEIhGawWS/astropy/constants/constant.py", line 11, in <module>
    from ..units.core import Unit, UnitsError
  File "/var/folders/wr/_dhmn18x1dj6t8ytjjd9rsxh0000gn/T/_MEIhGawWS/astropy/units/__init__.py", line 14, in <module>
    from .core import *
  File "/var/folders/wr/_dhmn18x1dj6t8ytjjd9rsxh0000gn/T/_MEIhGawWS/astropy/units/core.py", line 23, in <module>
    from .utils import (is_effectively_unity, sanitize_scale, validate_power,
  File "/var/folders/wr/_dhmn18x1dj6t8ytjjd9rsxh0000gn/T/_MEIhGawWS/astropy/units/utils.py", line 16, in <module>
    from fractions import Fraction
ImportError: No module named 'fractions'
[2338] Failed to execute script pyapi
```

I'm using a virtualenv named `vetest` in the directory `ve_test`, trying to run with the command:
`pyinstaller -F pyapi.py --exclude-module astropy --add-data /Users/lzkelley/Programs/cosmo/ve_test/vetest/lib/python3.5/site-packages/astropy:astropy`

The full output from `pyinstaller` is attached.

[out.txt](https://github.com/astropy/astropy/files/1608048/out.txt)

---------

An additional issue is that the resulting executable is >200MB, is that normal?  The application I'm trying to package is really just using the `astropy.cosmology.LambdaCDM` class.  Might there be a better way to include that alone?

**Comment by pllim** [comment]
Re: cosmology -- Discussion to separate it out comes up once in a while (e.g., #6567) but for now, the consensus is to keep it in the core.

**Comment by astrofrog** [comment]
@lzkelley - can you try with the latest developer version of astropy, without the 'six' trick? (since six is no longer required/included).

**Comment by lzkelley** [comment]
Ran into a (seemingly) [unrelated pyinstaller error](https://github.com/pyinstaller/pyinstaller/issues/3192) on a different system (standard system is in for repairs at the moment)... will update when I can try again.

**Comment by astrofrog** [comment]
I just tried running:

```
pyinstaller -F app.py 
```

with the latest astropy, and the six issue is gone but this is still a problem:

```
Traceback (most recent call last):
  File "app.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/Users/tom/miniconda3/envs/dev/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "astropy/__init__.py", line 122, in <module>
  File "astropy/__init__.py", line 129, in Conf
  File "astropy/config/configuration.py", line 229, in __init__
RuntimeError: Cannot automatically determine get_config module, because it is not called from inside a valid module
[28432] Failed to execute script app
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by lzkelley** [comment]
Thanks @astrofrog, the @maartenbreddels approach does seem to work (at least in python3.5).  I would volunteer for reapplying #960, but I really have no idea what it's doing...

**Comment by lzkelley** [comment]
@astrofrog  I'm trying the same approach in python2.7, but in that case I can't even get the dev version of astropy to install... is that a separated problem?

```
$ pip install git+https://github.com/astropy/astropy.git@v3.0rc1

Collecting git+https://github.com/astropy/astropy.git@v3.0rc1
  Cloning https://github.com/astropy/astropy.git (to v3.0rc1) to /private/var/folders/wr/_dhmn18x1dj6t8ytjjd9rsxh0000gn/T/pip-W7jspE-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/wr/_dhmn18x1dj6t8ytjjd9rsxh0000gn/T/pip-W7jspE-build/setup.py", line 8, in <module>
        import ah_bootstrap
      File "ah_bootstrap.py", line 885, in <module>
        BOOTSTRAPPER = _Bootstrapper.main()
      File "ah_bootstrap.py", line 221, in main
        bootstrapper.run()
      File "ah_bootstrap.py", line 307, in run
        dist = method()
      File "ah_bootstrap.py", line 365, in get_local_directory_dist
        dist = self._directory_import()
      File "ah_bootstrap.py", line 462, in _directory_import
        ['egg_info'])
      File "/Users/lzkelley/Programs/electron/test-cosmo/src/test-env-27/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/lzkelley/Programs/electron/test-cosmo/src/test-env-27/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/lzkelley/Programs/electron/test-cosmo/src/test-env-27/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/Users/lzkelley/Programs/electron/test-cosmo/src/test-env-27/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/Users/lzkelley/Programs/electron/test-cosmo/src/test-env-27/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/Users/lzkelley/Programs/electron/test-cosmo/src/test-env-27/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/Users/lzkelley/Programs/electron/test-cosmo/src/test-env-27/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/Users/lzkelley/Programs/electron/test-cosmo/src/test-env-27/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/private/var/folders/wr/_dhmn18x1dj6t8ytjjd9rsxh0000gn/T/pip-W7jspE-build/astropy_helpers/setup.py", line 7, in <module>
        from astropy_helpers.setup_helpers import register_commands, get_package_info
      File "/private/var/folders/wr/_dhmn18x1dj6t8ytjjd9rsxh0000gn/T/pip-W7jspE-build/astropy_helpers/astropy_helpers/__init__.py", line 46, in <module>
        import builtins
    ImportError: No module named builtins

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/wr/_dhmn18x1dj6t8ytjjd9rsxh0000gn/T/pip-W7jspE-build/
```

**Comment by astrofrog** [comment]
@lzkelley - the developer version of Astropy now only supports Python 3

**Comment by fockez** [comment]
I wait for the astropy 3.0 for a long time, because it no longer relies on six module. I use pyinstaller on windows to pack the app with astropy 30.rc2, and it also goes wrong.
The log is attached.
[astropy.zip](https://github.com/astropy/astropy/files/1715836/astropy.zip)

**Comment by pllim** [comment]
Seems like a different error than above, so... progress? 😬 
```
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\ast.py", line 263, in generic_visit
    self.visit(value)
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\ast.py", line 253, in visit
    return visitor(node)
RecursionError: maximum recursion depth exceeded
```

**Comment by fockez** [comment]
I don't know which one causes the problem, pyinstaller or astropy. https://github.com/pyinstaller/pyinstaller/pull/3061, this thread said using the latest dev version should be ok. But no luck with astropy.

**Comment by pllim** [comment]
Since I see some `python2.7` is traceback above, I just want to point out that you can only use Python 3 with Astropy 3.0.

**Comment by fockez** [comment]
I just mean that pyinstaller community has the similar error report. for me, i use anaconda3 with python3.6. I know that astropy 3.0 can only work with python3, I hope this will be better bacause with the former version, the six module always cause problem.

**Comment by lamourj** [comment]
I don't have a solution, but a potential workaround which worked for me was the following:
In the `*.spec` file, add:
```
import astropy
astropy_path, = astropy.__path__
```

Then in the Analysis, add `(astropy_path, 'astropy')` into the `datas` list and `'astropy'` in the `excludes` list.

Hope this helps.

**Comment by ocroquette** [comment]
Thanks @lamourj for the workaround. I had also to add the astropy dependencies as hiddenimports explicitly though:

```
# Integrate astropy as data directory instead of module:
import astropy
astropy_path, = astropy.__path__
datas=[(astropy_path, 'astropy')]
excludes=['astropy']
hiddenimports=['shelve', 'csv']    # Required by astropy
```

**Comment by datainvestor** [comment]
@ocroquette I have same problem. I tried putting those into the main.spec file however running the exe again yielded same error. Did you change anything again or did you added some flags when building the exe file?

**Comment by astrofrog** [comment]
Just for the record, I recently added a hook for astropy to pyinstaller:

https://github.com/pyinstaller/pyinstaller/pull/4274

so be sure to try with the latest version of pyinstaller.

**Comment by datainvestor** [comment]
I'm using version pyinstaller ver. 3.5, i think thats the newest?

**Comment by ocroquette** [comment]
@datainvestor Are you calling pyinstaller on the spec file, or the py file? It should be the former. See https://pyinstaller.readthedocs.io/en/stable/spec-files.html

**Comment by burhankhanlodhy** [comment]
I am unsure how to use frozen_astropy with my own file. Can someone please elaborate?

**Comment by burhankhanlodhy** [comment]
`import numpy as np
import pandas as pd
from astropy.io import fits
from photutils import DAOStarFinder
from astropy.stats import mad_std
import matplotlib.pyplot as plt
from photutils import aperture_photometry, CircularAperture
def photometry(filepath):
 hdulist  = fits.open(filepath, ignore_missing_end=True)
 hdu = hdulist[0]
 hdu.data.shape
 image = hdu.data.astype(float)
 image -= np.median(image)
 bkg_sigma = mad_std(image)
 daofind = DAOStarFinder(fwhm=41., threshold=40.*bkg_sigma)
 sources = daofind(image)    #Save Stellar Sources from DOA Star Algorithm
 for col in sources.colnames:
     sources[col].info.format = '%.8g'  # for consistent table output
 print(pd)
 print(sources)
 # Perform Aperture Photometry
 positions = (sources['xcentroid'], sources['ycentroid'])
 apertures = CircularAperture(positions, r=17.)
 phot_table = aperture_photometry(image, apertures)
 for col in phot_table.colnames:
     phot_table[col].info.format = '%.8g'  # for consistent table output
 filedest1 = input("Where to Save the result:")
 filedest2 = input("Where to Save the result 2:")
 print(phot_table)
 np.savetxt(filedest1, (sources), delimiter=',')  # Save Result in CSV
 np.savetxt(filedest2, (phot_table), delimiter=',')  # Save Result in CSV
 plt.imshow(image, cmap='gray_r', origin='lower')
 apertures.plot(color='blue', lw=1.5, alpha=0.5)
 plt.show()

if __name__ == '__main__':
 filepath = input("Enter Your File Path:")
 photometry(filepath)`

That is the code I am using and I am currently unable to convert it into exe file. every time I try it gives error regarding astropy. I have checked a sample code without astropy and it works but, I seriously need this to work. Hope anyone could give a solution.

**Comment by burhankhanlodhy** [comment]
Ok so i found the solution here [https://stackoverflow.com/a/35605281]

**Comment by paulmueller** [comment]
with PyInstaller 3.5 and astropy 3.2.1 I get a ``RuntimeError: Cannot automatically determine get_config module`` when I try to start the application:
![image](https://user-images.githubusercontent.com/2853022/64242336-a1ed9980-cf05-11e9-92ef-60fa43abc36c.png)

This is the appveyor build job: https://ci.appveyor.com/project/paulmueller/pyscanfcs/builds/27079725

**Comment by burhankhanlodhy** [comment]
@paulmueller  That is because of astropy. You should consider using the spec file to build the exe instead of the .py file. You can try this workaround I found and it works for me. If you have your .cpec file created just try to follow the workaround i have posted and it might work for you as well.

import astropy
astropy_path, = astropy.__path__
a = Analysis(['CLI.py'],
             pathex=['C:\\Users\\Burhan\\.PyCharmCE2019.2\\config\\scratches'],
             binaries=[],
             datas=[(astropy_path, 'astropy')],
             hiddenimports=['shelve', 'csv'],
             hookspath=[],
             runtime_hooks=[],
             excludes=['astropy'],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='CLI',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='CLI')

**Comment by paulmueller** [comment]
@burhankhanlodhy thanks this worked for me.

@astrofrog Shouldn't it be possible to add this to the PyInstaller hook? Otherwise this hook would somehow miss its intended purpose.

**Comment by astrofrog** [comment]
@paulmueller - can you check whether everything works fine with the latest developer version of astropy and pyinstaller? (it should)

**Comment by paulmueller** [comment]
yes, works!

**Comment by astrofrog** [comment]
Just to add that https://github.com/astropy/astropy/pull/8795 is merged, so we should hopefully be able to make sure things continue to work in future. If anyone still has issues with pyinstaller and astropy, please open a new issue!
