### ISSUE TITLE
python3.6u running pytest got the traceback 

### ISSUE THREAD

**Issue by liut12bw** [astropy/astropy#7099]
Not sure if it is already a known issue.  I have installed python 3.6 & pip 3.6 in CentOS 7.   
```
(# pytest test_cases/connectivity/connectivity_wlan0.py --topology topology/cs1.yaml )

Traceback (most recent call last):
 File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 342, in _getconftestmodules
   return self._path2confmods[path]
KeyError: local('/opt/auto/test-automation/test_cases/connectivity/connectivity_wlan0.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 342, in _getconftestmodules
   return self._path2confmods[path]
KeyError: local('/opt/auto/test-automation/test_cases/connectivity')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 373, in _importconftest
   return self._conftestpath2mod[conftestpath]
KeyError: local('/opt/auto/test-automation/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 379, in _importconftest
   mod = conftestpath.pyimport()
 File "/usr/lib/python3.6/site-packages/py/_path/local.py", line 662, in pyimport
   __import__(modname)
 File "<frozen importlib._bootstrap>", line 971, in _find_and_load
 File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
 File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
 File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
 File "/usr/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
   py.builtin.exec_(co, mod.__dict__)
 File "/opt/auto/test-automation/conftest.py", line 9, in <module>
   from library.lwm import lwm
 File "/opt/auto/test-automation/library/lwm.py", line 331
   <<<<<<< HEAD
    ^
SyntaxError: invalid syntax
ERROR: could not load /opt/auto/test-automation/conftest.py
```

**Comment by drdavella** [comment]
Hi @liut12bw. Thanks for the report. It's not clear from the traceback how this code is related to Astropy. Can you provide more details?

In any case, it looks like the error is the result of an unresolved merge conflict in git:
```
File "/opt/auto/test-automation/library/lwm.py", line 331
<<<<<<< HEAD
^
SyntaxError: invalid syntax
```

**Comment by liut12bw** [comment]
Sorry it is my test automation script problem.  Just closing this.  Thx!
