### ISSUE TITLE
conftest.py fails on my system RD 2

### ISSUE THREAD

**Issue by mtsolmn** [astropy/astropy#7192]
I'm sure this is a system-specific problem, but I cannot find any solutions to this error when running the full test suite:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/_pytest/config.py", line 366, in _importconftest
    mod = conftestpath.pyimport()
  File "/usr/local/lib/python2.7/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "/usr/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 213, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/usr/local/lib/python2.7/site-packages/py/_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "/usr/local/lib/python2.7/site-packages/astropy/conftest.py", line 8, in <module>
    import matplotlib
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1182, in <module>
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1015, in rc_params
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 846, in matplotlib_fname
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 336, in wrapper
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 749, in _get_data_path_cached
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 744, in _get_data_path
RuntimeError: Could not find the matplotlib data files
ERROR: could not load /usr/local/lib/python2.7/site-packages/astropy/conftest.py
```
If anyone of you fine folks could give me a hand, it would be much appreciated. Thanks.

**Comment by astrofrog** [comment]
@mtsolmn - can you confirm that just typing 'import matplotlib' in a Python session works?

**Comment by mtsolmn** [comment]
Yes, I have both 2.7 and 3.6 of python installed on my mac through homebrew - with separate installations of all my modules for each version. When I installed astropy for 3.6 and ran the tests they pass, but the above error is what I get when I installed it on 2.7. To answer your initial question, import matplotlib does work.

**Comment by pllim** [comment]
Is this still a problem? At any rate, our Python 2 support is limited to LTS, so closing.

**Comment by mtsolmn** [comment]
I honestly cannot say I remember whether I found a fix to the issue or just migrated my workflow to Python 3 - the project was so long ago. Thanks for checking in though.
