### ISSUE TITLE
pkg_resources.VersionConflict

### ISSUE THREAD

**Issue by MW-L** [astropy/astropy#7291]
When running: 
python setup.py test

I got this error:
```
Using /Users/fli/astropy/.eggs/pytest_doctestplus-0.1.2-py3.6.egg
Traceback (most recent call last):
  File "setup.py", line 119, in <module>
    **package_info
  File "/Users/fli/anaconda/envs/ENV/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/fli/anaconda/envs/ENV/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/fli/anaconda/envs/ENV/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/fli/astropy/astropy/tests/command.py", line 186, in run
    self.distribution.fetch_build_eggs(self.distribution.tests_require)
  File "/Users/fli/anaconda/envs/ENV/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py", line 361, in fetch_build_eggs
  File "/Users/fli/anaconda/envs/ENV/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 851, in resolve
  File "/Users/fli/anaconda/envs/ENV/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1116, in best_match
  File "/Users/fli/anaconda/envs/ENV/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 720, in find
pkg_resources.VersionConflict: (pytest 3.0.7 (/Users/fli/anaconda/envs/ENV/lib/python3.6/site-packages), Requirement.parse('pytest>=3.1.0'))
```

**Comment by pllim** [comment]
Hi. You need to upgrade your `pytest` from 3.0.7 to 3.1.0 or greater. Since you appear to be using Anaconda, you can try `conda update pytest`.

**Comment by MW-L** [comment]
It passed the test after I updated pytest. Thank you!

**Comment by pllim** [comment]
Good to hear! Thanks for letting us know.
