### ISSUE TITLE
error in setup.py while running build

### ISSUE THREAD

**Issue by amous4822** [astropy/astropy#7306]
```
C:\Users\Desktop\astropy>python setup.py build
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from astropy_helpers.setup_helpers import register_commands, get_package_info
  File "C:\Users\Desktop\astropy\astropy_helpers\astropy_helpers\__init__.py", line 46, in <module>
    import builtins
ImportError: No module named builtins
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import ah_bootstrap
  File "C:\Users\Desktop\astropy\ah_bootstrap.py", line 923, in <module>
    BOOTSTRAPPER = _Bootstrapper.main()
  File "C:\Users\Desktop\astropy\ah_bootstrap.py", line 226, in main
    bootstrapper.run()
  File "C:\Users\Desktop\astropy\ah_bootstrap.py", line 324, in run
    dist = method()
  File "C:\Users\Desktop\astropy\ah_bootstrap.py", line 382, in get_local_directory_dist
    dist = self._directory_import()
  File "C:\Users\Desktop\astropy\ah_bootstrap.py", line 480, in _directory_import
    sp.check_output([sys.executable, 'setup.py', 'egg_info'], cwd=path)
  File "C:\Python27\lib\subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'setup.py', 'egg_info']' returned non-zero exit status 1

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

C:\Users\Desktop\astropy>python setup.py build --help
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from astropy_helpers.setup_helpers import register_commands, get_package_info
  File "C:\Users\Desktop\astropy\astropy_helpers\astropy_helpers\__init__.py", line 46, in <module>
    import builtins
ImportError: No module named builtins
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import ah_bootstrap
  File "C:\Users\Desktop\astropy\ah_bootstrap.py", line 923, in <module>
    BOOTSTRAPPER = _Bootstrapper.main()
  File "C:\Users\Desktop\astropy\ah_bootstrap.py", line 226, in main
    bootstrapper.run()
  File "C:\Users\Desktop\astropy\ah_bootstrap.py", line 324, in run
    dist = method()
  File "C:\Users\Desktop\astropy\ah_bootstrap.py", line 382, in get_local_directory_dist
    dist = self._directory_import()
  File "C:\Users\Desktop\astropy\ah_bootstrap.py", line 480, in _directory_import
    sp.check_output([sys.executable, 'setup.py', 'egg_info'], cwd=path)
  File "C:\Python27\lib\subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'setup.py', 'egg_info']' returned non-zero exit status 1
```
astropy 2.0.5 / Numpy 1.14.2 / Windows 10

**Comment by bsipocz** [comment]
@amous4822 - It seems that you're trying to build the dev version of astropy? 

Please not that it requires Python 3.5+ while you attempt to build it with Python 2.7

**Comment by drdavella** [comment]
@bsipocz I wonder if we could have something at the top of `setup.py` that could prevent these kinds of errors. For example, see what I have done in ASDF:

https://github.com/spacetelescope/asdf/blob/e8cd31b7ba0cd0d1e1980f138bc7b66341004e64/setup.py#L1-L7

This could easily go in the package template so it could prevent these kinds of issues for all affiliated packages.

**Comment by bsipocz** [comment]
We already have that in `astropy/__init__.py`. I suppose we can repeat it in setup.py, too (as it already came up in https://github.com/astropy/astropy/pull/6595#issuecomment-331552442 but apparently was overseen).

**Comment by drdavella** [comment]
The advantage of doing it in `setup.py` is that it will prevent builds and installation on unsupported platforms as well. So, if someone tries to install (even from pip) in an unsupported environment, they'll get a helpful error message.

This actually could probably be hidden at the top of `ah_bootstrap.py` if that seemed like a better solution.

**Comment by pllim** [comment]
At one of the Python conferences, one of the talks is about transition from PY2 to PY3 for Jupyter notebooks. One of their recommendations is to have this check in `setup.py` as well.

**Comment by bsipocz** [comment]
OK, let's have this in setup.py, too. (Btw, pip should understand the requirements already (assuming that users have recent enough pip))
