### ISSUE TITLE
CSV table writer fails with cryptic message when meta contains "comments" key

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#7357]
I ran into this cryptic TypeError (with current Astropy, `3.1.dev21648`)
```
>>> from astropy.table import Table
>>> table = Table.read('https://www.mpi-hd.mpg.de/hfm/HESS/hgps/data/hgps_catalog_v1.fits.gz', hdu=1)
Downloading https://www.mpi-hd.mpg.de/hfm/HESS/hgps/data/hgps_catalog_v1.fits.gz
|=====================================================================================================================|  49k/ 49k (100.00%)         0s
>>> table.write('test.csv', format='ascii.csv', overwrite=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/astropy/table/table.py", line 2560, in write
    io_registry.write(self, *args, **kwargs)
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/astropy/io/registry.py", line 560, in write
    writer(data, *args, **kwargs)
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/astropy/io/ascii/connect.py", line 43, in io_write
    return write(table, filename, format=format, **kwargs)
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/astropy/io/ascii/ui.py", line 880, in write
    writer.write(table, output)
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/astropy/io/ascii/fastbasic.py", line 194, in write
    self._write(table, output, {'fill_values': [(core.masked, '')]})
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/astropy/io/ascii/fastbasic.py", line 171, in _write
    writer.write(output, header_output, output_types)
  File "astropy/io/ascii/cparser.pyx", line 1024, in astropy.io.ascii.cparser.FastWriter.write
  File "astropy/io/ascii/cparser.pyx", line 1004, in astropy.io.ascii.cparser.FastWriter._write_header
  File "astropy/io/ascii/cparser.pyx", line 995, in astropy.io.ascii.cparser.FastWriter._write_comments
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

I think the error is a bug in the CSV writer when `meta` contains a key named `comments`.
Here's a minimal example to trigger similar errors:
```
>>> table = Table(data={'a': [1, 2]}, meta={'comments': 'spam'})
>>> table
<Table length=2>
  a  
int64
-----
    1
    2
>>> table.meta
{'comments': 'spam'}
>>> table.write('test.csv', format='ascii.csv', overwrite=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/astropy/table/table.py", line 2560, in write
    io_registry.write(self, *args, **kwargs)
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/astropy/io/registry.py", line 560, in write
    writer(data, *args, **kwargs)
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/astropy/io/ascii/connect.py", line 43, in io_write
    return write(table, filename, format=format, **kwargs)
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/astropy/io/ascii/ui.py", line 880, in write
    writer.write(table, output)
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/astropy/io/ascii/fastbasic.py", line 194, in write
    self._write(table, output, {'fill_values': [(core.masked, '')]})
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/astropy/io/ascii/fastbasic.py", line 170, in _write
    writer = cparser.FastWriter(table, **write_kwargs)
  File "astropy/io/ascii/cparser.pyx", line 966, in astropy.io.ascii.cparser.FastWriter.__cinit__
TypeError: Expected list, got str
```

That error is better, but still doesn't mention that the problem is related to the `comments` key in `table.meta`.

Let's try  putting a list like the TypeError message suggested:
```
>>> table = Table(data={'a': [1, 2]}, meta={'comments': ['spam']})
>>> table.write('test.csv', format='ascii.csv', overwrite=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/astropy/table/table.py", line 2560, in write
    io_registry.write(self, *args, **kwargs)
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/astropy/io/registry.py", line 560, in write
    writer(data, *args, **kwargs)
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/astropy/io/ascii/connect.py", line 43, in io_write
    return write(table, filename, format=format, **kwargs)
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/astropy/io/ascii/ui.py", line 880, in write
    writer.write(table, output)
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/astropy/io/ascii/fastbasic.py", line 194, in write
    self._write(table, output, {'fill_values': [(core.masked, '')]})
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/astropy/io/ascii/fastbasic.py", line 171, in _write
    writer.write(output, header_output, output_types)
  File "astropy/io/ascii/cparser.pyx", line 1024, in astropy.io.ascii.cparser.FastWriter.write
  File "astropy/io/ascii/cparser.pyx", line 1004, in astropy.io.ascii.cparser.FastWriter._write_header
  File "astropy/io/ascii/cparser.pyx", line 995, in astropy.io.ascii.cparser.FastWriter._write_comments
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Now we get the
```
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
that I got from my actual FITS file that had `COMMENTS` in the header.

@taldcroft or anyone working on table these days - can this be fixed or the error messages improved?

**Comment by taldcroft** [comment]
Does this occur with the pure Python writer?

**Comment by cdeil** [comment]
How do I avoid Astropy using the fast writer again? The available formats only seem to have "fast" variants, I don't see anything to select the pure Python variant!?
```
The available formats are:
           Format           Read Write Auto-identify Deprecated
--------------------------- ---- ----- ------------- ----------
                      ascii  Yes   Yes            No           
               ascii.aastex  Yes   Yes            No           
                ascii.basic  Yes   Yes            No           
     ascii.commented_header  Yes   Yes            No           
                  ascii.csv  Yes   Yes            No           
                 ascii.ecsv  Yes   Yes           Yes           
           ascii.fast_basic  Yes   Yes            No           
ascii.fast_commented_header  Yes   Yes            No           
             ascii.fast_csv  Yes   Yes            No           
       ascii.fast_no_header  Yes   Yes            No           
             ascii.fast_rdb  Yes   Yes            No           
             ascii.fast_tab  Yes   Yes            No           
          ascii.fixed_width  Yes   Yes            No           
ascii.fixed_width_no_header  Yes   Yes            No           
 ascii.fixed_width_two_line  Yes   Yes            No           
                 ascii.html  Yes   Yes           Yes           
                 ascii.ipac  Yes   Yes            No           
                ascii.latex  Yes   Yes           Yes           
            ascii.no_header  Yes   Yes            No           
                  ascii.rdb  Yes   Yes           Yes           
                  ascii.rst  Yes   Yes            No           
                  ascii.tab  Yes   Yes            No           
                       fits  Yes   Yes           Yes           
                       hdf5  Yes   Yes           Yes           
                   jsviewer   No   Yes            No           
                    votable  Yes   Yes           Yes           
                     aastex  Yes   Yes            No        Yes
                        csv  Yes   Yes           Yes        Yes
                       html  Yes   Yes            No        Yes
                       ipac  Yes   Yes            No        Yes
                      latex  Yes   Yes            No        Yes
                        rdb  Yes   Yes            No        Yes
```

**Comment by taldcroft** [comment]
FWIW, a work-around is to specify the `comment` option:
```
>>> table = Table(data={'a': [1, 2]}, meta={'comments': ['spam']})
>>> table.write('test.csv', format='ascii.csv', overwrite=True, comment='#')
```
This works with both the fast C writer and the pure Python writer.

The root cause is at https://github.com/astropy/astropy/blob/732d89c2940156bdc0e200bb36dc38b5e424bcba/astropy/io/ascii/basic.py#L234
and here https://github.com/astropy/astropy/blob/732d89c2940156bdc0e200bb36dc38b5e424bcba/astropy/io/ascii/fastbasic.py#L187

I think the original motivation for this is that a pure CSV file cannot have comments.   See https://tools.ietf.org/html/rfc4180 and https://en.wikipedia.org/wiki/Comma-separated_values.  But of course the user can overwrite from the `write` or `read` function calls, *if they know to do so*.

So I think the answer here is better error handling and messages, and maybe some documentation.

**Comment by taldcroft** [comment]
I labeled this so newcomers or sprinters can tackle this.

**Comment by bsipocz** [comment]
@cdeil: - Not that it makes a difference in this case (I see the same error for the pure Python writer, too), but to answer your question:

> How do I avoid Astropy using the fast writer again?

Set the kwarg `fast_writer` to `False`

**Comment by astrofrog** [comment]
I ran into this today. If this doesn't get fixed soon in a sprint I think we should probably tackle it!

**Comment by astrofrog** [comment]
One weird related issue - if I do:

```
simple.write('2mass_subset.csv', format='ascii.csv', overwrite=True, comment='#')
```

Then the comments get printed out to stdout. Is that normal?

**Comment by pllim** [comment]
> If this doesn't get fixed soon in a sprint

Was it supposed to be a sprint goal? I see that you added the "sprint" label and then removed it on May 23.

**Comment by taldcroft** [comment]
FYI, I am in a busy spell for Chandra operations now and don't expect to look at this for a bit.

**Comment by pllim** [comment]
See #7801 for a potential fix. I think better error message counts as doc? 😬

**Comment by Gabriel-p** [comment]
I ran into long standing this issue today. Would simply checking for the `meta` attribute and dropping it be acceptable? Something like this perhaps:

```
if format == 'csv' and tt.meta is not None:
    tt.meta = None
    warnings.warn("Comments are not allowed in 'csv' file and have been removed")
```

**Comment by taldcroft** [comment]
@Gabriel-p - something like that would be fine, but I would suggest adding the workaround of setting `comment='#'` in the warning if the user really wants to store the comments.

**Comment by Gabriel-p** [comment]
@taldcroft I don't quite follow. You mean print out the full comment along with the warning?

**Comment by taldcroft** [comment]
@Gabriel-p - I mean have the warning message be like "Comments are not allowed by default in 'csv' files and have been removed. In order to force the comments into the output file add the keyword argument comment='#' to the write() call."

**Comment by Gabriel-p** [comment]
@taldcroft oh I wasn't even aware that was an option! Ok, so something like this:

```
if format == 'csv' and bool(tt.meta):
    tt.meta = None
    warnings.warn("Comments are not allowed by default in 'csv' files and have been removed. In order to force the comments into the output file add the keyword argument comment='#' to the write() call.")
```

@pllim @bsipocz @astrofrog thoughts?

**Comment by taldcroft** [comment]
I started thinking harder about this and there is a problem with setting `tt.meta = None` -- this is changing the user's input table in place, and that's not good.

So I dug around the code a bit and found the actual root problem that the test for whether to do the comment writing was missing the value for `write_comment = None` that is used for the CSV writers. I think this is a bit of a mistake in the original implementation, but the cleanest patch here is:
```
diff --git a/astropy/io/ascii/core.py b/astropy/io/ascii/core.py
index 698a1cb0d..c094c490a 100644
--- a/astropy/io/ascii/core.py
+++ b/astropy/io/ascii/core.py
@@ -613,7 +613,7 @@ class BaseHeader:
                 yield line
 
     def write_comments(self, lines, meta):
-        if self.write_comment is not False:
+        if self.write_comment not in (False, None):
             for comment in meta.get('comments', []):
                 lines.append(self.write_comment + comment)
 
diff --git a/astropy/io/ascii/cparser.pyx b/astropy/io/ascii/cparser.pyx
index a9fe19330..8a037c1b9 100644
--- a/astropy/io/ascii/cparser.pyx
+++ b/astropy/io/ascii/cparser.pyx
@@ -1053,7 +1053,7 @@ cdef class FastWriter:
                       for name in self.use_names]
 
     cdef _write_comments(self, output):
-        if self.comment is not False:
+        if self.comment not in (False, None):
             for comment_line in self.line_comments:
                 output.write(self.comment + comment_line + '\n')
```
I actually tried the alternative of having `write_comment = False` instead of `write_comment = None` in the CSV class definition, but this broke all kinds of tests. Instead the above patch is passing tests and also runs the following with the expected results:
```
from astropy.io import ascii
from astropy.table.table_helpers import simple_table

t = simple_table()
t.meta['comments'] = ['hello']

ascii.write(t, fast_writer=False, format='csv')
ascii.write(t, fast_writer=True, format='csv')
ascii.write(t, fast_writer=False, format='csv', comment='#')
ascii.write(t, fast_writer=True, format='csv', comment='#')
```

SO... are folks OK with just punting on all the warnings and silently dropping the comments when writing? That is, after all, the expected behavior for the formally defined CSV.

**Comment by pllim** [comment]
Warning with message on how to workaround it sounds reasonable to me. 👍

**Comment by taldcroft** [comment]
See #11475.
