### ISSUE TITLE
Cannot write HDUList to stream on Python 3

### ISSUE THREAD

**Issue by rmjarvis** [astropy/astropy#7435]
The following code works on Python 2, but not Python 3:
```
import astropy.io.fits
import numpy
import subprocess

data = numpy.array([[1,2,3],[4,5,6]])
hdu = astropy.io.fits.PrimaryHDU(data)
hdulist = astropy.io.fits.HDUList([hdu])

with open('test.fits', 'wb') as fout:
    p = subprocess.Popen(["cat"], stdin=subprocess.PIPE, stdout=fout)
    hdulist.writeto(p.stdin)
```
There seem to be 2 bugs in fact.  There is a second bug, which triggers during the error handling of the first.  (The latter I think is present for python 2 as well, but doesn't trigger.)
```
Traceback (most recent call last):
  File "/astro/u/mjarvis/.conda/envs/py3.5/lib/python3.5/site-packages/astropy/io/fits/util.py", line 872, in _free_space_check
    yield
  File "/astro/u/mjarvis/.conda/envs/py3.5/lib/python3.5/site-packages/astropy/io/fits/hdu/base.py", line 659, in _writeto
    self._writeto_internal(fileobj, inplace, copy)
  File "/astro/u/mjarvis/.conda/envs/py3.5/lib/python3.5/site-packages/astropy/io/fits/hdu/base.py", line 665, in _writeto_internal
    data_offset, data_size = self._writedata(fileobj)
  File "/astro/u/mjarvis/.conda/envs/py3.5/lib/python3.5/site-packages/astropy/io/fits/hdu/base.py", line 595, in _writedata
    size += self._writedata_internal(fileobj)
  File "/astro/u/mjarvis/.conda/envs/py3.5/lib/python3.5/site-packages/astropy/io/fits/hdu/image.py", line 641, in _writedata_internal
    fileobj.writearray(output)
  File "/astro/u/mjarvis/.conda/envs/py3.5/lib/python3.5/site-packages/astropy/io/fits/file.py", line 316, in writearray
    _array_to_file(array, self._file)
  File "/astro/u/mjarvis/.conda/envs/py3.5/lib/python3.5/site-packages/astropy/io/fits/util.py", line 678, in _array_to_file
    return write(arr, outfile)
  File "/astro/u/mjarvis/.conda/envs/py3.5/lib/python3.5/site-packages/astropy/io/fits/util.py", line 656, in <lambda>
    write = lambda a, f: a.tofile(f)
OSError: obtaining file position failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "write_to_stram.py", line 11, in <module>
    hdulist.writeto(p.stdin)
  File "/astro/u/mjarvis/.conda/envs/py3.5/lib/python3.5/site-packages/astropy/utils/decorators.py", line 507, in wrapper
    return function(*args, **kwargs)
  File "/astro/u/mjarvis/.conda/envs/py3.5/lib/python3.5/site-packages/astropy/io/fits/hdu/hdulist.py", line 888, in writeto
    hdu._writeto(hdulist._file)
  File "/astro/u/mjarvis/.conda/envs/py3.5/lib/python3.5/site-packages/astropy/io/fits/hdu/base.py", line 659, in _writeto
    self._writeto_internal(fileobj, inplace, copy)
  File "/astro/u/mjarvis/.conda/envs/py3.5/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/astro/u/mjarvis/.conda/envs/py3.5/lib/python3.5/site-packages/astropy/io/fits/util.py", line 878, in _free_space_check
    dirname = os.path.dirname(hdulist._file.name)
AttributeError: 'list' object has no attribute '_file'
```
It looks like the first error is because `isfile` returns True, which prompts it to use `a.tofile(f)` rather than using `_array_to_file_like`.  

I couldn't quite track through the logic of `isfile` though to figure out why it's returning the wrong answer for this.  Seems like some checks were added in python 3 to enable some file-like objects to be considered files.  But they wrongly swept this non-file in as well.

(Aside: My actual use case, of course, doesn't use `cat` for the process.  This is just a minimal test case to reproduce the problem.)

**Comment by pllim** [comment]
Thanks for providing a minimal test case. However, I do not understand what it is trying to accomplish. What is "test.fits" -- Is it image or table? What Astropy version are you using? Also, what is your actual use case, as I don't see the point to use Python file handler to handle FITS when `io.fits` has its own handler.

**Comment by saimn** [comment]
I got another error with master, but with a few changes I was able to reproduce the same error as you @rmjarvis . I agree that this should work, and your analysis seems good, but changing `isfile` is not possible as it breaks other use cases. 

So I think that changing the test in `_array_to_file` is safer, and I could run your test with this:
```diff
diff --git a/astropy/io/fits/hdu/base.py b/astropy/io/fits/hdu/base.py
index 4af52b055..53ca3b20c 100644
--- a/astropy/io/fits/hdu/base.py
+++ b/astropy/io/fits/hdu/base.py
@@ -635,7 +635,7 @@ class _BaseHDU(metaclass=_BaseHDUMeta):
     def _writeto(self, fileobj, inplace=False, copy=False):
         try:
             dirname = os.path.dirname(fileobj._file.name)
-        except AttributeError:
+        except (AttributeError, TypeError):
             dirname = None
 
         with _free_space_check(self, dirname):
diff --git a/astropy/io/fits/hdu/hdulist.py b/astropy/io/fits/hdu/hdulist.py
index 71ae187f8..ea005ad27 100644
--- a/astropy/io/fits/hdu/hdulist.py
+++ b/astropy/io/fits/hdu/hdulist.py
@@ -914,7 +914,7 @@ class HDUList(list, _Verify):
         hdulist = self.fromfile(fileobj)
         try:
             dirname = os.path.dirname(hdulist._file.name)
-        except AttributeError:
+        except (AttributeError, TypeError):
             dirname = None
 
         with _free_space_check(self, dirname=dirname):
diff --git a/astropy/io/fits/util.py b/astropy/io/fits/util.py
index 8aa7d25a0..1c1ecd3d0 100644
--- a/astropy/io/fits/util.py
+++ b/astropy/io/fits/util.py
@@ -610,7 +610,7 @@ def _array_to_file(arr, outfile):
     `ndarray.tofile`.  Otherwise a slower Python implementation is used.
     """
 
-    if isfile(outfile):
+    if isfile(outfile) and not isinstance(outfile, io.BufferedIOBase):
         write = lambda a, f: a.tofile(f)
     else:
         write = _array_to_file_like
```

Do you want to put this and a unit test (your minimal example above) in a PR ?

**Comment by pllim** [comment]
Since the potential solution is already given above by @saimn , I am going to mark this as novice for those looking to contribute. Thank you!

**Comment by pllim** [comment]
Note to maintainer who would milestone the PR to come: Since this only affects Python 3, there is no need to backport to 2.x.
