### ISSUE TITLE
astropy.table.Table.add_columns crash if rename_duplicate=True when there are no duplicates

### ISSUE THREAD

**Issue by Mikea1985** [astropy/astropy#7539]
When adding columns to an astropy table with add_columns (or add_column), an error occurs if using rename_duplicate=True when there are in fact no duplicates. From the description of rename_duplicate in the documentation, it seems that this is a bug (I would hope so; it would be nice if the user doesn't have to know whether there are duplicates in order to set the rename_duplicate keyword accordingly).

Here is the error: 

> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/home/mikea/anaconda2/envs/astroconda/lib/python2.7/site-packages/astropy/table/table.py", line 1569, in add_column
>    self.add_columns([col], [index], name, rename_duplicate=rename_duplicate)
>  File "/home/mikea/anaconda2/envs/astroconda/lib/python2.7/site-packages/astropy/table/table.py", line 1704, in add_columns
>    existing_names.add(new_name)
>UnboundLocalError: local variable 'new_name' referenced before assignment

Here is some example code that produces the error:

    import numpy as np
    from astropy.table import Table, Column
    t = Table(data=[np.arange(6)], names='a')
    t.add_column(Column(data=np.random.random(6), name='c'), rename_duplicate=True)

**Comment by Mikea1985** [comment]
I found a solution: it's a one-line fix (plus some adding indentation to other lines). I'll put in a pull request after I've had lunch.
