### ISSUE TITLE
table.show_in_browser() fails with unicode  characters in table

### ISSUE THREAD

**Issue by rmooser** [astropy/astropy#7604]
```python
from astropy.table import Table
from astropy.table import Column
data = [[u"\u2192"], [u"\u2191"]]
t = Table(data)
```
col0 col1
str1 str1

   →    ↑

but t.show_in_browser() results in:
```python
t.show_in_browser()

Traceback (most recent call last):

  File "<ipython-input-1-b348515f76c6>", line 5, in <module>
    t.show_in_browser()

  File "C:\Anaconda3\lib\site-packages\astropy\table\table.py", line 1102, in show_in_browser
    self.write(tmp, format='html')

  File "C:\Anaconda3\lib\site-packages\astropy\table\table.py", line 2560, in write
    io_registry.write(self, *args, **kwargs)

  File "C:\Anaconda3\lib\site-packages\astropy\io\registry.py", line 560, in write
    writer(data, *args, **kwargs)

  File "C:\Anaconda3\lib\site-packages\astropy\io\ascii\connect.py", line 43, in io_write
    return write(table, filename, format=format, **kwargs)

  File "C:\Anaconda3\lib\site-packages\astropy\io\ascii\ui.py", line 893, in write
    output.write(outstr)

  File "C:\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]

UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 248: character maps to <undefined>
```
Changing table.py, Line 1092 
```python
with open(path, 'w') as tmp:
```
to
```python
with open(path, 'w', encoding = 'utf-8') as tmp:
```
solves the problem, maybe add encoding as parameter to show_in_browser() ?

**Comment by pllim** [comment]
@rmooser , thanks for the report. If you are up for it, feel free to open a PR, given that you already have a solution in mind. Thanks!

**Comment by pllim** [comment]
But.... before you do that, I cannot reproduce the error with Astropy 3.1.dev22058 in Python 3.6. You might want to try with dev version first in case this has already been fixed.

**Comment by rmooser** [comment]
It seems that the issue is system-dependent and somehow connected to locale.getpreferredencoding(). Setting the default encoding to "utf-8" does solve the problem without changing the code, hence we can close the issuse
