### ISSUE TITLE
AttributeError for table column quantity info

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#7773]
In Gammapy we are getting an error (see https://github.com/gammapy/gammapy/issues/1714) because we are calling `.quantity.info` on a table column. 

Minimal example:
```
>>> from astropy.table import Table
>>> t = Table({'ENERGY': [3, 4, 5]})
>>> t['ENERGY'].quantity
<Quantity [3, 4, 5]>
>>> t['ENERGY'].quantity.info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/astropy/utils/data_info.py", line 444, in __repr__
    if self._parent is None:
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/astropy/utils/data_info.py", line 276, in __getattr__
    return super().__getattribute__(attr)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/astropy/utils/data_info.py", line 234, in _parent
    reference with ``c = col[3:5]`` followed by ``c.info``.""")
AttributeError: failed access "info" attribute on a temporary object.

It looks like you have done something like ``col[3:5].info``, i.e.
you accessed ``info`` from a temporary slice object ``col[3:5]`` that
only exists momentarily.  This has failed because the reference to
that temporary object is now lost.  Instead force a permanent
reference with ``c = col[3:5]`` followed by ``c.info``.
>>> t['ENERGY'].quantity.info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/astropy/utils/data_info.py", line 444, in __repr__
    if self._parent is None:
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/astropy/utils/data_info.py", line 276, in __getattr__
    return super().__getattribute__(attr)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.6/site-packages/astropy/utils/data_info.py", line 234, in _parent
    reference with ``c = col[3:5]`` followed by ``c.info``.""")
AttributeError: failed access "info" attribute on a temporary object.

It looks like you have done something like ``col[3:5].info``, i.e.
you accessed ``info`` from a temporary slice object ``col[3:5]`` that
only exists momentarily.  This has failed because the reference to
that temporary object is now lost.  Instead force a permanent
reference with ``c = col[3:5]`` followed by ``c.info``.
```

I see  in  #6277 that this might be expected, and indeed this works:
```
>>> q = t['ENERGY'].quantity
>>> q.info
dtype = int64
class = Quantity
n_bad = 0
length = 3
```

@taldcroft @mhvk - Will this weird behaviour remain?

If yes, maybe change the error message a bit?
To users it's not obvious that `col.quantity` is something like `col[3:5]`.

**Comment by taldcroft** [comment]
@cdeil - sadly nobody has found a way to remove the memory leak without having the side effect you are seeing.  I can put in a  tweak to the exception message 
```
It looks like you have done something like ``col[3:5].info`` or ``col.quantity.info`` ...
```
Would that help?
