### ISSUE TITLE
TST: AttributeError numpy.core.umath has no attribute _ones_like

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#7791]
New error surfaced in numpy-dev build. @mhvk , any idea?

https://travis-ci.org/astropy/astropy/jobs/423241942

```
Installed /home/travis/build/astropy/astropy/.eggs/psutil-5.4.7-py3.6-linux-x86_64.egg
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/astropy-test-i8xsw97c/lib/python3.6/site-packages/astropy/utils/decorators.py", line 827, in test
    func = make_function_with_signature(func, name=name, **wrapped_args)
  File "/tmp/astropy-test-i8xsw97c/lib/python3.6/site-packages/astropy/tests/runner.py", line 260, in test
    return runner.run_tests(**kwargs)
  File "/tmp/astropy-test-i8xsw97c/lib/python3.6/site-packages/astropy/tests/runner.py", line 602, in run_tests
    from ..table import Table  # pylint: disable=W0611
  File "/tmp/astropy-test-i8xsw97c/lib/python3.6/site-packages/astropy/table/__init__.py", line 41, in <module>
    from .column import Column, MaskedColumn, StringTruncateWarning, ColumnInfo
  File "/tmp/astropy-test-i8xsw97c/lib/python3.6/site-packages/astropy/table/column.py", line 21, in <module>
    from ..units import Unit, Quantity
  File "/tmp/astropy-test-i8xsw97c/lib/python3.6/site-packages/astropy/units/__init__.py", line 14, in <module>
    from .quantity import *
  File "/tmp/astropy-test-i8xsw97c/lib/python3.6/site-packages/astropy/units/quantity.py", line 29, in <module>
    from .quantity_helper import (converters_and_unit, can_have_arbitrary_unit,
  File "/tmp/astropy-test-i8xsw97c/lib/python3.6/site-packages/astropy/units/quantity_helper.py", line 401, in <module>
    UFUNC_HELPERS[np.core.umath._ones_like] = helper__ones_like
AttributeError: module 'numpy.core.umath' has no attribute '_ones_like'
```

**Comment by mhvk** [comment]
This seems to have a mistake in https://github.com/numpy/numpy/pull/10915; a fix is proposed in https://github.com/numpy/numpy/pull/11862.

**Comment by mhvk** [comment]
This should now be fixed upstream; do reopen if not...
