### ISSUE TITLE
Issue when writing out CSV file

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#7798]
I ran into an issue when trying to convert the following table to CSV:

https://gist.github.com/astrofrog/dd80a9ff4296c69ce8efe9492fc4ad33

The code is:

```python
from astropy.table import Table
t = Table.read('2mass.tbl', format='ascii.ipac')
t.write('2mass.csv', overwrite=True)
```

The error is:

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    t.write('2mass.csv', overwrite=True)
  File "/Users/tom/Dropbox/Code/Astropy/astropy/astropy/table/table.py", line 2598, in write
    io_registry.write(self, *args, **kwargs)
  File "/Users/tom/Dropbox/Code/Astropy/astropy/astropy/io/registry.py", line 560, in write
    writer(data, *args, **kwargs)
  File "/Users/tom/Dropbox/Code/Astropy/astropy/astropy/io/ascii/connect.py", line 86, in write_csv
    return write(table, filename, **kwargs)
  File "/Users/tom/Dropbox/Code/Astropy/astropy/astropy/io/ascii/ui.py", line 912, in write
    writer.write(table, output)
  File "/Users/tom/Dropbox/Code/Astropy/astropy/astropy/io/ascii/fastbasic.py", line 202, in write
    self._write(table, output, {'fill_values': [(core.masked, '')]})
  File "/Users/tom/Dropbox/Code/Astropy/astropy/astropy/io/ascii/fastbasic.py", line 179, in _write
    writer.write(output, header_output, output_types)
  File "astropy/io/ascii/cparser.pyx", line 1029, in astropy.io.ascii.cparser.FastWriter.write
  File "astropy/io/ascii/cparser.pyx", line 1009, in astropy.io.ascii.cparser.FastWriter._write_header
  File "astropy/io/ascii/cparser.pyx", line 1000, in astropy.io.ascii.cparser.FastWriter._write_comments
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

I haven't had a chance to investigate what is causing this.

**Comment by astrofrog** [comment]
Looks like a duplicate of https://github.com/astropy/astropy/issues/7357
