### ISSUE TITLE
Unrecognized/unimplemented WCS TPD distortion function

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#7828]
While debugging #7328, I discovered that some of our test FITS files cannot be read after updating their header WCS.  Here's a minimal example, where I don't even make any changes to the WCS:

```python
from astropy.io import fits
from astropy.utils.data import download_file
from astropy.wcs import WCS

url = 'http://data.astropy.org/tutorials/FITS-images/HorseHead.fits'
filename = download_file(url, cache=True)
hdu = fits.open(filename)[0]
wcs = WCS(hdu.header)
hdu.header.update(wcs.to_header())    # this line causes the issue
new_filename = 'test.fits'
hdu.writeto(new_filename, overwrite=True)
```

The file saves fine, but it cannot be read back in:

```python
hdu2 = fits.open(new_filename)
wcs2 = WCS(hdu2[0].header)
WARNING: VerifyWarning: Card is too long, comment will be truncated. [astropy.io.fits.card]
WARNING: FITSFixedWarning: 'celfix' made the change 'Invalid parameter value'. [astropy.wcs.wcs]
Traceback (most recent call last):
  File "wcs_bug.py", line 13, in <module>
    wcs2 = WCS(hdu2[0].header)
  File "/usr/local/lib/python3.7/site-packages/astropy/wcs/wcs.py", line 506, in __init__
    self.wcs.set()
ValueError: ERROR 5 in wcsset() at line 2219 of file cextern/wcslib/C/wcs.c:
Invalid parameter value.
ERROR 4 in linset() at line 696 of file cextern/wcslib/C/lin.c:
Failed to initialize distortion functions.
ERROR 3 in disset() at line 988 of file cextern/wcslib/C/dis.c:
Unrecognized/unimplemented distortion function: TPD     .
```

The file `https://astropy.stsci.edu/data/photometry/M6707HH.fits` gives the same error.

The updated header has a bunch of extra stuff (apparently for TPD distortions), but I think the original FITS file is rectified without any distortions:

```
WCSAXES =                    2 / Number of coordinate axes                      
CRPIX1  =     -716.33314429427 / Pixel coordinate of reference point            
CRPIX2  =     -8444.6494669823 / Pixel coordinate of reference point            
PC1_1   =    0.015029018460682 / Coordinate transformation matrix element       
PC1_2   =  -9.637357776572E-06 / Coordinate transformation matrix element       
PC2_1   =  1.0548917307846E-05 / Coordinate transformation matrix element       
PC2_2   =    0.015000473845055 / Coordinate transformation matrix element       
CDELT1  =   -0.018654788242111 / [deg] Coordinate increment at reference point  
CDELT2  =    0.018654788242111 / [deg] Coordinate increment at reference point  
CUNIT1  = 'deg'                / Units of coordinate increment and value        
CUNIT2  = 'deg'                / Units of coordinate increment and value        
CTYPE1  = 'RA---TAN'           / Right ascension, gnomonic projection           
CTYPE2  = 'DEC--TAN'           / Declination, gnomonic projection               
CRVAL1  =      85.599416666667 / [deg] Coordinate value at reference point      
CRVAL2  =     -4.9466388888889 / [deg] Coordinate value at reference point      
LONPOLE =                180.0 / [deg] Native longitude of celestial pole       
LATPOLE =     -4.9466388888889 / [deg] Native latitude of celestial pole        
WCSNAME = 'DSS PLATEID A0JP'   / Coordinate system title                        
RADESYS = 'ICRS'               / Equatorial coordinate system                   
MJD-OBS =      48247.575694444 / [d] MJD of observation matching DATE-OBS       
DATE-OBS= '1990-12-22T13:49:00' / ISO-8601 observation date matching MJD-OBS    
CQDIS1  = 'TPD'                / Q = sequent, Template Polynomial Distortion    
DQ1     = 'NAXES:  2'          / Two independent variables                      
DQ1     = 'AXIS.1: 1'          / 1st independent variable: axis 1 (= u)         
DQ1     = 'AXIS.2: 2'          / 2nd independent variable: axis 2 (= v)         
DQ1     = 'AUX.1.COEFF.0:      4.3576522421707' / TPD: x = c0 + c1*u + c2*v     
DQ1     = 'AUX.1.COEFF.1:     -1.0000315896703' / TPD: x = c0 + c1*u + c2*v     
DQ1     = 'AUX.1.COEFF.2: -0.00064249051843813' / TPD: x = c0 + c1*u + c2*v     
DQ1     = 'AUX.2.COEFF.0:     -4.7022420047339' / TPD: y = d0 + d1*u + d2*v     
DQ1     = 'AUX.2.COEFF.1: -0.00070188078830605' / TPD: y = d0 + d1*u + d2*v     
DQ1     = 'AUX.2.COEFF.2:     0.99996796039003' / TPD: y = d0 + d1*u + d2*v     
DQ1     = 'TPD.FWD.0:       4.3544914787891' / TPD coefficient: 1               
DQ1     = 'TPD.FWD.1:     -0.99996796039003' / TPD coefficient: x               
DQ1     = 'TPD.FWD.2:  -0.00064249051843813' / TPD coefficient: y               
DQ1     = 'TPD.FWD.4:   4.0045551905677E-07' / TPD coefficient: xx              
DQ1     = 'TPD.FWD.5:  -2.9651818656354E-07' / TPD coefficient: xy              
DQ1     = 'TPD.FWD.6:   3.5292090561852E-08' / TPD coefficient: yy              
DQ1     = 'TPD.FWD.7:  -3.2971336389947E-08' / TPD coefficient: xxx             
DQ1     = 'TPD.FWD.8:   1.2103558896061E-09' / TPD coefficient: xxy             
DQ1     = 'TPD.FWD.9:   -3.695343921597E-08' / TPD coefficient: xyy             
DQ1     = 'TPD.FWD.10: -4.1338646965135E-10' / TPD coefficient: yyy             
CQDIS2  = 'TPD'                / Q = sequent, Template Polynomial Distortion    
DQ2     = 'NAXES:  2'          / Two independent variables                      
DQ2     = 'AXIS.1: 1'          / 1st independent variable: axis 1 (= u)         
DQ2     = 'AXIS.2: 2'          / 2nd independent variable: axis 2 (= v)         
DQ2     = 'AUX.1.COEFF.0:     -4.7022420047339' / TPD: x = c0 + c1*u + c2*v     
DQ2     = 'AUX.1.COEFF.1: -0.00070188078830605' / TPD: x = c0 + c1*u + c2*v     
DQ2     = 'AUX.1.COEFF.2:     0.99996796039003' / TPD: x = c0 + c1*u + c2*v     
DQ2     = 'AUX.2.COEFF.0:      4.3576522421707' / TPD: y = d0 + d1*u + d2*v     
DQ2     = 'AUX.2.COEFF.1:     -1.0000315896703' / TPD: y = d0 + d1*u + d2*v     
DQ2     = 'AUX.2.COEFF.2: -0.00064249051843813' / TPD: y = d0 + d1*u + d2*v     
DQ2     = 'TPD.FWD.0:       4.7054490993996' / TPD coefficient: 1               
DQ2     = 'TPD.FWD.1:       1.0000315896703' / TPD coefficient: x               
DQ2     = 'TPD.FWD.2:  -0.00070188078830605' / TPD coefficient: y               
DQ2     = 'TPD.FWD.4:   4.2705471721818E-07' / TPD coefficient: xx              
DQ2     = 'TPD.FWD.5:  -2.9925030170201E-07' / TPD coefficient: xy              
DQ2     = 'TPD.FWD.6:   3.3926409293536E-07' / TPD coefficient: yy              
DQ2     = 'TPD.FWD.7:   3.3337447778272E-08' / TPD coefficient: xxx             
DQ2     = 'TPD.FWD.8:  -3.4003805305495E-10' / TPD coefficient: xxy             
DQ2     = 'TPD.FWD.9:    3.645606340931E-08' / TPD coefficient: xyy             
DQ2     = 'TPD.FWD.10: -8.5875701263674E-10' / TPD coefficient: yyy             
```

**Comment by pllim** [comment]
Looks like it just segfaults now at `wcs2 = WCS(hdu2[0].header)` with astropy v5.3.dev lol

```
malloc(): corrupted top size
Aborted
```
