### ISSUE TITLE
Cannot import IERS data (due to regression in Numpy 1.15.3?)

### ISSUE THREAD

**Issue by lpsinger** [astropy/astropy#7943]
I cannot load the IERS data using the latest version of Numpy. This is due to a change or possibly a regression in Numpy 1.15.13.

The test consists of the following Python code:

```python
from astropy.utils.iers import IERS_Auto
IERS_Auto.open()
```

It works with numpy==1.15.2:

```
$ docker run --rm -it python:slim bash -c 'pip install astropy numpy==1.15.2 && python -c "from astropy.utils.iers import IERS_Auto; IERS_Auto.open()"'
Collecting astropy
  Downloading https://files.pythonhosted.org/packages/5a/c6/5e823cb1b0a55eb0ab5da32553916867f7cd7349df98b517ba6f19c86edc/astropy-3.0.5-cp37-cp37m-manylinux1_x86_64.whl (6.0MB)
    100% |████████████████████████████████| 6.0MB 5.4MB/s 
Collecting numpy==1.15.2
  Downloading https://files.pythonhosted.org/packages/98/44/94cc2e139b611b16458384ff3b9c87f217144b5915b0a9798c07a7295437/numpy-1.15.2-cp37-cp37m-manylinux1_x86_64.whl (13.8MB)
    100% |████████████████████████████████| 13.9MB 1.7MB/s 
Installing collected packages: numpy, astropy
Successfully installed astropy-3.0.5 numpy-1.15.2
Downloading http://maia.usno.navy.mil/ser7/finals2000A.all
|==========================================| 3.2M/3.2M (100.00%)         2s
```

But it fails with numpy==1.15.3:

```
$ docker run --rm -it python:slim bash -c 'pip install astropy numpy==1.15.3 && python -c "from astropy.utils.iers import IERS_Auto; IERS_Auto.open()"'
Collecting astropy
  Downloading https://files.pythonhosted.org/packages/5a/c6/5e823cb1b0a55eb0ab5da32553916867f7cd7349df98b517ba6f19c86edc/astropy-3.0.5-cp37-cp37m-manylinux1_x86_64.whl (6.0MB)
    100% |████████████████████████████████| 6.0MB 4.1MB/s 
Collecting numpy==1.15.3
  Downloading https://files.pythonhosted.org/packages/f2/1f/a05544224706463a1c28589db5900247c7e85a077a0d254e7db012fbb008/numpy-1.15.3-cp37-cp37m-manylinux1_x86_64.whl (13.8MB)
    100% |████████████████████████████████| 13.9MB 1.8MB/s 
Installing collected packages: numpy, astropy
Successfully installed astropy-3.0.5 numpy-1.15.3
Downloading http://maia.usno.navy.mil/ser7/finals2000A.all
|==========================================| 3.2M/3.2M (100.00%)         1s
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 642, in open
    cls.iers_table = cls.read(file=filename)
  File "/usr/local/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 502, in read
    table = cls._combine_a_b_columns(iers_a)
  File "/usr/local/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 464, in _combine_a_b_columns
    is_predictive = (table['UT1Flag_A'] == 'P') | (table['PolPMFlag_A'] == 'P')
  File "/usr/local/lib/python3.7/site-packages/numpy/ma/core.py", line 3016, in __array_finalize__
    self._fill_value = _check_fill_value(self._fill_value, self.dtype)
  File "/usr/local/lib/python3.7/site-packages/numpy/ma/core.py", line 476, in _check_fill_value
    fill_value = np.array(fill_value, copy=False, dtype=ndtype)
ValueError: invalid literal for int() with base 10: 'N'
```

**Comment by lpsinger** [comment]
A search through the Numpy changelog shows one related PR that was merged in 1.15.13: numpy/numpy#12237.

**Comment by pllim** [comment]
@mhvk  ?

**Comment by bsipocz** [comment]
This is now blocker to deploy the docs for "stable".

**Comment by pllim** [comment]
Looking into this with `astropy` 3.1.dev22571 and `numpy` 1.15.3:

```python
>>> import numpy as np
>>> from astropy.table import Table
>>> IERS_A_URL = 'http://maia.usno.navy.mil/ser7/finals2000A.all'
>>> IERS_A_README = '/path/to/astropy/utils/iers/data/ReadMe.finals2000A'
>>> iers_a = Table.read(IERS_A_URL, format='cds', readme=IERS_A_README)
>>> x1 = table['UT1Flag_A'] == 'P'
>>> x2 = table['PolPMFlag_A'] == 'P'
>>> x1 | x2
ValueError: invalid literal for int() with base 10: 'N'
>>> c = table['UT1Flag_A']
>>> c
<MaskedColumn name='UT1Flag_A' dtype='str1' description='IERS (I) or Prediction (P) flag forBull. A UT1-UTC values' length=17149>
>>> c.fill_value
'N/A'
>>> set(table['UT1Flag_A'].filled())
{'I', 'N', 'P'}
```
Possible fix?
```python
>>> y1 = table['UT1Flag_A'].filled() == 'P'
>>> y2 = table['PolPMFlag_A'].filled() == 'P'
>>> is_predictive = y1 | y2
>>> np.min(np.flatnonzero(is_predictive))
16726
```

**Comment by pllim** [comment]
See #7946 for potential fix...

**Comment by astrofrog** [comment]
I've opened a Numpy issue as I think there is a real bug on their side: https://github.com/numpy/numpy/issues/12248 - I don't think we should fix it here.

**Comment by pllim** [comment]
Note to the next attempt to fix this:

* Undo  #7955 (if merged).
* Check with @bsipocz about Numpy pinning over at `ci-helpers`.
* Check numpy-dev build carefully over at Travis CI.
* This issue is known to affect the following subpackages: `coordinates`, `utils`, `table`

**Comment by bsipocz** [comment]
the ci-helpers PR is this one, and should be merged once CI is green on it: https://github.com/astropy/ci-helpers/pull/331

**Comment by pllim** [comment]
From discussions over at numpy/numpy#12248 , looks like they have a fix upstream, so maybe we can just wait this out.

**Comment by pllim** [comment]
Update: Upstream patch is numpy/numpy#12257

**Comment by pllim** [comment]
Patch upstream is merged. We'll just have to wait for 1.15.4.
