### ISSUE TITLE
Apparent Breaking change in coordinates

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#8021]
Fulfilling my purpose as the coordinates canary I have the following issue for you!

Importing sunpy coordinates is broken with astropy master, it seems that having `None` as a differential type somewhere along the line is no longer allowed? I assume this is not a deliberate API change?

```
$ python -c "import sunpy.coordinates"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/stuart/Git/DKIST/sunpy/sunpy/coordinates/__init__.py", line 6, in <module>
    from .ephemeris import *
  File "/home/stuart/Git/DKIST/sunpy/sunpy/coordinates/ephemeris.py", line 106, in <module>
    get_earth(_time_first_rotation).hcrs.cartesian.transform(_SUN_DETILT_MATRIX) \
  File "/home/stuart/Git/DKIST/sunpy/sunpy/coordinates/ephemeris.py", line 73, in get_earth
    earth = SkyCoord(0*u.deg, earth.lat, earth.radius, frame=earth)
  File "/home/stuart/Git/astropy/astropy/coordinates/sky_coordinate.py", line 259, in __init__
    frame_cls, frame_kwargs = _get_frame_without_data(args, kwargs)
  File "/home/stuart/Git/astropy/astropy/coordinates/sky_coordinate.py", line 1791, in _get_frame_without_data
    kwargs.pop('differential_type'))
  File "/home/stuart/Git/astropy/astropy/coordinates/baseframe.py", line 79, in _get_diff_cls
    value, list(r.DIFFERENTIAL_CLASSES)))
ValueError: Differential is None but must be a BaseDifferential class or one of the string aliases ['cartesian', 'unitspherical', 'spherical', 'unitsphericalcoslat', 'sphericalcoslat', 'radial', 'physicsspherical', 'cylindrical']
```

It seems to have been introduced by this commit (according to bisect):
https://github.com/astropy/astropy/commit/c912dbd378ed376f4beb13d3605cb1101df2a45c

ping @adrn @eteq

**Comment by Cadair** [comment]
A really dump patch for this is : 

```patch
diff --git a/astropy/coordinates/baseframe.py b/astropy/coordinates/baseframe.py
index bb6b71395..1616fbfdc 100644
--- a/astropy/coordinates/baseframe.py
+++ b/astropy/coordinates/baseframe.py
@@ -71,14 +71,15 @@ def _get_diff_cls(value):
 
     if value in r.DIFFERENTIAL_CLASSES:
         value = r.DIFFERENTIAL_CLASSES[value]
-    elif (not isinstance(value, type) or
-          not issubclass(value, r.BaseDifferential)):
+    elif value is not None and (not isinstance(value, type) or
+                                not issubclass(value, r.BaseDifferential)):
         raise ValueError(
             'Differential is {0!r} but must be a BaseDifferential class '
             'or one of the string aliases {1}'.format(
                 value, list(r.DIFFERENTIAL_CLASSES)))
     return value
 
+
 def _get_repr_classes(base, **differentials):
     """Get valid representation and differential classes.
 
-- 
2.19.1
```

**Comment by adrn** [comment]
I'm away on a panel and have very little time until Wednesday or Thursday. If @eteq can have a look at this before then, great, otherwise I'll get to it ASAP. Thanks @Cadair!

**Comment by adrn** [comment]
@bsipocz merged my PR, so can you check that master fixes the problem?

**Comment by Cadair** [comment]
This appears to work locally, I will kick our CI and yell again if it is broken.
