### ISSUE TITLE
convolution cannot be imported

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#8032]
```
✔ ~/munka/devel/astropy [hacking|✚ 1⚑ 14] $ python -c "from astropy import convolution"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/bsipocz/munka/devel/astropy/astropy/convolution/__init__.py", line 10, in <module>
    from .convolve import convolve, convolve_fft, interpolate_replace_nans, convolve_models
  File "/Users/bsipocz/munka/devel/astropy/astropy/convolution/convolve.py", line 28, in <module>
    lib_path = glob.glob(os.path.join(os.path.dirname(__file__), 'lib_convolve*'))[0]
IndexError: list index out of range
```

**Comment by bsipocz** [comment]
Some more cleanup of #7293 is needed.

**Comment by bsipocz** [comment]
Well, @pllim pointed out I can't be in the source library to import convolution, at least a bit less cryptic error message would be nice to avoid causing a heart attack.

Building in the source dir also doesn't solve all the issues, now I see another one:

```
In [2]: >>> from astropy.convolution import convolve
   ...: >>> convolve([1, 4, 5, 6, 5, 7, 8], [0.2, 0.6, 0.2])
   ...: 
   ...: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-843c8031be97> in <module>()
----> 1 from astropy.convolution import convolve
      2 convolve([1, 4, 5, 6, 5, 7, 8], [0.2, 0.6, 0.2])

~/munka/devel/astropy/astropy/convolution/__init__.py in <module>()
      8 try:
      9     # Not guaranteed available at setup time
---> 10     from .convolve import convolve, convolve_fft, interpolate_replace_nans, convolve_models
     11 except ImportError:
     12     if not _ASTROPY_SETUP_:

~/munka/devel/astropy/astropy/convolution/convolve.py in <module>()
     23 # Turn the faulthandler ON to help catch any signals, e.g. segfaults
     24 # or asserts. This doesn't, currently, work with Jupyter Notebook.
---> 25 faulthandler.enable()
     26 
     27 # Find and load C convolution library

AttributeError: '_StdoutProxy' object has no attribute 'fileno'
```

I had none of these on the LTS branch....

**Comment by astrofrog** [comment]
This is due to the refactoring of the convolution code. I think we should just remove the call to faulthandler, it's not actually needed for the convolution code. And I agree that we should basically make sure the error message when importing for the source tree is the same as for other extensions. I'll open a PR.

**Comment by jamienoss** [comment]
@bsipocz 
>Some more cleanup of #7293 is needed.

Regarding the _"more"_, are there other issues that I should be aware of? I just looked but couldn't find any open (or very recently closed).

**Comment by jdavies-st** [comment]
I also cannot import convolve running MacOS 10.13.6.  This is from last night on master, git hash g064dac1
```
In [1]: import astropy                                                                                                                   

In [2]: astropy.__version__                                                                                                              
Out[2]: '3.2.dev23162'

In [3]: from astropy.convolution import Kernel2D                                                                                         
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-0d49cdbc4685> in <module>
----> 1 from astropy.convolution import Kernel2D

~/miniconda3/envs/jwst_dev/lib/python3.7/site-packages/astropy/convolution/__init__.py in <module>
      8 try:
      9     # Not guaranteed available at setup time
---> 10     from .convolve import convolve, convolve_fft, interpolate_replace_nans, convolve_models
     11 except ImportError:
     12     if not _ASTROPY_SETUP_:

~/miniconda3/envs/jwst_dev/lib/python3.7/site-packages/astropy/convolution/convolve.py in <module>
     30     libConvolve = ctypes.windll.LoadLibrary(lib_path)
     31 else:
---> 32     libConvolve = ctypes.cdll.LoadLibrary(lib_path)
     33 
     34 

~/miniconda3/envs/jwst_dev/lib/python3.7/ctypes/__init__.py in LoadLibrary(self, name)
    432 
    433     def LoadLibrary(self, name):
--> 434         return self._dlltype(name)
    435 
    436 cdll = LibraryLoader(CDLL)

~/miniconda3/envs/jwst_dev/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    354 
    355         if handle is None:
--> 356             self._handle = _dlopen(self._name, mode)
    357         else:
    358             self._handle = handle

OSError: dlopen(/Users/jdavies/miniconda3/envs/jwst_dev/lib/python3.7/site-packages/astropy/convolution/lib_convolve.py, 6): no suitable image found.  Did find:
	/Users/jdavies/miniconda3/envs/jwst_dev/lib/python3.7/site-packages/astropy/convolution/lib_convolve.py: file too short
	/Users/jdavies/miniconda3/envs/jwst_dev/lib/python3.7/site-packages/astropy/convolution/lib_convolve.py: file too short

```

**Comment by nden** [comment]
Just to be clear #8035 does not fix the error @jdavies-st reported.

**Comment by astrofrog** [comment]
@jamienoss - any ideas about @jdavies-st's issue?

**Comment by jamienoss** [comment]
I'll walk over and find out...

**Comment by bsipocz** [comment]
> Regarding the "more", are there other issues that I should be aware of? I just looked but couldn't find any open (or very recently closed).

more, in addition to the last commit done in that PR. My first (wrong) though was that this is due to some remnants of openMP, but apparently ctypes messes with my pure python life just as much.

**Comment by jamienoss** [comment]
@bsipocz ok cool, just wanted to double check I wasn't missing something.

**Comment by jamienoss** [comment]
conda build and install works great for me, if you ignore the numpy 1.11 -> 1.15 issue and the failing erfa test:
```python
Traceback (most recent call last):
  File "//anaconda/conda-bld/astropy_1540921946927/test_tmp/run_test.py", line 6, in <module>
    import astropy._erfa._core
ModuleNotFoundError: No module named 'astropy._erfa._core'
```
conda-build doesn't generate the superfluous file, ``lib_conovlve.py``. Which is interesting since the build script only executes ``$PYTHON setup.py install --offline --old-and-unmanageable``.

**Comment by jamienoss** [comment]
Looks like the trick is ``--old-and-unmanageable`` thus preventing the egg build. Guess it is an egg  thing?

**Comment by jamienoss** [comment]
Should we split this issue out into two?

**Comment by jamienoss** [comment]
``lib_convolve.py`` is also produced on windows via ``./setup install``.
