### ISSUE TITLE
Documentation failure on RTD

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#8039]
It looks like the build on RTD is frequently broken because of IERS:
http://readthedocs.org/projects/astropy/builds/8020273/ (and many others in http://readthedocs.org/projects/astropy/builds/)

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/sphinx/application.py", line 234, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/sphinx/application.py", line 312, in _init_builder
    self.emit('builder-inited')
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/sphinx/application.py", line 489, in emit
    return self.events.emit(event, self, *args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/sphinx_gallery/gen_gallery.py", line 221, in generate_gallery_rst
    seen_backrefs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 462, in generate_dir_rst
    gallery_conf)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 681, in generate_file_rst
    block_vars, gallery_conf)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 550, in execute_code_block
    gallery_conf)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 544, in execute_code_block
    exec(compiler(code_ast, src_file, 'exec'), example_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/checkouts/latest/examples/coordinates/plot_obs-planning.py", line 77, in <module>
    m33altaz = m33.transform_to(AltAz(obstime=time,location=bear_mountain))
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/astropy/coordinates/sky_coordinate.py", line 441, in transform_to
    new_coord = trans(self.frame, generic_frame)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/astropy/coordinates/transformations.py", line 1377, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/astropy/coordinates/transformations.py", line 980, in __call__
    return supcall(fromcoord, toframe)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/astropy/coordinates/builtin_frames/cirs_observed_transforms.py", line 51, in cirs_to_altaz
    xp, yp = get_polar_motion(obstime)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/astropy/coordinates/builtin_frames/utils.py", line 40, in get_polar_motion
    xp, yp, status = iers.IERS_Auto.open().pm_xy(time, return_status=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/astropy/utils/iers/iers.py", line 643, in open
    cls.iers_table = cls.read(file=filename)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/astropy/utils/iers/iers.py", line 503, in read
    table = cls._combine_a_b_columns(iers_a)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/astropy/utils/iers/iers.py", line 465, in _combine_a_b_columns
    is_predictive = (table['UT1Flag_A'] == 'P') | (table['PolPMFlag_A'] == 'P')
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/numpy/ma/core.py", line 3016, in __array_finalize__
    self._fill_value = _check_fill_value(self._fill_value, self.dtype)
  File "/home/docs/checkouts/readthedocs.org/user_builds/astropy/envs/latest/lib/python3.6/site-packages/numpy/ma/core.py", line 476, in _check_fill_value
    fill_value = np.array(fill_value, copy=False, dtype=ndtype)
ValueError: invalid literal for int() with base 10: 'N'
```

**Comment by pllim** [comment]
Yes. For whatever reason, pinning in `pip` requirements file did not work on RTD. We are aware of this. Thanks for opening a formal issue though!

**Comment by pllim** [comment]
Right after I opened rtfd/readthedocs.org#4822 , I found the culprit:

https://github.com/astropy/astropy/blob/064dac1a63aec214cd0ab386bfb08ce523a7f719/setup.py#L76-L77

I think to fix the RTD build (unless their devs have better suggestions), we also need to pin to `numpy<1.15.3` in `setup.py`.

**Comment by saimn** [comment]
There are also build failures with *"You can not have two versions with the name latest or stable"*. Maybe related to the stable tag/branch, @bsipocz ?
http://readthedocs.org/projects/astropy/builds/8026504/

**Comment by bsipocz** [comment]
I'll try and wipe it, it ultimately solve the stable branch

**Comment by bsipocz** [comment]
(although I don't understand how this could even happen with latest (as for stable the tag sometimes lurking back, especially when I mess up a release by tagging rather than updating the branch 😊 )

**Comment by bsipocz** [comment]
It seems to be working again after the wipe.
