### ISSUE TITLE
Numpy 1.15.3 breaks Time.sidereal_time()

### ISSUE THREAD

**Issue by eigenbrot** [astropy/astropy#8054]
Using python 3.7.1 and astropy 3.0.4-1 on Arch linux

With numpy 1.15.2-1 I can do (numbers just made up):
```
>>> from astropy.time import Time
>>> t = Time(57560, format='mjd')
>>> t.siderial_time('apparent', longitude=180)
<Longitude 5.97469696 hourangle>
```

With numpy 1.15.3-1 I get:
```
>>> from astropy.time import Time
>>> t = Time(57560, format='mjd')
>>> t.siderial_time('apparent', longitude=180)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/astropy/time/core.py", line 754, in sidereal_time
    gst = self._erfa_sidereal_time(available_models[model.upper()])
  File "/usr/lib/python3.7/site-packages/astropy/time/core.py", line 769, in _erfa_sidereal_time
    for scale in model['scales']
  File "/usr/lib/python3.7/site-packages/astropy/time/core.py", line 770, in <listcomp>
    for jd_part in ('jd1', 'jd2')]
  File "/usr/lib/python3.7/site-packages/astropy/time/core.py", line 1121, in __getattr__
    tm._set_scale(attr)
  File "/usr/lib/python3.7/site-packages/astropy/time/core.py", line 492, in _set_scale
    args.append(get_dt(jd1, jd2))
  File "/usr/lib/python3.7/site-packages/astropy/time/core.py", line 1233, in _get_delta_ut1_utc
    iers_table = IERS_Auto.open()
  File "/usr/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 642, in open
    cls.iers_table = cls.read(file=filename)
  File "/usr/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 502, in read
    table = cls._combine_a_b_columns(iers_a)
  File "/usr/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 464, in _combine_a_b_columns
    is_predictive = (table['UT1Flag_A'] == 'P') | (table['PolPMFlag_A'] == 'P')
  File "/usr/lib/python3.7/site-packages/numpy/ma/core.py", line 3016, in __array_finalize__
    self._fill_value = _check_fill_value(self._fill_value, self.dtype)
  File "/usr/lib/python3.7/site-packages/numpy/ma/core.py", line 476, in _check_fill_value
    fill_value = np.array(fill_value, copy=False, dtype=ndtype)
ValueError: invalid literal for int() with base 10: 'N'
```

A few questions:
1. Is this a universal problem, or just something weird with my setup (although I don't see how that could be)?
2. Is this the right place to bring this issue or should I talk to the numpy folks?

Thanks!

**Comment by bsipocz** [comment]
Thanks for reporting. The issue has been fixed upstream in numpy and the fix will be releases in 1.15.4 (I don't know their ETA for that, you can ask it on a numpy forum). In the meantime, in astropy, we made the version requirement for numpy to not be 1.15.3. 

As a workaround, please downgrade to 1.15.2.

**Comment by pllim** [comment]
xref #7943

**Comment by eigenbrot** [comment]
Thanks for the info!
