### ISSUE TITLE
Numpy import error in 3.1.1 (in docker)

### ISSUE THREAD

**Issue by travisgroth** [astropy/astropy#8325]
It appears that when importing astropy.io.ascii, there is an error loading numpy starting at version 3.1.1.

From a clean container:

```
$ docker run -it python:3.6 /bin/bash
root@a13274f02663:/# pip install astropy==3.1.1
Collecting astropy==3.1.1
  Downloading https://files.pythonhosted.org/packages/eb/f7/1251bf6881861f24239efe0c24cbcfc4191ccdbb69ac3e9bb740d0c23352/astropy-3.1.1.tar.gz (8.2MB)
    100% |████████████████████████████████| 8.2MB 4.0MB/s
Collecting numpy>=1.13.0 (from astropy==3.1.1)
  Downloading https://files.pythonhosted.org/packages/ff/7f/9d804d2348471c67a7d8b5f84f9bc59fd1cefa148986f2b74552f8573555/numpy-1.15.4-cp36-cp36m-manylinux1_x86_64.whl (13.9MB)
    100% |████████████████████████████████| 13.9MB 2.3MB/s
Building wheels for collected packages: astropy
  Running setup.py bdist_wheel for astropy ... done
  Stored in directory: /root/.cache/pip/wheels/fb/14/cd/f2c011ba34de10ef429e694be2e776e1c28ac3204597295e97
Successfully built astropy
Installing collected packages: numpy, astropy
Successfully installed astropy-3.1.1 numpy-1.15.4
root@a13274f02663:/# python
Python 3.6.8 (default, Dec 29 2018, 07:23:17)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import astropy.io.ascii
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/astropy/io/ascii/__init__.py", line 7, in <module>
    from .core import (InconsistentTableError,
  File "/usr/local/lib/python3.6/site-packages/astropy/io/ascii/core.py", line 29, in <module>
    from astropy.table import Table
  File "/usr/local/lib/python3.6/site-packages/astropy/table/__init__.py", line 41, in <module>
    from .column import Column, MaskedColumn, StringTruncateWarning, ColumnInfo
  File "/usr/local/lib/python3.6/site-packages/astropy/table/column.py", line 26, in <module>
    from . import groups
  File "/usr/local/lib/python3.6/site-packages/astropy/table/groups.py", line 7, in <module>
    from .index import get_index_by_names
  File "/usr/local/lib/python3.6/site-packages/astropy/table/index.py", line 38, in <module>
    from astropy.time import Time
  File "/usr/local/lib/python3.6/site-packages/astropy/time/__init__.py", line 2, in <module>
    from .formats import *
  File "/usr/local/lib/python3.6/site-packages/astropy/time/formats.py", line 16, in <module>
    from astropy import _erfa as erfa
  File "/usr/local/lib/python3.6/site-packages/astropy/_erfa/__init__.py", line 4, in <module>
    from .core import *
  File "/usr/local/lib/python3.6/site-packages/astropy/_erfa/core.py", line 37, in <module>
    from . import ufunc
ImportError: numpy.core.multiarray failed to import
```

However if I force downgrade to 3.1.0 (same running container), there are no issues:

```
root@a13274f02663:/# pip install astropy==3.1.0
Collecting astropy==3.1.0
  Downloading https://files.pythonhosted.org/packages/ca/72/5d5784ab53387fc156f2a1bac5a822ef92c5096b915df0ca0880b639bc83/astropy-3.1-cp36-cp36m-manylinux1_x86_64.whl (6.2MB)
    100% |████████████████████████████████| 6.2MB 4.6MB/s
Requirement already satisfied: numpy>=1.13.0 in /usr/local/lib/python3.6/site-packages (from astropy==3.1.0) (1.15.4)
Installing collected packages: astropy
  Found existing installation: astropy 3.1.1
    Uninstalling astropy-3.1.1:
      Successfully uninstalled astropy-3.1.1
Successfully installed astropy-3.1
root@a13274f02663:/# python
Python 3.6.8 (default, Dec 29 2018, 07:23:17)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import astropy.io.ascii
>>>
```

**Comment by pllim** [comment]
I can't reproduce this using a combo of `conda` and `pip` on my local machine (Windows 10, no less). First, I created a fresh conda env with Python 3.6 (tried it on both 3.6.6 and 3.6.8). Then I `pip`-installed `astropy` as you did. For some weird reason (that I am pretty sure unrelated but rather caused by Git Bash + Anaconda + Windows weirdness), I also had to `conda install ipython` because the basic Python session hanged at starting up. So then, I go into my IPython session and did an `import astropy.io.ascii` and no traceback. Here is my `conda list` from Python 3.6.8 env:

```
$ conda list
# packages in environment at C:\...\Miniconda3\envs\py36tmp2:
#
# Name                    Version                   Build  Channel
astropy                   3.1.1                     <pip>
backcall                  0.1.0                      py_0    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
colorama                  0.4.1                      py_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
ipython                   7.2.0           py36h39e3cac_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.13.2                py36_1000    conda-forge
numpy                     1.15.4                    <pip>
parso                     0.3.1                      py_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pip                       18.1                  py36_1000    conda-forge
prompt_toolkit            2.0.7                      py_0    conda-forge
pygments                  2.3.1                      py_0    conda-forge
python                    3.6.8                h9f7ef89_0
setuptools                40.6.3                   py36_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
sqlite                    3.26.0            hfa6e2cd_1000    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
wincertstore              0.2                   py36_1002    conda-forge
```

Can this be caused by some other incompatibility in your Docker container rather than a problem with Astropy?

**Comment by mhvk** [comment]
Given #8330, I wonder if there perhaps is (or has been) a broken numpy version on pip or so that we are suffering from.

**Comment by travisgroth** [comment]
@mhvk I actually can't reproduce this anymore with the same image.  I'm unclear on how this is possible since it appears to be the same packages as the other day.  I was encountering it in multiple environments (granted, all docker) so I know it wasn't a single bad image or local system.

I'll reopen if I actually run into it again.
