### ISSUE TITLE
WCS: expected constructor to fail when given a missing FITS file

### ISSUE THREAD

**Issue by DougBurke** [astropy/astropy#8362]
I'm not sure if this is a bug or a feature, but it surprised me. I was expecting the call to `WCS` to fail, but instead it returns a "default" WCS object.

```
% ls -l ls -l does-not-exist
ls: cannot access does-not-exist: No such file or directory
% python -c 'from astropy.wcs import WCS; w = WCS("does-not-exist"); print("---"); print(w)'
WARNING: The following header keyword is invalid or follows an unrecognized non-standard convention:
does-not-exist                                                                   [astropy.io.fits.card]
---
WCS Keywords

Number of WCS axes: 2
CTYPE : ''  ''  
CRVAL : 0.0  0.0  
CRPIX : 0.0  0.0  
PC1_1 PC1_2  : 1.0  0.0  
PC2_1 PC2_2  : 0.0  1.0  
CDELT : 1.0  1.0  
NAXIS : 0  0
```

If I give an "obviously" missing FITS file (aka `/dev/null`) then I do get an error:

```
% python -c 'from astropy.wcs import WCS; w = WCS("/dev/null"); print("---"); print(w)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/lagado2.real/local/anaconda/envs/delme/lib/python3.7/site-packages/astropy/wcs/wcs.py", line 399, in __init__
    fobj = fits.open(header)
  File "/lagado2.real/local/anaconda/envs/delme/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 151, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/lagado2.real/local/anaconda/envs/delme/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 390, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/lagado2.real/local/anaconda/envs/delme/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1073, in _readfrom
    raise OSError('Empty or corrupt FITS file')
OSError: Empty or corrupt FITS file
```

While this is an edge case, I noticed it by accidentally giving my code an invalid file and then getting a result back from some coordinate conversion code rather than failing. For my current use case (some throw away code) it was easy to work around.

Seen with:

```
% conda list | egrep 'astropy|numpy|python'
astropy                   3.1.1            py37h7b6447c_0  
numpy                     1.15.4           py37h7e9f1db_0  
numpy-base                1.15.4           py37hde5b4d6_0  
pytest-astropy            0.5.0                    py37_0  
python                    3.7.2                h0371630_0  
```

and

```
% pip list --format=columns | egrep 'astropy|numpy|python'
astropy                  3.0.5     
ipython                  6.5.0     
ipython-genutils         0.2.0     
numpy                    1.12.1    
python-dateutil          2.7.3     
```

**Comment by pllim** [comment]
cc @nden

**Comment by nden** [comment]
Right, it creates a WCS object with naxis=2 by default. It's a convenience for programmatically creating  WCS objects. So I guess it's a feature.

**Comment by mcara** [comment]
Is this "feature" documented? If not, then it should be documented. This is indeed an unexpected behavior. Therefore documenting this is important so that users know that they need to check for existence of the file *before* attempting to create a `WCS` object and take appropriate action instead of proceeding as if everything is fine. This feature may be convenient in some situations but it could be dangerous in others.

**Comment by mcara** [comment]
> The programmatic use of the WCS class is documented.

What does this mean? On http://docs.astropy.org/en/stable/api/astropy.wcs.WCS.html#astropy.wcs.WCS the only thing that I see is:

> **header :** _astropy.io.fits header object, Primary HDU, Image HDU, string, dict-like, or None, optional_
If header is not provided or None, the object will be initialized to default values.

The documentation does not say anything about the behavior when header **is provided** but is invalid or does not exist. When I attempt to create a WCS from a non-existent file, I get:

```
In [4]: from astropy.wcs import WCS                                                                           

In [5]: w = WCS('not_existing.fits')                                                                          
WARNING: The following header keyword is invalid or follows an unrecognized non-standard convention:
not_existing.fits                                                                [astropy.io.fits.card]

In [6]: w                                                                                                     
Out[6]: 
WCS Keywords

Number of WCS axes: 2
CTYPE : ''  ''  
CRVAL : 0.0  0.0  
CRPIX : 0.0  0.0  
PC1_1 PC1_2  : 1.0  0.0  
PC2_1 PC2_2  : 0.0  1.0  
CDELT : 1.0  1.0  
NAXIS : 0  0
```

All that I get is a _warning_ about a _keyword_(!) There are no `OSError`s.

**Comment by pllim** [comment]
@mcara, perhaps your encounter is similar to #8362 . If the problem is outdated doc, we welcome PR to fix it. Thank you!

**Comment by nden** [comment]
IMHO there should be a limit to fool proofing the input. But I don't mind if you submit a PR to improve documentation or input checking in some sensible way. Note that the type of input you give above is valid as strings are a valid input. If you feel we need to validate the strings and you know what makes sense  please submit a PR.

If you pass a path to a file which exists but is not a FITS file it raises an `OSError`, as in the original failing example.

@DougBurke I apologize, I did not read the the question careful enough and my answer was referring to creating a WCS without passing an input, i.e. `w = wcs.WCS()`, which uses defaults and is part of the documentation.
