### ISSUE TITLE
Regression in std method on Angle objects

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#8368]
Since recently, there's one fail in the Gammapy tests with the dev version of Astropy (see [here](https://travis-ci.org/gammapy/gammapy/jobs/481550891#L2838)). Possibly this got introduced in #8316 ? cc @mhvk 

Here's a minimal test case:
```
$ python
>>> from astropy.coordinates import Angle
>>> Angle([1, 2], 'deg').std()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/software/anaconda3/envs/gammapy-dev-37/lib/python3.7/site-packages/numpy/core/_methods.py", line 140, in _std
    keepdims=keepdims)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev-37/lib/python3.7/site-packages/numpy/core/_methods.py", line 121, in _var
    x = um.multiply(x, x, out=x)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev-37/lib/python3.7/site-packages/astropy/units/quantity.py", line 453, in __array_ufunc__
    out_array = check_output(out, unit, inputs, function=function)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev-37/lib/python3.7/site-packages/astropy/units/quantity_helper/converters.py", line 324, in check_output
    output.__quantity_subclass__(unit)[0]))
astropy.units.core.UnitTypeError: Cannot store output with unit 'deg2' from multiply function in <class 'astropy.coordinates.angles.Angle'> instance.  Use <class 'astropy.units.quantity.Quantity'> instance instead.
```
I see this is on MacOS with Python 3.7 from conda (but I don't think the issue is Python version specific, only Astropy and Numpy version matter). My versions are:
```
>>> import astropy
>>> astropy.__version__
'3.2.dev23770'
>>> import numpy as np
>>> np.__version__
'1.15.4'
```

**Comment by mhvk** [comment]
@cdeil - thanks for catching that. Definitely due to #8316. It is a tricky one since the calculation of the standard deviation is done via the variance, which has units of deg2 and can thus not be stored in an `Angle` even though `std` itself can.

I think the best solution here is to revert the part for `std` and `var` - those probably better wait for an implementation of `__array_function__` (which allows overriding all numpy functions).

I pushed a fix in #8370.
