### ISSUE TITLE
Make it so that running pytest directly doesn't require an install

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#8488]
At the moment, the following doesn't work in the astropy repository:

```
python setup.py build_ext --inplace
pytest astropy
```

unless ``pip install -e .`` has been run beforehand, because of an issue related to asdf. The error in the above case is:

```
$ pytest astropy
Traceback (most recent call last):
  File "/Users/tom/python/dev/lib/python3.7/site-packages/_pytest/config/__init__.py", line 430, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/Users/tom/Dropbox/Code/Astropy/astropy/astropy/conftest.py')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tom/python/dev/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/Users/tom/python/dev/lib/python3.7/site-packages/_pytest/config/__init__.py", line 61, in main
    config = _prepareconfig(args, plugins)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/_pytest/config/__init__.py", line 196, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/Users/tom/python/dev/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/tom/python/dev/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/Users/tom/python/dev/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/tom/python/dev/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/_pytest/config/__init__.py", line 655, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/_pytest/config/__init__.py", line 841, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/_pytest/config/__init__.py", line 797, in _preparse
    early_config=self, args=args, parser=self._parser
  File "/Users/tom/python/dev/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/tom/python/dev/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/tom/python/dev/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/tom/python/dev/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/_pytest/config/__init__.py", line 699, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/_pytest/config/__init__.py", line 373, in _set_initial_conftests
    self._try_load_conftest(anchor)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/_pytest/config/__init__.py", line 379, in _try_load_conftest
    self._getconftestmodules(anchor)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/_pytest/config/__init__.py", line 414, in _getconftestmodules
    mod = self._importconftest(conftestpath.realpath())
  File "/Users/tom/python/dev/lib/python3.7/site-packages/_pytest/config/__init__.py", line 464, in _importconftest
    self.consider_conftest(mod)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/_pytest/config/__init__.py", line 503, in consider_conftest
    self.register(conftestmodule, name=conftestmodule.__file__)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/_pytest/config/__init__.py", line 318, in register
    self.consider_module(plugin)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/_pytest/config/__init__.py", line 509, in consider_module
    self._import_plugin_specs(getattr(mod, "pytest_plugins", []))
  File "/Users/tom/python/dev/lib/python3.7/site-packages/_pytest/config/__init__.py", line 514, in _import_plugin_specs
    self.import_plugin(import_spec)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/_pytest/config/__init__.py", line 533, in import_plugin
    __import__(importspec)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/tom/python/dev/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 296, in load_module
    six.exec_(co, mod.__dict__)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/asdf/tests/schema_tester.py", line 23, in <module>
    _ctx = AsdfFile()
  File "/Users/tom/python/dev/lib/python3.7/site-packages/asdf/asdf.py", line 122, in __init__
    self._process_extensions(extensions)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/asdf/asdf.py", line 206, in _process_extensions
    self._extensions = default_extensions.extension_list
  File "/Users/tom/python/dev/lib/python3.7/site-packages/asdf/extension.py", line 233, in extension_list
    self._extension_list = AsdfExtensionList(self.extensions)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/asdf/extension.py", line 226, in extensions
    self._load_installed_extensions()
  File "/Users/tom/python/dev/lib/python3.7/site-packages/asdf/extension.py", line 197, in _load_installed_extensions
    ext = entry_point.load()
  File "/Users/tom/python/dev/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2286, in load
    self.require(*args, **kwargs)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2303, in require
    items = working_set.resolve(reqs, env, installer)
  File "/Users/tom/python/dev/lib/python3.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'astropy' distribution was not found and is required by the application
```

@drdavella - could we make this a bit more robust so that e.g. we skip the ASDF tests if astropy is not installed?

**Comment by Cadair** [comment]
I mean as soon as you use things like entry points you really need to be installing the package. I am not sure this is really a usecase to be supported?

**Comment by astrofrog** [comment]
Looking at this closer, the issue is not about entry points per se, it's about the fact that currently the asdf pytest plugin is auto-registered if asdf is present but not necessarily if it is importable (it's only importable if astropy is installed).

@drdavella - is there any reason for using ``find_spec`` instead of just doing a ``try...except`` of importing asdf in ``conftest.py``?

**Comment by astrofrog** [comment]
A related issue is that ``find_spec`` sometimes gives weird results, for example I uninstalled asdf but ``find_spec`` is still returning not ``None`` so that I get the following error when running the tests:

```
$ pytest astropy
ImportError while loading conftest '/Users/tom/Dropbox/Code/Astropy/astropy/astropy/conftest.py'.
astropy/conftest.py:22: in <module>
    from asdf import __version__ as asdf_version
E   ImportError: cannot import name '__version__' from 'asdf' (unknown location)
```

I do think that for fast development of packages unrelated to entry points it would be good to avoid having to install the package, even in develop mode.

Related to this, I wonder whether adding the ASDF schema tester should be done via a pytest command-line argument rather than some magic in ``conftest.py``? Why not just make it opt-in with an ``--asdf-schema`` flag and add that in CI?

**Comment by drdavella** [comment]
The ASDF schema tester is a `pytest` plugin. The reason for the logic here is we can't make reference to the plugin if `asdf` is not installed (I believe this will cause a `pytest` error).

It's possible that using `try/except` is better in this case. I have seen weird issues with `find_spec` as well but assumed it was due to a degenerate state in my environment (e.g. installing a package with `conda` but removing it with `pip`).

**Comment by drdavella** [comment]
My comment above only addressed one aspect of this issue. My opinion is that we do not want to support this. Packages should be installed before being tested. This is a big part of the motivation behind the `src`/`test` directory discussion that came up on Slack recently. I'm not necessarily advocating for that particular change, but I would draw a hard line about requiring the package to be installed before testing.

**Comment by astrofrog** [comment]
Ok I think I'm convinced an install is necessary, but I would still advocate that the asdf schema tester be declared as a proper pytest plugin via entry points and enabled with a command-line flag rather than being auto-included based on whether it's installed or not.

**Comment by drdavella** [comment]
I've opened an issue to track this in `asdf`: https://github.com/spacetelescope/asdf/issues/657

Should this issue be closed now?

**Comment by astrofrog** [comment]
Yep, I'm happy with that option.
