### ISSUE TITLE
Table.read() is not guessing the format

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/astropy#8667]
Tested with `astropy` 2.0.12 and 3.1.2, both versions failed the following example:

    from astropy.table import Table
    data = Table.read('test.dat')

```
Traceback (most recent call last):
  File "/home/gabriel/Descargas/test.py", line 4, in <module>
    data = Table.read('test.dat')
  File "/home/gabriel/miniconda3/envs/asteca27/lib/python2.7/site-packages/astropy/table/table.py", line 2521, in read
    out = io_registry.read(cls, *args, **kwargs)
  File "/home/gabriel/miniconda3/envs/asteca27/lib/python2.7/site-packages/astropy/io/registry.py", line 528, in read
    'read', cls, path, fileobj, args, kwargs)
  File "/home/gabriel/miniconda3/envs/asteca27/lib/python2.7/site-packages/astropy/io/registry.py", line 616, in _get_valid_format
    "{0}".format(format_table_str))
astropy.io.registry.IORegistryError: Format could not be identified.
The available formats are:
           Format           Read Write Auto-identify Deprecated
--------------------------- ---- ----- ------------- ----------
                      ascii  Yes   Yes            No           
               ascii.aastex  Yes   Yes            No           
                ascii.basic  Yes   Yes            No           
                  ascii.cds  Yes    No            No           
     ascii.commented_header  Yes   Yes            No           
                  ascii.csv  Yes   Yes            No           
              ascii.daophot  Yes    No            No           
                 ascii.ecsv  Yes   Yes            No           
           ascii.fast_basic  Yes   Yes            No           
ascii.fast_commented_header  Yes   Yes            No           
             ascii.fast_csv  Yes   Yes            No           
       ascii.fast_no_header  Yes   Yes            No           
             ascii.fast_rdb  Yes   Yes            No           
             ascii.fast_tab  Yes   Yes            No           
          ascii.fixed_width  Yes   Yes            No           
ascii.fixed_width_no_header  Yes   Yes            No           
 ascii.fixed_width_two_line  Yes   Yes            No           
                 ascii.html  Yes   Yes           Yes           
                 ascii.ipac  Yes   Yes            No           
                ascii.latex  Yes   Yes           Yes           
            ascii.no_header  Yes   Yes            No           
                  ascii.rdb  Yes   Yes           Yes           
                  ascii.rst  Yes   Yes            No           
           ascii.sextractor  Yes    No            No           
                  ascii.tab  Yes   Yes            No           
                       fits  Yes   Yes           Yes           
                       hdf5  Yes   Yes           Yes           
                    votable  Yes   Yes           Yes           
                     aastex  Yes   Yes            No        Yes
                        cds  Yes    No            No        Yes
                        csv  Yes   Yes           Yes        Yes
                    daophot  Yes    No            No        Yes
                       html  Yes   Yes            No        Yes
                       ipac  Yes   Yes            No        Yes
                      latex  Yes   Yes            No        Yes
                        rdb  Yes   Yes            No        Yes
```

but work properly with:

    from astropy.table import Table
    data = Table.read('test.dat', format="ascii")

_________________________________________
`test.dat`

     16   3195.83   3736.45   11.869   0.039   0.3885   0.056   -0.0745    0.051    0.585     0.05  
     22   3071.23   1893.45   12.157    0.03   0.2805   0.035    0.0425    0.024    0.456    0.035  
     24    1235.4   1846.04   12.031   0.025   0.4285   0.036    0.0215    0.041    0.672    0.038  
     26   3335.12   2868.68   12.051    0.03   0.7865   0.041    0.0675    0.035    0.689    0.061

**Comment by taldcroft** [comment]
@Gabriel-p - this is just reflecting that the unified I/O layer does not recognize the `.dat` extension as a known extension associated with a specific format (e.g. `.fits` or `.ecsv`).  In this case it is never even trying `io.ascii` guessing.

I agree the exception message could be better, in particular you might have understood the situation if it said `Format could not be identified based on the extension ".dat", please provide a 'format' argument`.

**Comment by Gabriel-p** [comment]
@taldcroft absolutely, that would be a much more appropriate message to display.
