### ISSUE TITLE
IERS table update fails repeatedly 

### ISSUE THREAD

**Issue by jmccormac01** [astropy/astropy#8788]
I am using astropy.time to convert JD values. I've noticed recently that the update of the IERS data using the url ```http://maia.usno.navy.mil/ser7/finals2000A.all``` is constantly failing.

I seen this was an issue in older versions of astropy but from the issue tracker I thought there was a miror that would be attempted? I am using the latest release on pip, version 3.1.2

When updating the IERS data I get the following error:

```sh
>>> t.ut1
Downloading http://maia.usno.navy.mil/ser7/finals2000A.all
|>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|   0 /3.2M ( 0.00%)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.6/site-packages/astropy/time/core.py", line 1528, in __getattr__
    tm._set_scale(attr)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/astropy/time/core.py", line 718, in _set_scale
    args.append(get_dt(jd1, jd2))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/astropy/time/core.py", line 1653, in _get_delta_ut1_utc
    delta = iers_table.ut1_utc(jd1, jd2)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/astropy/utils/iers/iers.py", line 232, in ut1_utc
    self.ut1_utc_source if return_status else None)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/astropy/utils/iers/iers.py", line 361, in _interpolate
    self._check_interpolate_indices(i1, i, np.max(mjd))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/astropy/utils/iers/iers.py", line 679, in _check_interpolate_indices
    raise ValueError(INTERPOLATE_ERROR.format(auto_max_age))
ValueError: interpolating from IERS_Auto using predictive values that are more
than 30.0 days old.

Normally you should not see this error because this class
automatically downloads the latest IERS-A table.  Perhaps you are
offline?  If you understand what you are doing then this error can be
suppressed by setting the auto_max_age configuration variable to
``None``:

  from astropy.utils.iers import conf
  conf.auto_max_age = None

>>> t.ut1
Downloading http://maia.usno.navy.mil/ser7/finals2000A.all
|=======================================================================================================>----------------------------------------------------------------------------------------------------------------------------------| 1.4M/3.2M (44.14%) ETA    10s
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.6/site-packages/astropy/time/core.py", line 1528, in __getattr__
    tm._set_scale(attr)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/astropy/time/core.py", line 718, in _set_scale
    args.append(get_dt(jd1, jd2))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/astropy/time/core.py", line 1653, in _get_delta_ut1_utc
    delta = iers_table.ut1_utc(jd1, jd2)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/astropy/utils/iers/iers.py", line 232, in ut1_utc
    self.ut1_utc_source if return_status else None)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/astropy/utils/iers/iers.py", line 361, in _interpolate
    self._check_interpolate_indices(i1, i, np.max(mjd))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/astropy/utils/iers/iers.py", line 679, in _check_interpolate_indices
    raise ValueError(INTERPOLATE_ERROR.format(auto_max_age))
ValueError: interpolating from IERS_Auto using predictive values that are more
than 30.0 days old.

Normally you should not see this error because this class
automatically downloads the latest IERS-A table.  Perhaps you are
offline?  If you understand what you are doing then this error can be
suppressed by setting the auto_max_age configuration variable to
``None``:

  from astropy.utils.iers import conf
  conf.auto_max_age = None

>>>
``` 

Sometimes it starts to download then stalls, other times it does nothing. The example above is me trying to force an update by requesting a time in the future. 

Any help with this would be great, thanks. Also, if the table is out of date, do you know how wrong the times might be? If it is on the order of a second or so I don't really mind for this particular project. 

Thanks.

**Comment by pllim** [comment]
The server might have been down, which is beyond our control. Can you please try again?
