### ISSUE TITLE
download_file and flaky server (was: Trouble opening IERS table)

### ISSUE THREAD

**Issue by Warren-Porter** [astropy/astropy#8793]
This causes NumPy to throw an error:
```
from astropy.utils import iers
dat = iers.IERS_Auto.open()
```
I am guessing the error is because an empty array is being generated from the IERS data and being sent to NumPy. Here is the error traceback and error message:
```
ERROR: ValueError: zero-size array to reduction operation minimum which has no identity [numpy.core.fromnumeric]
Error in sys.excepthook:
Traceback (most recent call last):
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/astropy/logger.py", line 262, in _excepthook
    self._excepthook_orig(etype, value, traceback)
TypeError: 'NoneType' object is not callable

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 660, in open
    cls.iers_table = cls.read(file=filename)
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 507, in read
    table = cls._combine_a_b_columns(iers_a)
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 470, in _combine_a_b_columns
    table.meta['predictive_index'] = np.min(np.flatnonzero(is_predictive))
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2442, in amin
    initial=initial)
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 83, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

```
Any assistance would be greatly appreciated. Thank you!

**Comment by pllim** [comment]
Works fine for me. Are you sure it wasn't because the remote service was unavailable? 

```python
>>> from astropy.utils import iers
>>> dat = iers.IERS_Auto.open()
Downloading http://maia.usno.navy.mil/ser7/finals2000A.all
|==========================================| 3.2M/3.2M (100.00%)         0s
```

**Comment by pllim** [comment]
Note: Might be same underlying problem as #8788 , which is beyond our control.

**Comment by Warren-Porter** [comment]
I'm still a bit of a novice here. Is it realistic that I can access the data file at http://maia.usno.navy.mil/ser7/finals2000A.all with my browser, but not with AstroPy?

**Comment by pllim** [comment]
Ah, if you can see that file online, then maybe not connection issue. What are your Astropy, Numpy, and Python versions? How did you install them? What OS?

**Comment by Warren-Porter** [comment]
I'm using an anaconda environment with Python 3.7.2; NumPy 1.15.4; AstroPy 3.1.2 on a CentOS 7.6.1810 server.

I've also gotten the same problem on an older anaconda environment: Python 2.7.14; NumPy 1.14.2; AstroPy 2.0.8 running on both the aforementioned CentOS 7 server as well as a CentOS 6 server.

**Comment by mhvk** [comment]
@Warren-Porter - independently of the downloading problem (where the least we could do is give a better error message!), you should be able to open the downloaded file by passing it in to `IERS...open(file_name)`. Does that work?

**Comment by Warren-Porter** [comment]
Like this?
```
>>> iers.IERS.open('/data/home004/warren.porter/finals2000A.all')
Traceback (most recent call last):
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/astropy/io/ascii/core.py", line 953, in _convert_vals
    converter_func, converter_type = col.converters[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 166, in open
    cls.iers_table = cls.read(**kwargs)
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 579, in read
    data_start=data_start)
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/astropy/table/table.py", line 2550, in read
    out = io_registry.read(cls, *args, **kwargs)
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/astropy/io/registry.py", line 517, in read
    data = reader(*args, **kwargs)
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/astropy/io/ascii/connect.py", line 37, in io_read
    return read(filename, format=format, **kwargs)
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/astropy/io/ascii/ui.py", line 409, in read
    dat = reader.read(table)
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/astropy/io/ascii/cds.py", line 323, in read
    return super().read(table)
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/astropy/io/ascii/core.py", line 1197, in read
    table = self.outputter(cols, self.meta)
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/astropy/io/ascii/core.py", line 984, in __call__
    self._convert_vals(cols)
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/astropy/io/ascii/core.py", line 969, in _convert_vals
    raise ValueError('Column {} failed to convert: {}'.format(col.name, last_err))
ValueError: Column year failed to convert: invalid literal for int() with base 10: '73 1'

```

**Comment by mhvk** [comment]
Yes, but with `IERS_A.open(...)`.

**Comment by pllim** [comment]
`invalid literal for int() with base 10`

This sounds so familiar!!!

**Comment by Warren-Porter** [comment]
This seems to work:
```
>>> datA = iers.IERS_A.open('/data/home004/warren.porter/finals2000A.all')
>>> type(datA)
<class 'astropy.utils.iers.iers.IERS_A'>
```
Is datA equivalent to dat that I was using before?

**Comment by mhvk** [comment]
Yes, one can use the file. The idea is described in https://docs.astropy.org/en/latest/utils/iers.html#utils-iers; briefly, I think to circumvent the download, one would do
```
iers.IERS.iers_table = datA
iers.conf.auto_download = False
```
(but please check; I must admit it is quite a while since I wrote/used it...)

**Comment by pllim** [comment]
Sounds a lot like #7943 but you say you are using Numpy 1.15.4 and not 1.15.3. Do you have multiple versions of Numpy installed?

**Comment by Warren-Porter** [comment]
With the help of @mhvk, I've achieved a workaround using a copy of the IERS data that I've downloaded to my local storage using wget, but I'd really like to be able to run this script automatically each day and I'm still interested in fixing this problem so I won't have to manually downloading this file every week.

@pllim, I have multiple conda environments that I use to keep track of different package versions. I've encountered this problem in two different environments: one runs NumPy 1.14.5 and the other runs 1.14.2 and I've not tried this with NumPy 1.13.3

**Comment by pllim** [comment]
I wonder if you create a fresh env with latest Numpy and Astropy 3.2rc2, it would just work... :thinking:

**Comment by Warren-Porter** [comment]
I updated NumPy to 1.16.4, but the problem remains.
I am already using AstroPy 3.1.2, which is the latest version (I see no 3.2 version available).

**Comment by mhvk** [comment]
@Warren-Porter - weird that even the update doesn't work. It suggests there is something else that is special in your environment. To narrow it down, does
```
from astropy.utils import data, iers
data.download_file(iers.IERS_A_URL)
```
work? (this doesn't cache by default)

Also, could you let us know what you get from
```
iers.conf.__class__.__dict__
mappingproxy({'__module__': 'astropy.utils.iers.iers',
              '__doc__': '\n    Configuration parameters for `astropy.utils.iers`.\n    ',
              'auto_download': <ConfigItem: name='auto_download' value=True at 0x7f25b408f748>,
              'auto_max_age': <ConfigItem: name='auto_max_age' value=30.0 at 0x7f25a7dfc4a8>,
              'iers_auto_url': <ConfigItem: name='iers_auto_url' value='http://maia.usno.navy.mil/ser7/finals2000A.all' at 0x7f25a6fbcac8>,
              'iers_auto_url_mirror': <ConfigItem: name='iers_auto_url_mirror' value='http://toshi.nofs.navy.mil/ser7/finals2000A.all' at 0x7f25a7d6bb38>,
              'remote_timeout': <ConfigItem: name='remote_timeout' value=10.0 at 0x7f25a7d6bb70>})
```

**Comment by Warren-Porter** [comment]
When I try this, the download appears successful, but I get the same error when I try to read the temporary file:
```
>>>from astropy.utils import data, iers
>>> mytmpfile = data.download_file(iers.IERS_A_URL)
Downloading http://maia.usno.navy.mil/ser7/finals2000A.all
|=========================================================================================================================================================================| 3.2M/3.2M (100.00%)      1m 8s
>>> datA = iers.IERS_A.open(mytmpfile)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 166, in open
    cls.iers_table = cls.read(**kwargs)
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 507, in read
    table = cls._combine_a_b_columns(iers_a)
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 470, in _combine_a_b_columns
    table.meta['predictive_index'] = np.min(np.flatnonzero(is_predictive))
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2618, in amin
    initial=initial)
  File "/data/home004/warren.porter/anaconda3/envs/CrIS_geolocation_3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
>>> mytmpfile
'/tmp/tmpn7tj3bsx'
```
When I navigate to the /tmp/ directory, I cannot find any file named tmpn7tj3bsx, should I expect to see it here?

As requested:
```
>>> iers.conf.__class__.__dict__
mappingproxy({'__module__': 'astropy.utils.iers.iers', '__doc__': '\n    Configuration parameters for `astropy.utils.iers`.\n    ', 'auto_download': <ConfigItem: name='auto_download' value=True at 0x7fd8df808710>, 'auto_max_age': <ConfigItem: name='auto_max_age' value=30.0 at 0x7fd8df9ec9e8>, 'iers_auto_url': <ConfigItem: name='iers_auto_url' value='http://maia.usno.navy.mil/ser7/finals2000A.all' at 0x7fd8ec202c50>, 'iers_auto_url_mirror': <ConfigItem: name='iers_auto_url_mirror' value='http://toshi.nofs.navy.mil/ser7/finals2000A.all' at 0x7fd8e0052828>, 'remote_timeout': <ConfigItem: name='remote_timeout' value=10.0 at 0x7fd8e0052860>})
```

**Comment by mhvk** [comment]
Well, we're getting somewhere. The opening with `iers.IERS_A.open(mytmpfile)` works fine for me, and I do see the file in the location it indicates:
```
mytmpfile
# '/tmp/user/2500/tmpokm_a5t7'
ls -l /tmp/user/2500/tmpokm_a5t7
# -rw------- 1 mhvk mhvk 3266124 Jun  5 16:48 /tmp/user/2500/tmpokm_a5t7
```
So, at least we now know this is a problem with downloading rather than `iers`.

Clutching at straws here, but is your `/tmp` writable? I.e., in a shell, does
```
echo bla >/tmp/a.a
```
work?

**Comment by Warren-Porter** [comment]
Nevermind my previous comment. The tmp file is successfully created, but when I do iers.IERS_A.open(mytmpfile), I get the same error as before.

**Comment by mhvk** [comment]
OK, on we go! How large is the tmp file? Is it 3266124 like I got above?

**Comment by Warren-Porter** [comment]
I've created a bunch of these tmp files ever since I started troubleshooting this problem earlier this month. Only one is the proper size (and also works as intended). I'm guessing my connection with the server keeps getting interrupted and IERS isn't able to resume the download where it left off?
```
>>> for tmpfile in glob.glob('/tmp/tmp*'): tmpfile, datetime.datetime.utcfromtimestamp(os.path.getmtime(tmpfile)).strftime('%Y-%m-%d %H:%M:%S'), os.path.getsize(tmpfile)
...
('/tmp/tmp_sm08rlt', '2019-06-05 22:48:14', 77722)
('/tmp/tmpynrovssv', '2019-06-04 14:24:20', 6)
('/tmp/tmpi2c8b9yf', '2019-06-04 14:25:08', 89)
('/tmp/tmprfppo6qa', '2019-06-05 18:49:21', 103714)
('/tmp/tmpm4p2b71s', '2019-06-05 22:11:08', 2150242)
('/tmp/tmpdpcemvl3', '2019-06-05 22:38:50', 322594)
('/tmp/tmpdvelt1ry', '2019-06-05 22:44:55', 1471714)
('/tmp/tmpn13c8ryh', '2019-06-02 00:53:16', 1048576)
('/tmp/tmppqz7ycrc', '2019-06-02 00:53:13', 786432)
('/tmp/tmpp0zbk6_c', '2019-06-02 00:53:10', 786432)
('/tmp/tmpbkk7mmmn', '2019-06-02 00:53:10', 65536)
('/tmp/tmpy9ty4ghu', '2019-06-02 00:53:14', 786432)
('/tmp/tmpocua0487', '2019-06-02 00:53:14', 393216)
('/tmp/tmpdj6m8xqc', '2019-06-02 00:53:05', 0)
('/tmp/tmp04w61s89', '2019-06-02 00:53:16', 458752)
('/tmp/tmptp91bfgg', '2019-06-04 14:23:13', 385)
('/tmp/tmp8eow5vpe', '2019-06-04 14:24:19', 246)
('/tmp/tmpm0o14g2f', '2019-06-04 14:25:08', 10)
('/tmp/tmp2b8_mijk', '2019-06-05 22:28:44', 1434778)
('/tmp/tmpnyuxgaml', '2019-06-05 22:40:44', 3266124)
('/tmp/tmp3u4nafpn', '2019-06-02 00:53:07', 1769472)
('/tmp/tmpgt1ppf2a', '2019-06-02 00:53:09', 458752)
('/tmp/tmpaz0e0sim', '2019-06-02 00:53:16', 1245184)
('/tmp/tmpxtj8m030', '2019-06-02 00:53:16', 327680)
('/tmp/tmpbiljl7vm', '2019-06-02 00:53:11', 2097152)
('/tmp/tmpndnvwmas', '2019-06-02 00:53:08', 65536)
('/tmp/tmpwszliqgt', '2019-06-02 00:53:15', 851968)
('/tmp/tmp7sm5h1pv', '2019-06-02 00:53:16', 1703936)
('/tmp/tmpw6lt5zox', '2019-06-02 00:53:13', 458752)
('/tmp/tmp8544q_08', '2019-06-02 00:53:15', 917504)
('/tmp/tmp_xz9tq4u', '2019-06-02 00:53:12', 655360)
('/tmp/tmpbxk6hfaj', '2019-06-02 00:53:12', 1507328)
('/tmp/tmplu2r64xx', '2019-06-02 00:53:07', 524288)
('/tmp/tmp9y46fq7b', '2019-06-02 00:53:15', 655360)
('/tmp/tmpwwqeui04', '2019-06-02 00:53:14', 917504)
('/tmp/tmpn66cobcr', '2019-06-04 14:23:03', 146)
('/tmp/tmpqunfgu9d', '2019-06-04 14:23:03', 385)
('/tmp/tmps23k1l1l', '2019-06-04 14:24:19', 246)
('/tmp/tmpvvre4jth', '2019-06-04 14:25:08', 96)
('/tmp/tmpetgd895k', '2019-06-04 14:25:08', 89)
('/tmp/tmpr1j8yxt1', '2019-06-05 22:43:24', 1999762)
('/tmp/tmpsf4lbfs6', '2019-06-06 14:50:57', 84562)
('/tmp/tmpeay53rpy', '2019-06-06 14:58:23', 819178)
```

**Comment by pllim** [comment]
I wonder if a stricter check is necessary at

https://github.com/astropy/astropy/blob/18b43ddcbb9da43c8b05c791e18ce3f6613aec02/astropy/utils/iers/iers.py#L642-L648

to ensure that the downloaded file is actually not corrupted.

Side note: By default, calling `IERS_Auto.open()` should have tried to cache the data file. But why is it writing to `/tmp` and not `~/.astropy/cache`?

**Comment by Warren-Porter** [comment]
I think I actually was calling data.download_file(iers.IERS_A_URL) earlier. Before sharing my issue on here, I took a look at the iers.py source code and tried alternative ways to download this datafile. I didn't really know what I was doing and just copied and pasted lines that seemed to be connected with downloading that file and I think that may have been one of them.

**Comment by Warren-Porter** [comment]
At first I thought those were just created by my attempt to debug this on my own on Monday, but plenty of those files were created shortly after midnight on Sunday, which is right when my cronjob calls the IERS_Auto.open() function.

**Comment by Warren-Porter** [comment]
I'm guessing the frequent interruptions means this is ultimately a server side problem. Wget is able to tolerate these and reconnect to get more bytes, is it possible to configure AstroPy to do the same?
```
-bash 4.2 $ wget http://maia.usno.navy.mil/ser7/finals2000A.all
--2019-06-06 15:37:19--  http://maia.usno.navy.mil/ser7/finals2000A.all
Resolving maia.usno.navy.mil (maia.usno.navy.mil)... 199.211.133.23
Connecting to maia.usno.navy.mil (maia.usno.navy.mil)|199.211.133.23|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3266124 (3.1M) [text/plain]
Saving to: ‘finals2000A.all’

 5% [========>                                                                                                                                                             ] 177,548     6.54KB/s   in 24s

2019-06-06 15:37:43 (7.24 KB/s) - Connection closed at byte 177548. Retrying.

--2019-06-06 15:37:44--  (try: 2)  http://maia.usno.navy.mil/ser7/finals2000A.all
Connecting to maia.usno.navy.mil (maia.usno.navy.mil)|199.211.133.23|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 3266124 (3.1M), 3088576 (2.9M) remaining [text/plain]
Saving to: ‘finals2000A.all’

20% [+++++++++========================>                                                                                                                                    ] 676,518     10.9KB/s   in 39s

2019-06-06 15:38:23 (12.4 KB/s) - Connection closed at byte 676518. Retrying.

--2019-06-06 15:38:25--  (try: 3)  http://maia.usno.navy.mil/ser7/finals2000A.all
Connecting to maia.usno.navy.mil (maia.usno.navy.mil)|199.211.133.23|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 3266124 (3.1M), 2589606 (2.5M) remaining [text/plain]
Saving to: ‘finals2000A.all’

26% [++++++++++++++++++++++++++++++++++========>                                                                                                                           ] 863,584     10.5KB/s   in 17s

2019-06-06 15:38:42 (10.5 KB/s) - Connection closed at byte 863584. Retrying.

--2019-06-06 15:38:45--  (try: 4)  http://maia.usno.navy.mil/ser7/finals2000A.all
Connecting to maia.usno.navy.mil (maia.usno.navy.mil)|199.211.133.23|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 3266124 (3.1M), 2402540 (2.3M) remaining [text/plain]
Saving to: ‘finals2000A.all’

52% [+++++++++++++++++++++++++++++++++++++++++++===========================================>                                                                               ] 1,727,810   17.9KB/s   in 28s

2019-06-06 15:39:13 (30.3 KB/s) - Connection closed at byte 1727810. Retrying.

--2019-06-06 15:39:17--  (try: 5)  http://maia.usno.navy.mil/ser7/finals2000A.all
Connecting to maia.usno.navy.mil (maia.usno.navy.mil)|199.211.133.23|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 3266124 (3.1M), 1538314 (1.5M) remaining [text/plain]
Saving to: ‘finals2000A.all’

56% [+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++======>                                                                        ] 1,853,315   7.11KB/s   in 17s

2019-06-06 15:39:35 (7.11 KB/s) - Connection closed at byte 1853315. Retrying.

--2019-06-06 15:39:40--  (try: 6)  http://maia.usno.navy.mil/ser7/finals2000A.all
Connecting to maia.usno.navy.mil (maia.usno.navy.mil)|199.211.133.23|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 3266124 (3.1M), 1412809 (1.3M) remaining [text/plain]
Saving to: ‘finals2000A.all’

60% [++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++======>                                                                 ] 1,991,132   6.65KB/s   in 20s

2019-06-06 15:40:00 (6.65 KB/s) - Connection closed at byte 1991132. Retrying.

--2019-06-06 15:40:06--  (try: 7)  http://maia.usno.navy.mil/ser7/finals2000A.all
Connecting to maia.usno.navy.mil (maia.usno.navy.mil)|199.211.133.23|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 3266124 (3.1M), 1274992 (1.2M) remaining [text/plain]
Saving to: ‘finals2000A.all’

67% [+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++==========>                                                      ] 2,205,557   14.3KB/s   in 15s

2019-06-06 15:40:21 (14.3 KB/s) - Connection closed at byte 2205557. Retrying.

--2019-06-06 15:40:28--  (try: 8)  http://maia.usno.navy.mil/ser7/finals2000A.all
Connecting to maia.usno.navy.mil (maia.usno.navy.mil)|199.211.133.23|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 3266124 (3.1M), 1060567 (1.0M) remaining [text/plain]
Saving to: ‘finals2000A.all’

71% [++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++======>                                               ] 2,342,006   10.7KB/s   in 12s

2019-06-06 15:40:40 (10.7 KB/s) - Connection closed at byte 2342006. Retrying.

--2019-06-06 15:40:48--  (try: 9)  http://maia.usno.navy.mil/ser7/finals2000A.all
Connecting to maia.usno.navy.mil (maia.usno.navy.mil)|199.211.133.23|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 3266124 (3.1M), 924118 (902K) remaining [text/plain]
Saving to: ‘finals2000A.all’

86% [+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++=======================>                       ] 2,823,192   17.9KB/s   in 32s

2019-06-06 15:41:21 (14.6 KB/s) - Connection closed at byte 2823192. Retrying.

--2019-06-06 15:41:30--  (try:10)  http://maia.usno.navy.mil/ser7/finals2000A.all
Connecting to maia.usno.navy.mil (maia.usno.navy.mil)|199.211.133.23|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 3266124 (3.1M), 442932 (433K) remaining [text/plain]
Saving to: ‘finals2000A.all’

100%[+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++======================>] 3,266,124   13.3KB/s   in 24s

2019-06-06 15:41:53 (18.3 KB/s) - ‘finals2000A.all’ saved [3266124/3266124]
```

**Comment by pllim** [comment]
@Warren-Porter , `download_file` is not that smart. It calls `urllib` directly. You can check the code at

https://github.com/astropy/astropy/blob/18b43ddcbb9da43c8b05c791e18ce3f6613aec02/astropy/utils/data.py#L947

**Comment by Warren-Porter** [comment]
You don't say:

```
>>> if True:
...         with urllib.request.urlopen(remote_url, timeout=timeout) as remote:
...             # keep a hash to rename the local file to the hashed name
...             hash = hashlib.md5()
...             info = remote.info()
...             if 'Content-Length' in info:
...                 try:
...                     size = int(info['Content-Length'])
...                 except ValueError:
...                     size = None
...             else:
...                 size = None
...             if size is not None:
...                 data.check_free_space_in_dir(gettempdir(), size)
...                 if cache:
...                     data.check_free_space_in_dir(dldir, size)
...             if show_progress and sys.stdout.isatty():
...                 progress_stream = sys.stdout
...             else:
...                 progress_stream = io.StringIO()
...             dlmsg = "Downloading {0}".format(remote_url)
...             with ProgressBarOrSpinner(size, dlmsg, file=progress_stream) as p:
...                 with NamedTemporaryFile(delete=False) as f:
...                     try:
...                         bytes_read = 0
...                         block = remote.read(conf.download_block_size)
...                         while block:
...                             f.write(block)
...                             hash.update(block)
...                             bytes_read += len(block)
...                             p.update(bytes_read)
...                             block = remote.read(conf.download_block_size)
...                     except BaseException:
...                         if os.path.exists(f.name):
...                             os.remove(f.name)
...                         raise
...
Downloading http://maia.usno.navy.mil/ser7/finals2000A.all
|>------------------------------------------------------------------------------------------------------------------------------------------------------------------------|   0 /3.2M ( 0.00%)65536
|===>---------------------------------------------------------------------------------------------------------------------------------------------------------------------|  65k/3.2M ( 2.01%) ETA     0s65536
|======>------------------------------------------------------------------------------------------------------------------------------------------------------------------| 131k/3.2M ( 4.01%) ETA     0s65536
|==========>--------------------------------------------------------------------------------------------------------------------------------------------------------------| 196k/3.2M ( 6.02%) ETA     0s65536
|=============>-----------------------------------------------------------------------------------------------------------------------------------------------------------| 262k/3.2M ( 8.03%) ETA     0s65536
|================>--------------------------------------------------------------------------------------------------------------------------------------------------------| 327k/3.2M (10.03%) ETA    12s65536
|====================>----------------------------------------------------------------------------------------------------------------------------------------------------| 393k/3.2M (12.04%) ETA    20s65536
|=======================>-------------------------------------------------------------------------------------------------------------------------------------------------| 458k/3.2M (14.05%) ETA    17s65536
|===========================>---------------------------------------------------------------------------------------------------------------------------------------------| 524k/3.2M (16.05%) ETA    21s65536
|==============================>------------------------------------------------------------------------------------------------------------------------------------------| 589k/3.2M (18.06%) ETA  1m13s27010
|=========================================================================================================================================================================| 3.2M/3.2M (100.00%)        29s
```

**Comment by mhvk** [comment]
Removing `close?` as I'm not sure we reached a conclusion yet!

**Comment by pllim** [comment]
I don't know. Did we ever guarantee that `download_file` would work in spotty server connections? PR would be welcome but I don't have time to work on this.

**Comment by Warren-Porter** [comment]
At the very least, there should be a more informative error message so the user knows what is going on. Maybe the message can even suggest doing what I have done (download the file using wget and access the local file offline).

**Comment by pllim** [comment]
We could consider using [urlretrieve](https://docs.python.org/3/library/urllib.request.html#urllib.request.urlretrieve), not unlike astropy/package-template#410 . cc @bsipocz and @Cadair

**Comment by pllim** [comment]
Update: With #8993 , maybe it won't be as flaky anymore if the connection problem was not at your end? Try check with latest astropy dev version. FYI.

**Comment by timj** [comment]
Just a footnote here but LSST are hitting this exact problem with IERS A. Our problem is exacerbated by our CI system not having `$HOME` defined so every time we run multi-process pytest within the build we download the file again. Sometimes they are truncated and we were getting the exact same problem from line 470 of iers.py.  @pllim thanks for pointing me at this issue. We were hoping not to have to deal with a local copy of the tables in Jenkins in the short term but it sounds like we may have to bump that up a bit.

**Comment by aarchiba** [comment]
I don't know about Jenkins, but Travis CI supports caching certain files - that is, keeping the contents of certain directories stored between CI runs. We did this for PINT ( https://github.com/nanograv/PINT/blob/207275b4368df2a10703b99d596ed8d3c01f1faa/.travis.yml ) and our server problems have dropped to nearly zero, though we don't actually need continuously-updated files.

download_file already measures the file size and counts how many bytes it gets, it would be an easy patch to fix this. I'll put in a PR.

**Comment by pllim** [comment]
@Warren-Porter , if what @aarchiba did over at #9302 satisfies your request of a better error message, please close this issue.

**Comment by Warren-Porter** [comment]
That sounds promising. I'm currently traveling at the moment and I won't be able to test the update until mid-October, but I will let you folks know once I do so.

**Comment by pllim** [comment]
@Warren-Porter , please let us know when you have a chance. Thanks!
