### ISSUE TITLE
I/O for empty BinTableHDU

### ISSUE THREAD

**Issue by kbwestfall** [astropy/astropy#8802]
A bit of a low-priority corner case:

When an empty `BinTableHDU` is written to a file and then the file is reopened, the result depends on whether or not the written file was gzipped:

```
import numpy
from astropy.io import fits

ofile = 'emptytable.fits'
fits.HDUList([fits.PrimaryHDU(),
              fits.ImageHDU(data=numpy.zeros(100).reshape(10,10)),
              fits.BinTableHDU(header=None, data=None, name='TEST')]).writeto(ofile, overwrite=True)

hdu = fits.open(ofile)
print(hdu['TEST'].data is None)
print(hdu['TEST'].data.size == 0)

ofile = 'emptytable.fits.gz'
fits.HDUList([fits.PrimaryHDU(),
              fits.ImageHDU(data=numpy.zeros(100).reshape(10,10)),
              fits.BinTableHDU(header=None, data=None, name='TEST')]).writeto(ofile, overwrite=True)

hdu = fits.open(ofile)
print(hdu['TEST'].data is None)
```

The first two print statements work fine, but the last one faults with the following:
```
Traceback (most recent call last):
  File "binio.py", line 19, in <module>
    print(hdu['TEST'].data is None)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astropy/utils/decorators.py", line 744, in __get__
    val = self.fget(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astropy/io/fits/hdu/table.py", line 406, in data
    data = self._get_tbdata()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astropy/io/fits/hdu/table.py", line 172, in _get_tbdata
    self._data_offset)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 475, in _get_raw_data
    return self._file.readarray(offset=offset, dtype=code, shape=shape)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astropy/io/fits/file.py", line 338, in readarray
    data = _array_from_file(self._file, dtype, count)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astropy/io/fits/util.py", line 585, in _array_from_file
    array = np.frombuffer(s, dtype=dtype, count=count)
ValueError: itemsize cannot be zero in type
```

It's not hard to work around this (just don't write extensions with empty binary tables), but I thought I would bring it up.

Python 3.6.2
numpy==1.16.2
astropy==3.1.2

Let me know if you need any other versions.

Thanks!

**Comment by saimn** [comment]
Thanks for the report. The read method is different for gzipped file:

https://github.com/astropy/astropy/blob/781d4da99792c072c65a7d23aa91604390471df8/astropy/io/fits/util.py#L581-L590

We should probably make a special case when there are no bytes to read:
```
(Pdb++) s
b''
(Pdb++) dtype
dtype([])
(Pdb++) count
0
(Pdb++) np.frombuffer(s, dtype=dtype, count=count)
*** ValueError: itemsize cannot be zero in type
```

Not sure what the best solution is, maybe return something like `np.array([], dtype=dtype)` when `s` is empty?
@mhvk, do you see a better solution?

**Comment by mhvk** [comment]
I think in this case you might be able to use the regular `ndarray` initializer; at least, this works:
```
In [7]: np.ndarray(buffer=b'', dtype=np.dtype([]), shape=(0,))
Out[7]: array([], dtype=[])
```
Of course, for the general case you'd use `shape=(count,)`.
(`frombuffer` is more focussed on the actual buffer, e.g., adding the ability to read all bytes without giving an explicit shape).
