### ISSUE TITLE
'Column' object has no 'mask' on transforming coordinates

### ISSUE THREAD

**Issue by lnigro4** [astropy/astropy#8829]
I can't figure out why this code

```
from astropy.coordinates import EarthLocation
from astropy.time import Time
from astropy import units as u
from astropy.coordinates import SkyCoord, AltAz, ICRS
from astropy.table import Table

t0=Time('2019-06-9 1:00:00')
local= EarthLocation(lat='45d31m59.85s', lon='9d13m33.03s', height=144*u.m)
alt='66.2d'
azimuth='91.3d'
coord_aa=(SkyCoord(azimuth, alt, frame=AltAz(location=local,obstime=t0)))
coord_aa.transform_to('icrs')
```
is giving me this:
`AttributeError: 'Column' object has no attribute 'mask'`

**Comment by pllim** [comment]
What version are you using? I cannot reproduce your error with Astropy 3.2 and Numpy 1.16.3. I see this:

```python
>>> coord_aa.transform_to('icrs')
Downloading http://maia.usno.navy.mil/ser7/finals2000A.all
|==========================================| 3.2M/3.2M (100.00%)         0s
<SkyCoord (ICRS): (ra, dec) in deg
    (313.08421964, 40.21215673)>
```

**Comment by lnigro4** [comment]
>What version are you using? I cannot reproduce your error with Astropy 3.2 and Numpy 1.16.3. I see this: ...

@pllim just upgraded to Astropy 3.2 but still having same issue

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lnigro4** [comment]
This is the entire error message:
```
Traceback (most recent call last):
  File "/Users/nigresson/Documents/Test.py", line 12, in <module>
    coord_aa.transform_to('icrs')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/coordinates/sky_coordinate.py", line 443, in transform_to
    new_coord = trans(self.frame, generic_frame)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/coordinates/transformations.py", line 1377, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/coordinates/transformations.py", line 980, in __call__
    return supcall(fromcoord, toframe)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/coordinates/builtin_frames/cirs_observed_transforms.py", line 91, in altaz_to_cirs
    xp, yp = get_polar_motion(altaz_coo.obstime)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/coordinates/builtin_frames/utils.py", line 41, in get_polar_motion
    xp, yp, status = iers.IERS_Auto.open().pm_xy(time, return_status=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 660, in open
    cls.iers_table = cls.read(file=filename)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 507, in read
    table = cls._combine_a_b_columns(iers_a)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 420, in _combine_a_b_columns
    table = iers_a[~iers_a['UT1_UTC_A'].mask &
AttributeError: 'Column' object has no attribute 'mask'
```

**Comment by pllim** [comment]
Did you see a "Downloading" message?

**Comment by lnigro4** [comment]
>Did you see a "Downloading" message? 

@pllim only once

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pllim** [comment]
How big is the file? We had a problem recently where user saw weird behavior due to corrupted download (xref #8793). And what is your Numpy version?

**Comment by lnigro4** [comment]
>How big is the file? We had a problem recently where user saw weird behavior due to corrupted download (xref #8793). And what is your Numpy version?

@pllim last Numpy version...fir how big the file

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pllim** [comment]
Please provide both info:

* Downloaded file size
* Numpy version

**Comment by lnigro4** [comment]
- since it happened the first try of the code, I don't remember the file size (it MIGHT be possible 20/30s times 100kB makes somewhat around 2/3MB, but I'm really not sure)
- Numpy v1.16.4

**Comment by pllim** [comment]
Here is what I am going to suggest.

1. Delete your `~/.astropy/cache` directory. (Only do this if there is no cached files you want to keep.)
2. Make sure your internet connection is stable. Hard-wired ethernet cable, if possible.
3. Try again.

**Comment by lnigro4** [comment]
@pllim Just did what you suggested: I deleted the _pycache_ directory in Astropy, but I get the same error message without downloading anything

**Comment by pllim** [comment]
> I deleted the pycache directory in Astropy

`~/.astropy/cache` is not the same as `__pycache__`, if I understood you correctly. Please see http://docs.astropy.org/en/stable/config/

**Comment by lnigro4** [comment]
@pllim ok I removed the `__pycache__` before. 
Now that I did
```
rm -r .astropy/cache
```
I downloaded again the 3.2M file (but with a moderate wifi connection, I'm not home rn), but still error occur! This time is a different one:
```
Traceback (most recent call last):
  File "/Users/nigresson/Documents/Test.py", line 12, in <module>
    coord_aa.transform_to('icrs')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/coordinates/sky_coordinate.py", line 443, in transform_to
    new_coord = trans(self.frame, generic_frame)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/coordinates/transformations.py", line 1377, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/coordinates/transformations.py", line 980, in __call__
    return supcall(fromcoord, toframe)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/coordinates/builtin_frames/cirs_observed_transforms.py", line 91, in altaz_to_cirs
    xp, yp = get_polar_motion(altaz_coo.obstime)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/coordinates/builtin_frames/utils.py", line 41, in get_polar_motion
    xp, yp, status = iers.IERS_Auto.open().pm_xy(time, return_status=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 660, in open
    cls.iers_table = cls.read(file=filename)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 507, in read
    table = cls._combine_a_b_columns(iers_a)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/utils/iers/iers.py", line 470, in _combine_a_b_columns
    table.meta['predictive_index'] = np.min(np.flatnonzero(is_predictive))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2618, in amin
    initial=initial)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
```
I'm start thinking of a bad downloading of the file (?). I'll try later tonight with ethernet cable at home

**Comment by lnigro4** [comment]
@pllim Solved it! It was just a download-related problem, thank you.
