### ISSUE TITLE
AWS Lambda configuration error

### ISSUE THREAD

**Issue by jbcurtin** [astropy/astropy#9189]
When running `astroquery.mast import Observations` in AWSLambda, the following stack-trace appears
```
Traceback (most recent call last):
  File "/var/task/aws_fullframe_fits.py", line 18, in aws_fullframe_fits
    from astroquery.mast import Observations
  File "/var/task/astroquery/mast/__init__.py", line 34, in <module>
    from .core import Observations, ObservationsClass, Catalogs, CatalogsClass, Mast, MastClass
  File "/var/task/astroquery/mast/core.py", line 2204, in <module>
    Observations = ObservationsClass()
  File "/var/task/astroquery/mast/core.py", line 984, in __init__
    super(ObservationsClass, self).__init__(*args, **kwargs)
  File "/var/task/astroquery/mast/core.py", line 148, in __init__
    super(MastClass, self).__init__()
  File "/var/task/astroquery/query.py", line 372, in __init__
    super(QueryWithLogin, self).__init__()
  File "/var/task/astroquery/query.py", line 156, in __init__
    paths.get_cache_dir(), 'astroquery',
  File "/var/task/astropy/config/paths.py", line 159, in get_cache_dir
    return os.path.abspath(_find_or_create_astropy_dir('cache', linkto))
  File "/var/task/astropy/config/paths.py", line 273, in _find_or_create_astropy_dir
    innerdir = os.path.join(_find_home(), '.astropy')
  File "/var/task/astropy/config/paths.py", line 36, in _find_home
    raise OSError('Could not find unix home directory to search for '
OSError: Could not find unix home directory to search for astropy config dir
```

**Comment by pllim** [comment]
Yes, @mustaric and I came across that as well. We managed to get around it by setting `HOME = /tmp` in the environment variables section.

**Comment by pllim** [comment]
Might be related #6620 and #5899 .
