### ISSUE TITLE
Error while parsing years earlier than 4799BC

### ISSUE THREAD

**Issue by eawer** [astropy/astropy#9231]
Hello! I'm trying to parse a bunch of different dates, and BC ones are among them. And what I've noticed, is that if the date is earlier than 4799BC, astropy refuses to parse it and throws this:
```bash
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    print(Time('-04800-01-02T03:04:05', format='fits').unix)
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.7/site-packages/astropy/time/core.py", line 399, in __init__
    precision, in_subfmt, out_subfmt)
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.7/site-packages/astropy/time/core.py", line 454, in _init_from_vals
    precision, in_subfmt, out_subfmt)
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.7/site-packages/astropy/time/core.py", line 505, in _get_time_fmt
    raise ValueError('Input values did not match {0}'.format(err_msg))
ValueError: Input values did not match the format class fits
```
Here is the code and corresponding [repl.it](https://repl.it/repls/OriginalOnerlookedJavadocs)
```python
from astropy.time import Time

print(Time('-04799-01-02T03:04:05', format='fits').unix)
print(Time('-04800-01-02T03:04:05', format='fits').unix)
```

**Comment by mhvk** [comment]
Hmm, the error here is rather misleading. If I instance more directly:
```
from astropy.time import TimeFITS
TimeFITS(np.array(['-04800-01-02T03:04:05']), None, 'utc', 9, '*', '*', False)
# ErfaError: ERFA function "dtf2d" yielded 1 of "bad year"
```
This comes from https://github.com/astropy/astropy/blob/master/cextern/erfa/cal2jd.c#L54 - essentially, I guess calendar dates are considered undefined before that time...

**Comment by eawer** [comment]
Hmm, so looks like I can't handle the dates, earlier than that, correct?

**Comment by mhvk** [comment]
As is, not as a FITS or ISO string. Things like `Time(-10000., format='jyear')` work fine. Out of curiosity, what do you need the early dates for?

p.s. Note that our ERFA routines are just copies of the [Standards Of Fundamental Astronomy](http://www.iausofa.org/)...

**Comment by eawer** [comment]
I'm importing [freebase](https://developers.google.com/freebase/), which contains a bunch of dates in different formats (lot's of them are BC). To standardize it I've decided to convert everything to UNIX time.

**Comment by pllim** [comment]
@mhvk , is this essentially a "won't fix"?

**Comment by mhvk** [comment]
@pllim - I doubt we'd fix it inside astropy, but I'm wondering why the limitation is there in SOFA/ERFA, as there doesn't seem to be an intrinsic reason to prevent one from going further backwards. I.e., should we pass this on as an "upstream fix required"?

@eawer - what are those earlier dates?  Are they actually precise enough that one should be able to convert? Or more like "middle of stone age"? (in which case using something like `byear` might be good enough). I don't actually know if there is anything reliably dated before the babylonians (where do know dates because of their solar/lunar eclipse observations).

**Comment by eawer** [comment]
Well, they are pretty precise - `-7051` - [Clinker Peak last eruption](https://www.google.com/search?q=Clinker+Peak+last+eruption&oq=Clinker+Peak+last+eruption&aqs=chrome..69i57.4309j0j4&sourceid=chrome&ie=UTF-8), `-6000` - [Gatecliff Rockshelter open date](https://www.google.com/search?ei=VfB_Xc3fO8SckgWE5YywBQ&q=Gatecliff+Rockshelter+open+date&oq=Gatecliff+Rockshelter+open+date&gs_l=psy-ab.3...6733.8372..8811...0.0..0.119.963.7j3......0....1..gws-wiz.......0i22i30j33i160.aO9dw-bY3fk&ved=0ahUKEwiN3u-Hl9bkAhVEjqQKHYQyA1YQ4dUDCAs&uact=5) etc. No idea though if those are correct ones, yet they are in freebase

**Comment by mhvk** [comment]
By precise, I meant that the actual day/month and likely time were known... Easiest may be for early ~year accurate times to use `byear` or so. Actually, one probably has to check what people actually mean; it may well be the unit of year, which by definition is 365.25 days (i.e., julian year).

My overall feeling is that is it best to special-case those early dates and make an approximation that is clearly described.

**Comment by dhomeier** [comment]
See also [this thread](https://mail.python.org/pipermail/astropy/2019-August/004553.html) - the underlying reason earlier dates are not supported is that the algorithm for converting from the Gregorian calendar to Julian date in [cal2jd.c](https://github.com/liberfa/erfa/blob/master/src/cal2jd.c#L27), which is in turn taken from the correponding SOFA routine, is not valid before 1 March 4801 BCE. So it's indeed well beyond Astropy, but as long as no (Gregorian) calendar representations are involved, the times should still be accurate enough.

**Comment by eawer** [comment]
Thanks, that makes sense

**Comment by mhvk** [comment]
I guess we now know what the problem is, but not yet what to do. Easiest probably is try to document this somewhere...

**Comment by dhomeier** [comment]
Yes, I'd say the issue reported on the mailing list was also due to a lack of documentation. It follows the standards, but it's probably too much to expect every user to have the formatting rules and ranges covered by the ISO 8601 and FITS standards present. For the format, it might already help to add a 5-digit+prefix example to the initialisation examples. For the range, I think ideally we should compile a list of the properties that do not depend on the `cal2jd` transformation and thus are still available for a wider range of dates as constructed from `Time(-10000., format='jyear')`, and those that do, and thus only support the timespan `-04799-01-01T00:00:00` to `+99999-12-31T23:59:59`. And the error message could of course be more instructive than `'Input values did not match {0}'.format(err_msg)`.
On the topic of supporting 4- and 5-digit year strings, I was also wondering if it would not reduce confusion to accept the expanded date format `[ ±C]CCYY-MM-DD` in the `iso` formats as well. The standard only requires the 4-digit year, but expressly allows to define expanded formats by _"mutual agreement between the partners in information exchange"_, as the FITS standard has done.

**Comment by mhvk** [comment]
@dhomeier - I think it makes sense to accept the 5-digit years also in `iso[t]` - in fact, we already implicitly do this for output (just because the python formatter doesn't balk...):
```
Time('J50000').isot
# WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
# '50000-12-26T12:00:00.000'
```
Given that, we might as well accept it on input too. And, with that, as you say, it would be easier to add a note to the documentation about the supported range, since it is something that holds for all those similar formats.

The error message is a bit trickier to get right, since without an explicit `format`, the initializer simply tries all unique formats. But at least when one does give an explicit format, the message perhaps could be clearer. 

cc @taldcroft.

**Comment by taldcroft** [comment]
>  But at least when one does give an explicit format, the message perhaps could be clearer.

See #9296.

**Comment by taldcroft** [comment]
Agreed on making the input parsing for `iso[t]` more liberal to accept `[ ±C]CCYY-MM-DD`.  As noted if then try to get the string representation that will generate a warning, but it could be suppressed as needed.

**Comment by dhomeier** [comment]
> The error message is a bit trickier to get right, since without an explicit `format`, the initializer simply tries all unique formats. But at least when one does give an explicit format, the message perhaps could be clearer.

When trying all the formats, the `fits` case still has to fail in `formats.py`, probably with a
`astropy.utils.exceptions.ErfaError: ERFA function "d2dtf" yielded 1 of "unacceptable date (Note 6)"`
I could not figure out yet exactly where that exception is caught, but if it could instead be passed back up to `_get_time_fmt`, the caller might check for that specific error. Or at least let an ERFA warning pass though (although those are probably rather cryptic to the user, too).
