### ISSUE TITLE
masked Quantity fails on astropy master with numpy 1.17.2

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#9338]
Masked `Quantity` started failing with `astropy` master and `numpy 1.17.2`:

```python
>>> import numpy as np
>>> import astropy.units as u

>>> masked_quantity = np.ma.array([1, 2, 3 ,4] * u.kg,
...                               mask=[True, False, True, False])
>>> print(masked_quantity)
Traceback (most recent call last):
  File "/Users/lbradley/Dropbox/softw/packages/dev/astropy/astropy/units/quantity.py", line 1319, in _to_own_unit
    _value = value.to_value(self.unit)
AttributeError: '_MaskedPrintOption' object has no attribute 'to_value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./ma.py", line 8, in <module>
    print(masked_quantity)
  File "/Users/lbradley/local/conda/envs/dev/lib/python3.7/site-packages/numpy/ma/core.py", line 3870, in __str__
    return str(self._insert_masked_print())
  File "/Users/lbradley/local/conda/envs/dev/lib/python3.7/site-packages/numpy/ma/core.py", line 3864, in _insert_masked_print
    _recursive_printoption(res, mask, masked_print_option)
  File "/Users/lbradley/local/conda/envs/dev/lib/python3.7/site-packages/numpy/ma/core.py", line 2443, in _recursive_printoption
    np.copyto(result, printopt, where=mask)
  File "<__array_function__ internals>", line 6, in copyto
  File "/Users/lbradley/Dropbox/softw/packages/dev/astropy/astropy/units/quantity.py", line 1475, in __array_function__
    args, kwargs, unit, out = function_helper(*args, **kwargs)
  File "/Users/lbradley/Dropbox/softw/packages/dev/astropy/astropy/units/quantity_helper/function_helpers.py", line 270, in copyto
    return ((dst.view(np.ndarray), dst._to_own_unit(src)) + args,
  File "/Users/lbradley/Dropbox/softw/packages/dev/astropy/astropy/units/quantity.py", line 1324, in _to_own_unit
    as_quantity = Quantity(value)
  File "/Users/lbradley/Dropbox/softw/packages/dev/astropy/astropy/units/quantity.py", line 374, in __new__
    raise TypeError("The value must be a valid Python or "
TypeError: The value must be a valid Python or Numpy numeric type.
```

It works fine with `astropy` master and `numpy <= 1.17.1`.  It also works fine with `astropy 3.2.1` and `numpy = 1.17.2`:

```python
>>> import numpy as np
>>> import astropy.units as u

>>> masked_quantity = np.ma.array([1, 2, 3 ,4] * u.kg,
...                               mask=[True, False, True, False])
>>> print(masked_quantity)
[-- 2.0 -- 4.0] kg
```

Ping: @mhvk

**Comment by bsipocz** [comment]
I see the same issue on numpy-dev 
```
In [6]: numpy.__version__                                                                                               
Out[6]: '1.18.0.dev0+d0b0c60'
```

**Comment by mhvk** [comment]
Note that masked quantities never really worked, but no need to break this - fix in #9342

**Comment by larrybradley** [comment]
Thanks, @mhvk.  Is there any documentation describing their limitations?

**Comment by mhvk** [comment]
well, for one units do not propagate correctly... It is a long-standing wish list to have it work, but almost certainly we need to make our own masked type...
```
In [2]: q = np.ma.MaskedArray([1., 2., 3.]*u.m, mask=[True, False, True])

In [3]: q
Out[3]: 
masked_Quantity(data=[<Quantity -- m>, <Quantity 2. m>, <Quantity -- m>],
                mask=[ True, False,  True],
          fill_value=1e+20)

In [4]: q * q
Out[4]: 
masked_Quantity(data=[<Quantity -- m>, <Quantity 4. m>, <Quantity -- m>],
                mask=[ True, False,  True],
          fill_value=1e+20)
```

**Comment by bsipocz** [comment]
There was some plans upstream to revamp masked arrays, wasn't there?

**Comment by mhvk** [comment]
Yes, there is, and that would certainly help (but might take a while...)
