### ISSUE TITLE
IERS table failure on Windows

### ISSUE THREAD

**Issue by Erikmeier18** [astropy/astropy#9431]
### Description

We are trying to convert ra and dec to AltAz, and we get an error. 
### Expected behavior

To follow the docs.
### Actual behavior

```python
>>> from astropy import units as u
>>> from astropy.coordinates import SkyCoord
>>> c = SkyCoord(ra=10.68458*u.degree, dec=41.26917*u.degree)
>>> from astropy.coordinates import EarthLocation, AltAz
>>> location = EarthLocation(lat=30*u.degree, lon = -115*u.degree)
>>> from astropy.time import Time
>>> time = Time.now()
>>> time
<Time object: scale='utc' format='datetime' value=2019-10-22 09:33:00.972504>
>>> c
<SkyCoord (ICRS): (ra, dec) in deg
    (10.68458, 41.26917)>
>>> Aa = AltAz(location = location, obstime = time)
>>> c.transform_to(Aa)
Traceback (most recent call last):
  File "<pyshell#20>", line 1, in <module>
    c.transform_to(Aa)
  File "C:\Users\erikm\AppData\Local\Programs\Python\Python37\lib\site-packages\astropy\coordinates\sky_coordinate.py", line 443, in transform_to
    new_coord = trans(self.frame, generic_frame)
  File "C:\Users\erikm\AppData\Local\Programs\Python\Python37\lib\site-packages\astropy\coordinates\transformations.py", line 1377, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "C:\Users\erikm\AppData\Local\Programs\Python\Python37\lib\site-packages\astropy\coordinates\transformations.py", line 980, in __call__
    return supcall(fromcoord, toframe)
  File "C:\Users\erikm\AppData\Local\Programs\Python\Python37\lib\site-packages\astropy\coordinates\builtin_frames\cirs_observed_transforms.py", line 51, in cirs_to_altaz
    xp, yp = get_polar_motion(obstime)
  File "C:\Users\erikm\AppData\Local\Programs\Python\Python37\lib\site-packages\astropy\coordinates\builtin_frames\utils.py", line 41, in get_polar_motion
    xp, yp, status = iers.IERS_Auto.open().pm_xy(time, return_status=True)
  File "C:\Users\erikm\AppData\Local\Programs\Python\Python37\lib\site-packages\astropy\utils\iers\iers.py", line 660, in open
    cls.iers_table = cls.read(file=filename)
  File "C:\Users\erikm\AppData\Local\Programs\Python\Python37\lib\site-packages\astropy\utils\iers\iers.py", line 507, in read
    table = cls._combine_a_b_columns(iers_a)
  File "C:\Users\erikm\AppData\Local\Programs\Python\Python37\lib\site-packages\astropy\utils\iers\iers.py", line 469, in _combine_a_b_columns
    is_predictive = (table['UT1Flag_A'] == 'P') | (table['PolPMFlag_A'] == 'P')
  File "C:\Users\erikm\AppData\Local\Programs\Python\Python37\lib\site-packages\astropy\table\column.py", line 986, in _compare
    return result.data if isinstance(result, Column) else result
  File "C:\Users\erikm\AppData\Local\Programs\Python\Python37\lib\site-packages\astropy\table\column.py", line 1278, in data
    out.fill_value = self.fill_value
  File "C:\Users\erikm\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\ma\core.py", line 3647, in set_fill_value
    target = _check_fill_value(value, self.dtype)
  File "C:\Users\erikm\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\ma\core.py", line 472, in _check_fill_value
    raise TypeError(err_msg % ndtype)
TypeError: Cannot set fill value of string with array of dtype bool 
``` 

### System Details
```python
>>> import platform; print(platform.platform())
Windows-10-10.0.18362-SP0
>>> import sys; print("Python", sys.version)
Python 3.7.1rc1 (v3.7.1rc1:2064bcf6ce, Sep 26 2018, 15:15:36) [MSC v.1914 64 bit (AMD64)]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.15.2
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.1.0
>>> import astropy; print("astropy", astropy.__version__)
astropy 3.2.2 
```

**Comment by bmorris3** [comment]
Hi all! I'm working with @Erikmeier18 and can confirm that this error happens on his windows machine but not on my Mac. We're not sure if this is an IERS table error, a numpy error, or something else entirely.

**Comment by pllim** [comment]
Did you try the dev version? I got no problem on Windows 10. But it also downloaded the something from the Internet, so also make sure your download wasn't corrupted (which is a OS-independent problem).

```python
In [4]: c.transform_to(Aa)
Downloading https://maia.usno.navy.mil/ser7/finals2000A.all
|===========================================| 3.2M/3.2M (100.00%)         2s
Out[4]:
<SkyCoord (AltAz: obstime=2019-10-22 16:31:59.603477, location=(-2336342.2113544
2, -5010302.04092816, 3170373.73538364) m, pressure=0.0 hPa, temperature=0.0 deg
_C, relative_humidity=0.0, obswl=1.0 micron): (az, alt) in deg
    (339.30639502, -14.34378228)>
```

**Comment by bmorris3** [comment]
@Erikmeier18 and I just ran `astropy.utils.data.clear_download_cache`, and now the coordinate transformation works as expected! Thanks @adrn for the tip, it looks like a corrupted IERS table may have been the culprit 👍
