### ISSUE TITLE
Post-leap-second update to do

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#9479]
#9365 introduced the ability to update ERFA leap seconds. A few updates would still be nice
- [ ] Document how it can be used to simulate having missing leap seconds (@eteq).
- [ ] Make the various URLs lists that include mirrors (easier with #9182 merged).
- [ ] Hard-code system files for more operating systems.

**Comment by weaverba137** [comment]
How can I inhibit downloading the leap second file similar to how the [download of the IERS file can be inhibited](http://docs.astropy.org/en/stable/utils/iers.html#working-offline)?

**Comment by mhvk** [comment]
@weaverba137 - `iers.conf.auto_download = False` will also stop downloading leap-second files: https://github.com/astropy/astropy/blob/8267d16fac2b4743c35636880e729088e35699a4/astropy/utils/iers/iers.py#L993-L994

Looking at the linked documentation, it clearly needs to discuss this is more detail. For now, I've just added an action item to the list...

**Comment by weaverba137** [comment]
That's useful to know, but I've already seen cases where the download appears to be happening at import time, rather than when I explicitly use the LeapSeconds class.  I still need to track down exactly what is happening, but maybe you know of how that might happen?

**Comment by weaverba137** [comment]
Hmm, for example, would doing `from astropy.time import Time` cause LeapSeconds to be instantiated, in which case there's a sort of race condition where that import has to happen *after* `conf.auto_download` is set?

**Comment by weaverba137** [comment]
Yes, in fact, it's in `astropy.time.core.Time.__new__()`.

**Comment by mhvk** [comment]
Yes, it is the very first time a `Time` is initialized; I tried hard to avoid this but couldn't work out a secure way (there were rather horrible circular dependencies). 

The hope, though, was that if the very first thing one does is
```
from astropy.utils import iers
iers.conf.auto_download = False
```
it should work. But am not sure if this is actually the case (if not, do let me/us know).

What should work is to set it inside `.astropy/config` (but I never tried that myself, I fear...)

**Comment by mhvk** [comment]
p.s. Of course, the good solution is to have an up-to-date system file - which is possible for all linux/MacOS, but needs some auto-configuration.

**Comment by weaverba137** [comment]
Thanx, I'll run some tests soon.

**Comment by weaverba137** [comment]
In my tests, I am *definitely* setting `auto_download = False` *before* instantiating `astropy.time.Time`, but *after* `astropy.time.Time` is imported.  That suggests that the *configuration* is already loaded into `astropy.time.Time` before instantiation.  I thought the configuration was a singleton, but maybe it's not?

**Comment by pllim** [comment]
If `Time` is imported when `astropy` itself is imported and this problem happens there, then setting `~/.astropy/config/astropy.cfg` is your best bet.

**Comment by weaverba137** [comment]
Well, I can try that, but that's not the use case I'm aiming at.  I need this to be disabled in code, because that code will run on thousands of nodes, which can't be sending out thousands of download requests, and we won't necessarily be able to manipulate this file.

**Comment by mhvk** [comment]
@weaverba137 - quick fix: is there any hope of just ensuring the nodes have an up-to-date leap-second file? (either in astropy itself or in their system - though then you need to set that config item...) After all, the download requests only happen in the regular file is out of date, and ignoring out-of-date leap seconds is a recipe for hard-to-debug errors (it may not be relevant for your present purpose, but might be for a future one).

More directly relevant: thinking more about order, `iers` itself imports `Time` as well, which in turn imports `time.formats` which initializes quite a few epoch times, so I fear indeed the only way to circumvent that right now is setting the config outside of astropy... As I mentioned, when I wrote the leap-second code, I tried to avoid it, but couldn't; obviously, there is a balance to be made between allowing downloads to be turned off for the power user who knows they do not need correct times, and ensuring results are correct for the more typical user who doesn't generally think about leap seconds.

**Comment by weaverba137** [comment]
We don't have control over the nodes like that, we have to treat them as blank slates.

**Comment by weaverba137** [comment]
How do I find the system leap second file?  How does astropy for that matter?

https://github.com/astropy/astropy/blob/master/astropy/utils/iers/iers.py#L126 is blank, so how is it filled in?

**Comment by weaverba137** [comment]
In https://github.com/astropy/astropy/blob/master/astropy/utils/iers/iers.py#L975, how does that deal with `conf.auto_max_age = None`?

**Comment by pllim** [comment]
Re: system file -- from the docstring

https://github.com/astropy/astropy/blob/8267d16fac2b4743c35636880e729088e35699a4/astropy/utils/iers/iers.py#L871-L877

I think it is something you set yourself on your config if you have it.

**Comment by pllim** [comment]
Maybe looking at the tests might also help understanding how leap seconds are being handled in `astropy` -- https://github.com/astropy/astropy/blob/master/astropy/utils/iers/tests/test_leap_second.py

**Comment by weaverba137** [comment]
@pllim , OK, but the documentation doesn't say that you have to explicitly tell it to look for the system file.  The implication, as I read it, is that astropy auto-detects the system file.

**Comment by pllim** [comment]
I am not 100% sure either, hoping @mhvk can clarify.

**Comment by weaverba137** [comment]
Well, I think the solution I need is to force astropy to use its own built-in leap second file, or provide my own "system" leap second file in a separate package.  The remaining details are:

1. compatibility with `auto_max_age = None`
2. When precisely to set `auto_download = False`, or equivalently, proving beyond doubt that *importing* `astropy.utils.iers` in order to set `auto_download = False` does not in and of itself trigger a download of the leap seconds file.

**Comment by mhvk** [comment]
@weaverba137 - `auto_max_age` is not used, since leap second files themselves describe when they expire (unlike IERS_A, where in principle one can update every day, but in practice the gain is minimal). The system file location is not set since I only know where it lives on Debian/Ubuntu and was hoping for something more generic (see top of issue).

I fear your experiments already show that one cannot set `utils.iers.conf.auto_download` inside astropy (it comes to late, as `iers` imports `Time`, which initializes some), but sadly is forced to do so in the config file. Not ideal... But the problem is solved by either keeping the astropy file up to date, or letting `system_leap_second_file` point to something up to date (again, using the config file, I fear).

All this does show that it would be nice to actually do something with the action points this issue is about, if only to document the behaviour better. If you have any specific suggestions or possible solutions, now is the time - we're rapidly approaching the 4.1 feature freeze... (am not sure I'll have much time myself, sadly)

**Comment by weaverba137** [comment]
@mhvk , are you saying that `LeapSeconds.auto_open()`, never gets called?  Because if I set `auto_max_age = None`, and call it, I get an exception:
```python
import astropy.utils.iers as i
i.conf.auto_max_age = None
foo = i.LeapSeconds.auto_open()
WARNING: leap-second auto-update failed due to the following exception: TypeError("unsupported operand type(s) for -: 'int' and 'NoneType'",) [astropy.time.core]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/weaver/Documents/local/products/venv/astropy4/lib/python3.6/site-packages/astropy/utils/iers/iers.py", line 974, in auto_open
    good_enough = cls._today() + TimeDelta(180-conf.auto_max_age,
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

**Comment by mhvk** [comment]
Oops...  Clearly I should not go from memory but rather look at the actual code. It is used, though if you set it very large, it looks like you'd still get a warning.

Aside: just realized another way to avoid downloads, viz., pre-seed the cache with an up-to-date version. I could imagine this might be a more useful approach, as perhaps one wants to have other shared resources as well. Some documentation at the end of http://docs.astropy.org/en/latest/utils/data.html#cache-management

**Comment by weaverba137** [comment]
That also sounds promising.  I'll keep working on this & let you know.

**Comment by weaverba137** [comment]
Another data point (more related to my own use case than an actual bug): `from astropy.coordinates import EarthLocation` actually triggers a leap second file download if the code has not already been set up to avoid such a download.

**Comment by pllim** [comment]
Re: `EarthLocation` -- I think @adrn tried to address it but the work was never completed due to caching makeover in 4.0.

**Comment by weaverba137** [comment]
I'm pretty sure the trace of what's happening at import time goes like this:
```python
from astropy.coordinates import Earth Location  # This explicit import triggers all of the imports below, in order.
from astropy.coordinates.earth import * # in astropy/coordinates/__init__.py
from astropy.coordinates.builtin_frames import * # also in astropy/coordinates/__init__.py
from .fk5 import FK5 # in astropy/coordinates/builtin_frames/__init__.py
from astropy.coordinates import earth_orientation as earth # in astropy/coordinates/builtin_frames/fk5.py
from astropy.time import Time # in astropy/coordinates/earth_orientation.py
jd1950 = Time('B1950').jd # in astropy/coordinates/earth_orientation.py.
```
The last line almost certainly triggers the download, unless there's an earlier, module-level call to `Time()` in that chain of imports.

So in principle, *any* import from `astropy.coordinates` will trigger a download, because it will have to pass through `astropy/coordinates/__init__.py`.  I'll leave that for someone else to decide what to do with, but for my own use, it's important to know when to intercept that download.

**Comment by mhvk** [comment]
@weaverba137 - yes, `Time` is used almost everywhere and your traceback makes clear why...  I now recall that the main trouble I had was to avoid `Table` loading it too, since that would prevent the leap second `Table` from being created.

**Comment by pllim** [comment]
Would #10125 fix your problem, @weaverba137 ?

**Comment by weaverba137** [comment]
That PR is a good start but:

* Is that the *only* module-level call to `Time()` in `astropy.coordinates`?  In `astropy` as a whole?
* We still might call `Time()` in other contexts, so we still need to actively suppress downloads using other methods.

In other words, #10125  fixes an *unexpected* call to `Time()` but it doesn't fix *every* call to `Time()`.

**Comment by weaverba137** [comment]
#10126 fixes the specific problem with `auto_max_age = None`.

**Comment by mhvk** [comment]
I think one really useful thing would be to have a test that checks that importing all the modules of astropy does not cause any downloads...

**Comment by pllim** [comment]
I am surprised that our CI hasn't complained about it given that most of our jobs do not have remote data set. I'll investigate when I get the chance.

**Comment by mhvk** [comment]
@pllim - I was wondering too, but if the file included in astropy is up to date, it will not attempt to download anything. And the file we currently have expires Dec 2020 (I seem to have updated that as part of #9908).

**Comment by mhvk** [comment]
belatedly, on:

> We don't have control over the nodes like that, we have to treat them as blank slates.

But doesn't that mean you *can* install an up-to-date astropy, or set up an astropy cache that includes an up-to-date leap-second file?

**Comment by weaverba137** [comment]
@mhvk, no not really.

We need long-term version stability (for reproducibility among other things) so we change versions extremely infrequently.  We are only just now *starting* to prepare for transitioning to Astropy 4.  We can't just install the latest version of anything each time we run.

If we made significant structural changes to our pipeline, we could in principle prepare a node in advance with configuration files.  However, the effort involved would be much greater than simply making configuration changes in code at runtime.

**Comment by mhvk** [comment]
@weaverba137 - fair enough, and best would be to make it easy to support. Of course, if you use an old version, and you need times and coordinates that are correct for the present, you will have to update IERS and leap seconds regardless, so possibly we should mostly be focussing on how to do that most easily. I can definitely see, though, that adjusting the configuration inside the python code that does all the work is easier than changing configuration files, so allowing to import the various `conf` without side effects is important regardless.

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy/issues/9479#issuecomment-611128169 on testing.

I cannot seem to get this test below to work properly when I run it with `pytest`. The behavior is different form when I run it line-by-line in IPython interpreter. 🤷‍♀ 

```python
from pytest_remotedata.disable_internet import no_internet

from astropy.tests.helper import catch_warnings


def test_import_no_remote():
    from astropy.time import Time
    from astropy.utils.iers.iers import LeapSeconds, IERS_LEAP_SECOND_FILE

    LeapSeconds._auto_open_files[0] = ''  # Ignore ERFA
    LeapSeconds._auto_open_files[1] = ''  # Ignore package data

    with catch_warnings() as warns:
        with no_internet():
            assert Time('J2000').jd > 0

    assert len(warns) == 1 and 'An attempt was made to connect to the internet' in str(warns[0].message)

    LeapSeconds._auto_open_files[0] = 'erfa'
    LeapSeconds._auto_open_files[1] = IERS_LEAP_SECOND_FILE
```

Also see https://github.com/astropy/pytest-remotedata/issues/17#issuecomment-611201213

**Comment by pllim** [comment]
@mhvk is this issue still relevant?

**Comment by mhvk** [comment]
None of the pieces have really been addressed, so in that sense, yes, still relevant. On the other hand, no one seems to have minded enough to address them, so maybe it is fine to just close it... I think the discussion here has certainly been separate enough not to be of much help, so let me just close...
