### ISSUE TITLE
Environment error when pip installing astropy from git repository on Windows

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#9658]
Happens for conda and "normal" CPython installations with Python 3.7:

```
pip                 19.3.1
setuptools          41.6.0
wheel               0.33.6
```

```
python -m pip install . -vv
Created temporary directory: ...\Temp\pip-ephem-wheel-cache-idteu68j
Created temporary directory: ...\Temp\pip-req-tracker-e9_xdn9u
Created requirements tracker '...\\Temp\\pip-req-tracker-e9_xdn9u'
Created temporary directory: ...\Temp\pip-install-tl7132cx
Processing d:\gitrepos\astropy\astropy
  Created temporary directory: ...\Temp\pip-req-build-8dww0lt5
ERROR: Could not install packages due to an EnvironmentError.
Traceback (most recent call last):
  File "...\lib\site-packages\pip\_internal\commands\install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "...\lib\site-packages\pip\_internal\legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "...\lib\site-packages\pip\_internal\legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "...\lib\site-packages\pip\_internal\legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "...\lib\site-packages\pip\_internal\operations\prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "...\lib\site-packages\pip\_internal\download.py", line 452, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "...\lib\site-packages\pip\_internal\download.py", line 387, in unpack_file_url
    _copy_source_tree(link_path, location)
  File "...\lib\site-packages\pip\_internal\download.py", line 367, in _copy_source_tree
    shutil.copytree(source, target, **kwargs)
  File "...\lib\shutil.py", line 368, in copytree
    raise Error(errors)
shutil.Error: [('...\\astropy\\CITATION', '...\\Temp\\pip-req-build-8dww0lt5\\CITATION', 'symbolic link privilege not held')]
Cleaning up...
Removed build tracker '...\\Temp\\pip-req-tracker-e9_xdn9u'
```

But it works using Python 3.8 (conda and normal Python installation).

**Comment by MSeifert04** [comment]
I think this is probably because the CITATIONS file is a symlink.

**Comment by pllim** [comment]
Argh, the symlink attacks again!

**Comment by pllim** [comment]
How about we not use symlink then?

1. Choose one of the location as the canonical one. Update the other one to say "see this other file".
2. Make a full copy and have it at two places.

**Comment by MSeifert04** [comment]
> How about we not use symlink then?

Sounds good, either approach would be fine with me.

btw: This works on Python 3.8, it fails on 3.7 - after re-reading the original post it was probably ambiguous and I'll clarify it.

**Comment by bsipocz** [comment]
> How about we not use symlink then?

I wouldn't be against option1, assuming we keep the one in the package, as we need it for `__cite__`, etc., and replacing the symlink with the one sentence. However that top level file is the generarily suggested location in github land).

Option2 makes me worries they get out of sync, as well as it's super ugly to duplicate stuff like that.
