### ISSUE TITLE
Basic FITS BinTableHDU appending

### ISSUE THREAD

**Issue by roeiboot4** [astropy/astropy#9740]
### Description

Appending a simple hdu to an existing file is not possible due to some unneeded typechecking
### Expected behavior

when using fits.append() on an hdu. I expect the hdu to be appended to the hdu list
### Actual behavior

in fits.append(), the hdu is broken down and rebuilt, and then typechecking somehow fails to recognize the arrays as ndarrays.

### Steps to Reproduce

```
from astropy.io import fits
import numpy as np
import glob

files = glob.glob('/Users/matthiasf/Data/Spectra/9_Sgr/HARPS/*.fits')

lamb = [1, 2, 3]
flux = [4, 5, 6]
lambcol = fits.Column(name='lambda', array=np.array(lamb), format='E')
fluxcol = fits.Column(name='flux', array=np.array(flux), format='E')
newhdu = fits.BinTableHDU.from_columns([lambcol, fluxcol])
fits.append(files[0], newhdu)
```
output:
```
Darwin-19.0.0-x86_64-i386-64bit
Python 3.7.5 (default, Oct 25 2019, 10:52:18) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.17.4
Scipy 1.3.1
astropy 3.2.3
Traceback (most recent call last):
  File "/Users/matthiasf/Scripts/fitsappend.py", line 21, in <module>
    fits.append(files[0], newhdu)
  File "/Users/matthiasf/anaconda3/lib/python3.7/site-packages/astropy/io/fits/convenience.py", line 627, in append
    hdu = _makehdu(data, header)
  File "/Users/matthiasf/anaconda3/lib/python3.7/site-packages/astropy/io/fits/convenience.py", line 1051, in _makehdu
    raise KeyError('Data must be a numpy array.')
KeyError: 'Data must be a numpy array.'

Process finished with exit code 1
```

**Comment by saimn** [comment]
[`fits.append`](http://docs.astropy.org/en/latest/io/fits/api/files.html#astropy.io.fits.append) is not supposed to be used with an HDU object as argument. Correct use is with data and header:
```
fits.append('tmp.fits', newhdu.data, header=newhdu.header)
```
Or another option is to use `HDUList.append`:
```
>>> with fits.open('tmp.fits', mode='append') as hdul: 
...    hdul.append(newhdu) 
```

**Comment by roeiboot4** [comment]
Thank you, ```HDUlist.append()``` works as intended.
