### ISSUE TITLE
fitsdiff fails on FITS-IDI files

### ISSUE THREAD

**Issue by voitsik** [astropy/astropy#9790]
After applying a patch from #9711, I can successfully read [FITS-IDI](https://fits.gsfc.nasa.gov/registry/fitsidi.html) files. But `fitsdiff` fails on such files with the following error:

```
Traceback (most recent call last):
  File "/home/voitsik/opt/bin/fitsdiff", line 8, in <module>
    sys.exit(main())
  File "/home/voitsik/opt/lib64/python3.6/site-packages/astropy/io/fits/scripts/fitsdiff.py", line 322, in main
    ignore_blank_cards=opts.ignore_blank_cards)
  File "/home/voitsik/opt/lib64/python3.6/site-packages/astropy/io/fits/diff.py", line 315, in __init__
    super().__init__(a, b)
  File "/home/voitsik/opt/lib64/python3.6/site-packages/astropy/io/fits/diff.py", line 71, in __init__
    self._diff()
  File "/home/voitsik/opt/lib64/python3.6/site-packages/astropy/io/fits/diff.py", line 355, in _diff
    hdu_diff = HDUDiff.fromdiff(self, self.a[idx], self.b[idx])
  File "/home/voitsik/opt/lib64/python3.6/site-packages/astropy/io/fits/diff.py", line 106, in fromdiff
    return cls(a, b, **kwargs)
  File "/home/voitsik/opt/lib64/python3.6/site-packages/astropy/io/fits/diff.py", line 530, in __init__
    super().__init__(a, b)
  File "/home/voitsik/opt/lib64/python3.6/site-packages/astropy/io/fits/diff.py", line 71, in __init__
    self._diff()
  File "/home/voitsik/opt/lib64/python3.6/site-packages/astropy/io/fits/diff.py", line 549, in _diff
    if self.a.data is None or self.b.data is None:
  File "/home/voitsik/opt/lib64/python3.6/site-packages/astropy/utils/decorators.py", line 744, in __get__
    val = self.fget(obj)
  File "/home/voitsik/opt/lib64/python3.6/site-packages/astropy/io/fits/hdu/groups.py", line 293, in data
    data = self._get_tbdata()
  File "/home/voitsik/opt/lib64/python3.6/site-packages/astropy/io/fits/hdu/table.py", line 181, in _get_tbdata
    self._init_tbdata(data)
  File "/home/voitsik/opt/lib64/python3.6/site-packages/astropy/io/fits/hdu/table.py", line 197, in _init_tbdata
    tbsize = self._header['NAXIS1'] * self._header['NAXIS2']
  File "/home/voitsik/opt/lib64/python3.6/site-packages/astropy/io/fits/header.py", line 148, in __getitem__
    card = self._cards[self._cardindex(key)]
  File "/home/voitsik/opt/lib64/python3.6/site-packages/astropy/io/fits/header.py", line 1708, in _cardindex
    raise KeyError(f"Keyword {keyword!r} not found.")
KeyError: "Keyword 'NAXIS2' not found."
```

I use the following patch to fix this error:
```patch
--- io/fits/hdu/table.py.orig   2019-12-17 14:56:13.852876901 +0300
+++ io/fits/hdu/table.py        2019-12-17 15:29:15.343474000 +0300
@@ -194,7 +194,10 @@
         # pass datLoc, for P format
         data._heapoffset = self._theap
         data._heapsize = self._header['PCOUNT']
-        tbsize = self._header['NAXIS1'] * self._header['NAXIS2']
+        try:
+            tbsize = self._header['NAXIS1'] * self._header['NAXIS2']
+        except KeyError:
+            tbsize = 0
         data._gap = self._theap - tbsize
 
         # pass the attributes
```
But I'm not sure if this is an optimal solution.

### System Details
Linux-4.19.86-gentoo-x86_64-Intel-R-_Xeon-R-_CPU_E5-1650_0_@_3.20GHz-with-gentoo-2.6
Python 3.6.9 (default, Dec  2 2019, 12:56:17) 
[GCC 9.2.0]
Numpy 1.17.4
Scipy 1.1.0
astropy 4.0

**Comment by pllim** [comment]
cc @saimn and @MSeifert04

**Comment by saimn** [comment]
Could you share an example file ? I tried to get again the one from the other ticket, but it seems that it is no more there.

**Comment by voitsik** [comment]
You can use sample file from `fits.gsfc.nasa.gov`: [https://fits.gsfc.nasa.gov/registry/fitsidi/BL146_1.fits](https://fits.gsfc.nasa.gov/registry/fitsidi/BL146_1.fits)
