### ISSUE TITLE
RuntimeError: dictionary changed size during iteration @  plt.subplot(projection=WCS(hdu.header))

### ISSUE THREAD

**Issue by cxwx** [astropy/astropy#9825]
### Description

Traceback (most recent call last):
  File "<input>", line 1, in <module>
    plt.subplot(projection=wcs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 1069, in subplot
    a = fig.add_subplot(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/figure.py", line 1396, in add_subplot
    self._process_projection_requirements(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/figure.py", line 1122, in _process_projection_requirements
    projection_class, extra_kwargs = projection._as_mpl_axes()
  File "/usr/local/lib/python3.7/site-packages/astropy/wcs/wcsapi/low_level_api.py", line 331, in _as_mpl_axes
    from astropy.visualization.wcsaxes import WCSAxes
  File "/usr/local/Cellar/root/6.18.04_1/lib/root/ROOT.py", line 533, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/local/lib/python3.7/site-packages/astropy/visualization/wcsaxes/__init__.py", line 7, in <module>
    import pytest
  File "/usr/local/Cellar/root/6.18.04_1/lib/root/ROOT.py", line 533, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/local/lib/python3.7/site-packages/pytest.py", line 6, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/usr/local/Cellar/root/6.18.04_1/lib/root/ROOT.py", line 533, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/local/lib/python3.7/site-packages/_pytest/assertion/__init__.py", line 7, in <module>
    from _pytest.assertion import rewrite
  File "/usr/local/Cellar/root/6.18.04_1/lib/root/ROOT.py", line 533, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/local/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 26, in <module>
    from _pytest.assertion import util
  File "/usr/local/Cellar/root/6.18.04_1/lib/root/ROOT.py", line 533, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/local/lib/python3.7/site-packages/_pytest/assertion/util.py", line 8, in <module>
    import _pytest._code
  File "/usr/local/Cellar/root/6.18.04_1/lib/root/ROOT.py", line 533, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/local/lib/python3.7/site-packages/_pytest/_code/__init__.py", line 2, in <module>
    from .code import Code  # noqa
  File "/usr/local/Cellar/root/6.18.04_1/lib/root/ROOT.py", line 533, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/local/lib/python3.7/site-packages/_pytest/_code/code.py", line 24, in <module>
    import py
  File "/usr/local/Cellar/root/6.18.04_1/lib/root/ROOT.py", line 533, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/local/lib/python3.7/site-packages/py/__init__.py", line 153, in <module>
    'Syslog'             : '._log.log:Syslog',
  File "/usr/local/lib/python3.7/site-packages/py/_vendored_packages/apipkg.py", line 63, in initpkg
    for module in sys.modules.values():
RuntimeError: dictionary changed size during iteration
>>> plt.imshow(hdu.data, vmin=-2.e-5, vmax=2.e-4, origin='lower')
<matplotlib.image.AxesImage object at 0x14a1ef410>
>>> plt.grid(color='white', ls='solid')
>>> plt.grid(color='white', ls='solid')
┌──────────────────────────────────────────────────────────────────────────────────────────┐
│ Annotation                     Arrow                                                     │
│ Artist                         AutoLocator                                               │
│ Axes                           Button                                                    │
#<---History contiguity broken by rewind--->
  File "<input>", line 1, in <module>
    wcs = WCS(hdu.header)
NameError: name 'WCS' is not defined
>>> from astropy.wcs import WCS
>>> wcs = WCS(hdu.header)
>>> plt.subplot(projection=wcs)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    plt.subplot(projection=wcs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 1069, in subplot
    a = fig.add_subplot(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/figure.py", line 1396, in add_subplot
    self._process_projection_requirements(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/figure.py", line 1122, in _process_projection_requirements
    projection_class, extra_kwargs = projection._as_mpl_axes()
  File "/usr/local/lib/python3.7/site-packages/astropy/wcs/wcsapi/low_level_api.py", line 331, in _as_mpl_axes
    from astropy.visualization.wcsaxes import WCSAxes
  File "/usr/local/Cellar/root/6.18.04_1/lib/root/ROOT.py", line 533, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/local/lib/python3.7/site-packages/astropy/visualization/wcsaxes/__init__.py", line 7, in <module>
    import pytest
  File "/usr/local/Cellar/root/6.18.04_1/lib/root/ROOT.py", line 533, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/local/lib/python3.7/site-packages/pytest.py", line 6, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/usr/local/Cellar/root/6.18.04_1/lib/root/ROOT.py", line 533, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/local/lib/python3.7/site-packages/_pytest/assertion/__init__.py", line 7, in <module>
    from _pytest.assertion import rewrite
  File "/usr/local/Cellar/root/6.18.04_1/lib/root/ROOT.py", line 533, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/local/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 26, in <module>
    from _pytest.assertion import util
  File "/usr/local/Cellar/root/6.18.04_1/lib/root/ROOT.py", line 533, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/local/lib/python3.7/site-packages/_pytest/assertion/util.py", line 8, in <module>
    import _pytest._code
  File "/usr/local/Cellar/root/6.18.04_1/lib/root/ROOT.py", line 533, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/local/lib/python3.7/site-packages/_pytest/_code/__init__.py", line 2, in <module>
    from .code import Code  # noqa
  File "/usr/local/Cellar/root/6.18.04_1/lib/root/ROOT.py", line 533, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/local/lib/python3.7/site-packages/_pytest/_code/code.py", line 24, in <module>
    import py
  File "/usr/local/Cellar/root/6.18.04_1/lib/root/ROOT.py", line 533, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/local/lib/python3.7/site-packages/py/__init__.py", line 153, in <module>
    'Syslog'             : '._log.log:Syslog',
  File "/usr/local/lib/python3.7/site-packages/py/_vendored_packages/apipkg.py", line 63, in initpkg
    for module in sys.modules.values():
RuntimeError: dictionary changed size during iteration
### Expected behavior

```
>>> from astropy.wcs import WCS
>>> wcs = WCS(hdu.header)
>>> plt.subplot(projection=wcs)
```
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

```python
# Put your Python code snippet here.
```

**Comment by pllim** [comment]
Hi, @cxwx . Can you please provide the relevant parts of the FITS header that you used to produce the WCS?

If you can rerun your use case using dev version of `astropy`, even better. Thanks!

**Comment by saimn** [comment]
What is the `/usr/local/Cellar/root/6.18.04_1/lib/root/ROOT.py` that appears in your traceback ?
