### ISSUE TITLE
ISO time for midnight 24:00:00 not supported

### ISSUE THREAD

**Issue by richardgmcmahon** [astropy/astropy#9837]
### Description

I have been using astroplan to plan some observing and specified mightnight as 24:00:00. This is defined/allowed by the ISO standard 8601: https://en.wikipedia.org/wiki/ISO_8601

"Midnight is a special case and may be referred to as either "00:00" or "24:00". The notation "00:00" is used at the beginning of a calendar day and is the more frequently used. At the end of a day use "24:00". "2007-04-05T24:00" is the same instant as "2007-04-06T00:00" (see Combined date and time representations below)."

This issue appears to be a feature of python datetime, so documentation is probably the solution.

See: https://github.com/psycopg/psycopg2/issues/278 which reports:

"PostgreSQL can store time (with or without TZ) values from 0:00:00 to 24:00:00 while Python datetime.time only accepts values up to 23:59:59"

Digging into: astrpy core.py

   def strptime(cls, time_string, format_string, **kwargs):
        """
        Parse a string to a Time according to a format specification.
        See `time.strptime` documentation for format specification.

        >>> Time.strptime('2012-Jun-30 23:59:60', '%Y-%b-%d %H:%M:%S')
        <Time object: scale='utc' format='isot' value=2012-06-30T23:59:60.000>

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

```python
# Put your Python code snippet here.
```
24 problem example
>>> Time.strptime('2012-Jun-30 24:00:00', '%Y-%b-%d %H:%M:%S')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rgm/anaconda2/envs/py37/lib/python3.7/site-packages/astropy/time/core.py", line 570, in strptime
    tt, fraction = _strptime._strptime(to_string(time), format_string)
  File "/Users/rgm/anaconda2/envs/py37/lib/python3.7/site-packages/astropy/extern/_strptime.py", line 351, in _strptime
    (data_string, format))
ValueError: time data '2012-Jun-30 24:00:00' does not match format '%Y-%b-%d %H:%M:%S'

Example in core.py at line: 537
>>> Time.strptime('2012-Jun-30 23:59:60', '%Y-%b-%d %H:%M:%S')
<Time object: scale='utc' format='isot' value=2012-06-30T23:59:60.000>

### System Details

I am using python 3.7 and astropy 3.2.3

**Comment by taldcroft** [comment]
The problem here is two fold:
- The Python strptime implementation does not support 24 for the hour `%H` field: the regex is `r"(?P<H>2[0-3]|[0-1]\d|\d)"`
- ERFA also does not accept `24` for the hour field, since even if I hack the regex to allow 24 then one gets: `ErfaError: ERFA function "dtf2d" yielded 1 of "bad hour"`.  One gets the same trying `Time('2012-Feb-15 24:00:00', format='iso')`

So we have two upstream[1] libraries that don't adhere to the ISO standard.  The upstream SOFA library on which ERFA is based is historically pretty resistant to change and fairly slow.

[1]: technically speaking the `_strptime` we are using is a local copy of the Python 3.5 library and could be hacked, but that might not be a great idea. It is likely we don't need that local copy any more, but I don't recall right now the driver.

About the example `'2012-06-30 23:59:60'`, that is a leap second and so it is legal, and in this case not the same as `2012-06-30 24:00:00`.

**Comment by astrofrog** [comment]
I ran into the same issue a few days ago! I wonder if a possible fix would be to actually patch Python then copy the fix to our ``_strptime`` until we can drop the workaround.

**Comment by taldcroft** [comment]
Even if you patch `_strptime` the result still goes into ERFA and fails there:
```
>>> Time.strptime('2012-May-15 24:00:00', '%Y-%b-%d %H:%M:%S')
...
ValueError: Input values did not match the format class isot:
ErfaError: ERFA function "dtf2d" yielded 1 of "bad hour"
```
So we are back to either patching ERFA (and diverging from SOFA) or waiting for SOFA to accept a change.

**Comment by mhvk** [comment]
I think I agree with @richardgmcmahon's conclusion that we should just document it somewhere - I must admit while I would support it if our upstreams allowed, I don't quite like that there are two possible ways to describe the same instant in time in the same format. And we don't do timezones either so don't pretend to cover the full ISO specification.

**Comment by timj** [comment]
SOFA doesn't say it conforms to ISO8601.  It does support 60 seconds in a minute because of leap seconds.  Maybe @richardgmcmahon could ask Pat Wallace about SOFA supporting hour 24.

**Comment by richardgmcmahon** [comment]
@timj , as a great fan of slalib, the suggestion of asking Pat has made me smile :). I will give it a go and report back. In the medium term documentation, which effectively this discussion is doing, meets the present need.

**Comment by pllim** [comment]
Hello, has this issue been resolved?
