### ISSUE TITLE
Safer BaseCoordinateFrame?

### ISSUE THREAD

**Issue by niess** [astropy/astropy#9873]
Dear `astropy` developers,

first let me thank you for the great job you have done here :) I have been using the `astropy.coordinates` package for some time now and find it very convenient. Yet I have a few concerns which I discuss below.

The intent of `BaseCoordinateFrame` w.r.t. mutability is not clear to me. On one side the class restricts changing `self.data` (by not implementing the corresponding property setter) but on the other side the low level data are `numpy.ndarray` which are actually mutable. Furthermore, the class uses as cache which can get invalid without any notice.  This can lead to strange bugs, for example as following:

```python
>>> from numpy import zeros                                                       
>>> from astropy.coordinates import BaseCoordinateFrame, CartesianRepresentation                 

>>> z2 = zeros(2)                                                  
>>> frame = BaseCoordinateFrame(CartesianRepresentation(z2, z2, z2))       
>>> frame.spherical.distance  # This gets cached                                               
<Quantity [0., 0.]>                                                        

>>> frame.cartesian.x[:] += 1 # Someone modifies the coordinates in-place                 
>>> frame.spherical.distance  # The cached value is used                                               
<Quantity [0., 0.]> 
```
Explicitly clearing the cache (e.g. with `self.cache.clear()`) before the 2nd call to `frame.spherical` would solve the problem in this specific case. However, in a less obvious situation where the two calls are largely separated (e.g. in different functions implemented by different users) this can get really messy and error prone.

In order to prevent these types of errors a simple solution to me would be an option to disable the cache. This would allow for a more robust, yet less efficient, frame version.

Another confusing point to me is that in the previous example `frame.cartesian` while differing from the `frame.data` representation actually gets references to the data instead of copies. For example: 
 
```python
>>> frame.cartesian is frame.data
False
>>> frame.cartesian.x is frame.data.x
True
```
To me it would be safer if the representation like attributes of a frame (`frame.cartesian`, `frame.spherical`, ...) would always return a copy of the data, instead of references when matching the data representation.  If one explicitly wants a reference to the coordinates data then there is the `frame.data` property whose name clearly indicates that one is manipulating the initial data. Though, such a change could have a significant impact on the performances of existing codes :(

**Comment by pllim** [comment]
cc @eteq and @adrn

**Comment by mhvk** [comment]
@niess - in principle, `SkyCoord` are meant to be immutable,  i.e., one is not supposed to do in-place operations on arrays. We could enforce this by making the arrays read-only, but for some purposes it is simply too slow to do anything else (still working on improving that...). See http://docs.astropy.org/en/latest/coordinates/inplace.html.

As for solutions, as some of us would like to see coordinates become mutable, possibly the idea of stopping any caching is not bad. It would also circumvent similar problems in `Time`.

p.s. There are some other annoyances with the present design, such as `sky_coord.ra` not being the same (even the same unit) as `sky_coord.data.longiture`...

**Comment by taldcroft** [comment]
> in principle, SkyCoord are meant to be immutable, i.e., one is not supposed to do in-place operations on arrays.

Well, not entirely...  for some time now the process for changing a `SkyCoord` object in-place has been 
publicly documented, so can be considered as part of the public API.  This has been a requirement for certain high-performance apps that need to quickly change coordinates:
 https://docs.astropy.org/en/stable/coordinates/inplace.html

The point is that we are walking the line between performance and robustness, and caching is currently a key part of that.  See also #9857.

> There are some other annoyances with the present design, such as sky_coord.ra not being the same (even the same unit) as sky_coord.data.longiture...

@mhvk - recall that difference is by design.  There is no reason the `ra` attribute needs to have the same unit as the internal representation, they are conceptually and programmatically different views of the same underlying coordinate.  It may be more efficient to have a low-level representation in radians, while users rarely want to see `RA` in radians.

**Comment by niess** [comment]
Hello @mhvk and @taldcroft .Thanks for your answers :) Now I get a better picture.

Indeed, its probably complicated to have something that suites all use cases. In my case I am more concerned with robustness than performances. I am building tools for Physicists that would seldom read the doc but rather jump to any example on the web and copy paste it. In such a case `astropy.coordinates` looks unsafe to me. My users are familiar with numpy and could just extract and manipulate the raw numpy.array (or `astropy.units.Quantity`) the way they are used to. This could lead to severe and hard to detect bugs as illustrated in my example above.

If I understood correctly, the user of a frame has the responsibility to clear the cache if the data change.  That's too much of a responsibility for my users which are not all software fluent :P

As a work around, I am skeptical about wrapping setters to ensure that the cache gets cleared. At the end `numpy.ndarray` is managing a pointer that you can access purely through getters.  So one would end up clearing the cache like mad in order to be 100% safe. I would see only 2 robust solutions:

1. Disable the `automatic` caching and let the user backup cpu consuming computations by himself, i.e. working the old way :P

2. Tag all cached values with a hash of the frame data. So one can check if the cached value is up to date by comparing to the hash of the current data. However, this could significantly increase the CPU usage for fast to compute values.

Because at first it seemed easier to implement, I opted for the 1st solution. I ninja patch the cache `dict` of the `BaseCoordinateFrame` with a class that mocks an empty cache. However this is not 100% robust. It only works if the cache is queried with the `get` method, which seems to be the case in `BaseCoordinateFrame`. If `__getitem__` is used I still have to return the cached value because of [things like this](https://github.com/astropy/astropy/blob/master/astropy/coordinates/baseframe.py#L1145) where it is assumed that the requested value necessarily exists. I could ninja patch this as well, e.g. by wrapping the method with a `try/except KeyError` but this becomes very hackish.

This was the main motivation for my post. I thought that it would be nice to have a clean native *option* to deactivate the cache in `BaseCoordinateFrame`. Furthermore I could imagine use cases where systematically caching all results could be problematic, e.g. when manipulating large data sets. Then it could be more convenient to disable the cache and backup lengthy computations manually rather than spamming `cache.clear()`. Isn't it?

**Comment by mhvk** [comment]
@niess - I see your pain.... Though some of the caching really is useful. E.g., even in quite a bit of our own code, there is a tendency to do `coord.cartesian.x, coord.cartesian.y, coord.cartesian.z` - it is really wasteful to calculate the cartesian representation 3 times!

That said, there are other cases where the cache is not helpful, e.g., if one is memory limited because one is dealing with very large arrays. In that respect, the option to turn off caching would, in my opinion, be OK to have, and if that takes slightly rewriting patterns like the one you pointed out, then I think that is OK to upstream those to us.

On the yet other hand, I do wonder to what extent it is really useful to try to prevent people who don't read docs from shooting themselves in the foot - yes, they may now be able to write sloppy code that works with your patched version of astropy, but then when they send it to a friend who has regular astropy installed, it will just break.  In that respect, just setting arrays to read-only would be a simpler solution.

**Comment by mhvk** [comment]
p.s. I see I didn't read your last post very carefully - you mention the large data sets already! Anyway, as said, happy to see PRs for specific changes - for coordinates in particular there is also quite a bit that could be improved in the performance generally.

**Comment by taldcroft** [comment]
@niess - along with @mhvk I appreciate the points you are making.  One thing to bear in mind is that one of the most widely repeated concerns about astropy as a whole in surveys is that the coordinates package is slow.  So an opt-in mechanism that power-users could enable in some situations is an option, but we will be cautious of changes that impact performance for the average user.

Has there been serious discussion about making the representation data be read-only?  Maybe by default or as an opt-in?

**Comment by niess** [comment]
@mhvk - Indeed, I didn't thought about this simple case: `coord.cartesian.x`. Of course people would do that since it looks like `coord.cartesian` isn't a function. In that context I would say that making the economy of two brackets can be harmful :( Also, I agree with your last point concerning users running a patched astropy. So I finally changed my mind and switched to read only data arrays. Having convenient to use coordinates while being safe to mutate would imply too much changes at this point.

For my use case I have custom frames extensions (kinds of `EarthCoordinates` with extra functionalities). I set data to read only in the `__init__`. The same for the result of `represent_as`. Note that if a frame is created with `copy=False` the given representation is also set to read only. Doing so could have some annoying consequences :( But at least it is safe :)

@taldcroft - It looks like `SphericalRepresentation` converts to `PhysicsSphericalRepresentation` using in-place data modifications. For example, the following fails:

```Python
>>> r = SphericalRepresentation(0 * u.deg, 0 * u.deg, 1)
>>> r.lat.flags.writeable=False
>>> r.lon.flags.writeable=False
>>> r.distance.flags.writeable=False
>>> r.represent_as(PhysicsSphericalRepresentation)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/.mount_pythonSLjLgF/usr/python/lib/python3.7/site-packages/astropy/coordinates/representation.py", line 1633, in represent_as
    r=self.distance, copy=False)
  File "/tmp/.mount_pythonSLjLgF/usr/python/lib/python3.7/site-packages/astropy/coordinates/representation.py", line 1734, in __init__
    self._phi.wrap_at(360 * u.deg, inplace=True)
  File "/tmp/.mount_pythonSLjLgF/usr/python/lib/python3.7/site-packages/astropy/coordinates/angles.py", line 385, in wrap_at
    self[()] = wrapped
  File "/tmp/.mount_pythonSLjLgF/usr/python/lib/python3.7/site-packages/astropy/units/quantity.py", line 1060, in __setitem__
    self.view(np.ndarray).__setitem__(i, self._to_own_unit(value))
ValueError: assignment destination is read-only
```
Having frame representations being systematically read-only might bring some other surprises.

**Comment by mhvk** [comment]
@niess - makes sense!  On the `PhysicalSphericalRepresentation` problem, would you mind raising that as a new issue? That's definitely a bug!

**Comment by niess** [comment]
@mhvk - Done as #9898. As a result changing the 1st representation can modify the daughter one, since they now share some data, but apparently not all.

**Comment by niess** [comment]
> Has there been serious discussion about making the representation data be read-only? Maybe by default or as an opt-in?

@taldcroft - It would be cool if at least working with read-only arrays would be supported. Unfortunately, currently this is not 100% compatible. See e.g. #9898.
