### ISSUE TITLE
In-place data modification when changing from SphericalRepresentation to PhysicsSphericalRepresentation 

### ISSUE THREAD

**Issue by niess** [astropy/astropy#9898]
The following looks like a bug. At least the behaviour is rather surprising.

When representing a `SphericalRepresentation` as a `PhysicsSphericalRepresentation` some data are changed in-place, i.e. the two representations actually share some data.  For example:

```python
>>> r = SphericalRepresentation(0 * u.deg, 0 * u.deg, 1)
>>> r.lat.flags.writeable = False
>>> r.lon.flags.writeable = False
>>> r.distance.flags.writeable = False
>>> r.represent_as(PhysicsSphericalRepresentation)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/.mount_pythonSLjLgF/usr/python/lib/python3.7/site-packages/astropy/coordinates/representation.py", line 1633, in represent_as
    r=self.distance, copy=False)
  File "/tmp/.mount_pythonSLjLgF/usr/python/lib/python3.7/site-packages/astropy/coordinates/representation.py", line 1734, in __init__
    self._phi.wrap_at(360 * u.deg, inplace=True)
  File "/tmp/.mount_pythonSLjLgF/usr/python/lib/python3.7/site-packages/astropy/coordinates/angles.py", line 385, in wrap_at
    self[()] = wrapped
  File "/tmp/.mount_pythonSLjLgF/usr/python/lib/python3.7/site-packages/astropy/units/quantity.py", line 1060, in __setitem__
    self.view(np.ndarray).__setitem__(i, self._to_own_unit(value))
ValueError: assignment destination is read-only
```

Another example:

```python
>>> r0 = SphericalRepresentation(0 * u.deg, 0 * u.deg, 1)
>>> r1 = r0.represent_as(PhysicsSphericalRepresentation)                             
>>> r1
(0., 90., 1.) (deg, deg, )                                                                                                                   
>>> r0.lon[()] = 90 * u.deg                                                          
>>> r1
(90., 90., 1.) (deg, deg, )
```

**Comment by mhvk** [comment]
Actually, this looks like two somewhat separate issues/problems: 

1. It is tried to wrap the input longitude if it is not already in the right class, and this fails for `copy=False` and a non-writeable array:
```
from astropy import units as u
from astropy.coordinates import UnitSphericalRepresentation
lon = 0*u.degree
lon.flags.writeable = False
UnitSphericalRepresentation(lon, 0.*u.deg, copy=False)
# ValueError: output array is read-only
```
I guess one could either make a copy or just let the angle be (since there really is little wrong with a wrapped angle). For the specific issue at hand, perhaps in the initializer one should always copy if the input is readonly.

2. Input arrays are linked. But is this really a problem? Representations are meant to be immutable, so it should be fine to link arrays (and indeed this is good in case arrays are very large, especially for UnitSpherical and Spherical). It would be an issue if there were in-place changes, but since the wrapping is always to the same angle, that is not the case.

**Comment by niess** [comment]
This in-place wrapping seems to occur in several places. For example in [EarthLocation.from_geodetic()](https://github.com/astropy/astropy/blob/master/astropy/coordinates/earth.py#L283) as well. The input argument is actually modified. This makes it hard to work with read-only arrays as so. I would agree with @mhvk  and force copy to `True` in those initialisers when the input data are read-only.

I agree that the 2nd point is not an issue as long as the representations are used as immutable objects. My concern is that currently this is only guaranteed by good practices. Since the data are numpy arrays they can easily/accidentally be modified, e.g. by slicing. This can lead to severe bugs (see e.g. #9873). Being able to work with read-only arrays would provide an extra level of protection with that respect.

**Comment by mhvk** [comment]
Nice find. I think it will be useful to set up the tests so at least some/most run with read-only arrays just to check that everything works. And wrapping in `Longitude` with read-only arrays should not raise an error if nothing needs to be wrapped (or possibly wrapping should be ignored and give a warning instead - code will work, after all; for `EarthLocation` in particular, the longitude in its wrapped form is never exposed to the user!

**Comment by mhvk** [comment]
@niess - see #9900 for a fix for `EarthLocation`, as that is an easy one to address.  Definitely want to push fixes like those for other issues, and at the same time think whether/how we can perhaps support a read-only option (while ensuring no speed penalty and no clutter from possibly propagating readonly settings!).
