### ISSUE TITLE
astropy.extern.configobj.configobj.ParseError: Invalid line ('ock while accessing the data cache before')

### ISSUE THREAD

**Issue by loxlig** [astropy/astropy#9935]
The complete error message is as follows:
astropy.extern.configobj.configobj.ParseError: Invalid line ('ock while accessing the data cache before') (matched as neither section nor keyword) at line 152.

Upgrading astropy from 4.0 to 4.1 did not help. The installation of astropy was working well until this error began at some time during the night. I also removed the __pycache__ from the confgobj directory which did not help. Other installations of astropy via conda on other machines do not yet have this problem.  I only have to import astropy to generate the error.

platform: Linux-5.4.12-200.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
Python: 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
numpy: 1.18.1
astropy: 4.0   # Update to 4.1 did not change /astropy/version.py
scipy: 1.4.1

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

```python
# Put your Python code snippet here.
```

**Comment by pllim** [comment]
Hello. Can you please provide a fully reproducible code snippet and the full traceback that you saw?

> # Update to 4.1 did not change /astropy/version.py

This is curious as well. Can you please clarify exactly how you installed and then updated `astropy`?

**Comment by loxlig** [comment]
I only need to import astropy to generate the error:
>>> import astropy
astropy.extern.configobj.configobj.ParseError: Invalid line ('ock while accessing the data cache before') (matched as neither section nor keyword) at line 152.

I updated astropy via conda like so:
conda update astropy
The updated installation succeed considering the current file timestamps within the astropy base directory. The version.py file was not updated along with all of the other files. There were 3 other files that did not have their timestamps updated. Those were:
CITATION
compiler_version.cpython-37m-x86_64-linux-gnu.so
 cython_version.py

**Comment by loxlig** [comment]
Sorry - the complete traceback:
>>> import astropy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sel/anaconda3/lib/python3.7/site-packages/astropy/__init__.py", line 365, in <module>
    log = _init_log()
  File "/home/sel/anaconda3/lib/python3.7/site-packages/astropy/logger.py", line 101, in _init_log
    log._set_defaults()
  File "/home/sel/anaconda3/lib/python3.7/site-packages/astropy/logger.py", line 477, in _set_defaults
    self.setLevel(conf.log_level)
  File "/home/sel/anaconda3/lib/python3.7/site-packages/astropy/config/configuration.py", line 278, in __get__
    return self()
  File "/home/sel/anaconda3/lib/python3.7/site-packages/astropy/config/configuration.py", line 401, in __call__
    sec = get_config(self.module, rootname=self.rootname)
  File "/home/sel/anaconda3/lib/python3.7/site-packages/astropy/config/configuration.py", line 551, in get_config
    cobj = configobj.ConfigObj(cfgfn, interpolation=False)
  File "/home/sel/anaconda3/lib/python3.7/site-packages/astropy/extern/configobj/configobj.py", line 1227, in __init__
    self._load(infile, configspec)
  File "/home/sel/anaconda3/lib/python3.7/site-packages/astropy/extern/configobj/configobj.py", line 1316, in _load
    raise error
astropy.extern.configobj.configobj.ParseError: Invalid line ('ock while accessing the data cache before') (matched as neither section nor keyword) at line 152.
>>> import astropy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sel/anaconda3/lib/python3.7/site-packages/astropy/__init__.py", line 365, in <module>
    log = _init_log()
  File "/home/sel/anaconda3/lib/python3.7/site-packages/astropy/logger.py", line 101, in _init_log
    log._set_defaults()
  File "/home/sel/anaconda3/lib/python3.7/site-packages/astropy/logger.py", line 477, in _set_defaults
    self.setLevel(conf.log_level)
  File "/home/sel/anaconda3/lib/python3.7/site-packages/astropy/config/configuration.py", line 278, in __get__
    return self()
  File "/home/sel/anaconda3/lib/python3.7/site-packages/astropy/config/configuration.py", line 401, in __call__
    sec = get_config(self.module, rootname=self.rootname)
  File "/home/sel/anaconda3/lib/python3.7/site-packages/astropy/config/configuration.py", line 551, in get_config
    cobj = configobj.ConfigObj(cfgfn, interpolation=False)
  File "/home/sel/anaconda3/lib/python3.7/site-packages/astropy/extern/configobj/configobj.py", line 1227, in __init__
    self._load(infile, configspec)
  File "/home/sel/anaconda3/lib/python3.7/site-packages/astropy/extern/configobj/configobj.py", line 1316, in _load
    raise error
astropy.extern.configobj.configobj.ParseError: Invalid line ('ock while accessing the data cache before') (matched as neither section nor keyword) at line 152.

**Comment by pllim** [comment]
I think your `~/.astropy/astropy.cfg` file is corrupted. Unless you have some custom configuration saved in that file, it is the easiest to remove it and try `import astropy` again.

If this persists and your HOME directory is shared, check that other users are not corrupting it.

**Comment by saimn** [comment]
Can you check your config file, if this line has a linebreak and is not commented:
```
❯ grep 'accessing the data cache before' ~/.astropy/config/astropy.cfg
## Number of seconds to try to get the lock while accessing the data cache before
```

**Comment by loxlig** [comment]
This is how the line appears in the astropy.cfg file along with 2 subsequent lines:
## Number of seconds to try to get the lock while accessing the data cache before
## giving up
# download_cache_lock_attempts = 5

**Comment by saimn** [comment]
Hmm, weird. Did you try to delete this file as well ?

**Comment by loxlig** [comment]
astropy starts again. I may have been too hasty after upgrading to 4.1. I think the astropy.cfg file probably was corrupted then the update to 4.1 overwrote the astropy.cfg file. Now astropy is starting up without any error. Odd that the astropy.cfg file should have been corrupted but the update seems to have taken care of it.
Thanks.
